// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

pub(super) fn find_part_17(slug: &str) -> Option<Icon> {
    match slug {
        "resend" => Some(icons::SI_RESEND),
        "gamebanana" => Some(icons::SI_GAMEBANANA),
        "magic" => Some(icons::SI_MAGIC),
        "jrgroup" => Some(icons::SI_JRGROUP),
        "dash0" => Some(icons::SI_DASH0),
        "camunda" => Some(icons::SI_CAMUNDA),
        "cashapp" => Some(icons::SI_CASHAPP),
        "webcomponentsdotorg" => Some(icons::SI_WEBCOMPONENTSDOTORG),
        "carrefour" => Some(icons::SI_CARREFOUR),
        "crowdin" => Some(icons::SI_CROWDIN),
        "fossa" => Some(icons::SI_FOSSA),
        "googlepubsub" => Some(icons::SI_GOOGLEPUBSUB),
        "renault" => Some(icons::SI_RENAULT),
        "wails" => Some(icons::SI_WAILS),
        "checkmk" => Some(icons::SI_CHECKMK),
        "mtr" => Some(icons::SI_MTR),
        "esri" => Some(icons::SI_ESRI),
        "nordicsemiconductor" => Some(icons::SI_NORDICSEMICONDUCTOR),
        "drone" => Some(icons::SI_DRONE),
        "wayland" => Some(icons::SI_WAYLAND),
        "nim" => Some(icons::SI_NIM),
        "formik" => Some(icons::SI_FORMIK),
        "logstash" => Some(icons::SI_LOGSTASH),
        "chef" => Some(icons::SI_CHEF),
        "replicate" => Some(icons::SI_REPLICATE),
        "vsco" => Some(icons::SI_VSCO),
        "newegg" => Some(icons::SI_NEWEGG),
        "headlessui" => Some(icons::SI_HEADLESSUI),
        "davinciresolve" => Some(icons::SI_DAVINCIRESOLVE),
        "netbsd" => Some(icons::SI_NETBSD),
        "opensourcehardware" => Some(icons::SI_OPENSOURCEHARDWARE),
        "scratch" => Some(icons::SI_SCRATCH),
        "g2" => Some(icons::SI_G2),
        "concourse" => Some(icons::SI_CONCOURSE),
        "dcentertainment" => Some(icons::SI_DCENTERTAINMENT),
        "boxysvg" => Some(icons::SI_BOXYSVG),
        "opnsense" => Some(icons::SI_OPNSENSE),
        "parrotsecurity" => Some(icons::SI_PARROTSECURITY),
        "icomoon" => Some(icons::SI_ICOMOON),
        "htmx" => Some(icons::SI_HTMX),
        "envato" => Some(icons::SI_ENVATO),
        "datadog" => Some(icons::SI_DATADOG),
        "playerdotme" => Some(icons::SI_PLAYERDOTME),
        "sonarr" => Some(icons::SI_SONARR),
        "first" => Some(icons::SI_FIRST),
        "teamcity" => Some(icons::SI_TEAMCITY),
        "owncloud" => Some(icons::SI_OWNCLOUD),
        _ => None,
    }
}
