// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

pub(super) fn find_part_17(slug: &str) -> Option<Icon> {
    match slug {
        "odido" => Some(icons::SI_ODIDO),
        "lodash" => Some(icons::SI_LODASH),
        "probot" => Some(icons::SI_PROBOT),
        "zettlr" => Some(icons::SI_ZETTLR),
        "animalplanet" => Some(icons::SI_ANIMALPLANET),
        "xing" => Some(icons::SI_XING),
        "tarteaucitron" => Some(icons::SI_TARTEAUCITRON),
        "portainer" => Some(icons::SI_PORTAINER),
        "vencord" => Some(icons::SI_VENCORD),
        "premid" => Some(icons::SI_PREMID),
        "billboard" => Some(icons::SI_BILLBOARD),
        "mautic" => Some(icons::SI_MAUTIC),
        "reason" => Some(icons::SI_REASON),
        "accenture" => Some(icons::SI_ACCENTURE),
        "ethereum" => Some(icons::SI_ETHEREUM),
        "webdriverio" => Some(icons::SI_WEBDRIVERIO),
        "ford" => Some(icons::SI_FORD),
        "thefinals" => Some(icons::SI_THEFINALS),
        "stardock" => Some(icons::SI_STARDOCK),
        "e3" => Some(icons::SI_E3),
        "labview" => Some(icons::SI_LABVIEW),
        "fedora" => Some(icons::SI_FEDORA),
        "xml" => Some(icons::SI_XML),
        "openhab" => Some(icons::SI_OPENHAB),
        "egghead" => Some(icons::SI_EGGHEAD),
        "cdprojekt" => Some(icons::SI_CDPROJEKT),
        "deutschebank" => Some(icons::SI_DEUTSCHEBANK),
        "grocy" => Some(icons::SI_GROCY),
        "photopea" => Some(icons::SI_PHOTOPEA),
        "replicate" => Some(icons::SI_REPLICATE),
        "plurk" => Some(icons::SI_PLURK),
        "youtubestudio" => Some(icons::SI_YOUTUBESTUDIO),
        "convex" => Some(icons::SI_CONVEX),
        "pimcore" => Some(icons::SI_PIMCORE),
        "aegisauthenticator" => Some(icons::SI_AEGISAUTHENTICATOR),
        "dogecoin" => Some(icons::SI_DOGECOIN),
        _ => None,
    }
}
