// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

pub(super) fn find_part_17(slug: &str) -> Option<Icon> {
    match slug {
        "zebpay" => Some(icons::SI_ZEBPAY),
        "zebratechnologies" => Some(icons::SI_ZEBRATECHNOLOGIES),
        "zedindustries" => Some(icons::SI_ZEDINDUSTRIES),
        "zelle" => Some(icons::SI_ZELLE),
        "zenbrowser" => Some(icons::SI_ZENBROWSER),
        "zend" => Some(icons::SI_ZEND),
        "zendesk" => Some(icons::SI_ZENDESK),
        "zenn" => Some(icons::SI_ZENN),
        "zenodo" => Some(icons::SI_ZENODO),
        "zensar" => Some(icons::SI_ZENSAR),
        "zerodha" => Some(icons::SI_ZERODHA),
        "zerotier" => Some(icons::SI_ZEROTIER),
        "zettlr" => Some(icons::SI_ZETTLR),
        "zhihu" => Some(icons::SI_ZHIHU),
        "zig" => Some(icons::SI_ZIG),
        "zigbee" => Some(icons::SI_ZIGBEE),
        "zigbee2mqtt" => Some(icons::SI_ZIGBEE2MQTT),
        "ziggo" => Some(icons::SI_ZIGGO),
        "zilch" => Some(icons::SI_ZILCH),
        "zillow" => Some(icons::SI_ZILLOW),
        "zincsearch" => Some(icons::SI_ZINCSEARCH),
        "zingat" => Some(icons::SI_ZINGAT),
        "zod" => Some(icons::SI_ZOD),
        "zoho" => Some(icons::SI_ZOHO),
        "zoiper" => Some(icons::SI_ZOIPER),
        "zola" => Some(icons::SI_ZOLA),
        "zomato" => Some(icons::SI_ZOMATO),
        "zoom" => Some(icons::SI_ZOOM),
        "zorin" => Some(icons::SI_ZORIN),
        "zotero" => Some(icons::SI_ZOTERO),
        "zsh" => Some(icons::SI_ZSH),
        "zulip" => Some(icons::SI_ZULIP),
        "zyte" => Some(icons::SI_ZYTE),
        _ => None,
    }
}
