// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_2(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("NODE_16", icons::NODE_16)?;
    m.add("MOON_24", icons::MOON_24)?;
    m.add("MOVE_TO_TOP_16", icons::MOVE_TO_TOP_16)?;
    m.add("SMILEY_NEUTRAL_24", icons::SMILEY_NEUTRAL_24)?;
    m.add("FILE_16", icons::FILE_16)?;
    m.add("BELL_SLASH_24", icons::BELL_SLASH_24)?;
    m.add("DEVICE_CAMERA_VIDEO_24", icons::DEVICE_CAMERA_VIDEO_24)?;
    m.add("STOPWATCH_24", icons::STOPWATCH_24)?;
    m.add("PLUS_24", icons::PLUS_24)?;
    m.add("REPLY_24", icons::REPLY_24)?;
    m.add("KEY_24", icons::KEY_24)?;
    m.add("SPACING_SMALL_16", icons::SPACING_SMALL_16)?;
    m.add("FISCAL_HOST_16", icons::FISCAL_HOST_16)?;
    m.add("GLOBE_16", icons::GLOBE_16)?;
    m.add("CIRCLE_16", icons::CIRCLE_16)?;
    m.add("REPO_CLONE_24", icons::REPO_CLONE_24)?;
    m.add("CACHE_16", icons::CACHE_16)?;
    m.add("FILTER_REMOVE_16", icons::FILTER_REMOVE_16)?;
    m.add("FILE_DIFF_24", icons::FILE_DIFF_24)?;
    m.add("VERIFIED_24", icons::VERIFIED_24)?;
    m.add("PAPERCLIP_24", icons::PAPERCLIP_24)?;
    m.add("FEED_PERSON_16", icons::FEED_PERSON_16)?;
    m.add("ARROW_UP_LEFT_24", icons::ARROW_UP_LEFT_24)?;
    m.add("ITALIC_24", icons::ITALIC_24)?;
    m.add("FILTER_24", icons::FILTER_24)?;
    m.add("VIDEO_16", icons::VIDEO_16)?;
    m.add("INFINITY_24", icons::INFINITY_24)?;
    m.add("DIFF_MODIFIED_16", icons::DIFF_MODIFIED_16)?;
    m.add("MORTAR_BOARD_24", icons::MORTAR_BOARD_24)?;
    m.add("GIT_MERGE_QUEUE_24", icons::GIT_MERGE_QUEUE_24)?;
    m.add("FILE_ADDED_24", icons::FILE_ADDED_24)?;
    m.add("VSCODE_24", icons::VSCODE_24)?;
    m.add("REPO_FORKED_24", icons::REPO_FORKED_24)?;
    m.add("BOOK_LOCKED_16", icons::BOOK_LOCKED_16)?;
    m.add("TRIANGLE_DOWN_16", icons::TRIANGLE_DOWN_16)?;
    m.add("CHEVRON_DOWN_12", icons::CHEVRON_DOWN_12)?;
    m.add("IMAGE_24", icons::IMAGE_24)?;
    m.add("ISSUE_REOPENED_24", icons::ISSUE_REOPENED_24)?;
    m.add("NODE_24", icons::NODE_24)?;
    m.add("TRIANGLE_RIGHT_16", icons::TRIANGLE_RIGHT_16)?;
    m.add("BUG_24", icons::BUG_24)?;
    m.add("CHEVRON_UP_16", icons::CHEVRON_UP_16)?;
    m.add("UNFOLD_16", icons::UNFOLD_16)?;
    m.add("FILE_CHECK_16", icons::FILE_CHECK_16)?;
    m.add("LOGO_GITHUB_24", icons::LOGO_GITHUB_24)?;
    m.add("X_12", icons::X_12)?;
    m.add("DIFF_24", icons::DIFF_24)?;
    m.add("READ_16", icons::READ_16)?;
    m.add("FEED_REPO_16", icons::FEED_REPO_16)?;
    m.add("STOP_24", icons::STOP_24)?;
    m.add("SIDEBAR_EXPAND_16", icons::SIDEBAR_EXPAND_16)?;
    m.add("INBOX_FILL_24", icons::INBOX_FILL_24)?;
    m.add("SYNC_16", icons::SYNC_16)?;
    m.add("TROPHY_16", icons::TROPHY_16)?;
    m.add("PAPER_AIRPLANE_24", icons::PAPER_AIRPLANE_24)?;
    m.add("MAXIMIZE_24", icons::MAXIMIZE_24)?;
    m.add("CHECK_CIRCLE_FILL_12", icons::CHECK_CIRCLE_FILL_12)?;
    m.add("REPO_TEMPLATE_24", icons::REPO_TEMPLATE_24)?;
    m.add("HUBOT_16", icons::HUBOT_16)?;
    m.add("TOOLS_16", icons::TOOLS_16)?;
    m.add("X_CIRCLE_16", icons::X_CIRCLE_16)?;
    m.add("QUOTE_24", icons::QUOTE_24)?;
    m.add("TRASH_16", icons::TRASH_16)?;
    m.add("ARROW_SWITCH_16", icons::ARROW_SWITCH_16)?;
    m.add("MCP_16", icons::MCP_16)?;
    m.add("EXCLAMATION_24", icons::EXCLAMATION_24)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_24",
        icons::FILE_DIRECTORY_SYMLINK_24,
    )?;
    m.add("FILTER_REMOVE_24", icons::FILTER_REMOVE_24)?;
    m.add("TELESCOPE_24", icons::TELESCOPE_24)?;
    m.add("FLAG_16", icons::FLAG_16)?;
    m.add("FEED_HEART_16", icons::FEED_HEART_16)?;
    m.add("INFO_16", icons::INFO_16)?;
    m.add("PAUSE_24", icons::PAUSE_24)?;
    m.add("MOON_16", icons::MOON_16)?;
    m.add("FEED_TROPHY_16", icons::FEED_TROPHY_16)?;
    m.add("MUTE_16", icons::MUTE_16)?;
    m.add("FILE_DIFF_16", icons::FILE_DIFF_16)?;
    m.add("THUMBSDOWN_16", icons::THUMBSDOWN_16)?;
    m.add("GIT_MERGE_24", icons::GIT_MERGE_24)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_16",
        icons::FILE_DIRECTORY_OPEN_FILL_16,
    )?;
    m.add("ARROW_DOWN_RIGHT_24", icons::ARROW_DOWN_RIGHT_24)?;
    m.add("STRIKETHROUGH_24", icons::STRIKETHROUGH_24)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_24",
        icons::TRACKED_BY_CLOSED_COMPLETED_24,
    )?;
    m.add("LINK_EXTERNAL_24", icons::LINK_EXTERNAL_24)?;
    m.add("ZOOM_OUT_24", icons::ZOOM_OUT_24)?;
    m.add("SCREEN_NORMAL_16", icons::SCREEN_NORMAL_16)?;
    m.add("PLUS_CIRCLE_16", icons::PLUS_CIRCLE_16)?;
    m.add("ID_BADGE_24", icons::ID_BADGE_24)?;
    m.add("CHECK_CIRCLE_24", icons::CHECK_CIRCLE_24)?;
    m.add("CLOCK_24", icons::CLOCK_24)?;
    m.add("BELL_24", icons::BELL_24)?;
    m.add("COMMENT_AI_16", icons::COMMENT_AI_16)?;
    m.add("GIT_BRANCH_CHECK_16", icons::GIT_BRANCH_CHECK_16)?;
    m.add("TAB_24", icons::TAB_24)?;
    m.add("PAPERCLIP_16", icons::PAPERCLIP_16)?;
    m.add("GIT_COMMIT_16", icons::GIT_COMMIT_16)?;
    m.add("CODESCAN_CHECKMARK_16", icons::CODESCAN_CHECKMARK_16)?;
    m.add("PLUS_16", icons::PLUS_16)?;
    m.add("FILE_SYMLINK_FILE_16", icons::FILE_SYMLINK_FILE_16)?;
    m.add("BOOK_16", icons::BOOK_16)?;
    m.add("TOOLS_24", icons::TOOLS_24)?;
    m.add("SEARCH_16", icons::SEARCH_16)?;
    m.add("BOOKMARK_SLASH_16", icons::BOOKMARK_SLASH_16)?;
    m.add("SERVER_16", icons::SERVER_16)?;
    m.add(
        "FEED_PULL_REQUEST_OPEN_16",
        icons::FEED_PULL_REQUEST_OPEN_16,
    )?;
    m.add("FEED_ISSUE_CLOSED_16", icons::FEED_ISSUE_CLOSED_16)?;
    m.add("PAINTBRUSH_16", icons::PAINTBRUSH_16)?;
    m.add("SLIDERS_16", icons::SLIDERS_16)?;
    m.add("APPS_16", icons::APPS_16)?;
    m.add("GIFT_24", icons::GIFT_24)?;
    m.add("UNDO_16", icons::UNDO_16)?;
    m.add("ISSUE_TRACKED_BY_24", icons::ISSUE_TRACKED_BY_24)?;
    m.add("SMILEY_NEUTRAL_16", icons::SMILEY_NEUTRAL_16)?;
    m.add("COPILOT_ERROR_16", icons::COPILOT_ERROR_16)?;
    m.add("ISSUE_OPENED_24", icons::ISSUE_OPENED_24)?;
    m.add("SHIELD_16", icons::SHIELD_16)?;
    m.add("DIFF_IGNORED_24", icons::DIFF_IGNORED_24)?;
    m.add("FOLD_UP_16", icons::FOLD_UP_16)?;
    m.add("SINGLE_SELECT_24", icons::SINGLE_SELECT_24)?;
    m.add("ARROW_LEFT_24", icons::ARROW_LEFT_24)?;
    m.add("SCREEN_NORMAL_24", icons::SCREEN_NORMAL_24)?;
    m.add("PROJECT_ROADMAP_16", icons::PROJECT_ROADMAP_16)?;
    m.add("BOOLEAN_ON_16", icons::BOOLEAN_ON_16)?;
    m.add("TYPOGRAPHY_24", icons::TYPOGRAPHY_24)?;
    m.add("HASH_24", icons::HASH_24)?;
    m.add("BLOCKED_16", icons::BLOCKED_16)?;
    m.add("SIGN_OUT_24", icons::SIGN_OUT_24)?;
    m.add("BEAKER_24", icons::BEAKER_24)?;
    m.add("DOT_16", icons::DOT_16)?;
    m.add("BOOKMARK_SLASH_FILL_24", icons::BOOKMARK_SLASH_FILL_24)?;
    m.add("ZOOM_OUT_16", icons::ZOOM_OUT_16)?;
    m.add("PLAY_16", icons::PLAY_16)?;
    m.add("DASH_24", icons::DASH_24)?;
    m.add("REPORT_24", icons::REPORT_24)?;
    m.add("LOGO_GITHUB_16", icons::LOGO_GITHUB_16)?;
    m.add("MOVE_TO_TOP_24", icons::MOVE_TO_TOP_24)?;
    m.add("FLAME_16", icons::FLAME_16)?;
    m.add("HEART_16", icons::HEART_16)?;
    m.add("CODESCAN_24", icons::CODESCAN_24)?;
    m.add("FOLD_16", icons::FOLD_16)?;
    m.add("REPO_DELETE_24", icons::REPO_DELETE_24)?;
    m.add("WORKFLOW_24", icons::WORKFLOW_24)?;
    m.add("REL_FILE_PATH_16", icons::REL_FILE_PATH_16)?;
    m.add("ARROW_RIGHT_16", icons::ARROW_RIGHT_16)?;
    m.add("FILE_CODE_16", icons::FILE_CODE_16)?;
    m.add("ARROW_UP_LEFT_16", icons::ARROW_UP_LEFT_16)?;
    m.add("SKIP_FILL_24", icons::SKIP_FILL_24)?;
    m.add("ARROW_LEFT_16", icons::ARROW_LEFT_16)?;
    m.add("BOOKMARK_SLASH_FILL_16", icons::BOOKMARK_SLASH_FILL_16)?;
    m.add("HOME_24", icons::HOME_24)?;
    m.add("EYE_16", icons::EYE_16)?;
    m.add("STACK_REMOVE_16", icons::STACK_REMOVE_16)?;
    m.add("LIGHT_BULB_16", icons::LIGHT_BULB_16)?;
    m.add("TAB_16", icons::TAB_16)?;
    m.add("ZAP_24", icons::ZAP_24)?;
    m.add("SMILEY_FRUSTRATED_16", icons::SMILEY_FRUSTRATED_16)?;
    m.add("UNLINK_24", icons::UNLINK_24)?;
    m.add("BOOLEAN_ON_24", icons::BOOLEAN_ON_24)?;
    m.add("SQUIRREL_16", icons::SQUIRREL_16)?;
    m.add("DEVICES_16", icons::DEVICES_16)?;
    m.add("APPS_24", icons::APPS_24)?;
    m.add("ZOOM_IN_24", icons::ZOOM_IN_24)?;
    m.add("GIT_COMPARE_16", icons::GIT_COMPARE_16)?;
    m.add("HOME_FILL_24", icons::HOME_FILL_24)?;
    m.add("FILTER_16", icons::FILTER_16)?;
    m.add("CHEVRON_LEFT_12", icons::CHEVRON_LEFT_12)?;
    m.add("ISSUE_LOCKED_16", icons::ISSUE_LOCKED_16)?;
    m.add("MULTI_SELECT_24", icons::MULTI_SELECT_24)?;
    m.add("CONTAINER_16", icons::CONTAINER_16)?;
    m.add("ALERT_24", icons::ALERT_24)?;
    m.add("FILE_DIRECTORY_FILL_24", icons::FILE_DIRECTORY_FILL_24)?;
    m.add("SMILEY_FROWN_24", icons::SMILEY_FROWN_24)?;
    m.add("NORTH_STAR_16", icons::NORTH_STAR_16)?;
    m.add("PACKAGE_DEPENDENTS_24", icons::PACKAGE_DEPENDENTS_24)?;
    m.add("CROSSHAIRS_16", icons::CROSSHAIRS_16)?;
    m.add("CHECKLIST_16", icons::CHECKLIST_16)?;
    m.add("FILE_BINARY_16", icons::FILE_BINARY_16)?;
    m.add("COPILOT_16", icons::COPILOT_16)?;
    m.add("LOOP_16", icons::LOOP_16)?;
    m.add("LINK_24", icons::LINK_24)?;
    m.add(
        "GIT_PULL_REQUEST_DRAFT_16",
        icons::GIT_PULL_REQUEST_DRAFT_16,
    )?;
    m.add("PERSON_24", icons::PERSON_24)?;
    m.add("VSCODE_16", icons::VSCODE_16)?;
    m.add("PASTE_24", icons::PASTE_24)?;
    m.add("BRIEFCASE_16", icons::BRIEFCASE_16)?;
    m.add("LOG_16", icons::LOG_16)?;
    m.add("X_16", icons::X_16)?;
    m.add("SQUIRREL_24", icons::SQUIRREL_24)?;
    m.add("SMILEY_FROWN_16", icons::SMILEY_FROWN_16)?;
    m.add("UPLOAD_16", icons::UPLOAD_16)?;
    m.add("VERSIONS_16", icons::VERSIONS_16)?;
    m.add("GLOBE_24", icons::GLOBE_24)?;
    m.add("SHIELD_24", icons::SHIELD_24)?;
    m.add("SERVER_24", icons::SERVER_24)?;
    m.add("NUMBER_24", icons::NUMBER_24)?;
    m.add("CHECK_24", icons::CHECK_24)?;
    m.add("FOLD_24", icons::FOLD_24)?;
    m.add("STAR_FILL_24", icons::STAR_FILL_24)?;
    m.add("GRAPH_BAR_HORIZONTAL_16", icons::GRAPH_BAR_HORIZONTAL_16)?;
    m.add("UNMUTE_24", icons::UNMUTE_24)?;
    Ok(())
}
