// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_3(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("SPARKLE_16", icons::SPARKLE_16)?;
    m.add("ELLIPSIS_16", icons::ELLIPSIS_16)?;
    m.add("CLOCK_FILL_16", icons::CLOCK_FILL_16)?;
    m.add("ITERATIONS_24", icons::ITERATIONS_24)?;
    m.add("CHAT_ADD_16", icons::CHAT_ADD_16)?;
    m.add("SPARKLE_24", icons::SPARKLE_24)?;
    m.add("SHIELD_LOCK_24", icons::SHIELD_LOCK_24)?;
    m.add("BOOLEAN_OFF_16", icons::BOOLEAN_OFF_16)?;
    m.add("BOLD_24", icons::BOLD_24)?;
    m.add("FLOWCHART_24", icons::FLOWCHART_24)?;
    m.add("TERMINAL_LOCKED_24", icons::TERMINAL_LOCKED_24)?;
    m.add("PERSON_FILL_16", icons::PERSON_FILL_16)?;
    m.add("NUMBER_16", icons::NUMBER_16)?;
    m.add("SHARE_ANDROID_24", icons::SHARE_ANDROID_24)?;
    m.add("HISTORY_24", icons::HISTORY_24)?;
    m.add("DUPLICATE_16", icons::DUPLICATE_16)?;
    m.add("CROSS_REFERENCE_24", icons::CROSS_REFERENCE_24)?;
    m.add("PLAY_24", icons::PLAY_24)?;
    m.add("CHAT_QUESTION_16", icons::CHAT_QUESTION_16)?;
    m.add("LIST_ORDERED_24", icons::LIST_ORDERED_24)?;
    m.add("PASTE_24", icons::PASTE_24)?;
    m.add("COPY_16", icons::COPY_16)?;
    m.add("ACCESSIBILITY_INSET_16", icons::ACCESSIBILITY_INSET_16)?;
    m.add("STOP_16", icons::STOP_16)?;
    m.add("GEAR_16", icons::GEAR_16)?;
    m.add("ARROW_DOWN_16", icons::ARROW_DOWN_16)?;
    m.add("STOP_24", icons::STOP_24)?;
    m.add("TELESCOPE_24", icons::TELESCOPE_24)?;
    m.add("ISSUE_OPENED_16", icons::ISSUE_OPENED_16)?;
    m.add("STRIKETHROUGH_16", icons::STRIKETHROUGH_16)?;
    m.add("PLUG_16", icons::PLUG_16)?;
    m.add("ISSUE_RELATES_TO_16", icons::ISSUE_RELATES_TO_16)?;
    m.add("PASTE_16", icons::PASTE_16)?;
    m.add("PERSON_16", icons::PERSON_16)?;
    m.add("PROJECT_SYMLINK_24", icons::PROJECT_SYMLINK_24)?;
    m.add("GIT_COMPARE_16", icons::GIT_COMPARE_16)?;
    m.add("GEAR_24", icons::GEAR_24)?;
    m.add("LINK_EXTERNAL_24", icons::LINK_EXTERNAL_24)?;
    m.add("MUTE_16", icons::MUTE_16)?;
    m.add("SHIELD_SLASH_16", icons::SHIELD_SLASH_16)?;
    m.add("REPO_TEMPLATE_24", icons::REPO_TEMPLATE_24)?;
    m.add("NODE_16", icons::NODE_16)?;
    m.add("RSS_16", icons::RSS_16)?;
    m.add("CODESCAN_24", icons::CODESCAN_24)?;
    m.add("HASH_24", icons::HASH_24)?;
    m.add("LOCATION_24", icons::LOCATION_24)?;
    m.add("PLUS_CIRCLE_24", icons::PLUS_CIRCLE_24)?;
    m.add("PLAY_16", icons::PLAY_16)?;
    m.add("FILE_ZIP_16", icons::FILE_ZIP_16)?;
    m.add("TROPHY_24", icons::TROPHY_24)?;
    m.add("MAIL_16", icons::MAIL_16)?;
    m.add("GLOBE_24", icons::GLOBE_24)?;
    m.add("UNMUTE_24", icons::UNMUTE_24)?;
    m.add("CHECK_CIRCLE_FILL_24", icons::CHECK_CIRCLE_FILL_24)?;
    m.add("FLAG_16", icons::FLAG_16)?;
    m.add("PIN_SLASH_24", icons::PIN_SLASH_24)?;
    m.add("ZOOM_IN_24", icons::ZOOM_IN_24)?;
    m.add("PAINTBRUSH_16", icons::PAINTBRUSH_16)?;
    m.add("SMILEY_NEUTRAL_24", icons::SMILEY_NEUTRAL_24)?;
    m.add(
        "FEED_PULL_REQUEST_OPEN_16",
        icons::FEED_PULL_REQUEST_OPEN_16,
    )?;
    m.add("INFINITY_16", icons::INFINITY_16)?;
    m.add("MOVE_TO_START_16", icons::MOVE_TO_START_16)?;
    m.add("THUMBSUP_24", icons::THUMBSUP_24)?;
    m.add("SANDBOX_16", icons::SANDBOX_16)?;
    m.add("REPO_PUSH_16", icons::REPO_PUSH_16)?;
    m.add("SIGN_OUT_24", icons::SIGN_OUT_24)?;
    m.add("MARKDOWN_16", icons::MARKDOWN_16)?;
    m.add("TELESCOPE_16", icons::TELESCOPE_16)?;
    m.add("FILE_CODE_16", icons::FILE_CODE_16)?;
    m.add("MUTE_24", icons::MUTE_24)?;
    m.add("THUMBSDOWN_16", icons::THUMBSDOWN_16)?;
    m.add("COMMENT_16", icons::COMMENT_16)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_24",
        icons::FILE_DIRECTORY_OPEN_FILL_24,
    )?;
    m.add("FEED_PUBLIC_16", icons::FEED_PUBLIC_16)?;
    m.add("CROSSHAIRS_16", icons::CROSSHAIRS_16)?;
    m.add("PIN_16", icons::PIN_16)?;
    m.add("SHIELD_X_24", icons::SHIELD_X_24)?;
    m.add("LOCK_24", icons::LOCK_24)?;
    m.add("SORT_DESC_16", icons::SORT_DESC_16)?;
    m.add("CLOUD_24", icons::CLOUD_24)?;
    m.add("VERSIONS_16", icons::VERSIONS_16)?;
    m.add("PULSE_24", icons::PULSE_24)?;
    m.add("PAUSE_24", icons::PAUSE_24)?;
    m.add("REDO_16", icons::REDO_16)?;
    m.add("GLOBE_16", icons::GLOBE_16)?;
    m.add("MIRROR_24", icons::MIRROR_24)?;
    m.add("TRIANGLE_RIGHT_16", icons::TRIANGLE_RIGHT_16)?;
    m.add("CHECK_CIRCLE_24", icons::CHECK_CIRCLE_24)?;
    m.add("BOLD_16", icons::BOLD_16)?;
    m.add("FILE_DIFF_24", icons::FILE_DIFF_24)?;
    m.add("GIT_MERGE_16", icons::GIT_MERGE_16)?;
    m.add("FILE_BADGE_16", icons::FILE_BADGE_16)?;
    m.add("FILE_SUBMODULE_16", icons::FILE_SUBMODULE_16)?;
    m.add("FILE_DIFF_16", icons::FILE_DIFF_16)?;
    m.add("STAR_FILL_16", icons::STAR_FILL_16)?;
    m.add("TRIANGLE_16", icons::TRIANGLE_16)?;
    m.add("HEADING_16", icons::HEADING_16)?;
    m.add("FILTER_REMOVE_16", icons::FILTER_REMOVE_16)?;
    m.add("FEED_REPO_16", icons::FEED_REPO_16)?;
    m.add("FOLD_16", icons::FOLD_16)?;
    m.add("READ_24", icons::READ_24)?;
    m.add("CHAT_16", icons::CHAT_16)?;
    m.add("PROJECT_SYMLINK_16", icons::PROJECT_SYMLINK_16)?;
    m.add("ISSUE_TRACKED_BY_16", icons::ISSUE_TRACKED_BY_16)?;
    m.add("WRAP_16", icons::WRAP_16)?;
    m.add("CODE_REVIEW_16", icons::CODE_REVIEW_16)?;
    m.add("CLOUD_OFFLINE_16", icons::CLOUD_OFFLINE_16)?;
    m.add("PENCIL_AI_24", icons::PENCIL_AI_24)?;
    m.add("CHEVRON_UP_16", icons::CHEVRON_UP_16)?;
    m.add("SCREEN_NORMAL_24", icons::SCREEN_NORMAL_24)?;
    m.add("TELESCOPE_FILL_24", icons::TELESCOPE_FILL_24)?;
    m.add("REPORT_24", icons::REPORT_24)?;
    m.add("SMILEY_GRIN_24", icons::SMILEY_GRIN_24)?;
    m.add("THUMBSUP_16", icons::THUMBSUP_16)?;
    m.add("MAXIMIZE_16", icons::MAXIMIZE_16)?;
    m.add("MENTION_24", icons::MENTION_24)?;
    m.add("CROSSHAIRS_24", icons::CROSSHAIRS_24)?;
    m.add("ALERT_FILL_16", icons::ALERT_FILL_16)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_16",
        icons::FILE_DIRECTORY_OPEN_FILL_16,
    )?;
    m.add("CACHE_16", icons::CACHE_16)?;
    m.add("THUMBSDOWN_24", icons::THUMBSDOWN_24)?;
    m.add("BELL_SLASH_24", icons::BELL_SLASH_24)?;
    m.add(
        "GIT_PULL_REQUEST_CLOSED_16",
        icons::GIT_PULL_REQUEST_CLOSED_16,
    )?;
    m.add("PIN_24", icons::PIN_24)?;
    m.add("FLAME_16", icons::FLAME_16)?;
    m.add("UNLOCK_24", icons::UNLOCK_24)?;
    m.add("CODE_SQUARE_24", icons::CODE_SQUARE_24)?;
    m.add("COPILOT_ERROR_16", icons::COPILOT_ERROR_16)?;
    m.add("X_12", icons::X_12)?;
    m.add("UNVERIFIED_16", icons::UNVERIFIED_16)?;
    m.add("VERIFIED_16", icons::VERIFIED_16)?;
    m.add("GIT_BRANCH_16", icons::GIT_BRANCH_16)?;
    m.add("SIGN_OUT_16", icons::SIGN_OUT_16)?;
    m.add("COLUMNS_24", icons::COLUMNS_24)?;
    m.add("FEED_ISSUE_CLOSED_16", icons::FEED_ISSUE_CLOSED_16)?;
    m.add("CODE_OF_CONDUCT_16", icons::CODE_OF_CONDUCT_16)?;
    m.add("DISCUSSION_CLOSED_24", icons::DISCUSSION_CLOSED_24)?;
    m.add("SPACING_MEDIUM_16", icons::SPACING_MEDIUM_16)?;
    m.add("CODE_OF_CONDUCT_24", icons::CODE_OF_CONDUCT_24)?;
    m.add("NO_ENTRY_24", icons::NO_ENTRY_24)?;
    m.add("SHIELD_LOCK_16", icons::SHIELD_LOCK_16)?;
    m.add("CLOUD_OFFLINE_24", icons::CLOUD_OFFLINE_24)?;
    m.add("MAIL_24", icons::MAIL_24)?;
    m.add("CHECK_CIRCLE_16", icons::CHECK_CIRCLE_16)?;
    m.add("BLOCKED_16", icons::BLOCKED_16)?;
    m.add("PLUS_CIRCLE_16", icons::PLUS_CIRCLE_16)?;
    m.add("TRIANGLE_LEFT_24", icons::TRIANGLE_LEFT_24)?;
    m.add("SYNC_24", icons::SYNC_24)?;
    m.add("BOOLEAN_ON_24", icons::BOOLEAN_ON_24)?;
    m.add("FILE_REMOVED_24", icons::FILE_REMOVED_24)?;
    m.add("UNDO_16", icons::UNDO_16)?;
    m.add("SPONSOR_TIERS_16", icons::SPONSOR_TIERS_16)?;
    m.add("UNFOLD_16", icons::UNFOLD_16)?;
    m.add("FILE_CHECK_24", icons::FILE_CHECK_24)?;
    m.add("NOTE_24", icons::NOTE_24)?;
    m.add("FILE_MOVED_24", icons::FILE_MOVED_24)?;
    m.add("REPLY_16", icons::REPLY_16)?;
    m.add("BOOK_LOCKED_16", icons::BOOK_LOCKED_16)?;
    m.add("ARROW_BOTH_16", icons::ARROW_BOTH_16)?;
    m.add("ISSUE_CLOSED_16", icons::ISSUE_CLOSED_16)?;
    m.add("LAW_24", icons::LAW_24)?;
    m.add("REPO_DELETE_24", icons::REPO_DELETE_24)?;
    m.add("FILE_CHECK_16", icons::FILE_CHECK_16)?;
    m.add("GIFT_16", icons::GIFT_16)?;
    m.add("REPO_CLONE_24", icons::REPO_CLONE_24)?;
    m.add("HOME_16", icons::HOME_16)?;
    m.add("DOT_FILL_24", icons::DOT_FILL_24)?;
    m.add("ISSUE_DRAFT_24", icons::ISSUE_DRAFT_24)?;
    m.add("BOOKMARK_SLASH_16", icons::BOOKMARK_SLASH_16)?;
    Ok(())
}
