// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_0(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("HORIZONTAL_RULE_24", icons::HORIZONTAL_RULE_24)?;
    m.add("BRIEFCASE_24", icons::BRIEFCASE_24)?;
    m.add("HEART_24", icons::HEART_24)?;
    m.add("BOOLEAN_ON_24", icons::BOOLEAN_ON_24)?;
    m.add("ISSUE_CLOSED_24", icons::ISSUE_CLOSED_24)?;
    m.add("BRIEFCASE_16", icons::BRIEFCASE_16)?;
    m.add("DIFF_IGNORED_24", icons::DIFF_IGNORED_24)?;
    m.add("ITALIC_24", icons::ITALIC_24)?;
    m.add("GRAPH_BAR_HORIZONTAL_24", icons::GRAPH_BAR_HORIZONTAL_24)?;
    m.add("FILE_DIFF_24", icons::FILE_DIFF_24)?;
    m.add("KEY_ASTERISK_24", icons::KEY_ASTERISK_24)?;
    m.add("CLOCK_FILL_24", icons::CLOCK_FILL_24)?;
    m.add("FEED_PERSON_16", icons::FEED_PERSON_16)?;
    m.add("MOVE_TO_TOP_24", icons::MOVE_TO_TOP_24)?;
    m.add("HOURGLASS_24", icons::HOURGLASS_24)?;
    m.add("DUPLICATE_24", icons::DUPLICATE_24)?;
    m.add("ISSUE_TRACKS_24", icons::ISSUE_TRACKS_24)?;
    m.add("DIAMOND_16", icons::DIAMOND_16)?;
    m.add("FILE_CODE_24", icons::FILE_CODE_24)?;
    m.add("TELESCOPE_16", icons::TELESCOPE_16)?;
    m.add("REPO_LOCKED_16", icons::REPO_LOCKED_16)?;
    m.add("FILE_BINARY_16", icons::FILE_BINARY_16)?;
    m.add("SMILEY_FRUSTRATED_16", icons::SMILEY_FRUSTRATED_16)?;
    m.add("TROPHY_16", icons::TROPHY_16)?;
    m.add("MAIL_24", icons::MAIL_24)?;
    m.add("THREE_BARS_24", icons::THREE_BARS_24)?;
    m.add("GRAPH_24", icons::GRAPH_24)?;
    m.add("PASSKEY_FILL_16", icons::PASSKEY_FILL_16)?;
    m.add("BOOK_16", icons::BOOK_16)?;
    m.add("BOOKMARK_FILL_24", icons::BOOKMARK_FILL_24)?;
    m.add("UNLOCK_24", icons::UNLOCK_24)?;
    m.add("TRIANGLE_RIGHT_16", icons::TRIANGLE_RIGHT_16)?;
    m.add("GIT_BRANCH_CHECK_16", icons::GIT_BRANCH_CHECK_16)?;
    m.add("PLAY_16", icons::PLAY_16)?;
    m.add("REPO_CLONE_16", icons::REPO_CLONE_16)?;
    m.add("ISSUE_DRAFT_24", icons::ISSUE_DRAFT_24)?;
    m.add("DISCUSSION_DUPLICATE_24", icons::DISCUSSION_DUPLICATE_24)?;
    m.add("APPS_24", icons::APPS_24)?;
    m.add("BROADCAST_24", icons::BROADCAST_24)?;
    m.add("SQUIRREL_24", icons::SQUIRREL_24)?;
    m.add("ORGANIZATION_24", icons::ORGANIZATION_24)?;
    m.add("ALERT_FILL_12", icons::ALERT_FILL_12)?;
    m.add("CPU_16", icons::CPU_16)?;
    m.add(
        "GIT_PULL_REQUEST_LOCKED_16",
        icons::GIT_PULL_REQUEST_LOCKED_16,
    )?;
    m.add("SIGN_IN_24", icons::SIGN_IN_24)?;
    m.add("FEED_STAR_16", icons::FEED_STAR_16)?;
    m.add("PERSON_ADD_16", icons::PERSON_ADD_16)?;
    m.add("ARROW_UP_LEFT_24", icons::ARROW_UP_LEFT_24)?;
    m.add("CHECKLIST_24", icons::CHECKLIST_24)?;
    m.add("ZAP_16", icons::ZAP_16)?;
    m.add("FLAG_24", icons::FLAG_24)?;
    m.add("MINIMIZE_24", icons::MINIMIZE_24)?;
    m.add("LOOP_24", icons::LOOP_24)?;
    m.add("EXCLAMATION_16", icons::EXCLAMATION_16)?;
    m.add("VSCODE_16", icons::VSCODE_16)?;
    m.add("HOME_FILL_16", icons::HOME_FILL_16)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_24",
        icons::FILE_DIRECTORY_OPEN_FILL_24,
    )?;
    m.add("COPILOT_16", icons::COPILOT_16)?;
    m.add("GIT_PULL_REQUEST_24", icons::GIT_PULL_REQUEST_24)?;
    m.add("SCREEN_NORMAL_16", icons::SCREEN_NORMAL_16)?;
    m.add("CIRCLE_24", icons::CIRCLE_24)?;
    m.add("FEED_TROPHY_16", icons::FEED_TROPHY_16)?;
    m.add("HASH_24", icons::HASH_24)?;
    m.add("GIFT_16", icons::GIFT_16)?;
    m.add("FLAME_24", icons::FLAME_24)?;
    m.add("COMMENT_AI_16", icons::COMMENT_AI_16)?;
    m.add("BOOKMARK_SLASH_FILL_24", icons::BOOKMARK_SLASH_FILL_24)?;
    m.add("CLOCK_16", icons::CLOCK_16)?;
    m.add("CHECKBOX_24", icons::CHECKBOX_24)?;
    m.add("COMMENT_DISCUSSION_16", icons::COMMENT_DISCUSSION_16)?;
    m.add("GIT_COMMIT_24", icons::GIT_COMMIT_24)?;
    m.add("REPLY_24", icons::REPLY_24)?;
    m.add("UNLOCK_16", icons::UNLOCK_16)?;
    m.add("REPO_PUSH_16", icons::REPO_PUSH_16)?;
    m.add("CHECK_CIRCLE_FILL_12", icons::CHECK_CIRCLE_FILL_12)?;
    m.add("FILE_BINARY_24", icons::FILE_BINARY_24)?;
    m.add("COMMENT_16", icons::COMMENT_16)?;
    m.add("ARROW_BOTH_24", icons::ARROW_BOTH_24)?;
    m.add("SYNC_24", icons::SYNC_24)?;
    m.add("SQUARE_FILL_24", icons::SQUARE_FILL_24)?;
    m.add("CHECKLIST_16", icons::CHECKLIST_16)?;
    m.add("DEPENDABOT_16", icons::DEPENDABOT_16)?;
    m.add("CODE_SQUARE_16", icons::CODE_SQUARE_16)?;
    m.add("ACCESSIBILITY_INSET_24", icons::ACCESSIBILITY_INSET_24)?;
    m.add("PIN_24", icons::PIN_24)?;
    m.add("ARCHIVE_16", icons::ARCHIVE_16)?;
    m.add("EYE_16", icons::EYE_16)?;
    m.add("HORIZONTAL_RULE_16", icons::HORIZONTAL_RULE_16)?;
    m.add("SMILEY_FRUSTRATED_24", icons::SMILEY_FRUSTRATED_24)?;
    m.add("BOOLEAN_ON_16", icons::BOOLEAN_ON_16)?;
    m.add("THUMBSDOWN_16", icons::THUMBSDOWN_16)?;
    m.add("ISSUE_TRACKED_BY_24", icons::ISSUE_TRACKED_BY_24)?;
    m.add("STRIKETHROUGH_16", icons::STRIKETHROUGH_16)?;
    m.add("X_24", icons::X_24)?;
    m.add("FILE_ADDED_24", icons::FILE_ADDED_24)?;
    m.add("ARROW_LEFT_16", icons::ARROW_LEFT_16)?;
    m.add("SCREEN_FULL_24", icons::SCREEN_FULL_24)?;
    m.add("BROWSER_24", icons::BROWSER_24)?;
    m.add("IMAGE_16", icons::IMAGE_16)?;
    m.add("INBOX_24", icons::INBOX_24)?;
    m.add("PROJECT_16", icons::PROJECT_16)?;
    m.add("REPO_FORKED_LOCKED_24", icons::REPO_FORKED_LOCKED_24)?;
    m.add("TAB_EXTERNAL_24", icons::TAB_EXTERNAL_24)?;
    m.add(
        "GIT_PULL_REQUEST_CLOSED_24",
        icons::GIT_PULL_REQUEST_CLOSED_24,
    )?;
    m.add("DIFF_IGNORED_16", icons::DIFF_IGNORED_16)?;
    m.add("FILTER_REMOVE_24", icons::FILTER_REMOVE_24)?;
    m.add("TRASH_16", icons::TRASH_16)?;
    m.add("CROSSHAIRS_24", icons::CROSSHAIRS_24)?;
    m.add("GLOBE_24", icons::GLOBE_24)?;
    m.add("CROSS_REFERENCE_16", icons::CROSS_REFERENCE_16)?;
    m.add("CLOCK_24", icons::CLOCK_24)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_16",
        icons::FILE_DIRECTORY_SYMLINK_16,
    )?;
    m.add("APPS_16", icons::APPS_16)?;
    m.add("ORGANIZATION_16", icons::ORGANIZATION_16)?;
    m.add("SKIP_FILL_24", icons::SKIP_FILL_24)?;
    m.add("PAPER_AIRPLANE_24", icons::PAPER_AIRPLANE_24)?;
    m.add("WRAP_24", icons::WRAP_24)?;
    m.add("DIFF_REMOVED_24", icons::DIFF_REMOVED_24)?;
    m.add("SQUIRREL_16", icons::SQUIRREL_16)?;
    m.add("ITERATIONS_24", icons::ITERATIONS_24)?;
    m.add("READ_16", icons::READ_16)?;
    m.add("FILE_DIRECTORY_FILL_16", icons::FILE_DIRECTORY_FILL_16)?;
    m.add("FOCUS_CENTER_16", icons::FOCUS_CENTER_16)?;
    m.add("UNDO_24", icons::UNDO_24)?;
    m.add("FISCAL_HOST_16", icons::FISCAL_HOST_16)?;
    m.add("TYPOGRAPHY_24", icons::TYPOGRAPHY_24)?;
    m.add("LOGO_GIST_24", icons::LOGO_GIST_24)?;
    m.add("SHIELD_CHECK_24", icons::SHIELD_CHECK_24)?;
    m.add("ARROW_UP_RIGHT_16", icons::ARROW_UP_RIGHT_16)?;
    m.add("CLOUD_24", icons::CLOUD_24)?;
    m.add("PERSON_24", icons::PERSON_24)?;
    m.add("REPO_CLONE_24", icons::REPO_CLONE_24)?;
    m.add("FILE_REMOVED_24", icons::FILE_REMOVED_24)?;
    m.add("WORKFLOW_24", icons::WORKFLOW_24)?;
    m.add("DOWNLOAD_24", icons::DOWNLOAD_24)?;
    m.add("GOAL_16", icons::GOAL_16)?;
    m.add("SHIELD_24", icons::SHIELD_24)?;
    m.add("SMILEY_FROWN_16", icons::SMILEY_FROWN_16)?;
    m.add("VERIFIED_24", icons::VERIFIED_24)?;
    m.add("SPONSOR_TIERS_24", icons::SPONSOR_TIERS_24)?;
    m.add("FILE_MOVED_16", icons::FILE_MOVED_16)?;
    m.add("FILE_BADGE_16", icons::FILE_BADGE_16)?;
    m.add("SMILEY_24", icons::SMILEY_24)?;
    m.add("CIRCLE_SLASH_24", icons::CIRCLE_SLASH_24)?;
    m.add("NOTE_16", icons::NOTE_16)?;
    m.add("PLUS_CIRCLE_24", icons::PLUS_CIRCLE_24)?;
    m.add("REPO_DELETE_24", icons::REPO_DELETE_24)?;
    m.add("NORTH_STAR_24", icons::NORTH_STAR_24)?;
    m.add("CHEVRON_LEFT_16", icons::CHEVRON_LEFT_16)?;
    m.add("DEVICE_CAMERA_24", icons::DEVICE_CAMERA_24)?;
    m.add("HEART_FILL_24", icons::HEART_FILL_24)?;
    m.add(
        "GIT_PULL_REQUEST_CLOSED_16",
        icons::GIT_PULL_REQUEST_CLOSED_16,
    )?;
    m.add("DISCUSSION_DUPLICATE_16", icons::DISCUSSION_DUPLICATE_16)?;
    m.add("UNWRAP_16", icons::UNWRAP_16)?;
    m.add("THREE_BARS_16", icons::THREE_BARS_16)?;
    m.add("SIGN_OUT_24", icons::SIGN_OUT_24)?;
    m.add("ARROW_DOWN_LEFT_24", icons::ARROW_DOWN_LEFT_24)?;
    m.add("SPLIT_VIEW_24", icons::SPLIT_VIEW_24)?;
    m.add("GIT_COMPARE_16", icons::GIT_COMPARE_16)?;
    m.add("SUN_24", icons::SUN_24)?;
    m.add("CODESCAN_CHECKMARK_16", icons::CODESCAN_CHECKMARK_16)?;
    m.add("PACKAGE_DEPENDENCIES_16", icons::PACKAGE_DEPENDENCIES_16)?;
    m.add("FILE_SUBMODULE_24", icons::FILE_SUBMODULE_24)?;
    m.add("ARROW_DOWN_16", icons::ARROW_DOWN_16)?;
    m.add("SEARCH_16", icons::SEARCH_16)?;
    m.add("X_CIRCLE_FILL_24", icons::X_CIRCLE_FILL_24)?;
    m.add("SPARKLE_FILL_24", icons::SPARKLE_FILL_24)?;
    m.add("PERSON_16", icons::PERSON_16)?;
    m.add("SHARE_24", icons::SHARE_24)?;
    m.add("CHECKBOX_FILL_24", icons::CHECKBOX_FILL_24)?;
    m.add("GIT_MERGE_16", icons::GIT_MERGE_16)?;
    m.add("MEGAPHONE_24", icons::MEGAPHONE_24)?;
    m.add("ISSUE_TRACKS_16", icons::ISSUE_TRACKS_16)?;
    m.add("UNDO_16", icons::UNDO_16)?;
    m.add("HISTORY_16", icons::HISTORY_16)?;
    m.add("REPO_TEMPLATE_24", icons::REPO_TEMPLATE_24)?;
    m.add("REPO_FORKED_LOCKED_16", icons::REPO_FORKED_LOCKED_16)?;
    m.add("TABLE_16", icons::TABLE_16)?;
    m.add("SHIELD_X_16", icons::SHIELD_X_16)?;
    m.add("METER_24", icons::METER_24)?;
    m.add("FLOWCHART_16", icons::FLOWCHART_16)?;
    m.add("COMMENT_DISCUSSION_24", icons::COMMENT_DISCUSSION_24)?;
    m.add("SPARKLE_16", icons::SPARKLE_16)?;
    m.add("SIDEBAR_COLLAPSE_16", icons::SIDEBAR_COLLAPSE_16)?;
    m.add("GEAR_24", icons::GEAR_24)?;
    m.add("FEED_HEART_16", icons::FEED_HEART_16)?;
    m.add("CLOUD_16", icons::CLOUD_16)?;
    m.add("PIN_SLASH_16", icons::PIN_SLASH_16)?;
    m.add("LIGHT_BULB_16", icons::LIGHT_BULB_16)?;
    m.add("GIT_PULL_REQUEST_16", icons::GIT_PULL_REQUEST_16)?;
    m.add("CLOUD_OFFLINE_24", icons::CLOUD_OFFLINE_24)?;
    m.add("LOCK_24", icons::LOCK_24)?;
    m.add("ARROW_SWITCH_24", icons::ARROW_SWITCH_24)?;
    m.add("SPARKLES_FILL_24", icons::SPARKLES_FILL_24)?;
    m.add("DIAMOND_24", icons::DIAMOND_24)?;
    m.add("CODE_REVIEW_24", icons::CODE_REVIEW_24)?;
    m.add("BELL_SLASH_16", icons::BELL_SLASH_16)?;
    m.add("FEED_REPO_16", icons::FEED_REPO_16)?;
    m.add("KEY_ASTERISK_16", icons::KEY_ASTERISK_16)?;
    m.add("CODESCAN_16", icons::CODESCAN_16)?;
    Ok(())
}
