// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_1(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("CONTAINER_24", icons::CONTAINER_24)?;
    m.add(
        "GIT_PULL_REQUEST_DRAFT_24",
        icons::GIT_PULL_REQUEST_DRAFT_24,
    )?;
    m.add("FEED_TROPHY_16", icons::FEED_TROPHY_16)?;
    m.add("X_CIRCLE_FILL_24", icons::X_CIRCLE_FILL_24)?;
    m.add("SUN_24", icons::SUN_24)?;
    m.add("PAPERCLIP_24", icons::PAPERCLIP_24)?;
    m.add("ARROW_BOTH_24", icons::ARROW_BOTH_24)?;
    m.add("CHECKLIST_24", icons::CHECKLIST_24)?;
    m.add("WORKFLOW_16", icons::WORKFLOW_16)?;
    m.add("X_CIRCLE_24", icons::X_CIRCLE_24)?;
    m.add("UNWRAP_24", icons::UNWRAP_24)?;
    m.add("CHEVRON_RIGHT_12", icons::CHEVRON_RIGHT_12)?;
    m.add("ACCESSIBILITY_INSET_24", icons::ACCESSIBILITY_INSET_24)?;
    m.add("STACK_CHECK_16", icons::STACK_CHECK_16)?;
    m.add("BEAKER_16", icons::BEAKER_16)?;
    m.add("CPU_24", icons::CPU_24)?;
    m.add("DEVICE_DESKTOP_16", icons::DEVICE_DESKTOP_16)?;
    m.add("STOPWATCH_16", icons::STOPWATCH_16)?;
    m.add("CHAT_LOCKED_16", icons::CHAT_LOCKED_16)?;
    m.add("INFO_16", icons::INFO_16)?;
    m.add("ROCKET_24", icons::ROCKET_24)?;
    m.add("INFO_24", icons::INFO_24)?;
    m.add("MOVE_TO_TOP_24", icons::MOVE_TO_TOP_24)?;
    m.add("REPO_FORKED_LOCKED_24", icons::REPO_FORKED_LOCKED_24)?;
    m.add("HISTORY_16", icons::HISTORY_16)?;
    m.add("STOPWATCH_24", icons::STOPWATCH_24)?;
    m.add("PLUS_24", icons::PLUS_24)?;
    m.add("SIDEBAR_EXPAND_24", icons::SIDEBAR_EXPAND_24)?;
    m.add("GRAPH_BAR_VERTICAL_24", icons::GRAPH_BAR_VERTICAL_24)?;
    m.add("LOCATION_16", icons::LOCATION_16)?;
    m.add("SMILEY_GRIN_16", icons::SMILEY_GRIN_16)?;
    m.add("LOG_24", icons::LOG_24)?;
    m.add("INFINITY_24", icons::INFINITY_24)?;
    m.add("ARROW_UP_16", icons::ARROW_UP_16)?;
    m.add("GIT_MERGE_24", icons::GIT_MERGE_24)?;
    m.add("PROJECT_ROADMAP_16", icons::PROJECT_ROADMAP_16)?;
    m.add("COMMAND_PALETTE_24", icons::COMMAND_PALETTE_24)?;
    m.add("ARROW_DOWN_LEFT_16", icons::ARROW_DOWN_LEFT_16)?;
    m.add("TOOLS_24", icons::TOOLS_24)?;
    m.add("LOCKUP_GITHUB_24", icons::LOCKUP_GITHUB_24)?;
    m.add("PROJECT_16", icons::PROJECT_16)?;
    m.add("X_CIRCLE_16", icons::X_CIRCLE_16)?;
    m.add("DEVICE_CAMERA_VIDEO_24", icons::DEVICE_CAMERA_VIDEO_24)?;
    m.add("PENCIL_AI_16", icons::PENCIL_AI_16)?;
    m.add("ZOOM_OUT_24", icons::ZOOM_OUT_24)?;
    m.add("SIDEBAR_EXPAND_16", icons::SIDEBAR_EXPAND_16)?;
    m.add("UNMUTE_16", icons::UNMUTE_16)?;
    m.add("DOWNLOAD_16", icons::DOWNLOAD_16)?;
    m.add("COMMENT_LOCKED_16", icons::COMMENT_LOCKED_16)?;
    m.add("SORT_ASC_16", icons::SORT_ASC_16)?;
    m.add("REL_FILE_PATH_16", icons::REL_FILE_PATH_16)?;
    m.add(
        "GIT_PULL_REQUEST_UNLISTED_16",
        icons::GIT_PULL_REQUEST_UNLISTED_16,
    )?;
    m.add("COPILOT_24", icons::COPILOT_24)?;
    m.add("SINGLE_SELECT_24", icons::SINGLE_SELECT_24)?;
    m.add("APPS_16", icons::APPS_16)?;
    m.add("ARROW_SWITCH_16", icons::ARROW_SWITCH_16)?;
    m.add("PLUS_16", icons::PLUS_16)?;
    m.add("STAR_24", icons::STAR_24)?;
    m.add("UNLINK_16", icons::UNLINK_16)?;
    m.add("ARROW_DOWN_24", icons::ARROW_DOWN_24)?;
    m.add("TROPHY_16", icons::TROPHY_16)?;
    m.add("CODESCAN_CHECKMARK_16", icons::CODESCAN_CHECKMARK_16)?;
    m.add("ARROW_LEFT_16", icons::ARROW_LEFT_16)?;
    m.add("PERSON_ADD_24", icons::PERSON_ADD_24)?;
    m.add("QUESTION_16", icons::QUESTION_16)?;
    m.add("DIFF_24", icons::DIFF_24)?;
    m.add("REPO_LOCKED_24", icons::REPO_LOCKED_24)?;
    m.add("HEART_FILL_16", icons::HEART_FILL_16)?;
    m.add("ISSUE_REOPENED_16", icons::ISSUE_REOPENED_16)?;
    m.add("KEY_ASTERISK_16", icons::KEY_ASTERISK_16)?;
    m.add("BEAKER_24", icons::BEAKER_24)?;
    m.add("CHECKBOX_FILL_24", icons::CHECKBOX_FILL_24)?;
    m.add("CALENDAR_16", icons::CALENDAR_16)?;
    m.add("BELL_FILL_16", icons::BELL_FILL_16)?;
    m.add("REPO_24", icons::REPO_24)?;
    m.add("FISCAL_HOST_16", icons::FISCAL_HOST_16)?;
    m.add("COPILOT_48", icons::COPILOT_48)?;
    m.add("GRAPH_STACKED_AREA_16", icons::GRAPH_STACKED_AREA_16)?;
    m.add("FLAME_24", icons::FLAME_24)?;
    m.add("PACKAGE_DEPENDENTS_24", icons::PACKAGE_DEPENDENTS_24)?;
    m.add("DIFF_MODIFIED_16", icons::DIFF_MODIFIED_16)?;
    m.add("ACCESSIBILITY_24", icons::ACCESSIBILITY_24)?;
    m.add(
        "GIT_PULL_REQUEST_CLOSED_24",
        icons::GIT_PULL_REQUEST_CLOSED_24,
    )?;
    m.add("CHAT_ADD_24", icons::CHAT_ADD_24)?;
    m.add("ZOOM_IN_16", icons::ZOOM_IN_16)?;
    m.add("STACK_16", icons::STACK_16)?;
    m.add("TRIANGLE_CIRCLE_16", icons::TRIANGLE_CIRCLE_16)?;
    m.add("MARKDOWN_24", icons::MARKDOWN_24)?;
    m.add("UNFOLD_24", icons::UNFOLD_24)?;
    m.add("BROWSER_24", icons::BROWSER_24)?;
    m.add("METER_24", icons::METER_24)?;
    m.add("ZOOM_OUT_16", icons::ZOOM_OUT_16)?;
    m.add("SPACING_LARGE_16", icons::SPACING_LARGE_16)?;
    m.add("COMMAND_PALETTE_16", icons::COMMAND_PALETTE_16)?;
    m.add("CROSS_REFERENCE_16", icons::CROSS_REFERENCE_16)?;
    m.add("SLIDERS_16", icons::SLIDERS_16)?;
    m.add("ROWS_16", icons::ROWS_16)?;
    m.add("FOLD_UP_16", icons::FOLD_UP_16)?;
    m.add("COPILOT_16", icons::COPILOT_16)?;
    m.add("NO_ENTRY_16", icons::NO_ENTRY_16)?;
    m.add("STACK_REMOVE_16", icons::STACK_REMOVE_16)?;
    m.add("NO_ENTRY_FILL_12", icons::NO_ENTRY_FILL_12)?;
    m.add("SPARKLES_FILL_24", icons::SPARKLES_FILL_24)?;
    m.add("BLOCKED_24", icons::BLOCKED_24)?;
    m.add("CREDIT_CARD_16", icons::CREDIT_CARD_16)?;
    m.add("BOOKMARK_16", icons::BOOKMARK_16)?;
    m.add("CPU_16", icons::CPU_16)?;
    m.add("FILE_DIRECTORY_FILL_24", icons::FILE_DIRECTORY_FILL_24)?;
    m.add("PACKAGE_DEPENDENTS_16", icons::PACKAGE_DEPENDENTS_16)?;
    m.add("SYNC_16", icons::SYNC_16)?;
    m.add("KEY_ASTERISK_24", icons::KEY_ASTERISK_24)?;
    m.add("FILTER_REMOVE_24", icons::FILTER_REMOVE_24)?;
    m.add("FEED_TAG_16", icons::FEED_TAG_16)?;
    m.add("SQUARE_24", icons::SQUARE_24)?;
    m.add("AI_MODEL_16", icons::AI_MODEL_16)?;
    m.add("SERVER_24", icons::SERVER_24)?;
    m.add("BELL_16", icons::BELL_16)?;
    m.add("BELL_SLASH_16", icons::BELL_SLASH_16)?;
    m.add("REPO_DELETED_16", icons::REPO_DELETED_16)?;
    m.add("ARROW_UP_RIGHT_16", icons::ARROW_UP_RIGHT_16)?;
    m.add("TYPOGRAPHY_16", icons::TYPOGRAPHY_16)?;
    m.add("GIT_BRANCH_24", icons::GIT_BRANCH_24)?;
    m.add("DOT_16", icons::DOT_16)?;
    m.add("GRABBER_24", icons::GRABBER_24)?;
    m.add("DEVICE_MOBILE_16", icons::DEVICE_MOBILE_16)?;
    m.add("PASSKEY_FILL_16", icons::PASSKEY_FILL_16)?;
    m.add("CIRCLE_SLASH_16", icons::CIRCLE_SLASH_16)?;
    m.add("NORTH_STAR_16", icons::NORTH_STAR_16)?;
    m.add("CHAT_QUESTION_24", icons::CHAT_QUESTION_24)?;
    m.add("REL_FILE_PATH_24", icons::REL_FILE_PATH_24)?;
    m.add("MOVE_TO_BOTTOM_24", icons::MOVE_TO_BOTTOM_24)?;
    m.add("TAG_24", icons::TAG_24)?;
    m.add("FILE_CODE_24", icons::FILE_CODE_24)?;
    m.add("TRIANGLE_CIRCLE_24", icons::TRIANGLE_CIRCLE_24)?;
    m.add("PAPER_AIRPLANE_24", icons::PAPER_AIRPLANE_24)?;
    m.add("REPO_TEMPLATE_16", icons::REPO_TEMPLATE_16)?;
    m.add("ACCESSIBILITY_16", icons::ACCESSIBILITY_16)?;
    m.add("SHARE_ANDROID_16", icons::SHARE_ANDROID_16)?;
    m.add("PEOPLE_24", icons::PEOPLE_24)?;
    m.add("DISCUSSION_CLOSED_16", icons::DISCUSSION_CLOSED_16)?;
    m.add("ISSUE_TRACKS_24", icons::ISSUE_TRACKS_24)?;
    m.add("GRABBER_16", icons::GRABBER_16)?;
    m.add("AGENT_16", icons::AGENT_16)?;
    m.add("COMMENT_24", icons::COMMENT_24)?;
    m.add("CODESPACES_16", icons::CODESPACES_16)?;
    m.add("NOTE_16", icons::NOTE_16)?;
    m.add("PENCIL_24", icons::PENCIL_24)?;
    m.add("UNREAD_24", icons::UNREAD_24)?;
    m.add("PERSON_CURSOR_16", icons::PERSON_CURSOR_16)?;
    m.add("CIRCLE_16", icons::CIRCLE_16)?;
    m.add("GIFT_24", icons::GIFT_24)?;
    m.add("DEVICES_24", icons::DEVICES_24)?;
    m.add("COMMENT_AI_24", icons::COMMENT_AI_24)?;
    m.add("ELLIPSIS_24", icons::ELLIPSIS_24)?;
    m.add("SHARE_16", icons::SHARE_16)?;
    m.add("TAB_EXTERNAL_24", icons::TAB_EXTERNAL_24)?;
    m.add("INBOX_24", icons::INBOX_24)?;
    m.add("LIGHT_BULB_16", icons::LIGHT_BULB_16)?;
    m.add(
        "TRACKED_BY_CLOSED_NOT_PLANNED_16",
        icons::TRACKED_BY_CLOSED_NOT_PLANNED_16,
    )?;
    m.add("REPORT_16", icons::REPORT_16)?;
    m.add("REPO_FORKED_16", icons::REPO_FORKED_16)?;
    m.add("KEBAB_HORIZONTAL_24", icons::KEBAB_HORIZONTAL_24)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_24",
        icons::TRACKED_BY_CLOSED_COMPLETED_24,
    )?;
    m.add("HOURGLASS_24", icons::HOURGLASS_24)?;
    m.add("DICE_16", icons::DICE_16)?;
    m.add("PAPER_AIRPLANE_16", icons::PAPER_AIRPLANE_16)?;
    m.add("STAR_16", icons::STAR_16)?;
    m.add("SORT_ASC_24", icons::SORT_ASC_24)?;
    m.add("FEED_HEART_16", icons::FEED_HEART_16)?;
    m.add("EXCLAMATION_16", icons::EXCLAMATION_16)?;
    m.add("GRAPH_BAR_HORIZONTAL_24", icons::GRAPH_BAR_HORIZONTAL_24)?;
    m.add("PAINTBRUSH_24", icons::PAINTBRUSH_24)?;
    m.add("MULTI_SELECT_24", icons::MULTI_SELECT_24)?;
    m.add("GIT_COMMIT_16", icons::GIT_COMMIT_16)?;
    m.add("HEART_FILL_24", icons::HEART_FILL_24)?;
    m.add("DESKTOP_DOWNLOAD_24", icons::DESKTOP_DOWNLOAD_24)?;
    m.add("BUG_24", icons::BUG_24)?;
    m.add("TRIANGLE_FILL_16", icons::TRIANGLE_FILL_16)?;
    m.add("HOME_24", icons::HOME_24)?;
    m.add("ARROW_RIGHT_24", icons::ARROW_RIGHT_24)?;
    m.add("PERSON_24", icons::PERSON_24)?;
    m.add("DOWNLOAD_24", icons::DOWNLOAD_24)?;
    m.add("CHEVRON_LEFT_24", icons::CHEVRON_LEFT_24)?;
    m.add("REPO_LOCKED_16", icons::REPO_LOCKED_16)?;
    m.add("ID_BADGE_16", icons::ID_BADGE_16)?;
    m.add("FEED_PERSON_16", icons::FEED_PERSON_16)?;
    m.add("SINGLE_SELECT_16", icons::SINGLE_SELECT_16)?;
    m.add("GIT_COMPARE_24", icons::GIT_COMPARE_24)?;
    m.add("TABLE_16", icons::TABLE_16)?;
    m.add("CHECKLIST_16", icons::CHECKLIST_16)?;
    m.add("ARROW_DOWN_RIGHT_16", icons::ARROW_DOWN_RIGHT_16)?;
    m.add("TERMINAL_16", icons::TERMINAL_16)?;
    m.add("SPACING_SMALL_16", icons::SPACING_SMALL_16)?;
    m.add("DISCUSSION_OUTDATED_16", icons::DISCUSSION_OUTDATED_16)?;
    m.add("SIGN_IN_24", icons::SIGN_IN_24)?;
    m.add("FILE_ADDED_16", icons::FILE_ADDED_16)?;
    m.add("CLOUD_16", icons::CLOUD_16)?;
    m.add("TRASH_16", icons::TRASH_16)?;
    m.add("SCREEN_FULL_24", icons::SCREEN_FULL_24)?;
    m.add("INBOX_FILL_24", icons::INBOX_FILL_24)?;
    Ok(())
}
