// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_0(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("PACKAGE_DEPENDENTS_24", icons::PACKAGE_DEPENDENTS_24)?;
    m.add("CHEVRON_DOWN_24", icons::CHEVRON_DOWN_24)?;
    m.add("FILE_SYMLINK_FILE_24", icons::FILE_SYMLINK_FILE_24)?;
    m.add("FOLD_24", icons::FOLD_24)?;
    m.add("FEED_STAR_16", icons::FEED_STAR_16)?;
    m.add("SORT_DESC_16", icons::SORT_DESC_16)?;
    m.add("HASH_24", icons::HASH_24)?;
    m.add("PLUG_24", icons::PLUG_24)?;
    m.add("FEED_PUBLIC_16", icons::FEED_PUBLIC_16)?;
    m.add("FILE_CODE_24", icons::FILE_CODE_24)?;
    m.add("ARROW_UP_24", icons::ARROW_UP_24)?;
    m.add("SIGN_IN_24", icons::SIGN_IN_24)?;
    m.add("LOGO_GITHUB_16", icons::LOGO_GITHUB_16)?;
    m.add("REPO_CLONE_24", icons::REPO_CLONE_24)?;
    m.add("AI_MODEL_24", icons::AI_MODEL_24)?;
    m.add("WORKFLOW_16", icons::WORKFLOW_16)?;
    m.add("ALERT_FILL_16", icons::ALERT_FILL_16)?;
    m.add("SPLIT_VIEW_16", icons::SPLIT_VIEW_16)?;
    m.add("HUBOT_24", icons::HUBOT_24)?;
    m.add("FILE_BINARY_24", icons::FILE_BINARY_24)?;
    m.add("GRAPH_24", icons::GRAPH_24)?;
    m.add("CROSSHAIRS_24", icons::CROSSHAIRS_24)?;
    m.add("GRAPH_16", icons::GRAPH_16)?;
    m.add("BELL_FILL_24", icons::BELL_FILL_24)?;
    m.add("CODESPACES_24", icons::CODESPACES_24)?;
    m.add("CIRCLE_24", icons::CIRCLE_24)?;
    m.add("SQUARE_24", icons::SQUARE_24)?;
    m.add("SQUARE_FILL_16", icons::SQUARE_FILL_16)?;
    m.add("CODE_REVIEW_24", icons::CODE_REVIEW_24)?;
    m.add("CODE_OF_CONDUCT_24", icons::CODE_OF_CONDUCT_24)?;
    m.add("PIVOT_COLUMN_16", icons::PIVOT_COLUMN_16)?;
    m.add("FILE_SUBMODULE_16", icons::FILE_SUBMODULE_16)?;
    m.add("BOOKMARK_24", icons::BOOKMARK_24)?;
    m.add("SPACING_LARGE_24", icons::SPACING_LARGE_24)?;
    m.add("REPO_PUSH_24", icons::REPO_PUSH_24)?;
    m.add("SMILEY_FRUSTRATED_24", icons::SMILEY_FRUSTRATED_24)?;
    m.add("LOCK_16", icons::LOCK_16)?;
    m.add("DOT_FILL_24", icons::DOT_FILL_24)?;
    m.add("LOOP_16", icons::LOOP_16)?;
    m.add("ARROW_SWITCH_16", icons::ARROW_SWITCH_16)?;
    m.add("ARROW_DOWN_RIGHT_24", icons::ARROW_DOWN_RIGHT_24)?;
    m.add("THREE_BARS_16", icons::THREE_BARS_16)?;
    m.add("LOG_24", icons::LOG_24)?;
    m.add("CPU_24", icons::CPU_24)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_24",
        icons::FILE_DIRECTORY_OPEN_FILL_24,
    )?;
    m.add("ARROW_DOWN_24", icons::ARROW_DOWN_24)?;
    m.add("ARROW_DOWN_LEFT_16", icons::ARROW_DOWN_LEFT_16)?;
    m.add("SQUARE_CIRCLE_24", icons::SQUARE_CIRCLE_24)?;
    m.add("SHIELD_SLASH_16", icons::SHIELD_SLASH_16)?;
    m.add("ISSUE_REOPENED_16", icons::ISSUE_REOPENED_16)?;
    m.add("GOAL_16", icons::GOAL_16)?;
    m.add("ARROW_RIGHT_16", icons::ARROW_RIGHT_16)?;
    m.add("GIT_PULL_REQUEST_16", icons::GIT_PULL_REQUEST_16)?;
    m.add("NO_ENTRY_24", icons::NO_ENTRY_24)?;
    m.add("EYE_CLOSED_16", icons::EYE_CLOSED_16)?;
    m.add("SPONSOR_TIERS_24", icons::SPONSOR_TIERS_24)?;
    m.add("BLOCKED_16", icons::BLOCKED_16)?;
    m.add("BOOK_16", icons::BOOK_16)?;
    m.add("SPARKLE_16", icons::SPARKLE_16)?;
    m.add("BELL_SLASH_24", icons::BELL_SLASH_24)?;
    m.add("FLOWCHART_16", icons::FLOWCHART_16)?;
    m.add("ITERATIONS_16", icons::ITERATIONS_16)?;
    m.add("ARROW_DOWN_RIGHT_16", icons::ARROW_DOWN_RIGHT_16)?;
    m.add("REPO_LOCKED_24", icons::REPO_LOCKED_24)?;
    m.add("HORIZONTAL_RULE_24", icons::HORIZONTAL_RULE_24)?;
    m.add("HOME_24", icons::HOME_24)?;
    m.add("TOOLS_16", icons::TOOLS_16)?;
    m.add("FILE_MOVED_24", icons::FILE_MOVED_24)?;
    m.add("RUBY_16", icons::RUBY_16)?;
    m.add(
        "TRACKED_BY_CLOSED_NOT_PLANNED_16",
        icons::TRACKED_BY_CLOSED_NOT_PLANNED_16,
    )?;
    m.add("SIGN_OUT_16", icons::SIGN_OUT_16)?;
    m.add("CHECK_CIRCLE_FILL_12", icons::CHECK_CIRCLE_FILL_12)?;
    m.add("FILE_DIRECTORY_FILL_16", icons::FILE_DIRECTORY_FILL_16)?;
    m.add("FILE_MEDIA_16", icons::FILE_MEDIA_16)?;
    m.add(
        "FEED_PULL_REQUEST_OPEN_16",
        icons::FEED_PULL_REQUEST_OPEN_16,
    )?;
    m.add("MOVE_TO_START_16", icons::MOVE_TO_START_16)?;
    m.add("X_CIRCLE_FILL_12", icons::X_CIRCLE_FILL_12)?;
    m.add("COPILOT_24", icons::COPILOT_24)?;
    m.add("PACKAGE_DEPENDENTS_16", icons::PACKAGE_DEPENDENTS_16)?;
    m.add("DIFF_IGNORED_16", icons::DIFF_IGNORED_16)?;
    m.add("FEED_ISSUE_OPEN_16", icons::FEED_ISSUE_OPEN_16)?;
    m.add("REPO_DELETE_24", icons::REPO_DELETE_24)?;
    m.add("COMMAND_PALETTE_24", icons::COMMAND_PALETTE_24)?;
    m.add("HEART_24", icons::HEART_24)?;
    m.add("TRIANGLE_RIGHT_16", icons::TRIANGLE_RIGHT_16)?;
    m.add("EXCLAMATION_16", icons::EXCLAMATION_16)?;
    m.add("GIT_COMMIT_16", icons::GIT_COMMIT_16)?;
    m.add("MIRROR_24", icons::MIRROR_24)?;
    m.add("TRIANGLE_DOWN_24", icons::TRIANGLE_DOWN_24)?;
    m.add("ARROW_LEFT_16", icons::ARROW_LEFT_16)?;
    m.add("ID_BADGE_16", icons::ID_BADGE_16)?;
    m.add("SPACE_24", icons::SPACE_24)?;
    m.add("FILE_CODE_16", icons::FILE_CODE_16)?;
    m.add("NORTH_STAR_16", icons::NORTH_STAR_16)?;
    m.add("CLOCK_FILL_16", icons::CLOCK_FILL_16)?;
    m.add("TYPOGRAPHY_16", icons::TYPOGRAPHY_16)?;
    m.add("CODESCAN_CHECKMARK_16", icons::CODESCAN_CHECKMARK_16)?;
    m.add("FEED_MERGED_16", icons::FEED_MERGED_16)?;
    m.add("TASKLIST_16", icons::TASKLIST_16)?;
    m.add("NO_ENTRY_16", icons::NO_ENTRY_16)?;
    m.add("ARROW_SWITCH_24", icons::ARROW_SWITCH_24)?;
    m.add("PROJECT_16", icons::PROJECT_16)?;
    m.add("TELESCOPE_FILL_24", icons::TELESCOPE_FILL_24)?;
    m.add("UNMUTE_24", icons::UNMUTE_24)?;
    m.add("COPY_16", icons::COPY_16)?;
    m.add("GIT_BRANCH_CHECK_24", icons::GIT_BRANCH_CHECK_24)?;
    m.add("ZOOM_IN_16", icons::ZOOM_IN_16)?;
    m.add("CLOUD_OFFLINE_16", icons::CLOUD_OFFLINE_16)?;
    m.add("ROWS_24", icons::ROWS_24)?;
    m.add("COMPOSE_16", icons::COMPOSE_16)?;
    m.add("BOOKMARK_SLASH_16", icons::BOOKMARK_SLASH_16)?;
    m.add("COMMENT_AI_24", icons::COMMENT_AI_24)?;
    m.add("FOLD_DOWN_16", icons::FOLD_DOWN_16)?;
    m.add("UNWRAP_16", icons::UNWRAP_16)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_24",
        icons::TRACKED_BY_CLOSED_COMPLETED_24,
    )?;
    m.add("FILE_CHECK_24", icons::FILE_CHECK_24)?;
    m.add("SPONSOR_TIERS_16", icons::SPONSOR_TIERS_16)?;
    m.add("BROWSER_16", icons::BROWSER_16)?;
    m.add("SPACING_SMALL_24", icons::SPACING_SMALL_24)?;
    m.add("TELESCOPE_24", icons::TELESCOPE_24)?;
    m.add("TAB_EXTERNAL_16", icons::TAB_EXTERNAL_16)?;
    m.add("DIFF_24", icons::DIFF_24)?;
    m.add("PENCIL_AI_24", icons::PENCIL_AI_24)?;
    m.add("FISCAL_HOST_24", icons::FISCAL_HOST_24)?;
    m.add("BOOKMARK_FILL_24", icons::BOOKMARK_FILL_24)?;
    m.add("FILTER_REMOVE_24", icons::FILTER_REMOVE_24)?;
    m.add("TERMINAL_24", icons::TERMINAL_24)?;
    m.add("FILE_SUBMODULE_24", icons::FILE_SUBMODULE_24)?;
    m.add("VERIFIED_24", icons::VERIFIED_24)?;
    m.add("CODE_REVIEW_16", icons::CODE_REVIEW_16)?;
    m.add("X_CIRCLE_24", icons::X_CIRCLE_24)?;
    m.add("COMMENT_DISCUSSION_24", icons::COMMENT_DISCUSSION_24)?;
    m.add("SINGLE_SELECT_16", icons::SINGLE_SELECT_16)?;
    m.add("ARCHIVE_16", icons::ARCHIVE_16)?;
    m.add("TABLE_24", icons::TABLE_24)?;
    m.add("PAPER_AIRPLANE_24", icons::PAPER_AIRPLANE_24)?;
    m.add("DIFF_ADDED_16", icons::DIFF_ADDED_16)?;
    m.add("COPILOT_ERROR_16", icons::COPILOT_ERROR_16)?;
    m.add("PEOPLE_16", icons::PEOPLE_16)?;
    m.add("MINIMIZE_24", icons::MINIMIZE_24)?;
    m.add("HORIZONTAL_RULE_16", icons::HORIZONTAL_RULE_16)?;
    m.add("CHEVRON_UP_24", icons::CHEVRON_UP_24)?;
    m.add("DIFF_REMOVED_16", icons::DIFF_REMOVED_16)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_16",
        icons::FILE_DIRECTORY_OPEN_FILL_16,
    )?;
    m.add("SMILEY_NEUTRAL_16", icons::SMILEY_NEUTRAL_16)?;
    m.add("DISCUSSION_DUPLICATE_16", icons::DISCUSSION_DUPLICATE_16)?;
    m.add("DISCUSSION_DUPLICATE_24", icons::DISCUSSION_DUPLICATE_24)?;
    m.add("LAW_16", icons::LAW_16)?;
    m.add("ARROW_DOWN_LEFT_24", icons::ARROW_DOWN_LEFT_24)?;
    m.add("FILE_CHECK_16", icons::FILE_CHECK_16)?;
    m.add("SMILEY_FROWN_24", icons::SMILEY_FROWN_24)?;
    m.add("CIRCLE_SLASH_24", icons::CIRCLE_SLASH_24)?;
    m.add("METER_24", icons::METER_24)?;
    m.add("BELL_SLASH_16", icons::BELL_SLASH_16)?;
    m.add("PERSON_FILL_16", icons::PERSON_FILL_16)?;
    m.add("REPO_PUSH_16", icons::REPO_PUSH_16)?;
    m.add("ISSUE_REOPENED_24", icons::ISSUE_REOPENED_24)?;
    m.add("NUMBER_16", icons::NUMBER_16)?;
    m.add("EYE_16", icons::EYE_16)?;
    m.add("PACKAGE_DEPENDENCIES_24", icons::PACKAGE_DEPENDENCIES_24)?;
    m.add("REDO_24", icons::REDO_24)?;
    m.add("FILE_ADDED_24", icons::FILE_ADDED_24)?;
    m.add("PAPER_AIRPLANE_16", icons::PAPER_AIRPLANE_16)?;
    m.add("ISSUE_LOCKED_16", icons::ISSUE_LOCKED_16)?;
    m.add("MCP_24", icons::MCP_24)?;
    m.add("REPO_TEMPLATE_16", icons::REPO_TEMPLATE_16)?;
    m.add("FILE_MEDIA_24", icons::FILE_MEDIA_24)?;
    m.add("GIT_MERGE_QUEUE_16", icons::GIT_MERGE_QUEUE_16)?;
    m.add("COMPOSE_24", icons::COMPOSE_24)?;
    m.add("X_16", icons::X_16)?;
    m.add("RSS_16", icons::RSS_16)?;
    m.add("DICE_24", icons::DICE_24)?;
    m.add("TAB_EXTERNAL_24", icons::TAB_EXTERNAL_24)?;
    m.add("ISSUE_OPENED_24", icons::ISSUE_OPENED_24)?;
    m.add("FILE_DIFF_24", icons::FILE_DIFF_24)?;
    m.add("LIST_UNORDERED_24", icons::LIST_UNORDERED_24)?;
    m.add("LIST_UNORDERED_16", icons::LIST_UNORDERED_16)?;
    m.add("STACK_24", icons::STACK_24)?;
    m.add("ROCKET_24", icons::ROCKET_24)?;
    m.add("HEART_16", icons::HEART_16)?;
    m.add("STRIKETHROUGH_16", icons::STRIKETHROUGH_16)?;
    m.add("DIFF_ADDED_24", icons::DIFF_ADDED_24)?;
    m.add("WRAP_24", icons::WRAP_24)?;
    m.add("BOOKMARK_SLASH_24", icons::BOOKMARK_SLASH_24)?;
    m.add("GIFT_24", icons::GIFT_24)?;
    m.add("MILESTONE_16", icons::MILESTONE_16)?;
    m.add("HOURGLASS_24", icons::HOURGLASS_24)?;
    m.add("MOVE_TO_TOP_16", icons::MOVE_TO_TOP_16)?;
    m.add("IMAGE_24", icons::IMAGE_24)?;
    m.add("NOTE_16", icons::NOTE_16)?;
    m.add("ARROW_RIGHT_24", icons::ARROW_RIGHT_24)?;
    m.add("LINK_24", icons::LINK_24)?;
    m.add("QUESTION_24", icons::QUESTION_24)?;
    m.add("UNREAD_24", icons::UNREAD_24)?;
    m.add("FILTER_REMOVE_16", icons::FILTER_REMOVE_16)?;
    m.add("CHECKBOX_16", icons::CHECKBOX_16)?;
    m.add("GRABBER_24", icons::GRABBER_24)?;
    m.add("SHIELD_X_24", icons::SHIELD_X_24)?;
    m.add("TAB_24", icons::TAB_24)?;
    m.add("DOT_FILL_16", icons::DOT_FILL_16)?;
    Ok(())
}
