// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_3(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("HASH_24", icons::HASH_24)?;
    m.add("NORTH_STAR_24", icons::NORTH_STAR_24)?;
    m.add("COMPOSE_16", icons::COMPOSE_16)?;
    m.add("SHARE_24", icons::SHARE_24)?;
    m.add("ROCKET_24", icons::ROCKET_24)?;
    m.add("FILE_MEDIA_24", icons::FILE_MEDIA_24)?;
    m.add("HOURGLASS_16", icons::HOURGLASS_16)?;
    m.add("MUTE_24", icons::MUTE_24)?;
    m.add("VIEW_FILES_24", icons::VIEW_FILES_24)?;
    m.add("BOOK_24", icons::BOOK_24)?;
    m.add("BRIEFCASE_24", icons::BRIEFCASE_24)?;
    m.add("PACKAGE_16", icons::PACKAGE_16)?;
    m.add("THREE_BARS_16", icons::THREE_BARS_16)?;
    m.add("COMMENT_DISCUSSION_24", icons::COMMENT_DISCUSSION_24)?;
    m.add("GIT_COMMIT_16", icons::GIT_COMMIT_16)?;
    m.add("DOT_24", icons::DOT_24)?;
    m.add("PENCIL_24", icons::PENCIL_24)?;
    m.add(
        "GIT_PULL_REQUEST_DRAFT_16",
        icons::GIT_PULL_REQUEST_DRAFT_16,
    )?;
    m.add("METER_16", icons::METER_16)?;
    m.add("QUOTE_16", icons::QUOTE_16)?;
    m.add("SPARKLE_FILL_24", icons::SPARKLE_FILL_24)?;
    m.add("PROJECT_SYMLINK_16", icons::PROJECT_SYMLINK_16)?;
    m.add("FEED_PLUS_16", icons::FEED_PLUS_16)?;
    m.add("FILE_ADDED_16", icons::FILE_ADDED_16)?;
    m.add("CHECK_16", icons::CHECK_16)?;
    m.add("STAR_16", icons::STAR_16)?;
    m.add("DIFF_MODIFIED_24", icons::DIFF_MODIFIED_24)?;
    m.add("CIRCLE_SLASH_16", icons::CIRCLE_SLASH_16)?;
    m.add("FILE_ZIP_16", icons::FILE_ZIP_16)?;
    m.add("UNDO_16", icons::UNDO_16)?;
    m.add("REPO_FORKED_LOCKED_24", icons::REPO_FORKED_LOCKED_24)?;
    m.add("ALERT_24", icons::ALERT_24)?;
    m.add("SPARKLES_FILL_16", icons::SPARKLES_FILL_16)?;
    m.add("NODE_16", icons::NODE_16)?;
    m.add("ISSUE_CLOSED_16", icons::ISSUE_CLOSED_16)?;
    m.add("TAB_24", icons::TAB_24)?;
    m.add("DICE_16", icons::DICE_16)?;
    m.add("BOOKMARK_24", icons::BOOKMARK_24)?;
    m.add("DESKTOP_DOWNLOAD_24", icons::DESKTOP_DOWNLOAD_24)?;
    m.add("PACKAGE_24", icons::PACKAGE_24)?;
    m.add("PAPER_AIRPLANE_16", icons::PAPER_AIRPLANE_16)?;
    m.add("REPO_PUSH_24", icons::REPO_PUSH_24)?;
    m.add("GIT_MERGE_QUEUE_24", icons::GIT_MERGE_QUEUE_24)?;
    m.add("LIGHT_BULB_24", icons::LIGHT_BULB_24)?;
    m.add("FILTER_REMOVE_24", icons::FILTER_REMOVE_24)?;
    m.add("SCREEN_FULL_24", icons::SCREEN_FULL_24)?;
    m.add("FOCUS_CENTER_24", icons::FOCUS_CENTER_24)?;
    m.add("ISSUE_OPENED_24", icons::ISSUE_OPENED_24)?;
    m.add("CODE_OF_CONDUCT_16", icons::CODE_OF_CONDUCT_16)?;
    m.add("SHIELD_CHECK_24", icons::SHIELD_CHECK_24)?;
    m.add("SCREEN_NORMAL_16", icons::SCREEN_NORMAL_16)?;
    m.add("SINGLE_SELECT_16", icons::SINGLE_SELECT_16)?;
    m.add("CLOCK_16", icons::CLOCK_16)?;
    m.add("EXCLAMATION_24", icons::EXCLAMATION_24)?;
    m.add("COMMAND_PALETTE_24", icons::COMMAND_PALETTE_24)?;
    m.add("CLOCK_FILL_24", icons::CLOCK_FILL_24)?;
    m.add("STACK_16", icons::STACK_16)?;
    m.add("QUESTION_BUBBLE_16", icons::QUESTION_BUBBLE_16)?;
    m.add("ZOOM_OUT_16", icons::ZOOM_OUT_16)?;
    m.add("FILE_BINARY_16", icons::FILE_BINARY_16)?;
    m.add("CROSS_REFERENCE_24", icons::CROSS_REFERENCE_24)?;
    m.add("BLOCKED_24", icons::BLOCKED_24)?;
    m.add("TYPOGRAPHY_24", icons::TYPOGRAPHY_24)?;
    m.add("LOCK_24", icons::LOCK_24)?;
    m.add("STACK_ADD_16", icons::STACK_ADD_16)?;
    m.add("MOVE_TO_TOP_24", icons::MOVE_TO_TOP_24)?;
    m.add("MOVE_TO_BOTTOM_16", icons::MOVE_TO_BOTTOM_16)?;
    m.add("TROPHY_24", icons::TROPHY_24)?;
    m.add("DEVICE_MOBILE_24", icons::DEVICE_MOBILE_24)?;
    m.add("CREDIT_CARD_16", icons::CREDIT_CARD_16)?;
    m.add("SANDBOX_16", icons::SANDBOX_16)?;
    m.add("REPO_16", icons::REPO_16)?;
    m.add("ARROW_LEFT_16", icons::ARROW_LEFT_16)?;
    m.add("WRAP_24", icons::WRAP_24)?;
    m.add("UNREAD_24", icons::UNREAD_24)?;
    m.add("SPACE_24", icons::SPACE_24)?;
    m.add("FILTER_REMOVE_16", icons::FILTER_REMOVE_16)?;
    m.add("PLUG_24", icons::PLUG_24)?;
    m.add("UNLINK_16", icons::UNLINK_16)?;
    m.add("COMMENT_AI_24", icons::COMMENT_AI_24)?;
    m.add("KEY_24", icons::KEY_24)?;
    m.add("LOCATION_24", icons::LOCATION_24)?;
    m.add("DOT_FILL_16", icons::DOT_FILL_16)?;
    m.add("CHEVRON_UP_16", icons::CHEVRON_UP_16)?;
    m.add("DIFF_REMOVED_16", icons::DIFF_REMOVED_16)?;
    m.add("NORTH_STAR_16", icons::NORTH_STAR_16)?;
    m.add("FILTER_24", icons::FILTER_24)?;
    m.add("HEART_24", icons::HEART_24)?;
    m.add("CHECK_CIRCLE_16", icons::CHECK_CIRCLE_16)?;
    m.add("LOCKUP_GITHUB_24", icons::LOCKUP_GITHUB_24)?;
    m.add("ISSUE_CLOSED_24", icons::ISSUE_CLOSED_24)?;
    m.add("SORT_DESC_24", icons::SORT_DESC_24)?;
    m.add("ITERATIONS_16", icons::ITERATIONS_16)?;
    m.add("GIT_PULL_REQUEST_16", icons::GIT_PULL_REQUEST_16)?;
    m.add("ARROW_UP_RIGHT_16", icons::ARROW_UP_RIGHT_16)?;
    m.add("FEED_ROCKET_16", icons::FEED_ROCKET_16)?;
    m.add("MOVE_TO_END_16", icons::MOVE_TO_END_16)?;
    m.add("ITALIC_16", icons::ITALIC_16)?;
    m.add("DIFF_RENAMED_24", icons::DIFF_RENAMED_24)?;
    m.add("DEVICE_DESKTOP_24", icons::DEVICE_DESKTOP_24)?;
    m.add("SQUARE_16", icons::SQUARE_16)?;
    m.add("FILE_CODE_24", icons::FILE_CODE_24)?;
    m.add("NUMBER_24", icons::NUMBER_24)?;
    m.add("AI_MODEL_24", icons::AI_MODEL_24)?;
    m.add("CHEVRON_UP_24", icons::CHEVRON_UP_24)?;
    m.add("SIDEBAR_COLLAPSE_16", icons::SIDEBAR_COLLAPSE_16)?;
    m.add("HISTORY_16", icons::HISTORY_16)?;
    m.add("TOOLS_24", icons::TOOLS_24)?;
    m.add("SHARE_ANDROID_24", icons::SHARE_ANDROID_24)?;
    m.add("PAPERCLIP_24", icons::PAPERCLIP_24)?;
    m.add("BOOK_16", icons::BOOK_16)?;
    m.add("HUBOT_16", icons::HUBOT_16)?;
    m.add("BOOKMARK_SLASH_16", icons::BOOKMARK_SLASH_16)?;
    m.add("KEY_16", icons::KEY_16)?;
    m.add("PASTE_24", icons::PASTE_24)?;
    m.add("SIDEBAR_COLLAPSE_24", icons::SIDEBAR_COLLAPSE_24)?;
    m.add("DISCUSSION_DUPLICATE_24", icons::DISCUSSION_DUPLICATE_24)?;
    m.add("CODESPACES_16", icons::CODESPACES_16)?;
    m.add("IMAGE_24", icons::IMAGE_24)?;
    m.add("ISSUE_OPENED_16", icons::ISSUE_OPENED_16)?;
    m.add("FEED_ISSUE_CLOSED_16", icons::FEED_ISSUE_CLOSED_16)?;
    m.add("COPILOT_16", icons::COPILOT_16)?;
    m.add("PROJECT_24", icons::PROJECT_24)?;
    m.add("MARK_GITHUB_24", icons::MARK_GITHUB_24)?;
    m.add("ARROW_DOWN_24", icons::ARROW_DOWN_24)?;
    m.add("VIDEO_24", icons::VIDEO_24)?;
    m.add(
        "GIT_PULL_REQUEST_LOCKED_16",
        icons::GIT_PULL_REQUEST_LOCKED_16,
    )?;
    m.add("FILE_CHECK_24", icons::FILE_CHECK_24)?;
    m.add("SQUARE_CIRCLE_24", icons::SQUARE_CIRCLE_24)?;
    m.add("EYE_CLOSED_16", icons::EYE_CLOSED_16)?;
    m.add("COPILOT_WARNING_16", icons::COPILOT_WARNING_16)?;
    m.add("UNWRAP_16", icons::UNWRAP_16)?;
    m.add("THUMBSDOWN_24", icons::THUMBSDOWN_24)?;
    m.add("STOP_24", icons::STOP_24)?;
    m.add("TERMINAL_16", icons::TERMINAL_16)?;
    m.add("MINIMIZE_24", icons::MINIMIZE_24)?;
    m.add("ISSUE_TRACKED_BY_24", icons::ISSUE_TRACKED_BY_24)?;
    m.add(
        "GIT_PULL_REQUEST_DRAFT_24",
        icons::GIT_PULL_REQUEST_DRAFT_24,
    )?;
    m.add("BROADCAST_24", icons::BROADCAST_24)?;
    m.add("CHEVRON_DOWN_24", icons::CHEVRON_DOWN_24)?;
    m.add("FILE_DIRECTORY_24", icons::FILE_DIRECTORY_24)?;
    m.add("CODESCAN_CHECKMARK_24", icons::CODESCAN_CHECKMARK_24)?;
    m.add("FILE_MOVED_24", icons::FILE_MOVED_24)?;
    Ok(())
}
