// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_1(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("ISSUE_CLOSED_16", icons::ISSUE_CLOSED_16)?;
    m.add("TAB_EXTERNAL_24", icons::TAB_EXTERNAL_24)?;
    m.add("ISSUE_TRACKED_BY_24", icons::ISSUE_TRACKED_BY_24)?;
    m.add("NOTE_24", icons::NOTE_24)?;
    m.add("LIST_UNORDERED_24", icons::LIST_UNORDERED_24)?;
    m.add("TRIANGLE_RIGHT_24", icons::TRIANGLE_RIGHT_24)?;
    m.add("FILE_CODE_16", icons::FILE_CODE_16)?;
    m.add("DEVICE_DESKTOP_24", icons::DEVICE_DESKTOP_24)?;
    m.add("TRIANGLE_UP_16", icons::TRIANGLE_UP_16)?;
    m.add("PLUG_16", icons::PLUG_16)?;
    m.add("QUESTION_24", icons::QUESTION_24)?;
    m.add("FILE_ADDED_24", icons::FILE_ADDED_24)?;
    m.add("CLOCK_24", icons::CLOCK_24)?;
    m.add("NODE_16", icons::NODE_16)?;
    m.add("THREE_BARS_16", icons::THREE_BARS_16)?;
    m.add("MARK_GITHUB_16", icons::MARK_GITHUB_16)?;
    m.add("ARROW_LEFT_16", icons::ARROW_LEFT_16)?;
    m.add("NODE_24", icons::NODE_24)?;
    m.add("FEED_TROPHY_16", icons::FEED_TROPHY_16)?;
    m.add("ARCHIVE_24", icons::ARCHIVE_24)?;
    m.add("DATABASE_16", icons::DATABASE_16)?;
    m.add("ISSUE_TRACKS_16", icons::ISSUE_TRACKS_16)?;
    m.add("STAR_24", icons::STAR_24)?;
    m.add("DISCUSSION_DUPLICATE_24", icons::DISCUSSION_DUPLICATE_24)?;
    m.add("PACKAGE_DEPENDENCIES_24", icons::PACKAGE_DEPENDENCIES_24)?;
    m.add("ARROW_DOWN_24", icons::ARROW_DOWN_24)?;
    m.add("REPO_DELETE_24", icons::REPO_DELETE_24)?;
    m.add("X_CIRCLE_FILL_12", icons::X_CIRCLE_FILL_12)?;
    m.add("CALENDAR_24", icons::CALENDAR_24)?;
    m.add("BOOKMARK_FILL_24", icons::BOOKMARK_FILL_24)?;
    m.add("PULSE_24", icons::PULSE_24)?;
    m.add("CODE_16", icons::CODE_16)?;
    m.add("ALERT_FILL_16", icons::ALERT_FILL_16)?;
    m.add(
        "GIT_PULL_REQUEST_DRAFT_16",
        icons::GIT_PULL_REQUEST_DRAFT_16,
    )?;
    m.add("SHIELD_X_24", icons::SHIELD_X_24)?;
    m.add("UNLINK_16", icons::UNLINK_16)?;
    m.add("WRAP_16", icons::WRAP_16)?;
    m.add("DIFF_RENAMED_16", icons::DIFF_RENAMED_16)?;
    m.add("INBOX_16", icons::INBOX_16)?;
    m.add("CHECKBOX_FILL_16", icons::CHECKBOX_FILL_16)?;
    m.add("SKIP_16", icons::SKIP_16)?;
    m.add("FILE_BINARY_16", icons::FILE_BINARY_16)?;
    m.add("DIFF_MODIFIED_16", icons::DIFF_MODIFIED_16)?;
    m.add("GIFT_24", icons::GIFT_24)?;
    m.add("GIT_COMPARE_16", icons::GIT_COMPARE_16)?;
    m.add("REPO_PULL_24", icons::REPO_PULL_24)?;
    m.add("CODE_REVIEW_24", icons::CODE_REVIEW_24)?;
    m.add("FILE_24", icons::FILE_24)?;
    m.add("THUMBSUP_24", icons::THUMBSUP_24)?;
    m.add("UNDO_24", icons::UNDO_24)?;
    m.add("COMMENT_LOCKED_16", icons::COMMENT_LOCKED_16)?;
    m.add("VIDEO_24", icons::VIDEO_24)?;
    m.add("MAIL_16", icons::MAIL_16)?;
    m.add("HEART_FILL_24", icons::HEART_FILL_24)?;
    m.add("ZOOM_OUT_16", icons::ZOOM_OUT_16)?;
    m.add("TYPOGRAPHY_16", icons::TYPOGRAPHY_16)?;
    m.add("ELLIPSIS_16", icons::ELLIPSIS_16)?;
    m.add("DASH_24", icons::DASH_24)?;
    m.add("SINGLE_SELECT_24", icons::SINGLE_SELECT_24)?;
    m.add("FILTER_REMOVE_24", icons::FILTER_REMOVE_24)?;
    m.add("FLAME_24", icons::FLAME_24)?;
    m.add("DESKTOP_DOWNLOAD_24", icons::DESKTOP_DOWNLOAD_24)?;
    m.add("SLIDERS_24", icons::SLIDERS_24)?;
    m.add("AGENT_16", icons::AGENT_16)?;
    m.add("MILESTONE_16", icons::MILESTONE_16)?;
    m.add("PLUS_CIRCLE_16", icons::PLUS_CIRCLE_16)?;
    m.add("SHIELD_16", icons::SHIELD_16)?;
    m.add("CHEVRON_RIGHT_12", icons::CHEVRON_RIGHT_12)?;
    m.add("MEGAPHONE_16", icons::MEGAPHONE_16)?;
    m.add("KEBAB_HORIZONTAL_16", icons::KEBAB_HORIZONTAL_16)?;
    m.add("STOP_24", icons::STOP_24)?;
    m.add("TRIANGLE_LEFT_16", icons::TRIANGLE_LEFT_16)?;
    m.add("DIFF_ADDED_24", icons::DIFF_ADDED_24)?;
    m.add("COMMENT_AI_16", icons::COMMENT_AI_16)?;
    m.add("BOOK_24", icons::BOOK_24)?;
    m.add("FOLD_UP_16", icons::FOLD_UP_16)?;
    m.add("PLUS_16", icons::PLUS_16)?;
    m.add("PACKAGE_DEPENDENTS_24", icons::PACKAGE_DEPENDENTS_24)?;
    m.add("COPILOT_96", icons::COPILOT_96)?;
    m.add("BRIEFCASE_16", icons::BRIEFCASE_16)?;
    m.add("VERSIONS_24", icons::VERSIONS_24)?;
    m.add("TRASH_24", icons::TRASH_24)?;
    m.add("FILE_ADDED_16", icons::FILE_ADDED_16)?;
    m.add("FLOWCHART_16", icons::FLOWCHART_16)?;
    m.add("SYNC_24", icons::SYNC_24)?;
    m.add("ARROW_RIGHT_24", icons::ARROW_RIGHT_24)?;
    m.add("UNFOLD_16", icons::UNFOLD_16)?;
    m.add("COPY_24", icons::COPY_24)?;
    m.add("MOVE_TO_START_16", icons::MOVE_TO_START_16)?;
    m.add("ARROW_BOTH_16", icons::ARROW_BOTH_16)?;
    m.add("ROCKET_16", icons::ROCKET_16)?;
    m.add("MIRROR_24", icons::MIRROR_24)?;
    m.add("WORKFLOW_16", icons::WORKFLOW_16)?;
    m.add("CHEVRON_DOWN_16", icons::CHEVRON_DOWN_16)?;
    m.add("ARROW_DOWN_RIGHT_16", icons::ARROW_DOWN_RIGHT_16)?;
    m.add("TRIANGLE_DOWN_24", icons::TRIANGLE_DOWN_24)?;
    m.add("ALERT_FILL_12", icons::ALERT_FILL_12)?;
    m.add("REPO_CLONE_24", icons::REPO_CLONE_24)?;
    m.add("HISTORY_16", icons::HISTORY_16)?;
    m.add("MARK_GITHUB_24", icons::MARK_GITHUB_24)?;
    m.add("TABLE_24", icons::TABLE_24)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_16",
        icons::TRACKED_BY_CLOSED_COMPLETED_16,
    )?;
    m.add("SIGN_IN_24", icons::SIGN_IN_24)?;
    m.add("SMILEY_16", icons::SMILEY_16)?;
    m.add("VSCODE_32", icons::VSCODE_32)?;
    m.add("PASSKEY_FILL_16", icons::PASSKEY_FILL_16)?;
    m.add("SIDEBAR_EXPAND_24", icons::SIDEBAR_EXPAND_24)?;
    m.add(
        "FEED_PULL_REQUEST_OPEN_16",
        icons::FEED_PULL_REQUEST_OPEN_16,
    )?;
    m.add("BEAKER_24", icons::BEAKER_24)?;
    m.add("X_CIRCLE_FILL_16", icons::X_CIRCLE_FILL_16)?;
    m.add("ORGANIZATION_24", icons::ORGANIZATION_24)?;
    m.add("FLAME_16", icons::FLAME_16)?;
    m.add("SQUARE_CIRCLE_24", icons::SQUARE_CIRCLE_24)?;
    m.add("CIRCLE_SLASH_16", icons::CIRCLE_SLASH_16)?;
    m.add("DEVICE_CAMERA_VIDEO_16", icons::DEVICE_CAMERA_VIDEO_16)?;
    m.add("SORT_ASC_24", icons::SORT_ASC_24)?;
    m.add("BROADCAST_24", icons::BROADCAST_24)?;
    m.add("NUMBER_16", icons::NUMBER_16)?;
    m.add("GIT_COMMIT_24", icons::GIT_COMMIT_24)?;
    m.add("MOVE_TO_BOTTOM_24", icons::MOVE_TO_BOTTOM_24)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_24",
        icons::FILE_DIRECTORY_SYMLINK_24,
    )?;
    m.add("REPO_TEMPLATE_16", icons::REPO_TEMPLATE_16)?;
    m.add("REPORT_24", icons::REPORT_24)?;
    m.add("SLIDERS_16", icons::SLIDERS_16)?;
    m.add("DIAMOND_24", icons::DIAMOND_24)?;
    m.add("DEVICE_CAMERA_24", icons::DEVICE_CAMERA_24)?;
    m.add("FILE_DIRECTORY_FILL_16", icons::FILE_DIRECTORY_FILL_16)?;
    m.add("DIFF_ADDED_16", icons::DIFF_ADDED_16)?;
    m.add("CODE_24", icons::CODE_24)?;
    m.add("LOCK_16", icons::LOCK_16)?;
    m.add("ZAP_24", icons::ZAP_24)?;
    m.add("CALENDAR_16", icons::CALENDAR_16)?;
    m.add("SYNC_16", icons::SYNC_16)?;
    m.add("SQUARE_FILL_16", icons::SQUARE_FILL_16)?;
    m.add("HISTORY_24", icons::HISTORY_24)?;
    m.add("MOON_24", icons::MOON_24)?;
    m.add("GIT_BRANCH_CHECK_24", icons::GIT_BRANCH_CHECK_24)?;
    m.add("FILE_REMOVED_16", icons::FILE_REMOVED_16)?;
    m.add("IMAGE_24", icons::IMAGE_24)?;
    m.add("GIT_MERGE_QUEUE_16", icons::GIT_MERGE_QUEUE_16)?;
    m.add("SINGLE_SELECT_16", icons::SINGLE_SELECT_16)?;
    m.add("COMMAND_PALETTE_24", icons::COMMAND_PALETTE_24)?;
    m.add("PIN_SLASH_24", icons::PIN_SLASH_24)?;
    m.add("DICE_16", icons::DICE_16)?;
    m.add("BOOKMARK_SLASH_FILL_16", icons::BOOKMARK_SLASH_FILL_16)?;
    m.add("BOLD_16", icons::BOLD_16)?;
    m.add("REPLY_16", icons::REPLY_16)?;
    m.add("ELLIPSIS_24", icons::ELLIPSIS_24)?;
    m.add("ARROW_UP_RIGHT_24", icons::ARROW_UP_RIGHT_24)?;
    m.add("PASTE_16", icons::PASTE_16)?;
    m.add("CODESPACES_16", icons::CODESPACES_16)?;
    m.add("SQUIRREL_16", icons::SQUIRREL_16)?;
    m.add("CHECKBOX_24", icons::CHECKBOX_24)?;
    m.add("INBOX_24", icons::INBOX_24)?;
    m.add("BROADCAST_16", icons::BROADCAST_16)?;
    m.add("PROJECT_SYMLINK_16", icons::PROJECT_SYMLINK_16)?;
    m.add("DIFF_REMOVED_24", icons::DIFF_REMOVED_24)?;
    m.add("FOLD_UP_24", icons::FOLD_UP_24)?;
    m.add("PLAY_24", icons::PLAY_24)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_16",
        icons::FILE_DIRECTORY_SYMLINK_16,
    )?;
    m.add("LOGO_GITHUB_24", icons::LOGO_GITHUB_24)?;
    m.add("CLOCK_FILL_16", icons::CLOCK_FILL_16)?;
    m.add("LIST_ORDERED_16", icons::LIST_ORDERED_16)?;
    m.add("ARROW_UP_16", icons::ARROW_UP_16)?;
    m.add("SMILEY_NEUTRAL_24", icons::SMILEY_NEUTRAL_24)?;
    m.add("FILE_MEDIA_24", icons::FILE_MEDIA_24)?;
    m.add("SQUIRREL_24", icons::SQUIRREL_24)?;
    m.add("MOVE_TO_END_16", icons::MOVE_TO_END_16)?;
    m.add("REPO_PULL_16", icons::REPO_PULL_16)?;
    m.add("FILE_SYMLINK_FILE_16", icons::FILE_SYMLINK_FILE_16)?;
    m.add("QUESTION_16", icons::QUESTION_16)?;
    m.add("X_24", icons::X_24)?;
    m.add("PULSE_16", icons::PULSE_16)?;
    m.add("CACHE_24", icons::CACHE_24)?;
    m.add("HORIZONTAL_RULE_24", icons::HORIZONTAL_RULE_24)?;
    m.add("UPLOAD_24", icons::UPLOAD_24)?;
    m.add("CHEVRON_DOWN_24", icons::CHEVRON_DOWN_24)?;
    m.add("SPACING_MEDIUM_16", icons::SPACING_MEDIUM_16)?;
    m.add("DISCUSSION_CLOSED_24", icons::DISCUSSION_CLOSED_24)?;
    m.add("NO_ENTRY_16", icons::NO_ENTRY_16)?;
    m.add("MENTION_24", icons::MENTION_24)?;
    m.add("DEVICE_MOBILE_16", icons::DEVICE_MOBILE_16)?;
    m.add("ISSUE_DRAFT_16", icons::ISSUE_DRAFT_16)?;
    m.add("HOURGLASS_16", icons::HOURGLASS_16)?;
    m.add("CHECKLIST_24", icons::CHECKLIST_24)?;
    m.add("BRIEFCASE_24", icons::BRIEFCASE_24)?;
    m.add("PERSON_24", icons::PERSON_24)?;
    m.add("PENCIL_24", icons::PENCIL_24)?;
    m.add("READ_16", icons::READ_16)?;
    m.add("PROJECT_TEMPLATE_24", icons::PROJECT_TEMPLATE_24)?;
    m.add("BEAKER_16", icons::BEAKER_16)?;
    m.add("FILE_CHECK_24", icons::FILE_CHECK_24)?;
    m.add("BOLD_24", icons::BOLD_24)?;
    m.add("FEED_HEART_16", icons::FEED_HEART_16)?;
    m.add("HEADING_16", icons::HEADING_16)?;
    m.add("CODESCAN_24", icons::CODESCAN_24)?;
    m.add("DEVICE_MOBILE_24", icons::DEVICE_MOBILE_24)?;
    m.add("SPACING_LARGE_24", icons::SPACING_LARGE_24)?;
    m.add("PERSON_ADD_24", icons::PERSON_ADD_24)?;
    m.add("FILE_MOVED_24", icons::FILE_MOVED_24)?;
    Ok(())
}
