// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_1(m: &Bound<PyModule>) -> PyResult<()> {
    m.add(
        "FEED_PULL_REQUEST_DRAFT_16",
        icons::FEED_PULL_REQUEST_DRAFT_16,
    )?;
    m.add("BEAKER_16", icons::BEAKER_16)?;
    m.add("FEED_ISSUE_OPEN_16", icons::FEED_ISSUE_OPEN_16)?;
    m.add("COPILOT_ERROR_16", icons::COPILOT_ERROR_16)?;
    m.add("RUBY_16", icons::RUBY_16)?;
    m.add("PASSKEY_FILL_16", icons::PASSKEY_FILL_16)?;
    m.add("UNLOCK_16", icons::UNLOCK_16)?;
    m.add("FILE_BADGE_24", icons::FILE_BADGE_24)?;
    m.add("DUPLICATE_16", icons::DUPLICATE_16)?;
    m.add("HOURGLASS_24", icons::HOURGLASS_24)?;
    m.add("FILE_CODE_16", icons::FILE_CODE_16)?;
    m.add("GRAPH_BAR_VERTICAL_16", icons::GRAPH_BAR_VERTICAL_16)?;
    m.add("ISSUE_RELATES_TO_24", icons::ISSUE_RELATES_TO_24)?;
    m.add("CHECK_CIRCLE_FILL_12", icons::CHECK_CIRCLE_FILL_12)?;
    m.add("KEBAB_HORIZONTAL_24", icons::KEBAB_HORIZONTAL_24)?;
    m.add("HORIZONTAL_RULE_24", icons::HORIZONTAL_RULE_24)?;
    m.add("SMILEY_FRUSTRATED_24", icons::SMILEY_FRUSTRATED_24)?;
    m.add("REDO_24", icons::REDO_24)?;
    m.add(
        "FEED_PULL_REQUEST_OPEN_16",
        icons::FEED_PULL_REQUEST_OPEN_16,
    )?;
    m.add("FISCAL_HOST_24", icons::FISCAL_HOST_24)?;
    m.add("GIT_MERGE_16", icons::GIT_MERGE_16)?;
    m.add("IMAGE_16", icons::IMAGE_16)?;
    m.add("SYNC_24", icons::SYNC_24)?;
    m.add("CHECK_CIRCLE_FILL_24", icons::CHECK_CIRCLE_FILL_24)?;
    m.add("GIT_BRANCH_24", icons::GIT_BRANCH_24)?;
    m.add("SMILEY_NEUTRAL_16", icons::SMILEY_NEUTRAL_16)?;
    m.add("CROSS_REFERENCE_16", icons::CROSS_REFERENCE_16)?;
    m.add("CHEVRON_LEFT_12", icons::CHEVRON_LEFT_12)?;
    m.add("RSS_24", icons::RSS_24)?;
    m.add("SKIP_FILL_24", icons::SKIP_FILL_24)?;
    m.add("BEAKER_24", icons::BEAKER_24)?;
    m.add("GIFT_16", icons::GIFT_16)?;
    m.add("ISSUE_REOPENED_16", icons::ISSUE_REOPENED_16)?;
    m.add("CHEVRON_RIGHT_16", icons::CHEVRON_RIGHT_16)?;
    m.add("TAG_16", icons::TAG_16)?;
    m.add("THUMBSUP_24", icons::THUMBSUP_24)?;
    m.add("DATABASE_24", icons::DATABASE_24)?;
    m.add("PACKAGE_DEPENDENTS_24", icons::PACKAGE_DEPENDENTS_24)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_24",
        icons::TRACKED_BY_CLOSED_COMPLETED_24,
    )?;
    m.add("MAXIMIZE_16", icons::MAXIMIZE_16)?;
    m.add("STAR_FILL_24", icons::STAR_FILL_24)?;
    m.add("SMILEY_FROWN_16", icons::SMILEY_FROWN_16)?;
    m.add("CLOUD_24", icons::CLOUD_24)?;
    m.add("MORTAR_BOARD_24", icons::MORTAR_BOARD_24)?;
    m.add("TROPHY_16", icons::TROPHY_16)?;
    m.add("ROCKET_16", icons::ROCKET_16)?;
    m.add("QUESTION_16", icons::QUESTION_16)?;
    m.add("LOCATION_16", icons::LOCATION_16)?;
    m.add("INFO_24", icons::INFO_24)?;
    m.add("COLUMNS_24", icons::COLUMNS_24)?;
    m.add("X_CIRCLE_FILL_12", icons::X_CIRCLE_FILL_12)?;
    m.add("CHEVRON_RIGHT_12", icons::CHEVRON_RIGHT_12)?;
    m.add("PIN_SLASH_16", icons::PIN_SLASH_16)?;
    m.add("ISSUE_RELATES_TO_16", icons::ISSUE_RELATES_TO_16)?;
    m.add("BELL_FILL_16", icons::BELL_FILL_16)?;
    m.add("CIRCLE_24", icons::CIRCLE_24)?;
    m.add("ACCESSIBILITY_INSET_16", icons::ACCESSIBILITY_INSET_16)?;
    m.add("ARROW_DOWN_RIGHT_16", icons::ARROW_DOWN_RIGHT_16)?;
    m.add("CODESCAN_24", icons::CODESCAN_24)?;
    m.add("ARROW_DOWN_LEFT_16", icons::ARROW_DOWN_LEFT_16)?;
    m.add("ARCHIVE_24", icons::ARCHIVE_24)?;
    m.add("CLOCK_24", icons::CLOCK_24)?;
    m.add("INBOX_16", icons::INBOX_16)?;
    m.add("REPO_FORKED_LOCKED_16", icons::REPO_FORKED_LOCKED_16)?;
    m.add("PERSON_ADD_24", icons::PERSON_ADD_24)?;
    m.add("PROJECT_SYMLINK_24", icons::PROJECT_SYMLINK_24)?;
    m.add("TABLE_16", icons::TABLE_16)?;
    m.add("FEED_MERGED_16", icons::FEED_MERGED_16)?;
    m.add("REPO_DELETE_24", icons::REPO_DELETE_24)?;
    m.add("SMILEY_GRIN_24", icons::SMILEY_GRIN_24)?;
    m.add("FEED_FORKED_16", icons::FEED_FORKED_16)?;
    m.add("LIST_ORDERED_16", icons::LIST_ORDERED_16)?;
    m.add("DISCUSSION_CLOSED_16", icons::DISCUSSION_CLOSED_16)?;
    m.add("MOVE_TO_END_24", icons::MOVE_TO_END_24)?;
    m.add("TRASH_24", icons::TRASH_24)?;
    m.add("READ_16", icons::READ_16)?;
    m.add("DEPENDABOT_24", icons::DEPENDABOT_24)?;
    m.add("NOTE_16", icons::NOTE_16)?;
    m.add("PLUS_CIRCLE_24", icons::PLUS_CIRCLE_24)?;
    m.add("DIFF_RENAMED_16", icons::DIFF_RENAMED_16)?;
    m.add("SIGN_IN_16", icons::SIGN_IN_16)?;
    m.add("NOTE_24", icons::NOTE_24)?;
    m.add("SHIELD_CHECK_16", icons::SHIELD_CHECK_16)?;
    m.add("PIN_24", icons::PIN_24)?;
    m.add("TELESCOPE_24", icons::TELESCOPE_24)?;
    m.add("CODE_OF_CONDUCT_24", icons::CODE_OF_CONDUCT_24)?;
    m.add("SUN_16", icons::SUN_16)?;
    m.add("COMMENT_DISCUSSION_16", icons::COMMENT_DISCUSSION_16)?;
    m.add("ARROW_DOWN_RIGHT_24", icons::ARROW_DOWN_RIGHT_24)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_24",
        icons::FILE_DIRECTORY_SYMLINK_24,
    )?;
    m.add("SERVER_16", icons::SERVER_16)?;
    m.add("SPARKLE_24", icons::SPARKLE_24)?;
    m.add("DATABASE_16", icons::DATABASE_16)?;
    m.add("COMMENT_AI_16", icons::COMMENT_AI_16)?;
    m.add("FLAME_16", icons::FLAME_16)?;
    m.add("UPLOAD_24", icons::UPLOAD_24)?;
    m.add("ROWS_24", icons::ROWS_24)?;
    m.add("DIAMOND_24", icons::DIAMOND_24)?;
    m.add("LOGO_GIST_24", icons::LOGO_GIST_24)?;
    m.add("ITALIC_24", icons::ITALIC_24)?;
    m.add("SQUIRREL_16", icons::SQUIRREL_16)?;
    m.add("GEAR_24", icons::GEAR_24)?;
    m.add("UNLINK_24", icons::UNLINK_24)?;
    m.add("VERSIONS_24", icons::VERSIONS_24)?;
    m.add("LOG_16", icons::LOG_16)?;
    m.add("REPO_CLONE_16", icons::REPO_CLONE_16)?;
    m.add("MOVE_TO_START_16", icons::MOVE_TO_START_16)?;
    m.add("BROWSER_16", icons::BROWSER_16)?;
    m.add("MAXIMIZE_24", icons::MAXIMIZE_24)?;
    m.add("HEADING_16", icons::HEADING_16)?;
    m.add("SINGLE_SELECT_24", icons::SINGLE_SELECT_24)?;
    m.add("TRIANGLE_DOWN_16", icons::TRIANGLE_DOWN_16)?;
    m.add("STAR_24", icons::STAR_24)?;
    m.add("SHARE_16", icons::SHARE_16)?;
    m.add("FILE_SYMLINK_FILE_16", icons::FILE_SYMLINK_FILE_16)?;
    m.add("UNMUTE_16", icons::UNMUTE_16)?;
    m.add("NUMBER_16", icons::NUMBER_16)?;
    m.add("DEVICE_CAMERA_VIDEO_16", icons::DEVICE_CAMERA_VIDEO_16)?;
    m.add("PROJECT_ROADMAP_16", icons::PROJECT_ROADMAP_16)?;
    m.add("PENCIL_AI_16", icons::PENCIL_AI_16)?;
    m.add("X_CIRCLE_FILL_16", icons::X_CIRCLE_FILL_16)?;
    m.add("LIGHT_BULB_16", icons::LIGHT_BULB_16)?;
    m.add("PACKAGE_DEPENDENCIES_24", icons::PACKAGE_DEPENDENCIES_24)?;
    m.add("SKIP_FILL_16", icons::SKIP_FILL_16)?;
    m.add("BOOKMARK_FILL_24", icons::BOOKMARK_FILL_24)?;
    m.add("VIDEO_16", icons::VIDEO_16)?;
    m.add("DEVICES_24", icons::DEVICES_24)?;
    m.add("PEOPLE_16", icons::PEOPLE_16)?;
    m.add("MCP_16", icons::MCP_16)?;
    m.add("KEBAB_HORIZONTAL_16", icons::KEBAB_HORIZONTAL_16)?;
    m.add("LINK_EXTERNAL_24", icons::LINK_EXTERNAL_24)?;
    m.add("DISCUSSION_DUPLICATE_16", icons::DISCUSSION_DUPLICATE_16)?;
    m.add("DISCUSSION_CLOSED_24", icons::DISCUSSION_CLOSED_24)?;
    m.add("DUPLICATE_24", icons::DUPLICATE_24)?;
    m.add("PROJECT_TEMPLATE_16", icons::PROJECT_TEMPLATE_16)?;
    m.add("MAIL_24", icons::MAIL_24)?;
    m.add("ALERT_FILL_12", icons::ALERT_FILL_12)?;
    m.add("CROSSHAIRS_16", icons::CROSSHAIRS_16)?;
    m.add("PROJECT_ROADMAP_24", icons::PROJECT_ROADMAP_24)?;
    m.add("VERIFIED_24", icons::VERIFIED_24)?;
    m.add("FILE_MEDIA_16", icons::FILE_MEDIA_16)?;
    m.add("COMPOSE_24", icons::COMPOSE_24)?;
    m.add("REPO_TEMPLATE_16", icons::REPO_TEMPLATE_16)?;
    m.add("COPY_24", icons::COPY_24)?;
    m.add("SLIDERS_24", icons::SLIDERS_24)?;
    m.add("LIST_ORDERED_24", icons::LIST_ORDERED_24)?;
    m.add("CROSSHAIRS_24", icons::CROSSHAIRS_24)?;
    m.add("QUOTE_24", icons::QUOTE_24)?;
    m.add("COMMENT_LOCKED_16", icons::COMMENT_LOCKED_16)?;
    m.add("SHIELD_SLASH_16", icons::SHIELD_SLASH_16)?;
    m.add("LIST_UNORDERED_16", icons::LIST_UNORDERED_16)?;
    m.add("LOCKUP_GITHUB_16", icons::LOCKUP_GITHUB_16)?;
    m.add("LINK_EXTERNAL_16", icons::LINK_EXTERNAL_16)?;
    m.add("GLOBE_16", icons::GLOBE_16)?;
    m.add("GOAL_16", icons::GOAL_16)?;
    m.add("GRAPH_16", icons::GRAPH_16)?;
    m.add("REDO_16", icons::REDO_16)?;
    m.add("BOOLEAN_OFF_24", icons::BOOLEAN_OFF_24)?;
    m.add("MENTION_16", icons::MENTION_16)?;
    m.add("CHEVRON_UP_12", icons::CHEVRON_UP_12)?;
    m.add("CIRCLE_SLASH_24", icons::CIRCLE_SLASH_24)?;
    m.add("SQUARE_CIRCLE_16", icons::SQUARE_CIRCLE_16)?;
    m.add("CHECK_24", icons::CHECK_24)?;
    m.add("ARROW_UP_RIGHT_24", icons::ARROW_UP_RIGHT_24)?;
    m.add("ARROW_SWITCH_16", icons::ARROW_SWITCH_16)?;
    m.add("CLOUD_16", icons::CLOUD_16)?;
    m.add("EYE_24", icons::EYE_24)?;
    m.add("MULTI_SELECT_16", icons::MULTI_SELECT_16)?;
    m.add("DIFF_REMOVED_24", icons::DIFF_REMOVED_24)?;
    m.add("UNLOCK_24", icons::UNLOCK_24)?;
    m.add("SHIELD_LOCK_24", icons::SHIELD_LOCK_24)?;
    m.add("LIST_UNORDERED_24", icons::LIST_UNORDERED_24)?;
    m.add("LAW_24", icons::LAW_24)?;
    m.add("GRABBER_24", icons::GRABBER_24)?;
    m.add("BOOLEAN_ON_16", icons::BOOLEAN_ON_16)?;
    m.add("SEARCH_16", icons::SEARCH_16)?;
    m.add("SQUARE_FILL_16", icons::SQUARE_FILL_16)?;
    m.add("DESKTOP_DOWNLOAD_16", icons::DESKTOP_DOWNLOAD_16)?;
    m.add("CODE_REVIEW_24", icons::CODE_REVIEW_24)?;
    m.add("CHECKBOX_FILL_16", icons::CHECKBOX_FILL_16)?;
    m.add("SPARKLE_FILL_16", icons::SPARKLE_FILL_16)?;
    m.add("BROWSER_24", icons::BROWSER_24)?;
    m.add("BUG_16", icons::BUG_16)?;
    m.add("FILE_DIFF_16", icons::FILE_DIFF_16)?;
    m.add("APPS_16", icons::APPS_16)?;
    m.add("ZAP_16", icons::ZAP_16)?;
    m.add("TABLE_24", icons::TABLE_24)?;
    m.add("QUESTION_BUBBLE_24", icons::QUESTION_BUBBLE_24)?;
    m.add(
        "GIT_PULL_REQUEST_CLOSED_16",
        icons::GIT_PULL_REQUEST_CLOSED_16,
    )?;
    m.add("RUBY_24", icons::RUBY_24)?;
    m.add("GRAPH_STACKED_AREA_16", icons::GRAPH_STACKED_AREA_16)?;
    m.add("STRIKETHROUGH_16", icons::STRIKETHROUGH_16)?;
    m.add("SKIP_24", icons::SKIP_24)?;
    m.add("SPARKLES_FILL_24", icons::SPARKLES_FILL_24)?;
    m.add("CODE_SQUARE_24", icons::CODE_SQUARE_24)?;
    m.add("FLOWCHART_16", icons::FLOWCHART_16)?;
    m.add("CODE_SQUARE_16", icons::CODE_SQUARE_16)?;
    m.add("SKIP_16", icons::SKIP_16)?;
    m.add("ROWS_16", icons::ROWS_16)?;
    m.add("LINK_24", icons::LINK_24)?;
    Ok(())
}
