// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_3(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("SHIELD_LOCK_16", icons::SHIELD_LOCK_16)?;
    m.add("NO_ENTRY_16", icons::NO_ENTRY_16)?;
    m.add("FILE_SYMLINK_FILE_24", icons::FILE_SYMLINK_FILE_24)?;
    m.add("BOOKMARK_FILL_24", icons::BOOKMARK_FILL_24)?;
    m.add("CHECK_CIRCLE_24", icons::CHECK_CIRCLE_24)?;
    m.add("GIT_COMMIT_24", icons::GIT_COMMIT_24)?;
    m.add("METER_16", icons::METER_16)?;
    m.add("BOOKMARK_SLASH_16", icons::BOOKMARK_SLASH_16)?;
    m.add("PLUS_24", icons::PLUS_24)?;
    m.add("PERSON_FILL_24", icons::PERSON_FILL_24)?;
    m.add("ISSUE_LOCKED_16", icons::ISSUE_LOCKED_16)?;
    m.add("ISSUE_REOPENED_16", icons::ISSUE_REOPENED_16)?;
    m.add("TERMINAL_16", icons::TERMINAL_16)?;
    m.add("INFINITY_16", icons::INFINITY_16)?;
    m.add("FEED_HEART_16", icons::FEED_HEART_16)?;
    m.add("MIRROR_16", icons::MIRROR_16)?;
    m.add("HEADING_24", icons::HEADING_24)?;
    m.add("SMILEY_FRUSTRATED_16", icons::SMILEY_FRUSTRATED_16)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_16",
        icons::FILE_DIRECTORY_SYMLINK_16,
    )?;
    m.add("GRABBER_24", icons::GRABBER_24)?;
    m.add("TAG_24", icons::TAG_24)?;
    m.add("BEAKER_24", icons::BEAKER_24)?;
    m.add("TABLE_24", icons::TABLE_24)?;
    m.add("ORGANIZATION_16", icons::ORGANIZATION_16)?;
    m.add("DIFF_ADDED_24", icons::DIFF_ADDED_24)?;
    m.add("HUBOT_16", icons::HUBOT_16)?;
    m.add("SCREEN_FULL_24", icons::SCREEN_FULL_24)?;
    m.add("PAUSE_16", icons::PAUSE_16)?;
    m.add(
        "FILE_DIRECTORY_SYMLINK_24",
        icons::FILE_DIRECTORY_SYMLINK_24,
    )?;
    m.add("HOME_16", icons::HOME_16)?;
    m.add("REDO_24", icons::REDO_24)?;
    m.add("CODESCAN_CHECKMARK_24", icons::CODESCAN_CHECKMARK_24)?;
    m.add("FILE_CHECK_24", icons::FILE_CHECK_24)?;
    m.add("SORT_ASC_24", icons::SORT_ASC_24)?;
    m.add("SINGLE_SELECT_24", icons::SINGLE_SELECT_24)?;
    m.add("WRAP_24", icons::WRAP_24)?;
    m.add("VERSIONS_24", icons::VERSIONS_24)?;
    m.add("MAXIMIZE_24", icons::MAXIMIZE_24)?;
    m.add("CHEVRON_LEFT_16", icons::CHEVRON_LEFT_16)?;
    m.add("HORIZONTAL_RULE_16", icons::HORIZONTAL_RULE_16)?;
    m.add("CHECK_CIRCLE_FILL_24", icons::CHECK_CIRCLE_FILL_24)?;
    m.add("BELL_24", icons::BELL_24)?;
    m.add("BOOK_LOCKED_16", icons::BOOK_LOCKED_16)?;
    m.add("LIST_UNORDERED_16", icons::LIST_UNORDERED_16)?;
    m.add("PROJECT_CHECK_24", icons::PROJECT_CHECK_24)?;
    m.add("ARROW_DOWN_LEFT_16", icons::ARROW_DOWN_LEFT_16)?;
    m.add("LOCKUP_GITHUB_16", icons::LOCKUP_GITHUB_16)?;
    m.add("SHIELD_16", icons::SHIELD_16)?;
    m.add("SUN_16", icons::SUN_16)?;
    m.add("HORIZONTAL_RULE_24", icons::HORIZONTAL_RULE_24)?;
    m.add("PENCIL_16", icons::PENCIL_16)?;
    m.add("SHIELD_CHECK_16", icons::SHIELD_CHECK_16)?;
    m.add(
        "GIT_PULL_REQUEST_CLOSED_24",
        icons::GIT_PULL_REQUEST_CLOSED_24,
    )?;
    m.add("LINK_EXTERNAL_24", icons::LINK_EXTERNAL_24)?;
    m.add("FEED_DISCUSSION_16", icons::FEED_DISCUSSION_16)?;
    m.add("FILE_SYMLINK_FILE_16", icons::FILE_SYMLINK_FILE_16)?;
    m.add("CROSSHAIRS_24", icons::CROSSHAIRS_24)?;
    m.add("SLIDERS_16", icons::SLIDERS_16)?;
    m.add("PIN_SLASH_24", icons::PIN_SLASH_24)?;
    m.add("LIGHT_BULB_16", icons::LIGHT_BULB_16)?;
    m.add("UNFOLD_16", icons::UNFOLD_16)?;
    m.add("SIGN_OUT_16", icons::SIGN_OUT_16)?;
    m.add("HEART_FILL_16", icons::HEART_FILL_16)?;
    m.add("STAR_FILL_16", icons::STAR_FILL_16)?;
    m.add("PAUSE_24", icons::PAUSE_24)?;
    m.add("LIST_UNORDERED_24", icons::LIST_UNORDERED_24)?;
    m.add("COMMENT_LOCKED_16", icons::COMMENT_LOCKED_16)?;
    m.add("CONTAINER_16", icons::CONTAINER_16)?;
    m.add("THUMBSDOWN_24", icons::THUMBSDOWN_24)?;
    m.add("MOVE_TO_END_16", icons::MOVE_TO_END_16)?;
    m.add("STACK_24", icons::STACK_24)?;
    m.add("LOG_16", icons::LOG_16)?;
    m.add("COPILOT_ERROR_16", icons::COPILOT_ERROR_16)?;
    m.add("PACKAGE_DEPENDENCIES_24", icons::PACKAGE_DEPENDENCIES_24)?;
    m.add("SKIP_16", icons::SKIP_16)?;
    m.add("DUPLICATE_16", icons::DUPLICATE_16)?;
    m.add("MEGAPHONE_16", icons::MEGAPHONE_16)?;
    m.add("REPO_TEMPLATE_24", icons::REPO_TEMPLATE_24)?;
    m.add("DISCUSSION_OUTDATED_16", icons::DISCUSSION_OUTDATED_16)?;
    m.add("DIFF_IGNORED_16", icons::DIFF_IGNORED_16)?;
    m.add("FILE_ZIP_16", icons::FILE_ZIP_16)?;
    m.add("FISCAL_HOST_16", icons::FISCAL_HOST_16)?;
    m.add("GEAR_16", icons::GEAR_16)?;
    m.add("MOVE_TO_BOTTOM_24", icons::MOVE_TO_BOTTOM_24)?;
    m.add("SCREEN_NORMAL_16", icons::SCREEN_NORMAL_16)?;
    m.add("GIT_BRANCH_24", icons::GIT_BRANCH_24)?;
    m.add("SORT_DESC_24", icons::SORT_DESC_24)?;
    m.add("GIT_MERGE_16", icons::GIT_MERGE_16)?;
    m.add("ARROW_RIGHT_24", icons::ARROW_RIGHT_24)?;
    m.add("FILE_SUBMODULE_16", icons::FILE_SUBMODULE_16)?;
    m.add("DEVICES_24", icons::DEVICES_24)?;
    m.add("FILTER_16", icons::FILTER_16)?;
    m.add("DOWNLOAD_24", icons::DOWNLOAD_24)?;
    m.add("FILE_ADDED_16", icons::FILE_ADDED_16)?;
    m.add("LOGO_GITHUB_16", icons::LOGO_GITHUB_16)?;
    m.add("QUESTION_24", icons::QUESTION_24)?;
    m.add("STACK_16", icons::STACK_16)?;
    m.add("PLUS_CIRCLE_24", icons::PLUS_CIRCLE_24)?;
    m.add("KEY_ASTERISK_24", icons::KEY_ASTERISK_24)?;
    m.add("LOG_24", icons::LOG_24)?;
    m.add("MARKDOWN_16", icons::MARKDOWN_16)?;
    m.add("REPO_PUSH_24", icons::REPO_PUSH_24)?;
    m.add("FOLD_16", icons::FOLD_16)?;
    m.add("GIT_MERGE_24", icons::GIT_MERGE_24)?;
    m.add("HASH_16", icons::HASH_16)?;
    m.add("LIST_ORDERED_16", icons::LIST_ORDERED_16)?;
    m.add("INFO_16", icons::INFO_16)?;
    m.add("SPACING_LARGE_16", icons::SPACING_LARGE_16)?;
    m.add("GRAPH_STACKED_AREA_16", icons::GRAPH_STACKED_AREA_16)?;
    m.add("SHARE_ANDROID_16", icons::SHARE_ANDROID_16)?;
    m.add("UNVERIFIED_16", icons::UNVERIFIED_16)?;
    m.add("PERSON_ADD_16", icons::PERSON_ADD_16)?;
    m.add("COPILOT_WARNING_16", icons::COPILOT_WARNING_16)?;
    m.add("UNLOCK_24", icons::UNLOCK_24)?;
    m.add("FILE_DIRECTORY_FILL_24", icons::FILE_DIRECTORY_FILL_24)?;
    m.add("DATABASE_16", icons::DATABASE_16)?;
    m.add("ITERATIONS_24", icons::ITERATIONS_24)?;
    m.add("LOGO_GIST_24", icons::LOGO_GIST_24)?;
    m.add("TRIANGLE_RIGHT_16", icons::TRIANGLE_RIGHT_16)?;
    m.add("FILE_REMOVED_16", icons::FILE_REMOVED_16)?;
    m.add("VIDEO_16", icons::VIDEO_16)?;
    m.add("LOGO_GIST_16", icons::LOGO_GIST_16)?;
    m.add("DIFF_MODIFIED_16", icons::DIFF_MODIFIED_16)?;
    m.add("CLOCK_16", icons::CLOCK_16)?;
    m.add("MARKDOWN_24", icons::MARKDOWN_24)?;
    m.add("COMMENT_DISCUSSION_16", icons::COMMENT_DISCUSSION_16)?;
    m.add("FLAG_16", icons::FLAG_16)?;
    m.add("CHEVRON_RIGHT_16", icons::CHEVRON_RIGHT_16)?;
    m.add("REPLY_16", icons::REPLY_16)?;
    m.add("PIN_SLASH_16", icons::PIN_SLASH_16)?;
    m.add("KEY_24", icons::KEY_24)?;
    m.add("ELLIPSIS_16", icons::ELLIPSIS_16)?;
    m.add("PACKAGE_DEPENDENTS_16", icons::PACKAGE_DEPENDENTS_16)?;
    m.add("MILESTONE_24", icons::MILESTONE_24)?;
    m.add("BOOK_16", icons::BOOK_16)?;
    m.add("PACKAGE_DEPENDENCIES_16", icons::PACKAGE_DEPENDENCIES_16)?;
    m.add("HOME_FILL_24", icons::HOME_FILL_24)?;
    m.add("REPO_16", icons::REPO_16)?;
    m.add("WEBHOOK_16", icons::WEBHOOK_16)?;
    m.add("BOOKMARK_SLASH_FILL_24", icons::BOOKMARK_SLASH_FILL_24)?;
    m.add("LINK_EXTERNAL_16", icons::LINK_EXTERNAL_16)?;
    m.add("DEVICE_CAMERA_16", icons::DEVICE_CAMERA_16)?;
    m.add("VIDEO_24", icons::VIDEO_24)?;
    Ok(())
}
