// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_2(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("DEVICE_CAMERA_24", icons::DEVICE_CAMERA_24)?;
    m.add("SMILEY_GRIN_24", icons::SMILEY_GRIN_24)?;
    m.add("CHEVRON_DOWN_24", icons::CHEVRON_DOWN_24)?;
    m.add("GIT_COMPARE_24", icons::GIT_COMPARE_24)?;
    m.add("PROJECT_CHECK_16", icons::PROJECT_CHECK_16)?;
    m.add("FILE_BINARY_16", icons::FILE_BINARY_16)?;
    m.add("PROJECT_TEMPLATE_24", icons::PROJECT_TEMPLATE_24)?;
    m.add("STOP_16", icons::STOP_16)?;
    m.add("MIRROR_24", icons::MIRROR_24)?;
    m.add("DIAMOND_24", icons::DIAMOND_24)?;
    m.add("GRAPH_BAR_VERTICAL_16", icons::GRAPH_BAR_VERTICAL_16)?;
    m.add("MOVE_TO_TOP_24", icons::MOVE_TO_TOP_24)?;
    m.add("STOPWATCH_24", icons::STOPWATCH_24)?;
    m.add("CODE_OF_CONDUCT_24", icons::CODE_OF_CONDUCT_24)?;
    m.add("GIT_BRANCH_16", icons::GIT_BRANCH_16)?;
    m.add("MARK_GITHUB_16", icons::MARK_GITHUB_16)?;
    m.add("CODE_24", icons::CODE_24)?;
    m.add("CHEVRON_LEFT_12", icons::CHEVRON_LEFT_12)?;
    m.add("BOOKMARK_SLASH_24", icons::BOOKMARK_SLASH_24)?;
    m.add("SHIELD_CHECK_24", icons::SHIELD_CHECK_24)?;
    m.add("THUMBSDOWN_16", icons::THUMBSDOWN_16)?;
    m.add("TELESCOPE_FILL_16", icons::TELESCOPE_FILL_16)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_16",
        icons::TRACKED_BY_CLOSED_COMPLETED_16,
    )?;
    m.add("BROWSER_24", icons::BROWSER_24)?;
    m.add("MOVE_TO_START_24", icons::MOVE_TO_START_24)?;
    m.add("CODESCAN_24", icons::CODESCAN_24)?;
    m.add("CHECKBOX_FILL_16", icons::CHECKBOX_FILL_16)?;
    m.add("BELL_16", icons::BELL_16)?;
    m.add("DOT_FILL_24", icons::DOT_FILL_24)?;
    m.add("UNDO_24", icons::UNDO_24)?;
    m.add("REL_FILE_PATH_24", icons::REL_FILE_PATH_24)?;
    m.add("FILE_DIRECTORY_FILL_16", icons::FILE_DIRECTORY_FILL_16)?;
    m.add("TOOLS_16", icons::TOOLS_16)?;
    m.add("COLUMNS_24", icons::COLUMNS_24)?;
    m.add("GRABBER_16", icons::GRABBER_16)?;
    m.add("DASH_24", icons::DASH_24)?;
    m.add("PIVOT_COLUMN_24", icons::PIVOT_COLUMN_24)?;
    m.add("AGENT_24", icons::AGENT_24)?;
    m.add("ZOOM_IN_24", icons::ZOOM_IN_24)?;
    m.add("ARROW_LEFT_24", icons::ARROW_LEFT_24)?;
    m.add("STACK_REMOVE_16", icons::STACK_REMOVE_16)?;
    m.add("SQUARE_24", icons::SQUARE_24)?;
    m.add("SQUARE_FILL_24", icons::SQUARE_FILL_24)?;
    m.add("CODE_OF_CONDUCT_16", icons::CODE_OF_CONDUCT_16)?;
    m.add("TROPHY_24", icons::TROPHY_24)?;
    m.add("PROJECT_TEMPLATE_16", icons::PROJECT_TEMPLATE_16)?;
    m.add("HOURGLASS_24", icons::HOURGLASS_24)?;
    m.add("PROJECT_SYMLINK_24", icons::PROJECT_SYMLINK_24)?;
    m.add("ITALIC_16", icons::ITALIC_16)?;
    m.add("CACHE_16", icons::CACHE_16)?;
    m.add("ROWS_24", icons::ROWS_24)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_24",
        icons::TRACKED_BY_CLOSED_COMPLETED_24,
    )?;
    m.add("CHECKBOX_FILL_24", icons::CHECKBOX_FILL_24)?;
    m.add("ISSUE_CLOSED_16", icons::ISSUE_CLOSED_16)?;
    m.add("SIDEBAR_EXPAND_24", icons::SIDEBAR_EXPAND_24)?;
    m.add("DIFF_RENAMED_24", icons::DIFF_RENAMED_24)?;
    m.add("SYNC_24", icons::SYNC_24)?;
    m.add("THUMBSUP_24", icons::THUMBSUP_24)?;
    m.add("ARROW_RIGHT_16", icons::ARROW_RIGHT_16)?;
    m.add("BOLD_16", icons::BOLD_16)?;
    m.add("MOVE_TO_START_16", icons::MOVE_TO_START_16)?;
    m.add("ARROW_SWITCH_24", icons::ARROW_SWITCH_24)?;
    m.add("ACCESSIBILITY_24", icons::ACCESSIBILITY_24)?;
    m.add("SEARCH_16", icons::SEARCH_16)?;
    m.add("TELESCOPE_24", icons::TELESCOPE_24)?;
    m.add("PROJECT_24", icons::PROJECT_24)?;
    m.add("ARROW_DOWN_16", icons::ARROW_DOWN_16)?;
    m.add("RUBY_24", icons::RUBY_24)?;
    m.add("CODESCAN_CHECKMARK_16", icons::CODESCAN_CHECKMARK_16)?;
    m.add("ARROW_UP_24", icons::ARROW_UP_24)?;
    m.add("FOCUS_CENTER_24", icons::FOCUS_CENTER_24)?;
    m.add("SPACING_SMALL_16", icons::SPACING_SMALL_16)?;
    m.add("ARROW_DOWN_RIGHT_24", icons::ARROW_DOWN_RIGHT_24)?;
    m.add("REPO_PULL_24", icons::REPO_PULL_24)?;
    m.add("FEED_ROCKET_16", icons::FEED_ROCKET_16)?;
    m.add("TRIANGLE_LEFT_24", icons::TRIANGLE_LEFT_24)?;
    m.add("FOLD_UP_16", icons::FOLD_UP_16)?;
    m.add("MENTION_24", icons::MENTION_24)?;
    m.add("REPO_CLONE_16", icons::REPO_CLONE_16)?;
    m.add("TAG_16", icons::TAG_16)?;
    m.add("UNREAD_16", icons::UNREAD_16)?;
    m.add("BRIEFCASE_16", icons::BRIEFCASE_16)?;
    m.add("NO_ENTRY_24", icons::NO_ENTRY_24)?;
    m.add("IMAGE_16", icons::IMAGE_16)?;
    m.add("NODE_24", icons::NODE_24)?;
    m.add("PULSE_16", icons::PULSE_16)?;
    m.add("GRAPH_BAR_VERTICAL_24", icons::GRAPH_BAR_VERTICAL_24)?;
    m.add("X_CIRCLE_FILL_16", icons::X_CIRCLE_FILL_16)?;
    m.add("PERSON_ADD_24", icons::PERSON_ADD_24)?;
    m.add("PULSE_24", icons::PULSE_24)?;
    m.add("CODESPACES_24", icons::CODESPACES_24)?;
    m.add("GIT_PULL_REQUEST_16", icons::GIT_PULL_REQUEST_16)?;
    m.add("TRASH_24", icons::TRASH_24)?;
    m.add("SMILEY_FRUSTRATED_24", icons::SMILEY_FRUSTRATED_24)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_16",
        icons::FILE_DIRECTORY_OPEN_FILL_16,
    )?;
    m.add("ZAP_24", icons::ZAP_24)?;
    m.add("SPACING_MEDIUM_16", icons::SPACING_MEDIUM_16)?;
    m.add("ITERATIONS_16", icons::ITERATIONS_16)?;
    m.add("SERVER_24", icons::SERVER_24)?;
    m.add("SHARE_16", icons::SHARE_16)?;
    m.add("LOCKUP_GITHUB_24", icons::LOCKUP_GITHUB_24)?;
    m.add("REPO_PUSH_16", icons::REPO_PUSH_16)?;
    m.add("REPO_CLONE_24", icons::REPO_CLONE_24)?;
    m.add("LINK_24", icons::LINK_24)?;
    m.add(
        "TRACKED_BY_CLOSED_NOT_PLANNED_16",
        icons::TRACKED_BY_CLOSED_NOT_PLANNED_16,
    )?;
    m.add("DOT_FILL_16", icons::DOT_FILL_16)?;
    m.add("UPLOAD_24", icons::UPLOAD_24)?;
    m.add("BOLD_24", icons::BOLD_24)?;
    m.add("SPARKLES_FILL_16", icons::SPARKLES_FILL_16)?;
    m.add("APPS_24", icons::APPS_24)?;
    m.add("COMPOSE_24", icons::COMPOSE_24)?;
    m.add("COMMAND_PALETTE_16", icons::COMMAND_PALETTE_16)?;
    m.add("FLAME_24", icons::FLAME_24)?;
    m.add("STRIKETHROUGH_24", icons::STRIKETHROUGH_24)?;
    m.add("ALERT_24", icons::ALERT_24)?;
    m.add("SQUIRREL_16", icons::SQUIRREL_16)?;
    m.add("FOLD_DOWN_24", icons::FOLD_DOWN_24)?;
    m.add("STAR_16", icons::STAR_16)?;
    m.add("NOTE_24", icons::NOTE_24)?;
    m.add(
        "GIT_PULL_REQUEST_DRAFT_16",
        icons::GIT_PULL_REQUEST_DRAFT_16,
    )?;
    m.add("DEVICE_MOBILE_24", icons::DEVICE_MOBILE_24)?;
    m.add("MORTAR_BOARD_16", icons::MORTAR_BOARD_16)?;
    m.add("SPONSOR_TIERS_16", icons::SPONSOR_TIERS_16)?;
    m.add("ISSUE_CLOSED_24", icons::ISSUE_CLOSED_24)?;
    m.add("BOOKMARK_24", icons::BOOKMARK_24)?;
    m.add("X_12", icons::X_12)?;
    m.add("MUTE_16", icons::MUTE_16)?;
    m.add("CHECK_CIRCLE_FILL_16", icons::CHECK_CIRCLE_FILL_16)?;
    m.add("ITALIC_24", icons::ITALIC_24)?;
    m.add("TRIANGLE_UP_24", icons::TRIANGLE_UP_24)?;
    m.add("MINIMIZE_16", icons::MINIMIZE_16)?;
    m.add("ACCESSIBILITY_INSET_16", icons::ACCESSIBILITY_INSET_16)?;
    m.add("INFINITY_24", icons::INFINITY_24)?;
    m.add("LIGHT_BULB_24", icons::LIGHT_BULB_24)?;
    m.add("SHIELD_SLASH_24", icons::SHIELD_SLASH_24)?;
    m.add("ISSUE_DRAFT_16", icons::ISSUE_DRAFT_16)?;
    m.add("CLOUD_16", icons::CLOUD_16)?;
    m.add("MOON_24", icons::MOON_24)?;
    m.add("STRIKETHROUGH_16", icons::STRIKETHROUGH_16)?;
    m.add("CROSSHAIRS_16", icons::CROSSHAIRS_16)?;
    m.add("HISTORY_16", icons::HISTORY_16)?;
    m.add("HOME_FILL_16", icons::HOME_FILL_16)?;
    m.add("FLAME_16", icons::FLAME_16)?;
    m.add("FEED_PLUS_16", icons::FEED_PLUS_16)?;
    m.add("CODESCAN_16", icons::CODESCAN_16)?;
    m.add("CIRCLE_24", icons::CIRCLE_24)?;
    m.add("COMMENT_16", icons::COMMENT_16)?;
    m.add("COPY_16", icons::COPY_16)?;
    m.add("SHARE_24", icons::SHARE_24)?;
    m.add("CHECKLIST_16", icons::CHECKLIST_16)?;
    m.add("DICE_16", icons::DICE_16)?;
    m.add("CHECK_CIRCLE_FILL_12", icons::CHECK_CIRCLE_FILL_12)?;
    m.add("MOVE_TO_TOP_16", icons::MOVE_TO_TOP_16)?;
    m.add("GRAPH_16", icons::GRAPH_16)?;
    m.add("CREDIT_CARD_24", icons::CREDIT_CARD_24)?;
    m.add("GIT_COMPARE_16", icons::GIT_COMPARE_16)?;
    m.add("SPLIT_VIEW_24", icons::SPLIT_VIEW_24)?;
    m.add("MULTI_SELECT_24", icons::MULTI_SELECT_24)?;
    m.add("MILESTONE_16", icons::MILESTONE_16)?;
    m.add("STACK_CHECK_16", icons::STACK_CHECK_16)?;
    m.add("REPO_TEMPLATE_16", icons::REPO_TEMPLATE_16)?;
    m.add("SMILEY_GRIN_16", icons::SMILEY_GRIN_16)?;
    m.add("PENCIL_AI_16", icons::PENCIL_AI_16)?;
    m.add("FLAG_24", icons::FLAG_24)?;
    m.add("GIFT_16", icons::GIFT_16)?;
    m.add("DOT_16", icons::DOT_16)?;
    m.add("ROWS_16", icons::ROWS_16)?;
    m.add("CODE_SQUARE_16", icons::CODE_SQUARE_16)?;
    m.add("CHEVRON_LEFT_24", icons::CHEVRON_LEFT_24)?;
    m.add("ARROW_UP_LEFT_16", icons::ARROW_UP_LEFT_16)?;
    m.add("THREE_BARS_16", icons::THREE_BARS_16)?;
    m.add("REPO_PULL_16", icons::REPO_PULL_16)?;
    m.add("SQUIRREL_24", icons::SQUIRREL_24)?;
    m.add("ISSUE_REOPENED_24", icons::ISSUE_REOPENED_24)?;
    m.add("HISTORY_24", icons::HISTORY_24)?;
    m.add("QUESTION_16", icons::QUESTION_16)?;
    m.add("DUPLICATE_24", icons::DUPLICATE_24)?;
    m.add("SMILEY_FROWN_16", icons::SMILEY_FROWN_16)?;
    m.add("CODE_REVIEW_24", icons::CODE_REVIEW_24)?;
    m.add("GIT_BRANCH_CHECK_24", icons::GIT_BRANCH_CHECK_24)?;
    m.add("FOLD_UP_24", icons::FOLD_UP_24)?;
    m.add("BELL_FILL_24", icons::BELL_FILL_24)?;
    m.add("REPO_DELETED_16", icons::REPO_DELETED_16)?;
    m.add("ELLIPSIS_24", icons::ELLIPSIS_24)?;
    m.add("COMMENT_DISCUSSION_24", icons::COMMENT_DISCUSSION_24)?;
    m.add("CROSS_REFERENCE_16", icons::CROSS_REFERENCE_16)?;
    m.add("CLOUD_24", icons::CLOUD_24)?;
    m.add("EYE_CLOSED_24", icons::EYE_CLOSED_24)?;
    m.add("UPLOAD_16", icons::UPLOAD_16)?;
    m.add("NORTH_STAR_16", icons::NORTH_STAR_16)?;
    m.add("SQUARE_CIRCLE_24", icons::SQUARE_CIRCLE_24)?;
    m.add("TRIANGLE_UP_16", icons::TRIANGLE_UP_16)?;
    m.add("PAPERCLIP_24", icons::PAPERCLIP_24)?;
    m.add("ARCHIVE_16", icons::ARCHIVE_16)?;
    m.add("TROPHY_16", icons::TROPHY_16)?;
    m.add("FILE_CODE_24", icons::FILE_CODE_24)?;
    m.add("REPORT_24", icons::REPORT_24)?;
    m.add("REL_FILE_PATH_16", icons::REL_FILE_PATH_16)?;
    m.add("SHIELD_LOCK_16", icons::SHIELD_LOCK_16)?;
    m.add("NO_ENTRY_16", icons::NO_ENTRY_16)?;
    Ok(())
}
