// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_2(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("FILE_MOVED_24", icons::FILE_MOVED_24)?;
    m.add("X_CIRCLE_24", icons::X_CIRCLE_24)?;
    m.add("UNFOLD_24", icons::UNFOLD_24)?;
    m.add("INBOX_FILL_16", icons::INBOX_FILL_16)?;
    m.add("MINIMIZE_24", icons::MINIMIZE_24)?;
    m.add("HOME_24", icons::HOME_24)?;
    m.add("HOME_FILL_16", icons::HOME_FILL_16)?;
    m.add("UNREAD_16", icons::UNREAD_16)?;
    m.add("MUTE_16", icons::MUTE_16)?;
    m.add("HEADING_24", icons::HEADING_24)?;
    m.add("MOVE_TO_TOP_24", icons::MOVE_TO_TOP_24)?;
    m.add("ARROW_DOWN_16", icons::ARROW_DOWN_16)?;
    m.add("GRABBER_16", icons::GRABBER_16)?;
    m.add("SPACING_SMALL_24", icons::SPACING_SMALL_24)?;
    m.add("HOURGLASS_24", icons::HOURGLASS_24)?;
    m.add("PLUS_24", icons::PLUS_24)?;
    m.add("WEBHOOK_16", icons::WEBHOOK_16)?;
    m.add("TABLE_16", icons::TABLE_16)?;
    m.add("MUTE_24", icons::MUTE_24)?;
    m.add("PAUSE_16", icons::PAUSE_16)?;
    m.add("COPILOT_ERROR_16", icons::COPILOT_ERROR_16)?;
    m.add("DUPLICATE_24", icons::DUPLICATE_24)?;
    m.add("HEART_16", icons::HEART_16)?;
    m.add("KEY_16", icons::KEY_16)?;
    m.add("SHIELD_SLASH_24", icons::SHIELD_SLASH_24)?;
    m.add("BOOKMARK_SLASH_16", icons::BOOKMARK_SLASH_16)?;
    m.add("MIRROR_16", icons::MIRROR_16)?;
    m.add("FISCAL_HOST_16", icons::FISCAL_HOST_16)?;
    m.add("RSS_24", icons::RSS_24)?;
    m.add("FEED_PERSON_16", icons::FEED_PERSON_16)?;
    m.add("DEVICES_16", icons::DEVICES_16)?;
    m.add("CPU_16", icons::CPU_16)?;
    m.add("ARROW_SWITCH_24", icons::ARROW_SWITCH_24)?;
    m.add("FILE_BINARY_24", icons::FILE_BINARY_24)?;
    m.add("LIGHT_BULB_24", icons::LIGHT_BULB_24)?;
    m.add("SPARKLE_16", icons::SPARKLE_16)?;
    m.add("COMMAND_PALETTE_16", icons::COMMAND_PALETTE_16)?;
    m.add(
        "GIT_PULL_REQUEST_LOCKED_16",
        icons::GIT_PULL_REQUEST_LOCKED_16,
    )?;
    m.add("FILE_DIRECTORY_16", icons::FILE_DIRECTORY_16)?;
    m.add("SUN_24", icons::SUN_24)?;
    m.add("ISSUE_OPENED_24", icons::ISSUE_OPENED_24)?;
    m.add("HOME_FILL_24", icons::HOME_FILL_24)?;
    m.add("REPO_DELETED_16", icons::REPO_DELETED_16)?;
    m.add("NO_ENTRY_FILL_12", icons::NO_ENTRY_FILL_12)?;
    m.add("X_12", icons::X_12)?;
    m.add("COPILOT_WARNING_16", icons::COPILOT_WARNING_16)?;
    m.add("SMILEY_FRUSTRATED_16", icons::SMILEY_FRUSTRATED_16)?;
    m.add("ARROW_DOWN_RIGHT_24", icons::ARROW_DOWN_RIGHT_24)?;
    m.add("PERSON_16", icons::PERSON_16)?;
    m.add("STRIKETHROUGH_24", icons::STRIKETHROUGH_24)?;
    m.add("DEVICE_CAMERA_VIDEO_24", icons::DEVICE_CAMERA_VIDEO_24)?;
    m.add("REPO_PUSH_16", icons::REPO_PUSH_16)?;
    m.add("BOOKMARK_SLASH_FILL_24", icons::BOOKMARK_SLASH_FILL_24)?;
    m.add("MOVE_TO_TOP_16", icons::MOVE_TO_TOP_16)?;
    m.add("ARROW_DOWN_LEFT_24", icons::ARROW_DOWN_LEFT_24)?;
    m.add("CODE_SQUARE_16", icons::CODE_SQUARE_16)?;
    m.add("COMMENT_16", icons::COMMENT_16)?;
    m.add("HASH_24", icons::HASH_24)?;
    m.add("UNLOCK_24", icons::UNLOCK_24)?;
    m.add("BELL_SLASH_24", icons::BELL_SLASH_24)?;
    m.add("RUBY_16", icons::RUBY_16)?;
    m.add("PROJECT_SYMLINK_24", icons::PROJECT_SYMLINK_24)?;
    m.add("CLOUD_OFFLINE_24", icons::CLOUD_OFFLINE_24)?;
    m.add("DIFF_REMOVED_16", icons::DIFF_REMOVED_16)?;
    m.add("GIT_MERGE_QUEUE_24", icons::GIT_MERGE_QUEUE_24)?;
    m.add("PERSON_ADD_16", icons::PERSON_ADD_16)?;
    m.add("ACCESSIBILITY_INSET_24", icons::ACCESSIBILITY_INSET_24)?;
    m.add("BOOLEAN_ON_24", icons::BOOLEAN_ON_24)?;
    m.add("STOP_16", icons::STOP_16)?;
    m.add("PASSKEY_FILL_24", icons::PASSKEY_FILL_24)?;
    m.add("TRIANGLE_UP_24", icons::TRIANGLE_UP_24)?;
    m.add(
        "TRACKED_BY_CLOSED_NOT_PLANNED_24",
        icons::TRACKED_BY_CLOSED_NOT_PLANNED_24,
    )?;
    m.add("SPARKLE_24", icons::SPARKLE_24)?;
    m.add("SMILEY_NEUTRAL_16", icons::SMILEY_NEUTRAL_16)?;
    m.add("SPLIT_VIEW_16", icons::SPLIT_VIEW_16)?;
    m.add("FEED_PLUS_16", icons::FEED_PLUS_16)?;
    m.add("SKIP_FILL_16", icons::SKIP_FILL_16)?;
    m.add("DISCUSSION_OUTDATED_16", icons::DISCUSSION_OUTDATED_16)?;
    m.add("EYE_CLOSED_16", icons::EYE_CLOSED_16)?;
    m.add("FILE_REMOVED_24", icons::FILE_REMOVED_24)?;
    m.add("GLOBE_16", icons::GLOBE_16)?;
    m.add("MINIMIZE_16", icons::MINIMIZE_16)?;
    m.add("MARKDOWN_24", icons::MARKDOWN_24)?;
    m.add("CODESCAN_CHECKMARK_16", icons::CODESCAN_CHECKMARK_16)?;
    m.add("SORT_DESC_24", icons::SORT_DESC_24)?;
    m.add("CODE_OF_CONDUCT_24", icons::CODE_OF_CONDUCT_24)?;
    m.add("PAPERCLIP_24", icons::PAPERCLIP_24)?;
    m.add("THUMBSDOWN_24", icons::THUMBSDOWN_24)?;
    m.add("CHEVRON_UP_16", icons::CHEVRON_UP_16)?;
    m.add("CLOCK_FILL_24", icons::CLOCK_FILL_24)?;
    m.add("PAINTBRUSH_24", icons::PAINTBRUSH_24)?;
    m.add("ZOOM_IN_24", icons::ZOOM_IN_24)?;
    m.add("SPACING_MEDIUM_24", icons::SPACING_MEDIUM_24)?;
    m.add("SMILEY_GRIN_24", icons::SMILEY_GRIN_24)?;
    m.add("BOOLEAN_OFF_24", icons::BOOLEAN_OFF_24)?;
    m.add("LOGO_GIST_24", icons::LOGO_GIST_24)?;
    m.add("TASKLIST_16", icons::TASKLIST_16)?;
    m.add("BUG_24", icons::BUG_24)?;
    m.add("LIST_ORDERED_24", icons::LIST_ORDERED_24)?;
    m.add("CHECK_CIRCLE_24", icons::CHECK_CIRCLE_24)?;
    m.add("PIN_16", icons::PIN_16)?;
    m.add("AGENT_24", icons::AGENT_24)?;
    m.add("LOGO_GITHUB_16", icons::LOGO_GITHUB_16)?;
    m.add("TYPOGRAPHY_24", icons::TYPOGRAPHY_24)?;
    m.add(
        "TRACKED_BY_CLOSED_COMPLETED_24",
        icons::TRACKED_BY_CLOSED_COMPLETED_24,
    )?;
    m.add("GIFT_16", icons::GIFT_16)?;
    m.add("APPS_24", icons::APPS_24)?;
    m.add("LAW_16", icons::LAW_16)?;
    m.add("MOVE_TO_BOTTOM_16", icons::MOVE_TO_BOTTOM_16)?;
    m.add("CHECKLIST_16", icons::CHECKLIST_16)?;
    m.add("SPACE_24", icons::SPACE_24)?;
    m.add("CROSS_REFERENCE_16", icons::CROSS_REFERENCE_16)?;
    m.add("BOOK_LOCKED_16", icons::BOOK_LOCKED_16)?;
    m.add("ROWS_16", icons::ROWS_16)?;
    m.add("TRIANGLE_LEFT_24", icons::TRIANGLE_LEFT_24)?;
    m.add("ID_BADGE_16", icons::ID_BADGE_16)?;
    m.add("PAUSE_24", icons::PAUSE_24)?;
    m.add("FEED_PUBLIC_16", icons::FEED_PUBLIC_16)?;
    m.add("PAINTBRUSH_16", icons::PAINTBRUSH_16)?;
    m.add("VSCODE_16", icons::VSCODE_16)?;
    m.add("ISSUE_OPENED_16", icons::ISSUE_OPENED_16)?;
    m.add("GIT_MERGE_16", icons::GIT_MERGE_16)?;
    m.add("BOOLEAN_ON_16", icons::BOOLEAN_ON_16)?;
    m.add("LOG_16", icons::LOG_16)?;
    m.add("CODE_REVIEW_16", icons::CODE_REVIEW_16)?;
    m.add("FILE_DIRECTORY_FILL_24", icons::FILE_DIRECTORY_FILL_24)?;
    m.add("ARROW_DOWN_LEFT_16", icons::ARROW_DOWN_LEFT_16)?;
    m.add("SPACING_SMALL_16", icons::SPACING_SMALL_16)?;
    m.add("ARROW_BOTH_24", icons::ARROW_BOTH_24)?;
    m.add("MEGAPHONE_24", icons::MEGAPHONE_24)?;
    m.add("APPS_16", icons::APPS_16)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_16",
        icons::FILE_DIRECTORY_OPEN_FILL_16,
    )?;
    m.add("CHEVRON_LEFT_12", icons::CHEVRON_LEFT_12)?;
    m.add("KEBAB_HORIZONTAL_24", icons::KEBAB_HORIZONTAL_24)?;
    m.add("REPO_LOCKED_24", icons::REPO_LOCKED_24)?;
    m.add("ACCESSIBILITY_INSET_16", icons::ACCESSIBILITY_INSET_16)?;
    m.add("FEED_REPO_16", icons::FEED_REPO_16)?;
    m.add("ALERT_24", icons::ALERT_24)?;
    m.add("ARCHIVE_16", icons::ARCHIVE_16)?;
    m.add("CODESPACES_24", icons::CODESPACES_24)?;
    m.add("BOOLEAN_OFF_16", icons::BOOLEAN_OFF_16)?;
    m.add("BROWSER_16", icons::BROWSER_16)?;
    m.add("FLOWCHART_24", icons::FLOWCHART_24)?;
    m.add("ISSUE_LOCKED_16", icons::ISSUE_LOCKED_16)?;
    m.add("FILE_SUBMODULE_24", icons::FILE_SUBMODULE_24)?;
    m.add("DIFF_IGNORED_24", icons::DIFF_IGNORED_24)?;
    m.add("SMILEY_FROWN_16", icons::SMILEY_FROWN_16)?;
    m.add("GRAPH_16", icons::GRAPH_16)?;
    m.add("FILTER_REMOVE_16", icons::FILTER_REMOVE_16)?;
    m.add("BOOKMARK_SLASH_24", icons::BOOKMARK_SLASH_24)?;
    m.add("UNDO_16", icons::UNDO_16)?;
    m.add("NO_ENTRY_24", icons::NO_ENTRY_24)?;
    m.add("PERSON_FILL_24", icons::PERSON_FILL_24)?;
    m.add("GRAPH_BAR_VERTICAL_16", icons::GRAPH_BAR_VERTICAL_16)?;
    m.add("ARROW_UP_RIGHT_16", icons::ARROW_UP_RIGHT_16)?;
    m.add("SEARCH_16", icons::SEARCH_16)?;
    m.add("ID_BADGE_24", icons::ID_BADGE_24)?;
    m.add("BOOKMARK_FILLED_16", icons::BOOKMARK_FILLED_16)?;
    m.add("CREDIT_CARD_16", icons::CREDIT_CARD_16)?;
    m.add("QUOTE_16", icons::QUOTE_16)?;
    m.add("LIGHT_BULB_16", icons::LIGHT_BULB_16)?;
    m.add("CONTAINER_16", icons::CONTAINER_16)?;
    m.add("PACKAGE_16", icons::PACKAGE_16)?;
    m.add("FILE_CODE_24", icons::FILE_CODE_24)?;
    m.add("FILE_16", icons::FILE_16)?;
    m.add("FILE_DIRECTORY_24", icons::FILE_DIRECTORY_24)?;
    m.add("CHEVRON_RIGHT_16", icons::CHEVRON_RIGHT_16)?;
    m.add("DESKTOP_DOWNLOAD_16", icons::DESKTOP_DOWNLOAD_16)?;
    m.add("BOOK_16", icons::BOOK_16)?;
    m.add("SHARE_ANDROID_24", icons::SHARE_ANDROID_24)?;
    m.add("SCREEN_FULL_24", icons::SCREEN_FULL_24)?;
    m.add("STRIKETHROUGH_16", icons::STRIKETHROUGH_16)?;
    m.add("SHARE_24", icons::SHARE_24)?;
    m.add("FILE_SUBMODULE_16", icons::FILE_SUBMODULE_16)?;
    m.add("UNVERIFIED_24", icons::UNVERIFIED_24)?;
    m.add("TROPHY_24", icons::TROPHY_24)?;
    m.add("TELESCOPE_16", icons::TELESCOPE_16)?;
    m.add("DOWNLOAD_16", icons::DOWNLOAD_16)?;
    m.add("FILE_CHECK_16", icons::FILE_CHECK_16)?;
    m.add("FOLD_16", icons::FOLD_16)?;
    m.add("SMILEY_FRUSTRATED_24", icons::SMILEY_FRUSTRATED_24)?;
    m.add("PROJECT_16", icons::PROJECT_16)?;
    m.add("GIT_COMMIT_16", icons::GIT_COMMIT_16)?;
    m.add("SHIELD_X_16", icons::SHIELD_X_16)?;
    m.add("REDO_16", icons::REDO_16)?;
    m.add("FEED_ISSUE_CLOSED_16", icons::FEED_ISSUE_CLOSED_16)?;
    m.add("SHIELD_LOCK_24", icons::SHIELD_LOCK_24)?;
    m.add("SQUARE_FILL_24", icons::SQUARE_FILL_24)?;
    m.add("CHECK_CIRCLE_16", icons::CHECK_CIRCLE_16)?;
    m.add(
        "FILE_DIRECTORY_OPEN_FILL_24",
        icons::FILE_DIRECTORY_OPEN_FILL_24,
    )?;
    m.add("SUN_16", icons::SUN_16)?;
    m.add("QUOTE_24", icons::QUOTE_24)?;
    m.add("MULTI_SELECT_16", icons::MULTI_SELECT_16)?;
    m.add("DEVICE_CAMERA_16", icons::DEVICE_CAMERA_16)?;
    m.add("TERMINAL_24", icons::TERMINAL_24)?;
    m.add("STOPWATCH_16", icons::STOPWATCH_16)?;
    m.add("BELL_FILL_24", icons::BELL_FILL_24)?;
    m.add("MAIL_24", icons::MAIL_24)?;
    m.add("SHARE_ANDROID_16", icons::SHARE_ANDROID_16)?;
    m.add("ARROW_LEFT_24", icons::ARROW_LEFT_24)?;
    Ok(())
}
