# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

# Allow beta ecosystems.
# This can be removed when deno support is stable.
# see https://github.com/dependabot/dependabot-core/issues/2417
enable-beta-ecosystems: true

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      uv-pip:
        patterns:
          - "*"
  - package-ecosystem: deno # zizmor: ignore[dependabot-cooldown]
    directories:
      - /
      - /common
      - /crates/fontawesome
      - /crates/mdi
      - /crates/octicons
      - /crates/simple-icons
    schedule:
      interval: "daily"
      # run sunday, tuesday, and thursday
      # cronjob: 0 0 * * 0,2,4
    groups:
      deno:
        patterns:
          - "*"
