// This file was generated. DO NOT EDIT.
use crate::icons;
use pyo3::prelude::*;

pub(super) fn bind_part_9(m: &Bound<PyModule>) -> PyResult<()> {
    m.add("SI_ROON", icons::SI_ROON)?;
    m.add(
        "SI_HOMEASSISTANTCOMMUNITYSTORE",
        icons::SI_HOMEASSISTANTCOMMUNITYSTORE,
    )?;
    m.add("SI_THEWASHINGTONPOST", icons::SI_THEWASHINGTONPOST)?;
    m.add("SI_CLOUDRON", icons::SI_CLOUDRON)?;
    m.add("SI_MOLECULER", icons::SI_MOLECULER)?;
    m.add("SI_IMPROVMX", icons::SI_IMPROVMX)?;
    m.add("SI_MINI", icons::SI_MINI)?;
    m.add("SI_FOSSA", icons::SI_FOSSA)?;
    m.add("SI_VIBLO", icons::SI_VIBLO)?;
    m.add("SI_IFTTT", icons::SI_IFTTT)?;
    m.add("SI_BREX", icons::SI_BREX)?;
    m.add("SI_SPOTIFY", icons::SI_SPOTIFY)?;
    m.add("SI_FACEBOOKGAMING", icons::SI_FACEBOOKGAMING)?;
    m.add("SI_BOWER", icons::SI_BOWER)?;
    m.add("SI_APACHENIFI", icons::SI_APACHENIFI)?;
    m.add("SI_DUCKDUCKGO", icons::SI_DUCKDUCKGO)?;
    m.add("SI_ADBLOCK", icons::SI_ADBLOCK)?;
    m.add("SI_DENODEPLOY", icons::SI_DENODEPLOY)?;
    m.add("SI_IONIC", icons::SI_IONIC)?;
    m.add("SI_LIDL", icons::SI_LIDL)?;
    m.add(
        "SI_INTERACTIONDESIGNFOUNDATION",
        icons::SI_INTERACTIONDESIGNFOUNDATION,
    )?;
    m.add("SI_SPACEX", icons::SI_SPACEX)?;
    m.add("SI_ECLIPSECHE", icons::SI_ECLIPSECHE)?;
    m.add("SI_MEETUP", icons::SI_MEETUP)?;
    m.add("SI_IBERIA", icons::SI_IBERIA)?;
    m.add("SI_PUBLONS", icons::SI_PUBLONS)?;
    m.add("SI_LINKSYS", icons::SI_LINKSYS)?;
    m.add("SI_SKY", icons::SI_SKY)?;
    m.add("SI_TRANSIFEX", icons::SI_TRANSIFEX)?;
    m.add("SI_BEATSTARS", icons::SI_BEATSTARS)?;
    m.add("SI_NOW", icons::SI_NOW)?;
    m.add("SI_TIDE", icons::SI_TIDE)?;
    m.add("SI_DEVUAN", icons::SI_DEVUAN)?;
    m.add("SI_HOSTINGER", icons::SI_HOSTINGER)?;
    m.add("SI_LOOM", icons::SI_LOOM)?;
    m.add("SI_SERVERLESS", icons::SI_SERVERLESS)?;
    m.add("SI_MXLINUX", icons::SI_MXLINUX)?;
    m.add("SI_CHAI", icons::SI_CHAI)?;
    m.add("SI_ROOTSBEDROCK", icons::SI_ROOTSBEDROCK)?;
    m.add("SI_UBIQUITI", icons::SI_UBIQUITI)?;
    m.add("SI_LEROYMERLIN", icons::SI_LEROYMERLIN)?;
    m.add("SI_RING", icons::SI_RING)?;
    m.add("SI_SAT1", icons::SI_SAT1)?;
    m.add("SI_UBER", icons::SI_UBER)?;
    m.add("SI_TARGET", icons::SI_TARGET)?;
    m.add("SI_SMARTTHINGS", icons::SI_SMARTTHINGS)?;
    m.add("SI_PIX", icons::SI_PIX)?;
    m.add("SI_BAIDU", icons::SI_BAIDU)?;
    m.add("SI_SESSIONIZE", icons::SI_SESSIONIZE)?;
    m.add("SI_NISSAN", icons::SI_NISSAN)?;
    m.add("SI_TRANSPORTFORIRELAND", icons::SI_TRANSPORTFORIRELAND)?;
    m.add("SI_DAZN", icons::SI_DAZN)?;
    m.add("SI_PEAKDESIGN", icons::SI_PEAKDESIGN)?;
    m.add("SI_MTR", icons::SI_MTR)?;
    m.add(
        "SI_COMMONWORKFLOWLANGUAGE",
        icons::SI_COMMONWORKFLOWLANGUAGE,
    )?;
    m.add("SI_PROSIEBEN", icons::SI_PROSIEBEN)?;
    m.add("SI_GITFORWINDOWS", icons::SI_GITFORWINDOWS)?;
    m.add("SI_SIFIVE", icons::SI_SIFIVE)?;
    m.add("SI_BACKENDLESS", icons::SI_BACKENDLESS)?;
    m.add("SI_NANOSTORES", icons::SI_NANOSTORES)?;
    m.add("SI_PREFECT", icons::SI_PREFECT)?;
    m.add("SI_ARGOS", icons::SI_ARGOS)?;
    m.add("SI_NX", icons::SI_NX)?;
    m.add("SI_TERATAIL", icons::SI_TERATAIL)?;
    m.add("SI_RABBITMQ", icons::SI_RABBITMQ)?;
    m.add("SI_IMMICH", icons::SI_IMMICH)?;
    m.add("SI_LESS", icons::SI_LESS)?;
    m.add("SI_DAISYUI", icons::SI_DAISYUI)?;
    m.add("SI_PAPERSPACE", icons::SI_PAPERSPACE)?;
    m.add("SI_WANTEDLY", icons::SI_WANTEDLY)?;
    m.add("SI_DISTROKID", icons::SI_DISTROKID)?;
    m.add("SI_DUOLINGO", icons::SI_DUOLINGO)?;
    m.add("SI_FLUENTBIT", icons::SI_FLUENTBIT)?;
    m.add("SI_TRILIUM", icons::SI_TRILIUM)?;
    m.add("SI_OXYGEN", icons::SI_OXYGEN)?;
    m.add("SI_ALFRED", icons::SI_ALFRED)?;
    m.add("SI_WHATSAPP", icons::SI_WHATSAPP)?;
    m.add("SI_ZEBPAY", icons::SI_ZEBPAY)?;
    m.add("SI_LIBREOFFICE", icons::SI_LIBREOFFICE)?;
    m.add("SI_WISH", icons::SI_WISH)?;
    m.add("SI_CASTBOX", icons::SI_CASTBOX)?;
    m.add("SI_GRIDDOTAI", icons::SI_GRIDDOTAI)?;
    m.add("SI_BITDEFENDER", icons::SI_BITDEFENDER)?;
    m.add("SI_FORMSPREE", icons::SI_FORMSPREE)?;
    m.add("SI_KEEWEB", icons::SI_KEEWEB)?;
    m.add("SI_LIT", icons::SI_LIT)?;
    m.add("SI_INTERBASE", icons::SI_INTERBASE)?;
    m.add("SI_RAYCAST", icons::SI_RAYCAST)?;
    m.add("SI_WPROCKET", icons::SI_WPROCKET)?;
    m.add("SI_SURFSHARK", icons::SI_SURFSHARK)?;
    m.add("SI_ICON", icons::SI_ICON)?;
    m.add("SI_DEEPSEEK", icons::SI_DEEPSEEK)?;
    m.add("SI_NASA", icons::SI_NASA)?;
    m.add("SI_GPLV3", icons::SI_GPLV3)?;
    m.add("SI_MASTERCARD", icons::SI_MASTERCARD)?;
    m.add("SI_MANGAUPDATES", icons::SI_MANGAUPDATES)?;
    m.add("SI_TWENTY", icons::SI_TWENTY)?;
    m.add("SI_BRITISHAIRWAYS", icons::SI_BRITISHAIRWAYS)?;
    m.add("SI_SURREALDB", icons::SI_SURREALDB)?;
    m.add("SI_FRANPRIX", icons::SI_FRANPRIX)?;
    m.add("SI_N26", icons::SI_N26)?;
    m.add("SI_NEC", icons::SI_NEC)?;
    m.add("SI_GERRIT", icons::SI_GERRIT)?;
    m.add("SI_OPENVERSE", icons::SI_OPENVERSE)?;
    m.add("SI_SIMKL", icons::SI_SIMKL)?;
    m.add("SI_INSTATUS", icons::SI_INSTATUS)?;
    m.add("SI_KIA", icons::SI_KIA)?;
    m.add(
        "SI_GOOGLEDISPLAYANDVIDEO360",
        icons::SI_GOOGLEDISPLAYANDVIDEO360,
    )?;
    m.add("SI_ROBOTFRAMEWORK", icons::SI_ROBOTFRAMEWORK)?;
    m.add("SI_PINETWORK", icons::SI_PINETWORK)?;
    m.add("SI_WAKATIME", icons::SI_WAKATIME)?;
    m.add("SI_ALDISUD", icons::SI_ALDISUD)?;
    m.add("SI_QUARTO", icons::SI_QUARTO)?;
    m.add("SI_DEVBOX", icons::SI_DEVBOX)?;
    m.add("SI_JIRA", icons::SI_JIRA)?;
    m.add("SI_DECENTRALAND", icons::SI_DECENTRALAND)?;
    m.add("SI_RUST", icons::SI_RUST)?;
    m.add("SI_GITHUBCOPILOT", icons::SI_GITHUBCOPILOT)?;
    m.add("SI_EIGHT", icons::SI_EIGHT)?;
    m.add("SI_THREEMA", icons::SI_THREEMA)?;
    m.add("SI_FAKER", icons::SI_FAKER)?;
    m.add("SI_PUPPETEER", icons::SI_PUPPETEER)?;
    m.add("SI_SONY", icons::SI_SONY)?;
    m.add("SI_KEENETIC", icons::SI_KEENETIC)?;
    m.add("SI_CREWAI", icons::SI_CREWAI)?;
    m.add("SI_MALWAREBYTES", icons::SI_MALWAREBYTES)?;
    m.add("SI_NODERED", icons::SI_NODERED)?;
    m.add("SI_THEMIGHTY", icons::SI_THEMIGHTY)?;
    m.add("SI_MODIN", icons::SI_MODIN)?;
    m.add("SI_LIVEJOURNAL", icons::SI_LIVEJOURNAL)?;
    m.add("SI_HP", icons::SI_HP)?;
    m.add("SI_KDENEON", icons::SI_KDENEON)?;
    m.add("SI_FIAT", icons::SI_FIAT)?;
    m.add("SI_1PANEL", icons::SI_1PANEL)?;
    m.add("SI_GOOGLETV", icons::SI_GOOGLETV)?;
    m.add("SI_RAILWAY", icons::SI_RAILWAY)?;
    m.add("SI_OPENTEXT", icons::SI_OPENTEXT)?;
    m.add("SI_MYANIMELIST", icons::SI_MYANIMELIST)?;
    m.add("SI_WIZZAIR", icons::SI_WIZZAIR)?;
    m.add("SI_HITACHI", icons::SI_HITACHI)?;
    m.add("SI_AIRPLAYVIDEO", icons::SI_AIRPLAYVIDEO)?;
    m.add("SI_WIKIDOTJS", icons::SI_WIKIDOTJS)?;
    m.add("SI_EFFECT", icons::SI_EFFECT)?;
    m.add("SI_ANYTYPE", icons::SI_ANYTYPE)?;
    m.add("SI_MUI", icons::SI_MUI)?;
    m.add("SI_MAAS", icons::SI_MAAS)?;
    m.add("SI_XSPLIT", icons::SI_XSPLIT)?;
    m.add("SI_AUTOCAD", icons::SI_AUTOCAD)?;
    m.add("SI_ZOMATO", icons::SI_ZOMATO)?;
    m.add("SI_TREZOR", icons::SI_TREZOR)?;
    m.add("SI_COCACOLA", icons::SI_COCACOLA)?;
    m.add("SI_OSMAND", icons::SI_OSMAND)?;
    m.add("SI_PUMA", icons::SI_PUMA)?;
    m.add("SI_PYSCAFFOLD", icons::SI_PYSCAFFOLD)?;
    m.add("SI_HABR", icons::SI_HABR)?;
    m.add("SI_CRYENGINE", icons::SI_CRYENGINE)?;
    m.add("SI_NIKE", icons::SI_NIKE)?;
    m.add("SI_MOJEEK", icons::SI_MOJEEK)?;
    m.add("SI_EBAY", icons::SI_EBAY)?;
    m.add(
        "SI_GOOGLECAMPAIGNMANAGER360",
        icons::SI_GOOGLECAMPAIGNMANAGER360,
    )?;
    m.add("SI_TOGGL", icons::SI_TOGGL)?;
    m.add("SI_ETSY", icons::SI_ETSY)?;
    m.add("SI_EMIRATES", icons::SI_EMIRATES)?;
    m.add("SI_PNPM", icons::SI_PNPM)?;
    m.add("SI_DATOCMS", icons::SI_DATOCMS)?;
    m.add("SI_HTTPIE", icons::SI_HTTPIE)?;
    m.add("SI_FORTNITE", icons::SI_FORTNITE)?;
    m.add("SI_LINKFIRE", icons::SI_LINKFIRE)?;
    m.add("SI_GRADLEPLAYPUBLISHER", icons::SI_GRADLEPLAYPUBLISHER)?;
    m.add("SI_OPENWRT", icons::SI_OPENWRT)?;
    m.add("SI_WEASYL", icons::SI_WEASYL)?;
    m.add("SI_EXPENSIFY", icons::SI_EXPENSIFY)?;
    m.add("SI_BATA", icons::SI_BATA)?;
    m.add("SI_SILVERAIRWAYS", icons::SI_SILVERAIRWAYS)?;
    m.add("SI_IATA", icons::SI_IATA)?;
    m.add("SI_SOURCEHUT", icons::SI_SOURCEHUT)?;
    m.add("SI_DISCOURSE", icons::SI_DISCOURSE)?;
    m.add("SI_FERRETDB", icons::SI_FERRETDB)?;
    m.add("SI_MONERO", icons::SI_MONERO)?;
    m.add("SI_30SECONDSOFCODE", icons::SI_30SECONDSOFCODE)?;
    m.add("SI_ICELAND", icons::SI_ICELAND)?;
    m.add("SI_UNSTOP", icons::SI_UNSTOP)?;
    m.add("SI_NUSHELL", icons::SI_NUSHELL)?;
    m.add("SI_TOYOTA", icons::SI_TOYOTA)?;
    m.add("SI_SPDX", icons::SI_SPDX)?;
    m.add("SI_AMD", icons::SI_AMD)?;
    m.add("SI_COMPTIA", icons::SI_COMPTIA)?;
    m.add("SI_EXPRESSDOTCOM", icons::SI_EXPRESSDOTCOM)?;
    m.add("SI_PINESCRIPT", icons::SI_PINESCRIPT)?;
    m.add("SI_OTTO", icons::SI_OTTO)?;
    m.add("SI_TIDAL", icons::SI_TIDAL)?;
    m.add("SI_DOCSIFY", icons::SI_DOCSIFY)?;
    m.add("SI_FLAT", icons::SI_FLAT)?;
    m.add("SI_DEEPGRAM", icons::SI_DEEPGRAM)?;
    m.add("SI_ALDINORD", icons::SI_ALDINORD)?;
    m.add("SI_BENTOML", icons::SI_BENTOML)?;
    m.add("SI_MEILISEARCH", icons::SI_MEILISEARCH)?;
    m.add("SI_SPHINX", icons::SI_SPHINX)?;
    m.add("SI_VIRUSTOTAL", icons::SI_VIRUSTOTAL)?;
    m.add("SI_JETPACKCOMPOSE", icons::SI_JETPACKCOMPOSE)?;
    Ok(())
}
