// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_35(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "invoice-text-outline" => Some(icons::INVOICE_TEXT_OUTLINE),
        "briefcase-arrow-up-down-outline" => Some(icons::BRIEFCASE_ARROW_UP_DOWN_OUTLINE),
        "account-cowboy-hat-outline" => Some(icons::ACCOUNT_COWBOY_HAT_OUTLINE),
        "lock-clock" => Some(icons::LOCK_CLOCK),
        "printer-pos-edit-outline" => Some(icons::PRINTER_POS_EDIT_OUTLINE),
        #[allow(deprecated)]
        "google-play" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'google-play' is deprecated.").print(py);
            }
            Some(icons::GOOGLE_PLAY)
        }
        "music-clef-bass" => Some(icons::MUSIC_CLEF_BASS),
        "sort-alphabetical-ascending-variant" => Some(icons::SORT_ALPHABETICAL_ASCENDING_VARIANT),
        "spray-bottle" => Some(icons::SPRAY_BOTTLE),
        "toy-brick-marker-outline" => Some(icons::TOY_BRICK_MARKER_OUTLINE),
        "clock-start" => Some(icons::CLOCK_START),
        #[allow(deprecated)]
        "sass" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'sass' is deprecated.").print(py);
            }
            Some(icons::SASS)
        }
        "home-circle-outline" => Some(icons::HOME_CIRCLE_OUTLINE),
        "power-socket-fr" => Some(icons::POWER_SOCKET_FR),
        "pine-tree" => Some(icons::PINE_TREE),
        "comment-arrow-left" => Some(icons::COMMENT_ARROW_LEFT),
        "message-badge-outline" => Some(icons::MESSAGE_BADGE_OUTLINE),
        "airplane-marker" => Some(icons::AIRPLANE_MARKER),
        "pail-off" => Some(icons::PAIL_OFF),
        "steering" => Some(icons::STEERING),
        "camcorder-off" => Some(icons::CAMCORDER_OFF),
        "access-point-remove" => Some(icons::ACCESS_POINT_REMOVE),
        "pencil-minus" => Some(icons::PENCIL_MINUS),
        "disc" => Some(icons::DISC),
        "rewind-15" => Some(icons::REWIND_15),
        "compass-off" => Some(icons::COMPASS_OFF),
        "file-document-refresh-outline" => Some(icons::FILE_DOCUMENT_REFRESH_OUTLINE),
        "moon-first-quarter" => Some(icons::MOON_FIRST_QUARTER),
        "clipboard-off" => Some(icons::CLIPBOARD_OFF),
        "scooter-electric" => Some(icons::SCOOTER_ELECTRIC),
        "circle-medium" => Some(icons::CIRCLE_MEDIUM),
        "credit-card-refund-outline" => Some(icons::CREDIT_CARD_REFUND_OUTLINE),
        "text-account" => Some(icons::TEXT_ACCOUNT),
        "tray" => Some(icons::TRAY),
        "wifi-arrow-down" => Some(icons::WIFI_ARROW_DOWN),
        "white-balance-incandescent" => Some(icons::WHITE_BALANCE_INCANDESCENT),
        "water-check-outline" => Some(icons::WATER_CHECK_OUTLINE),
        "archive-star" => Some(icons::ARCHIVE_STAR),
        "store-settings-outline" => Some(icons::STORE_SETTINGS_OUTLINE),
        "alpha" => Some(icons::ALPHA),
        "image-sync-outline" => Some(icons::IMAGE_SYNC_OUTLINE),
        "email-arrow-right" => Some(icons::EMAIL_ARROW_RIGHT),
        "numeric-10-circle" => Some(icons::NUMERIC_10_CIRCLE),
        "select-inverse" => Some(icons::SELECT_INVERSE),
        "bell-sleep" => Some(icons::BELL_SLEEP),
        "lightbulb-night-outline" => Some(icons::LIGHTBULB_NIGHT_OUTLINE),
        "candelabra-fire" => Some(icons::CANDELABRA_FIRE),
        "cards-playing-spade-multiple" => Some(icons::CARDS_PLAYING_SPADE_MULTIPLE),
        "car-seat-cooler" => Some(icons::CAR_SEAT_COOLER),
        "network-strength-1-alert" => Some(icons::NETWORK_STRENGTH_1_ALERT),
        "script-text-key-outline" => Some(icons::SCRIPT_TEXT_KEY_OUTLINE),
        "decimal-comma" => Some(icons::DECIMAL_COMMA),
        "star-plus-outline" => Some(icons::STAR_PLUS_OUTLINE),
        "mosque" => Some(icons::MOSQUE),
        "anvil" => Some(icons::ANVIL),
        "check-underline" => Some(icons::CHECK_UNDERLINE),
        "music-rest-eighth" => Some(icons::MUSIC_REST_EIGHTH),
        "fire-alert" => Some(icons::FIRE_ALERT),
        "clipboard-text-play-outline" => Some(icons::CLIPBOARD_TEXT_PLAY_OUTLINE),
        "boom-gate-up-outline" => Some(icons::BOOM_GATE_UP_OUTLINE),
        "robot-angry" => Some(icons::ROBOT_ANGRY),
        "folder-arrow-down-outline" => Some(icons::FOLDER_ARROW_DOWN_OUTLINE),
        "comment-arrow-right-outline" => Some(icons::COMMENT_ARROW_RIGHT_OUTLINE),
        "information-slab-box" => Some(icons::INFORMATION_SLAB_BOX),
        "table-arrow-left" => Some(icons::TABLE_ARROW_LEFT),
        "cpu-64-bit" => Some(icons::CPU_64_BIT),
        "speaker-bluetooth" => Some(icons::SPEAKER_BLUETOOTH),
        "alpha-c-circle" => Some(icons::ALPHA_C_CIRCLE),
        "rocket" => Some(icons::ROCKET),
        "image-move" => Some(icons::IMAGE_MOVE),
        "cast-education" => Some(icons::CAST_EDUCATION),
        "gas-station-outline" => Some(icons::GAS_STATION_OUTLINE),
        "face-man-profile" => Some(icons::FACE_MAN_PROFILE),
        "invoice-text-multiple-outline" => Some(icons::INVOICE_TEXT_MULTIPLE_OUTLINE),
        "alpha-v" => Some(icons::ALPHA_V),
        "format-strikethrough-variant" => Some(icons::FORMAT_STRIKETHROUGH_VARIANT),
        "page-layout-body" => Some(icons::PAGE_LAYOUT_BODY),
        "folder-question-outline" => Some(icons::FOLDER_QUESTION_OUTLINE),
        "cloud-upload" => Some(icons::CLOUD_UPLOAD),
        "bullhorn-variant-outline" => Some(icons::BULLHORN_VARIANT_OUTLINE),
        "subtitles-outline" => Some(icons::SUBTITLES_OUTLINE),
        "alpha-p" => Some(icons::ALPHA_P),
        "pail-off-outline" => Some(icons::PAIL_OFF_OUTLINE),
        "lock-alert-outline" => Some(icons::LOCK_ALERT_OUTLINE),
        "puzzle-heart-outline" => Some(icons::PUZZLE_HEART_OUTLINE),
        "home-city-outline" => Some(icons::HOME_CITY_OUTLINE),
        "lead-pencil" => Some(icons::LEAD_PENCIL),
        "format-indent-decrease" => Some(icons::FORMAT_INDENT_DECREASE),
        "database-sync-outline" => Some(icons::DATABASE_SYNC_OUTLINE),
        "format-color-fill" => Some(icons::FORMAT_COLOR_FILL),
        "file-table-box-outline" => Some(icons::FILE_TABLE_BOX_OUTLINE),
        "lightbulb-on-10" => Some(icons::LIGHTBULB_ON_10),
        "tally-mark-4" => Some(icons::TALLY_MARK_4),
        "camera-lock" => Some(icons::CAMERA_LOCK),
        "cloud-braces" => Some(icons::CLOUD_BRACES),
        "cellphone-sound" => Some(icons::CELLPHONE_SOUND),
        "file-document-arrow-right-outline" => Some(icons::FILE_DOCUMENT_ARROW_RIGHT_OUTLINE),
        "heart-plus-outline" => Some(icons::HEART_PLUS_OUTLINE),
        "microphone-message-off" => Some(icons::MICROPHONE_MESSAGE_OFF),
        "lightbulb-on-20" => Some(icons::LIGHTBULB_ON_20),
        "speaker-off" => Some(icons::SPEAKER_OFF),
        "flag-variant-outline" => Some(icons::FLAG_VARIANT_OUTLINE),
        "send-variant" => Some(icons::SEND_VARIANT),
        "clipboard-remove-outline" => Some(icons::CLIPBOARD_REMOVE_OUTLINE),
        "book-plus-multiple" => Some(icons::BOOK_PLUS_MULTIPLE),
        "fuse-off" => Some(icons::FUSE_OFF),
        "check-outline" => Some(icons::CHECK_OUTLINE),
        "virus-outline" => Some(icons::VIRUS_OUTLINE),
        "alarm-light-off" => Some(icons::ALARM_LIGHT_OFF),
        "link-variant-minus" => Some(icons::LINK_VARIANT_MINUS),
        "vector-polyline-plus" => Some(icons::VECTOR_POLYLINE_PLUS),
        "drag" => Some(icons::DRAG),
        "clipboard-clock-outline" => Some(icons::CLIPBOARD_CLOCK_OUTLINE),
        #[allow(deprecated)]
        "google-chrome" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'google-chrome' is deprecated.").print(py);
            }
            Some(icons::GOOGLE_CHROME)
        }
        "curtains" => Some(icons::CURTAINS),
        "file-multiple" => Some(icons::FILE_MULTIPLE),
        "briefcase-upload" => Some(icons::BRIEFCASE_UPLOAD),
        "shield-key-outline" => Some(icons::SHIELD_KEY_OUTLINE),
        "light-flood-up" => Some(icons::LIGHT_FLOOD_UP),
        "screwdriver" => Some(icons::SCREWDRIVER),
        "window-shutter-cog" => Some(icons::WINDOW_SHUTTER_COG),
        "power-socket-uk" => Some(icons::POWER_SOCKET_UK),
        "transfer-right" => Some(icons::TRANSFER_RIGHT),
        "arrow-left-thick" => Some(icons::ARROW_LEFT_THICK),
        "heart-half-full" => Some(icons::HEART_HALF_FULL),
        "shuffle" => Some(icons::SHUFFLE),
        "division-box" => Some(icons::DIVISION_BOX),
        "ferris-wheel" => Some(icons::FERRIS_WHEEL),
        "eye-remove" => Some(icons::EYE_REMOVE),
        "bluetooth-transfer" => Some(icons::BLUETOOTH_TRANSFER),
        "email-sync-outline" => Some(icons::EMAIL_SYNC_OUTLINE),
        "bullseye-arrow" => Some(icons::BULLSEYE_ARROW),
        "transmission-tower-import" => Some(icons::TRANSMISSION_TOWER_IMPORT),
        "car-child-seat" => Some(icons::CAR_CHILD_SEAT),
        "sunglasses" => Some(icons::SUNGLASSES),
        "clipboard-plus" => Some(icons::CLIPBOARD_PLUS),
        "timelapse" => Some(icons::TIMELAPSE),
        "decagram-outline" => Some(icons::DECAGRAM_OUTLINE),
        "circle-slice-2" => Some(icons::CIRCLE_SLICE_2),
        "mirror" => Some(icons::MIRROR),
        "percent-circle-outline" => Some(icons::PERCENT_CIRCLE_OUTLINE),
        "compass-outline" => Some(icons::COMPASS_OUTLINE),
        "chart-timeline-variant-shimmer" => Some(icons::CHART_TIMELINE_VARIANT_SHIMMER),
        "wrap-disabled" => Some(icons::WRAP_DISABLED),
        "boom-gate-alert" => Some(icons::BOOM_GATE_ALERT),
        "rocket-launch" => Some(icons::ROCKET_LAUNCH),
        "typewriter" => Some(icons::TYPEWRITER),
        "toy-brick-search" => Some(icons::TOY_BRICK_SEARCH),
        "download-off" => Some(icons::DOWNLOAD_OFF),
        "settings-helper" => Some(icons::SETTINGS_HELPER),
        "cloud-check-variant" => Some(icons::CLOUD_CHECK_VARIANT),
        "account-file" => Some(icons::ACCOUNT_FILE),
        "table-column-remove" => Some(icons::TABLE_COLUMN_REMOVE),
        "filter-variant" => Some(icons::FILTER_VARIANT),
        "more" => Some(icons::MORE),
        "doctor" => Some(icons::DOCTOR),
        "numeric-9-box-outline" => Some(icons::NUMERIC_9_BOX_OUTLINE),
        "radiobox-marked" => Some(icons::RADIOBOX_MARKED),
        "bag-suitcase-off-outline" => Some(icons::BAG_SUITCASE_OFF_OUTLINE),
        "eye-circle" => Some(icons::EYE_CIRCLE),
        "relation-many-to-zero-or-many" => Some(icons::RELATION_MANY_TO_ZERO_OR_MANY),
        "car-clutch" => Some(icons::CAR_CLUTCH),
        "credit-card-refund" => Some(icons::CREDIT_CARD_REFUND),
        "arrow-u-down-left" => Some(icons::ARROW_U_DOWN_LEFT),
        "invoice-text-remove" => Some(icons::INVOICE_TEXT_REMOVE),
        "bottle-tonic-plus-outline" => Some(icons::BOTTLE_TONIC_PLUS_OUTLINE),
        "alpha-h-box" => Some(icons::ALPHA_H_BOX),
        "traffic-light" => Some(icons::TRAFFIC_LIGHT),
        "scooter" => Some(icons::SCOOTER),
        "format-list-bulleted-square" => Some(icons::FORMAT_LIST_BULLETED_SQUARE),
        "lightning-bolt-circle" => Some(icons::LIGHTNING_BOLT_CIRCLE),
        "book-arrow-right" => Some(icons::BOOK_ARROW_RIGHT),
        "wind-turbine" => Some(icons::WIND_TURBINE),
        "battery-check" => Some(icons::BATTERY_CHECK),
        "camera-lock-outline" => Some(icons::CAMERA_LOCK_OUTLINE),
        "script-text-play-outline" => Some(icons::SCRIPT_TEXT_PLAY_OUTLINE),
        "database-edit-outline" => Some(icons::DATABASE_EDIT_OUTLINE),
        "file-powerpoint-box" => Some(icons::FILE_POWERPOINT_BOX),
        "microphone-message" => Some(icons::MICROPHONE_MESSAGE),
        "label-multiple-outline" => Some(icons::LABEL_MULTIPLE_OUTLINE),
        "comment-text-multiple-outline" => Some(icons::COMMENT_TEXT_MULTIPLE_OUTLINE),
        "alpha-q-circle-outline" => Some(icons::ALPHA_Q_CIRCLE_OUTLINE),
        "heat-pump" => Some(icons::HEAT_PUMP),
        "sort-numeric-descending-variant" => Some(icons::SORT_NUMERIC_DESCENDING_VARIANT),
        "cheese-off" => Some(icons::CHEESE_OFF),
        "tshirt-crew" => Some(icons::TSHIRT_CREW),
        "battery-charging-40" => Some(icons::BATTERY_CHARGING_40),
        "merge" => Some(icons::MERGE),
        "pause-box-outline" => Some(icons::PAUSE_BOX_OUTLINE),
        "flask-round-bottom-empty-outline" => Some(icons::FLASK_ROUND_BOTTOM_EMPTY_OUTLINE),
        "key-variant" => Some(icons::KEY_VARIANT),
        "arrow-u-left-top" => Some(icons::ARROW_U_LEFT_TOP),
        "gamma" => Some(icons::GAMMA),
        "message-minus-outline" => Some(icons::MESSAGE_MINUS_OUTLINE),
        "radiobox-indeterminate-variant" => Some(icons::RADIOBOX_INDETERMINATE_VARIANT),
        "map-marker-question" => Some(icons::MAP_MARKER_QUESTION),
        "arrow-top-right-thin-circle-outline" => Some(icons::ARROW_TOP_RIGHT_THIN_CIRCLE_OUTLINE),
        "file-document-alert" => Some(icons::FILE_DOCUMENT_ALERT),
        "printer-search" => Some(icons::PRINTER_SEARCH),
        "train-car-flatbed" => Some(icons::TRAIN_CAR_FLATBED),
        _ => None,
    }
}
