// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_32(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "passport-alert" => Some(icons::PASSPORT_ALERT),
        "folder-table" => Some(icons::FOLDER_TABLE),
        "folder-cog-outline" => Some(icons::FOLDER_COG_OUTLINE),
        "relation-zero-or-one-to-one-or-many" => Some(icons::RELATION_ZERO_OR_ONE_TO_ONE_OR_MANY),
        "camera-plus-outline" => Some(icons::CAMERA_PLUS_OUTLINE),
        "credit-card-settings-outline" => Some(icons::CREDIT_CARD_SETTINGS_OUTLINE),
        "hockey-sticks" => Some(icons::HOCKEY_STICKS),
        "dice-3" => Some(icons::DICE_3),
        "tennis-ball-outline" => Some(icons::TENNIS_BALL_OUTLINE),
        "database-arrow-right" => Some(icons::DATABASE_ARROW_RIGHT),
        "chart-multiline" => Some(icons::CHART_MULTILINE),
        "church" => Some(icons::CHURCH),
        "flask-empty-remove-outline" => Some(icons::FLASK_EMPTY_REMOVE_OUTLINE),
        "card-account-details-outline" => Some(icons::CARD_ACCOUNT_DETAILS_OUTLINE),
        "gamepad-variant" => Some(icons::GAMEPAD_VARIANT),
        "alpha-q-box-outline" => Some(icons::ALPHA_Q_BOX_OUTLINE),
        "all-inclusive-box" => Some(icons::ALL_INCLUSIVE_BOX),
        "elephant" => Some(icons::ELEPHANT),
        "clock-in" => Some(icons::CLOCK_IN),
        #[allow(deprecated)]
        "microsoft-xbox-controller-battery-full" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err(
                    "The icon 'microsoft-xbox-controller-battery-full' is deprecated.",
                )
                .print(py);
            }
            Some(icons::MICROSOFT_XBOX_CONTROLLER_BATTERY_FULL)
        }
        "book-arrow-down-outline" => Some(icons::BOOK_ARROW_DOWN_OUTLINE),
        "alpha-k-box-outline" => Some(icons::ALPHA_K_BOX_OUTLINE),
        "credit-card-wireless" => Some(icons::CREDIT_CARD_WIRELESS),
        "shield-refresh-outline" => Some(icons::SHIELD_REFRESH_OUTLINE),
        "note-off-outline" => Some(icons::NOTE_OFF_OUTLINE),
        "sort-alphabetical-descending-variant" => Some(icons::SORT_ALPHABETICAL_DESCENDING_VARIANT),
        "send" => Some(icons::SEND),
        "angle-acute" => Some(icons::ANGLE_ACUTE),
        "file-presentation-box" => Some(icons::FILE_PRESENTATION_BOX),
        "chevron-right-box-outline" => Some(icons::CHEVRON_RIGHT_BOX_OUTLINE),
        "record-rec" => Some(icons::RECORD_REC),
        "head-minus" => Some(icons::HEAD_MINUS),
        #[allow(deprecated)]
        "artstation" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'artstation' is deprecated.").print(py);
            }
            Some(icons::ARTSTATION)
        }
        "text-box-search-outline" => Some(icons::TEXT_BOX_SEARCH_OUTLINE),
        "diabetes" => Some(icons::DIABETES),
        "lock-open-minus-outline" => Some(icons::LOCK_OPEN_MINUS_OUTLINE),
        "alert-circle" => Some(icons::ALERT_CIRCLE),
        "inbox-arrow-down-outline" => Some(icons::INBOX_ARROW_DOWN_OUTLINE),
        "clock-time-nine" => Some(icons::CLOCK_TIME_NINE),
        "bag-carry-on" => Some(icons::BAG_CARRY_ON),
        "gift-off-outline" => Some(icons::GIFT_OFF_OUTLINE),
        "flag-variant-off" => Some(icons::FLAG_VARIANT_OFF),
        "phone-rotate-portrait" => Some(icons::PHONE_ROTATE_PORTRAIT),
        "network-outline" => Some(icons::NETWORK_OUTLINE),
        "chess-queen" => Some(icons::CHESS_QUEEN),
        "car-hatchback" => Some(icons::CAR_HATCHBACK),
        "water-well" => Some(icons::WATER_WELL),
        "database-export-outline" => Some(icons::DATABASE_EXPORT_OUTLINE),
        "beekeeper" => Some(icons::BEEKEEPER),
        "hexagon-multiple-outline" => Some(icons::HEXAGON_MULTIPLE_OUTLINE),
        "card-minus" => Some(icons::CARD_MINUS),
        "bed-double-outline" => Some(icons::BED_DOUBLE_OUTLINE),
        "heart-cog" => Some(icons::HEART_COG),
        "toy-brick-plus-outline" => Some(icons::TOY_BRICK_PLUS_OUTLINE),
        "axis-arrow-info" => Some(icons::AXIS_ARROW_INFO),
        "send-check-outline" => Some(icons::SEND_CHECK_OUTLINE),
        "lock-percent-outline" => Some(icons::LOCK_PERCENT_OUTLINE),
        "drag-variant" => Some(icons::DRAG_VARIANT),
        "stairs-up" => Some(icons::STAIRS_UP),
        "web-check" => Some(icons::WEB_CHECK),
        "beaker-plus" => Some(icons::BEAKER_PLUS),
        "blur-off" => Some(icons::BLUR_OFF),
        "signal-4g" => Some(icons::SIGNAL_4G),
        "blinds-vertical" => Some(icons::BLINDS_VERTICAL),
        "noodles" => Some(icons::NOODLES),
        "hololens" => Some(icons::HOLOLENS),
        "ear-hearing" => Some(icons::EAR_HEARING),
        "car-info" => Some(icons::CAR_INFO),
        "archive-off" => Some(icons::ARCHIVE_OFF),
        "view-gallery-outline" => Some(icons::VIEW_GALLERY_OUTLINE),
        "elevator-passenger-off" => Some(icons::ELEVATOR_PASSENGER_OFF),
        "eiffel-tower" => Some(icons::EIFFEL_TOWER),
        "timeline-check" => Some(icons::TIMELINE_CHECK),
        "wiper-wash-alert" => Some(icons::WIPER_WASH_ALERT),
        "dice-d12-outline" => Some(icons::DICE_D12_OUTLINE),
        "video-box" => Some(icons::VIDEO_BOX),
        "movie-search-outline" => Some(icons::MOVIE_SEARCH_OUTLINE),
        "arrow-u-up-left" => Some(icons::ARROW_U_UP_LEFT),
        "key-minus" => Some(icons::KEY_MINUS),
        "flask-round-bottom-empty" => Some(icons::FLASK_ROUND_BOTTOM_EMPTY),
        "network-strength-off-outline" => Some(icons::NETWORK_STRENGTH_OFF_OUTLINE),
        "camera-document-off" => Some(icons::CAMERA_DOCUMENT_OFF),
        "comment-processing" => Some(icons::COMMENT_PROCESSING),
        "shuffle-variant" => Some(icons::SHUFFLE_VARIANT),
        "arrow-left-bold-outline" => Some(icons::ARROW_LEFT_BOLD_OUTLINE),
        "storefront" => Some(icons::STOREFRONT),
        "food-drumstick-outline" => Some(icons::FOOD_DRUMSTICK_OUTLINE),
        "weather-partly-snowy-rainy" => Some(icons::WEATHER_PARTLY_SNOWY_RAINY),
        "filmstrip" => Some(icons::FILMSTRIP),
        "sort-alphabetical-ascending" => Some(icons::SORT_ALPHABETICAL_ASCENDING),
        "cloud-question" => Some(icons::CLOUD_QUESTION),
        "file-upload" => Some(icons::FILE_UPLOAD),
        "roller-skate" => Some(icons::ROLLER_SKATE),
        "email-newsletter" => Some(icons::EMAIL_NEWSLETTER),
        "cloud-lock-outline" => Some(icons::CLOUD_LOCK_OUTLINE),
        "equal" => Some(icons::EQUAL),
        "asterisk-circle-outline" => Some(icons::ASTERISK_CIRCLE_OUTLINE),
        "truck-outline" => Some(icons::TRUCK_OUTLINE),
        "receipt-text-remove-outline" => Some(icons::RECEIPT_TEXT_REMOVE_OUTLINE),
        "phone-cancel" => Some(icons::PHONE_CANCEL),
        "heart" => Some(icons::HEART),
        "email-arrow-left-outline" => Some(icons::EMAIL_ARROW_LEFT_OUTLINE),
        "movie-check-outline" => Some(icons::MOVIE_CHECK_OUTLINE),
        "table-heart" => Some(icons::TABLE_HEART),
        "train-car-centerbeam-full" => Some(icons::TRAIN_CAR_CENTERBEAM_FULL),
        "egg" => Some(icons::EGG),
        "upload-lock-outline" => Some(icons::UPLOAD_LOCK_OUTLINE),
        "flask-plus" => Some(icons::FLASK_PLUS),
        "wrench-check-outline" => Some(icons::WRENCH_CHECK_OUTLINE),
        "briefcase-outline" => Some(icons::BRIEFCASE_OUTLINE),
        "plus-outline" => Some(icons::PLUS_OUTLINE),
        "glass-tulip" => Some(icons::GLASS_TULIP),
        "layers-triple" => Some(icons::LAYERS_TRIPLE),
        "alert-rhombus-outline" => Some(icons::ALERT_RHOMBUS_OUTLINE),
        "heart-broken" => Some(icons::HEART_BROKEN),
        "pin" => Some(icons::PIN),
        "timer-lock-outline" => Some(icons::TIMER_LOCK_OUTLINE),
        "play-network-outline" => Some(icons::PLAY_NETWORK_OUTLINE),
        "sign-direction" => Some(icons::SIGN_DIRECTION),
        "database-eye-outline" => Some(icons::DATABASE_EYE_OUTLINE),
        "piggy-bank" => Some(icons::PIGGY_BANK),
        "credit-card-scan-outline" => Some(icons::CREDIT_CARD_SCAN_OUTLINE),
        "calendar-lock-outline" => Some(icons::CALENDAR_LOCK_OUTLINE),
        "align-vertical-distribute" => Some(icons::ALIGN_VERTICAL_DISTRIBUTE),
        "numeric-0-box-outline" => Some(icons::NUMERIC_0_BOX_OUTLINE),
        "credit-card-marker" => Some(icons::CREDIT_CARD_MARKER),
        "cupcake" => Some(icons::CUPCAKE),
        "text-box-minus-outline" => Some(icons::TEXT_BOX_MINUS_OUTLINE),
        "format-align-bottom" => Some(icons::FORMAT_ALIGN_BOTTOM),
        "mushroom-off-outline" => Some(icons::MUSHROOM_OFF_OUTLINE),
        "led-variant-outline" => Some(icons::LED_VARIANT_OUTLINE),
        "video-plus" => Some(icons::VIDEO_PLUS),
        "camera-off-outline" => Some(icons::CAMERA_OFF_OUTLINE),
        "help-box-multiple" => Some(icons::HELP_BOX_MULTIPLE),
        "usb-c-port" => Some(icons::USB_C_PORT),
        "folder-upload" => Some(icons::FOLDER_UPLOAD),
        "set-center" => Some(icons::SET_CENTER),
        "forum-minus" => Some(icons::FORUM_MINUS),
        "flash-off" => Some(icons::FLASH_OFF),
        "lipstick" => Some(icons::LIPSTICK),
        "playlist-edit" => Some(icons::PLAYLIST_EDIT),
        "fruit-pear" => Some(icons::FRUIT_PEAR),
        "circle-slice-5" => Some(icons::CIRCLE_SLICE_5),
        "truck-check" => Some(icons::TRUCK_CHECK),
        "briefcase-eye" => Some(icons::BRIEFCASE_EYE),
        "image-refresh-outline" => Some(icons::IMAGE_REFRESH_OUTLINE),
        "movie-plus-outline" => Some(icons::MOVIE_PLUS_OUTLINE),
        "unicycle" => Some(icons::UNICYCLE),
        "battery-charging" => Some(icons::BATTERY_CHARGING),
        "police-badge" => Some(icons::POLICE_BADGE),
        "invoice-send-outline" => Some(icons::INVOICE_SEND_OUTLINE),
        "file-swap-outline" => Some(icons::FILE_SWAP_OUTLINE),
        "message-cog" => Some(icons::MESSAGE_COG),
        "airplane-plus" => Some(icons::AIRPLANE_PLUS),
        "shield-check" => Some(icons::SHIELD_CHECK),
        "paper-cut-vertical" => Some(icons::PAPER_CUT_VERTICAL),
        "image-size-select-small" => Some(icons::IMAGE_SIZE_SELECT_SMALL),
        "circle-multiple" => Some(icons::CIRCLE_MULTIPLE),
        "content-save-off-outline" => Some(icons::CONTENT_SAVE_OFF_OUTLINE),
        "hand-front-left" => Some(icons::HAND_FRONT_LEFT),
        "wifi-alert" => Some(icons::WIFI_ALERT),
        "battery-outline" => Some(icons::BATTERY_OUTLINE),
        "account-arrow-up" => Some(icons::ACCOUNT_ARROW_UP),
        "blinds-vertical-closed" => Some(icons::BLINDS_VERTICAL_CLOSED),
        "folder-open-outline" => Some(icons::FOLDER_OPEN_OUTLINE),
        "camera-burst" => Some(icons::CAMERA_BURST),
        "mouse-left-click-outline" => Some(icons::MOUSE_LEFT_CLICK_OUTLINE),
        "printer-pos-off-outline" => Some(icons::PRINTER_POS_OFF_OUTLINE),
        "arrow-top-left-bottom-right-bold" => Some(icons::ARROW_TOP_LEFT_BOTTOM_RIGHT_BOLD),
        "calendar-collapse-horizontal" => Some(icons::CALENDAR_COLLAPSE_HORIZONTAL),
        "folder-hidden" => Some(icons::FOLDER_HIDDEN),
        "thought-bubble-outline" => Some(icons::THOUGHT_BUBBLE_OUTLINE),
        "square-circle" => Some(icons::SQUARE_CIRCLE),
        "post-lamp" => Some(icons::POST_LAMP),
        "crosshairs-question" => Some(icons::CROSSHAIRS_QUESTION),
        "wifi-minus" => Some(icons::WIFI_MINUS),
        "chart-bell-curve-cumulative" => Some(icons::CHART_BELL_CURVE_CUMULATIVE),
        "phone-bluetooth" => Some(icons::PHONE_BLUETOOTH),
        "briefcase-account" => Some(icons::BRIEFCASE_ACCOUNT),
        "home" => Some(icons::HOME),
        "key-remove" => Some(icons::KEY_REMOVE),
        "select-multiple-marker" => Some(icons::SELECT_MULTIPLE_MARKER),
        "et" => Some(icons::ET),
        "alpha-m-circle-outline" => Some(icons::ALPHA_M_CIRCLE_OUTLINE),
        "book-minus-multiple" => Some(icons::BOOK_MINUS_MULTIPLE),
        "card-account-phone" => Some(icons::CARD_ACCOUNT_PHONE),
        "water-boiler-off" => Some(icons::WATER_BOILER_OFF),
        "delete-circle" => Some(icons::DELETE_CIRCLE),
        "chevron-down-circle-outline" => Some(icons::CHEVRON_DOWN_CIRCLE_OUTLINE),
        "arrow-left" => Some(icons::ARROW_LEFT),
        "application-outline" => Some(icons::APPLICATION_OUTLINE),
        "atom" => Some(icons::ATOM),
        "led-on" => Some(icons::LED_ON),
        "dock-window" => Some(icons::DOCK_WINDOW),
        "sickle" => Some(icons::SICKLE),
        "car-lifted-pickup" => Some(icons::CAR_LIFTED_PICKUP),
        "sun-snowflake-variant" => Some(icons::SUN_SNOWFLAKE_VARIANT),
        "skip-next" => Some(icons::SKIP_NEXT),
        "format-line-weight" => Some(icons::FORMAT_LINE_WEIGHT),
        "swap-vertical-circle" => Some(icons::SWAP_VERTICAL_CIRCLE),
        _ => None,
    }
}
