// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_19(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "select-multiple" => Some(icons::SELECT_MULTIPLE),
        "motion-pause" => Some(icons::MOTION_PAUSE),
        "phone-check-outline" => Some(icons::PHONE_CHECK_OUTLINE),
        "cursor-move" => Some(icons::CURSOR_MOVE),
        "book-education-outline" => Some(icons::BOOK_EDUCATION_OUTLINE),
        "checkbox-blank-badge" => Some(icons::CHECKBOX_BLANK_BADGE),
        "emoticon-tongue" => Some(icons::EMOTICON_TONGUE),
        "transfer" => Some(icons::TRANSFER),
        "cow-off" => Some(icons::COW_OFF),
        "water-off-outline" => Some(icons::WATER_OFF_OUTLINE),
        "ampersand" => Some(icons::AMPERSAND),
        "bag-carry-on-check" => Some(icons::BAG_CARRY_ON_CHECK),
        "notebook-edit-outline" => Some(icons::NOTEBOOK_EDIT_OUTLINE),
        "archive-lock-outline" => Some(icons::ARCHIVE_LOCK_OUTLINE),
        "file-send" => Some(icons::FILE_SEND),
        "tag-multiple" => Some(icons::TAG_MULTIPLE),
        "alpha-i-circle-outline" => Some(icons::ALPHA_I_CIRCLE_OUTLINE),
        "launch" => Some(icons::LAUNCH),
        "source-branch-refresh" => Some(icons::SOURCE_BRANCH_REFRESH),
        "bee-flower" => Some(icons::BEE_FLOWER),
        "lightbulb-on-outline" => Some(icons::LIGHTBULB_ON_OUTLINE),
        "alpha-d-circle-outline" => Some(icons::ALPHA_D_CIRCLE_OUTLINE),
        "timer-star-outline" => Some(icons::TIMER_STAR_OUTLINE),
        "database-search-outline" => Some(icons::DATABASE_SEARCH_OUTLINE),
        "archive-cancel" => Some(icons::ARCHIVE_CANCEL),
        "layers-edit" => Some(icons::LAYERS_EDIT),
        "yin-yang" => Some(icons::YIN_YANG),
        "relation-one-or-many-to-zero-or-many" => Some(icons::RELATION_ONE_OR_MANY_TO_ZERO_OR_MANY),
        "format-header-1" => Some(icons::FORMAT_HEADER_1),
        "qrcode-remove" => Some(icons::QRCODE_REMOVE),
        "cog" => Some(icons::COG),
        "escalator-down" => Some(icons::ESCALATOR_DOWN),
        "home-edit-outline" => Some(icons::HOME_EDIT_OUTLINE),
        #[allow(deprecated)]
        "teamviewer" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'teamviewer' is deprecated.").print(py);
            }
            Some(icons::TEAMVIEWER)
        }
        "clock-time-eight" => Some(icons::CLOCK_TIME_EIGHT),
        "robot-dead" => Some(icons::ROBOT_DEAD),
        "trash-can-outline" => Some(icons::TRASH_CAN_OUTLINE),
        "numeric-9-plus-box-outline" => Some(icons::NUMERIC_9_PLUS_BOX_OUTLINE),
        "progress-alert" => Some(icons::PROGRESS_ALERT),
        "file-account" => Some(icons::FILE_ACCOUNT),
        "file-compare" => Some(icons::FILE_COMPARE),
        "mouse" => Some(icons::MOUSE),
        "white-balance-sunny" => Some(icons::WHITE_BALANCE_SUNNY),
        "alpha-f" => Some(icons::ALPHA_F),
        "alpha-u-circle-outline" => Some(icons::ALPHA_U_CIRCLE_OUTLINE),
        "shield" => Some(icons::SHIELD),
        "octagram-edit" => Some(icons::OCTAGRAM_EDIT),
        "airplane-takeoff" => Some(icons::AIRPLANE_TAKEOFF),
        "folder-arrow-left-outline" => Some(icons::FOLDER_ARROW_LEFT_OUTLINE),
        "dice-d8-outline" => Some(icons::DICE_D8_OUTLINE),
        "tanker-truck" => Some(icons::TANKER_TRUCK),
        "perspective-less" => Some(icons::PERSPECTIVE_LESS),
        "home-group-minus" => Some(icons::HOME_GROUP_MINUS),
        "kettlebell" => Some(icons::KETTLEBELL),
        "bicycle-basket" => Some(icons::BICYCLE_BASKET),
        "flask-empty-remove" => Some(icons::FLASK_EMPTY_REMOVE),
        "car-light-fog" => Some(icons::CAR_LIGHT_FOG),
        "pirate" => Some(icons::PIRATE),
        "emoticon-sad-outline" => Some(icons::EMOTICON_SAD_OUTLINE),
        "alpha-a" => Some(icons::ALPHA_A),
        "arrow-u-down-right-bold" => Some(icons::ARROW_U_DOWN_RIGHT_BOLD),
        "format-indent-increase" => Some(icons::FORMAT_INDENT_INCREASE),
        "wallet-membership" => Some(icons::WALLET_MEMBERSHIP),
        "zodiac-cancer" => Some(icons::ZODIAC_CANCER),
        "window-shutter-alert" => Some(icons::WINDOW_SHUTTER_ALERT),
        "sign-caution" => Some(icons::SIGN_CAUTION),
        "square-medium" => Some(icons::SQUARE_MEDIUM),
        "table-arrow-up" => Some(icons::TABLE_ARROW_UP),
        "application-variable" => Some(icons::APPLICATION_VARIABLE),
        "folder-search-outline" => Some(icons::FOLDER_SEARCH_OUTLINE),
        "flask" => Some(icons::FLASK),
        #[allow(deprecated)]
        "twitch" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'twitch' is deprecated.").print(py);
            }
            Some(icons::TWITCH)
        }
        "help-box-outline" => Some(icons::HELP_BOX_OUTLINE),
        "printer-check" => Some(icons::PRINTER_CHECK),
        "robot-happy" => Some(icons::ROBOT_HAPPY),
        "archive-lock-open-outline" => Some(icons::ARCHIVE_LOCK_OPEN_OUTLINE),
        "link-box" => Some(icons::LINK_BOX),
        #[allow(deprecated)]
        "skype-business" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'skype-business' is deprecated.").print(py);
            }
            Some(icons::SKYPE_BUSINESS)
        }
        "cup-outline" => Some(icons::CUP_OUTLINE),
        "numeric-10-circle-outline" => Some(icons::NUMERIC_10_CIRCLE_OUTLINE),
        "phone-lock" => Some(icons::PHONE_LOCK),
        "alpha-f-circle" => Some(icons::ALPHA_F_CIRCLE),
        "movie-open-off" => Some(icons::MOVIE_OPEN_OFF),
        "notebook-multiple" => Some(icons::NOTEBOOK_MULTIPLE),
        "pinwheel-outline" => Some(icons::PINWHEEL_OUTLINE),
        "help-network-outline" => Some(icons::HELP_NETWORK_OUTLINE),
        "heart-box" => Some(icons::HEART_BOX),
        "archive-marker-outline" => Some(icons::ARCHIVE_MARKER_OUTLINE),
        "camera-wireless-outline" => Some(icons::CAMERA_WIRELESS_OUTLINE),
        "bookmark-box-outline" => Some(icons::BOOKMARK_BOX_OUTLINE),
        "comma" => Some(icons::COMMA),
        "subdirectory-arrow-right" => Some(icons::SUBDIRECTORY_ARROW_RIGHT),
        "window-shutter-open" => Some(icons::WINDOW_SHUTTER_OPEN),
        "beaker-remove-outline" => Some(icons::BEAKER_REMOVE_OUTLINE),
        "arrow-down-bold-hexagon-outline" => Some(icons::ARROW_DOWN_BOLD_HEXAGON_OUTLINE),
        "car-brake-worn-linings" => Some(icons::CAR_BRAKE_WORN_LININGS),
        "fire-circle" => Some(icons::FIRE_CIRCLE),
        "bug-pause" => Some(icons::BUG_PAUSE),
        "tag-arrow-left" => Some(icons::TAG_ARROW_LEFT),
        "unfold-more-horizontal" => Some(icons::UNFOLD_MORE_HORIZONTAL),
        "image-remove" => Some(icons::IMAGE_REMOVE),
        "rodent" => Some(icons::RODENT),
        "social-distance-6-feet" => Some(icons::SOCIAL_DISTANCE_6_FEET),
        "phone-return-outline" => Some(icons::PHONE_RETURN_OUTLINE),
        "snowmobile" => Some(icons::SNOWMOBILE),
        "star-four-points-circle" => Some(icons::STAR_FOUR_POINTS_CIRCLE),
        "chevron-triple-left" => Some(icons::CHEVRON_TRIPLE_LEFT),
        "video-input-antenna" => Some(icons::VIDEO_INPUT_ANTENNA),
        "arrow-oscillating" => Some(icons::ARROW_OSCILLATING),
        "send-circle-outline" => Some(icons::SEND_CIRCLE_OUTLINE),
        "home-alert" => Some(icons::HOME_ALERT),
        "airplane-landing" => Some(icons::AIRPLANE_LANDING),
        "select-marker" => Some(icons::SELECT_MARKER),
        "database-eye-off-outline" => Some(icons::DATABASE_EYE_OFF_OUTLINE),
        "emoticon-tongue-outline" => Some(icons::EMOTICON_TONGUE_OUTLINE),
        "wifi-arrow-left-right" => Some(icons::WIFI_ARROW_LEFT_RIGHT),
        "storage-tank-outline" => Some(icons::STORAGE_TANK_OUTLINE),
        "fax" => Some(icons::FAX),
        "magnify-plus-cursor" => Some(icons::MAGNIFY_PLUS_CURSOR),
        "movie-star" => Some(icons::MOVIE_STAR),
        "cube-unfolded" => Some(icons::CUBE_UNFOLDED),
        "folder-alert" => Some(icons::FOLDER_ALERT),
        "volume-plus" => Some(icons::VOLUME_PLUS),
        "arrow-expand-right" => Some(icons::ARROW_EXPAND_RIGHT),
        "key-arrow-right" => Some(icons::KEY_ARROW_RIGHT),
        "ip-network" => Some(icons::IP_NETWORK),
        "drawing" => Some(icons::DRAWING),
        "biathlon" => Some(icons::BIATHLON),
        "shield-link-variant" => Some(icons::SHIELD_LINK_VARIANT),
        "forum-plus" => Some(icons::FORUM_PLUS),
        "arrow-collapse-horizontal" => Some(icons::ARROW_COLLAPSE_HORIZONTAL),
        "home-map-marker" => Some(icons::HOME_MAP_MARKER),
        "table-large" => Some(icons::TABLE_LARGE),
        "carabiner" => Some(icons::CARABINER),
        "content-save-outline" => Some(icons::CONTENT_SAVE_OUTLINE),
        "format-pilcrow-arrow-left" => Some(icons::FORMAT_PILCROW_ARROW_LEFT),
        "snowshoeing" => Some(icons::SNOWSHOEING),
        "sale" => Some(icons::SALE),
        "head-remove-outline" => Some(icons::HEAD_REMOVE_OUTLINE),
        "form-textbox" => Some(icons::FORM_TEXTBOX),
        "hand-extended" => Some(icons::HAND_EXTENDED),
        "text-box-outline" => Some(icons::TEXT_BOX_OUTLINE),
        "movie-play" => Some(icons::MOVIE_PLAY),
        "diving-scuba-mask" => Some(icons::DIVING_SCUBA_MASK),
        "border-all-variant" => Some(icons::BORDER_ALL_VARIANT),
        "account-arrow-right-outline" => Some(icons::ACCOUNT_ARROW_RIGHT_OUTLINE),
        "crop-portrait" => Some(icons::CROP_PORTRAIT),
        "piggy-bank-outline" => Some(icons::PIGGY_BANK_OUTLINE),
        "text-box-edit" => Some(icons::TEXT_BOX_EDIT),
        "tab-plus" => Some(icons::TAB_PLUS),
        "cloud-check-outline" => Some(icons::CLOUD_CHECK_OUTLINE),
        "receipt-text" => Some(icons::RECEIPT_TEXT),
        "size-xs" => Some(icons::SIZE_XS),
        "hours-24" => Some(icons::HOURS_24),
        "flash-triangle" => Some(icons::FLASH_TRIANGLE),
        "message-question" => Some(icons::MESSAGE_QUESTION),
        "truck-remove" => Some(icons::TRUCK_REMOVE),
        "polo" => Some(icons::POLO),
        "squeegee" => Some(icons::SQUEEGEE),
        "bus-stop-uncovered" => Some(icons::BUS_STOP_UNCOVERED),
        "cursor-default-click" => Some(icons::CURSOR_DEFAULT_CLICK),
        "fuse-alert" => Some(icons::FUSE_ALERT),
        "panorama-wide-angle-outline" => Some(icons::PANORAMA_WIDE_ANGLE_OUTLINE),
        "gender-male" => Some(icons::GENDER_MALE),
        "emoticon-minus" => Some(icons::EMOTICON_MINUS),
        "locker" => Some(icons::LOCKER),
        "file-cog" => Some(icons::FILE_COG),
        "earth-box-minus" => Some(icons::EARTH_BOX_MINUS),
        "car-defrost-front" => Some(icons::CAR_DEFROST_FRONT),
        "tumble-dryer-off" => Some(icons::TUMBLE_DRYER_OFF),
        "view-quilt-outline" => Some(icons::VIEW_QUILT_OUTLINE),
        "chevron-right-circle-outline" => Some(icons::CHEVRON_RIGHT_CIRCLE_OUTLINE),
        "folder-arrow-up-down" => Some(icons::FOLDER_ARROW_UP_DOWN),
        "ear-hearing-off" => Some(icons::EAR_HEARING_OFF),
        "plus-minus" => Some(icons::PLUS_MINUS),
        "folder-star-outline" => Some(icons::FOLDER_STAR_OUTLINE),
        "cash-lock" => Some(icons::CASH_LOCK),
        "key-chain-variant" => Some(icons::KEY_CHAIN_VARIANT),
        "album" => Some(icons::ALBUM),
        "bookmark-off" => Some(icons::BOOKMARK_OFF),
        "book-lock-open-outline" => Some(icons::BOOK_LOCK_OPEN_OUTLINE),
        "rug" => Some(icons::RUG),
        "home-floor-0" => Some(icons::HOME_FLOOR_0),
        "music-rest-half" => Some(icons::MUSIC_REST_HALF),
        "timer-off-outline" => Some(icons::TIMER_OFF_OUTLINE),
        "link-circle-outline" => Some(icons::LINK_CIRCLE_OUTLINE),
        "shield-alert-outline" => Some(icons::SHIELD_ALERT_OUTLINE),
        "mortar-pestle-plus" => Some(icons::MORTAR_PESTLE_PLUS),
        "gate-buffer" => Some(icons::GATE_BUFFER),
        "alpha-f-box" => Some(icons::ALPHA_F_BOX),
        "picture-in-picture-bottom-right" => Some(icons::PICTURE_IN_PICTURE_BOTTOM_RIGHT),
        "shield-half" => Some(icons::SHIELD_HALF),
        "sofa-single-outline" => Some(icons::SOFA_SINGLE_OUTLINE),
        "currency-usd-off" => Some(icons::CURRENCY_USD_OFF),
        "moon-waning-crescent" => Some(icons::MOON_WANING_CRESCENT),
        "weather-partly-rainy" => Some(icons::WEATHER_PARTLY_RAINY),
        "download-off-outline" => Some(icons::DOWNLOAD_OFF_OUTLINE),
        "numeric-5" => Some(icons::NUMERIC_5),
        "shoe-heel" => Some(icons::SHOE_HEEL),
        "read" => Some(icons::READ),
        _ => None,
    }
}
