// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_29(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "phone-alert-outline" => Some(icons::PHONE_ALERT_OUTLINE),
        "check-outline" => Some(icons::CHECK_OUTLINE),
        "flask-minus" => Some(icons::FLASK_MINUS),
        #[allow(deprecated)]
        "google-chrome" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'google-chrome' is deprecated.").print(py);
            }
            Some(icons::GOOGLE_CHROME)
        }
        "emoticon-frown" => Some(icons::EMOTICON_FROWN),
        "egg-easter" => Some(icons::EGG_EASTER),
        "format-letter-case-upper" => Some(icons::FORMAT_LETTER_CASE_UPPER),
        "ceiling-light-multiple" => Some(icons::CEILING_LIGHT_MULTIPLE),
        "roman-numeral-1" => Some(icons::ROMAN_NUMERAL_1),
        "printer-pos-play" => Some(icons::PRINTER_POS_PLAY),
        "animation" => Some(icons::ANIMATION),
        "faucet" => Some(icons::FAUCET),
        "format-quote-close-outline" => Some(icons::FORMAT_QUOTE_CLOSE_OUTLINE),
        "gradient-vertical" => Some(icons::GRADIENT_VERTICAL),
        "format-text-rotation-angle-down" => Some(icons::FORMAT_TEXT_ROTATION_ANGLE_DOWN),
        "hexagon-multiple" => Some(icons::HEXAGON_MULTIPLE),
        "motion-sensor" => Some(icons::MOTION_SENSOR),
        "bicycle-electric" => Some(icons::BICYCLE_ELECTRIC),
        "clipboard-flow-outline" => Some(icons::CLIPBOARD_FLOW_OUTLINE),
        "pause" => Some(icons::PAUSE),
        "view-agenda" => Some(icons::VIEW_AGENDA),
        "calendar-today-outline" => Some(icons::CALENDAR_TODAY_OUTLINE),
        "navigation-outline" => Some(icons::NAVIGATION_OUTLINE),
        "printer-pos-cancel" => Some(icons::PRINTER_POS_CANCEL),
        #[allow(deprecated)]
        "microsoft-outlook" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'microsoft-outlook' is deprecated.")
                    .print(py);
            }
            Some(icons::MICROSOFT_OUTLOOK)
        }
        "card-account-mail-outline" => Some(icons::CARD_ACCOUNT_MAIL_OUTLINE),
        "lightbulb-auto-outline" => Some(icons::LIGHTBULB_AUTO_OUTLINE),
        "account-lock-outline" => Some(icons::ACCOUNT_LOCK_OUTLINE),
        "ticket-confirmation-outline" => Some(icons::TICKET_CONFIRMATION_OUTLINE),
        "cloud-cancel-outline" => Some(icons::CLOUD_CANCEL_OUTLINE),
        "human-handsdown" => Some(icons::HUMAN_HANDSDOWN),
        "alphabet-piqad" => Some(icons::ALPHABET_PIQAD),
        "video-vintage" => Some(icons::VIDEO_VINTAGE),
        "bulletin-board" => Some(icons::BULLETIN_BOARD),
        "timer-music" => Some(icons::TIMER_MUSIC),
        "tsunami" => Some(icons::TSUNAMI),
        "pill" => Some(icons::PILL),
        "storefront-minus" => Some(icons::STOREFRONT_MINUS),
        "alpha-u-box" => Some(icons::ALPHA_U_BOX),
        "gesture-tap-button" => Some(icons::GESTURE_TAP_BUTTON),
        "account-network" => Some(icons::ACCOUNT_NETWORK),
        "card-account-details-star-outline" => Some(icons::CARD_ACCOUNT_DETAILS_STAR_OUTLINE),
        "arrow-u-up-right-bold" => Some(icons::ARROW_U_UP_RIGHT_BOLD),
        "axis-z-rotate-counterclockwise" => Some(icons::AXIS_Z_ROTATE_COUNTERCLOCKWISE),
        "harddisk-plus" => Some(icons::HARDDISK_PLUS),
        "weather-sunny-off" => Some(icons::WEATHER_SUNNY_OFF),
        "waves-arrow-left" => Some(icons::WAVES_ARROW_LEFT),
        "progress-clock" => Some(icons::PROGRESS_CLOCK),
        "hydraulic-oil-level" => Some(icons::HYDRAULIC_OIL_LEVEL),
        "calendar-range" => Some(icons::CALENDAR_RANGE),
        "movie-star" => Some(icons::MOVIE_STAR),
        "tournament" => Some(icons::TOURNAMENT),
        "phone-remove-outline" => Some(icons::PHONE_REMOVE_OUTLINE),
        "podium" => Some(icons::PODIUM),
        "axis-arrow" => Some(icons::AXIS_ARROW),
        "timer-outline" => Some(icons::TIMER_OUTLINE),
        "train-car-box-open" => Some(icons::TRAIN_CAR_BOX_OPEN),
        "code-greater-than-or-equal" => Some(icons::CODE_GREATER_THAN_OR_EQUAL),
        "database-arrow-down-outline" => Some(icons::DATABASE_ARROW_DOWN_OUTLINE),
        "brightness-4" => Some(icons::BRIGHTNESS_4),
        "message-flash-outline" => Some(icons::MESSAGE_FLASH_OUTLINE),
        "file-table-box-multiple" => Some(icons::FILE_TABLE_BOX_MULTIPLE),
        "delete-forever-outline" => Some(icons::DELETE_FOREVER_OUTLINE),
        "power-cycle" => Some(icons::POWER_CYCLE),
        "circle-expand" => Some(icons::CIRCLE_EXPAND),
        "tooltip-outline" => Some(icons::TOOLTIP_OUTLINE),
        "ip-outline" => Some(icons::IP_OUTLINE),
        "note-multiple" => Some(icons::NOTE_MULTIPLE),
        "table-arrow-left" => Some(icons::TABLE_ARROW_LEFT),
        "cloud-clock" => Some(icons::CLOUD_CLOCK),
        "hand-pointing-down" => Some(icons::HAND_POINTING_DOWN),
        "dishwasher-alert" => Some(icons::DISHWASHER_ALERT),
        "view-module" => Some(icons::VIEW_MODULE),
        "stretch-to-page-outline" => Some(icons::STRETCH_TO_PAGE_OUTLINE),
        "text-recognition" => Some(icons::TEXT_RECOGNITION),
        "pail-minus" => Some(icons::PAIL_MINUS),
        "label-multiple-outline" => Some(icons::LABEL_MULTIPLE_OUTLINE),
        "printer" => Some(icons::PRINTER),
        "cookie-off" => Some(icons::COOKIE_OFF),
        "engine" => Some(icons::ENGINE),
        "shield-lock-open" => Some(icons::SHIELD_LOCK_OPEN),
        "source-commit-end-local" => Some(icons::SOURCE_COMMIT_END_LOCAL),
        "chart-areaspline-variant" => Some(icons::CHART_AREASPLINE_VARIANT),
        "pause-circle" => Some(icons::PAUSE_CIRCLE),
        "format-title" => Some(icons::FORMAT_TITLE),
        "zodiac-virgo" => Some(icons::ZODIAC_VIRGO),
        "chart-timeline-variant" => Some(icons::CHART_TIMELINE_VARIANT),
        "grid-off" => Some(icons::GRID_OFF),
        "play-network" => Some(icons::PLAY_NETWORK),
        "gamepad-variant-outline" => Some(icons::GAMEPAD_VARIANT_OUTLINE),
        "numeric-7-circle" => Some(icons::NUMERIC_7_CIRCLE),
        "razor-double-edge" => Some(icons::RAZOR_DOUBLE_EDGE),
        "code-equal" => Some(icons::CODE_EQUAL),
        "hub-outline" => Some(icons::HUB_OUTLINE),
        "cellphone-wireless" => Some(icons::CELLPHONE_WIRELESS),
        "import" => Some(icons::IMPORT),
        "briefcase-arrow-left-right-outline" => Some(icons::BRIEFCASE_ARROW_LEFT_RIGHT_OUTLINE),
        "arrow-right-bold" => Some(icons::ARROW_RIGHT_BOLD),
        "magnet-on" => Some(icons::MAGNET_ON),
        "battery-charging-wireless-40" => Some(icons::BATTERY_CHARGING_WIRELESS_40),
        "water-well-outline" => Some(icons::WATER_WELL_OUTLINE),
        "label-percent" => Some(icons::LABEL_PERCENT),
        "fuse-blade" => Some(icons::FUSE_BLADE),
        "compass-off-outline" => Some(icons::COMPASS_OFF_OUTLINE),
        "trophy-variant" => Some(icons::TROPHY_VARIANT),
        "home-floor-a" => Some(icons::HOME_FLOOR_A),
        "puzzle-edit-outline" => Some(icons::PUZZLE_EDIT_OUTLINE),
        "image-refresh" => Some(icons::IMAGE_REFRESH),
        "network-strength-1-alert" => Some(icons::NETWORK_STRENGTH_1_ALERT),
        "radio-tower" => Some(icons::RADIO_TOWER),
        "close-box" => Some(icons::CLOSE_BOX),
        "book-settings-outline" => Some(icons::BOOK_SETTINGS_OUTLINE),
        "decimal-decrease" => Some(icons::DECIMAL_DECREASE),
        "mosque" => Some(icons::MOSQUE),
        "fire-hydrant-off" => Some(icons::FIRE_HYDRANT_OFF),
        "arrow-left-bold-circle" => Some(icons::ARROW_LEFT_BOLD_CIRCLE),
        "shield-airplane-outline" => Some(icons::SHIELD_AIRPLANE_OUTLINE),
        "pan" => Some(icons::PAN),
        "pen-plus" => Some(icons::PEN_PLUS),
        "delete-circle" => Some(icons::DELETE_CIRCLE),
        "table-row-remove" => Some(icons::TABLE_ROW_REMOVE),
        "pin-off" => Some(icons::PIN_OFF),
        "temple-buddhist-outline" => Some(icons::TEMPLE_BUDDHIST_OUTLINE),
        "cloud-cancel" => Some(icons::CLOUD_CANCEL),
        "comment-check" => Some(icons::COMMENT_CHECK),
        "calendar-end-outline" => Some(icons::CALENDAR_END_OUTLINE),
        "tray-full" => Some(icons::TRAY_FULL),
        "bus-marker" => Some(icons::BUS_MARKER),
        "numeric-6-box-outline" => Some(icons::NUMERIC_6_BOX_OUTLINE),
        "heat-wave" => Some(icons::HEAT_WAVE),
        "tally-mark-4" => Some(icons::TALLY_MARK_4),
        "rss-box" => Some(icons::RSS_BOX),
        "basket-minus" => Some(icons::BASKET_MINUS),
        "movie-open-cog" => Some(icons::MOVIE_OPEN_COG),
        "hand-back-left-outline" => Some(icons::HAND_BACK_LEFT_OUTLINE),
        "arrow-down-bold-box-outline" => Some(icons::ARROW_DOWN_BOLD_BOX_OUTLINE),
        "car-child-seat" => Some(icons::CAR_CHILD_SEAT),
        "chart-box-plus-outline" => Some(icons::CHART_BOX_PLUS_OUTLINE),
        "usb-flash-drive-outline" => Some(icons::USB_FLASH_DRIVE_OUTLINE),
        "smoking-off" => Some(icons::SMOKING_OFF),
        "projector-screen-variant-outline" => Some(icons::PROJECTOR_SCREEN_VARIANT_OUTLINE),
        "heart-half-full" => Some(icons::HEART_HALF_FULL),
        "comment-arrow-right-outline" => Some(icons::COMMENT_ARROW_RIGHT_OUTLINE),
        "emoticon-kiss" => Some(icons::EMOTICON_KISS),
        "battery-charging-80" => Some(icons::BATTERY_CHARGING_80),
        "cards" => Some(icons::CARDS),
        "safe" => Some(icons::SAFE),
        "border-color" => Some(icons::BORDER_COLOR),
        "calendar-week-begin" => Some(icons::CALENDAR_WEEK_BEGIN),
        "cow-off" => Some(icons::COW_OFF),
        "pail-off-outline" => Some(icons::PAIL_OFF_OUTLINE),
        #[allow(deprecated)]
        "goodreads" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'goodreads' is deprecated.").print(py);
            }
            Some(icons::GOODREADS)
        }
        "map-marker-off" => Some(icons::MAP_MARKER_OFF),
        "content-save-move" => Some(icons::CONTENT_SAVE_MOVE),
        "syllabary-katakana" => Some(icons::SYLLABARY_KATAKANA),
        "tab" => Some(icons::TAB),
        "abugida-devanagari" => Some(icons::ABUGIDA_DEVANAGARI),
        "fridge-industrial-alert" => Some(icons::FRIDGE_INDUSTRIAL_ALERT),
        "lightning-bolt-circle" => Some(icons::LIGHTNING_BOLT_CIRCLE),
        "invoice-fast-outline" => Some(icons::INVOICE_FAST_OUTLINE),
        "sync-alert" => Some(icons::SYNC_ALERT),
        "weather-partly-snowy" => Some(icons::WEATHER_PARTLY_SNOWY),
        "bell-outline" => Some(icons::BELL_OUTLINE),
        "cloud-download" => Some(icons::CLOUD_DOWNLOAD),
        "phone-forward-outline" => Some(icons::PHONE_FORWARD_OUTLINE),
        "alpha-t" => Some(icons::ALPHA_T),
        "message-arrow-right-outline" => Some(icons::MESSAGE_ARROW_RIGHT_OUTLINE),
        "watch-export" => Some(icons::WATCH_EXPORT),
        "view-grid-plus-outline" => Some(icons::VIEW_GRID_PLUS_OUTLINE),
        "slash-forward-box" => Some(icons::SLASH_FORWARD_BOX),
        "tooltip-plus" => Some(icons::TOOLTIP_PLUS),
        "chat-remove" => Some(icons::CHAT_REMOVE),
        "identifier" => Some(icons::IDENTIFIER),
        "meter-gas-outline" => Some(icons::METER_GAS_OUTLINE),
        "currency-krw" => Some(icons::CURRENCY_KRW),
        "information-slab-circle-outline" => Some(icons::INFORMATION_SLAB_CIRCLE_OUTLINE),
        "newspaper-variant-outline" => Some(icons::NEWSPAPER_VARIANT_OUTLINE),
        "contacts" => Some(icons::CONTACTS),
        "train-car-flatbed" => Some(icons::TRAIN_CAR_FLATBED),
        "offer" => Some(icons::OFFER),
        "id-card" => Some(icons::ID_CARD),
        "equalizer" => Some(icons::EQUALIZER),
        "chili-mild-outline" => Some(icons::CHILI_MILD_OUTLINE),
        "television-shimmer" => Some(icons::TELEVISION_SHIMMER),
        "basket-check" => Some(icons::BASKET_CHECK),
        "cellphone-arrow-down-variant" => Some(icons::CELLPHONE_ARROW_DOWN_VARIANT),
        "help-box-outline" => Some(icons::HELP_BOX_OUTLINE),
        "clipboard-search-outline" => Some(icons::CLIPBOARD_SEARCH_OUTLINE),
        "wifi-strength-1" => Some(icons::WIFI_STRENGTH_1),
        "plus-box-multiple" => Some(icons::PLUS_BOX_MULTIPLE),
        "home-silo-outline" => Some(icons::HOME_SILO_OUTLINE),
        "package-variant-closed-remove" => Some(icons::PACKAGE_VARIANT_CLOSED_REMOVE),
        #[allow(deprecated)]
        "unicode" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'unicode' is deprecated.").print(py);
            }
            Some(icons::UNICODE)
        }
        "table-alert" => Some(icons::TABLE_ALERT),
        "bank-off-outline" => Some(icons::BANK_OFF_OUTLINE),
        "store-cog-outline" => Some(icons::STORE_COG_OUTLINE),
        "content-save-check-outline" => Some(icons::CONTENT_SAVE_CHECK_OUTLINE),
        "car-brake-parking" => Some(icons::CAR_BRAKE_PARKING),
        "cellphone" => Some(icons::CELLPHONE),
        "gesture-two-double-tap" => Some(icons::GESTURE_TWO_DOUBLE_TAP),
        _ => None,
    }
}
