// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_24(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "pan-up" => Some(icons::PAN_UP),
        "scale-off" => Some(icons::SCALE_OFF),
        "message-text-clock" => Some(icons::MESSAGE_TEXT_CLOCK),
        "scanner-off" => Some(icons::SCANNER_OFF),
        "train-car-gondola-full" => Some(icons::TRAIN_CAR_GONDOLA_FULL),
        "tooltip-edit" => Some(icons::TOOLTIP_EDIT),
        "coach-lamp-variant" => Some(icons::COACH_LAMP_VARIANT),
        "script" => Some(icons::SCRIPT),
        "share-outline" => Some(icons::SHARE_OUTLINE),
        "chart-timeline-variant" => Some(icons::CHART_TIMELINE_VARIANT),
        "transit-skip" => Some(icons::TRANSIT_SKIP),
        "walk" => Some(icons::WALK),
        "map-outline" => Some(icons::MAP_OUTLINE),
        "numeric-8-box-multiple-outline" => Some(icons::NUMERIC_8_BOX_MULTIPLE_OUTLINE),
        "printer-pos-check-outline" => Some(icons::PRINTER_POS_CHECK_OUTLINE),
        "account-filter" => Some(icons::ACCOUNT_FILTER),
        "rename-box-outline" => Some(icons::RENAME_BOX_OUTLINE),
        "domain-switch" => Some(icons::DOMAIN_SWITCH),
        "shape-polygon-plus" => Some(icons::SHAPE_POLYGON_PLUS),
        "numeric-9-circle-outline" => Some(icons::NUMERIC_9_CIRCLE_OUTLINE),
        "beaker-alert-outline" => Some(icons::BEAKER_ALERT_OUTLINE),
        "folder-wrench" => Some(icons::FOLDER_WRENCH),
        "archive-eye" => Some(icons::ARCHIVE_EYE),
        "coffee-off" => Some(icons::COFFEE_OFF),
        "movie-cog" => Some(icons::MOVIE_COG),
        "numeric-5-box-multiple" => Some(icons::NUMERIC_5_BOX_MULTIPLE),
        "ambulance" => Some(icons::AMBULANCE),
        "cloud-cog" => Some(icons::CLOUD_COG),
        "pen-off" => Some(icons::PEN_OFF),
        #[allow(deprecated)]
        "google-downasaur" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'google-downasaur' is deprecated.")
                    .print(py);
            }
            Some(icons::GOOGLE_DOWNASAUR)
        }
        "alpha-r" => Some(icons::ALPHA_R),
        "radio-am" => Some(icons::RADIO_AM),
        "chili-off" => Some(icons::CHILI_OFF),
        "cellphone-wireless" => Some(icons::CELLPHONE_WIRELESS),
        "backup-restore" => Some(icons::BACKUP_RESTORE),
        "weather-hurricane" => Some(icons::WEATHER_HURRICANE),
        "monitor-multiple" => Some(icons::MONITOR_MULTIPLE),
        "archive-music" => Some(icons::ARCHIVE_MUSIC),
        "bullet" => Some(icons::BULLET),
        "music-note-bluetooth" => Some(icons::MUSIC_NOTE_BLUETOOTH),
        "clock-star-four-points-outline" => Some(icons::CLOCK_STAR_FOUR_POINTS_OUTLINE),
        "heart-flash" => Some(icons::HEART_FLASH),
        "butterfly-outline" => Some(icons::BUTTERFLY_OUTLINE),
        "glass-fragile" => Some(icons::GLASS_FRAGILE),
        "music-rest-whole" => Some(icons::MUSIC_REST_WHOLE),
        "folder-pound-outline" => Some(icons::FOLDER_POUND_OUTLINE),
        "invoice-plus-outline" => Some(icons::INVOICE_PLUS_OUTLINE),
        "microphone-question" => Some(icons::MICROPHONE_QUESTION),
        "microphone-settings" => Some(icons::MICROPHONE_SETTINGS),
        "mouse-left-click" => Some(icons::MOUSE_LEFT_CLICK),
        "circle" => Some(icons::CIRCLE),
        "roman-numeral-8" => Some(icons::ROMAN_NUMERAL_8),
        "battery-minus-outline" => Some(icons::BATTERY_MINUS_OUTLINE),
        "distribute-horizontal-right" => Some(icons::DISTRIBUTE_HORIZONTAL_RIGHT),
        "alert-circle-check-outline" => Some(icons::ALERT_CIRCLE_CHECK_OUTLINE),
        "cross-outline" => Some(icons::CROSS_OUTLINE),
        "receipt-text-clock-outline" => Some(icons::RECEIPT_TEXT_CLOCK_OUTLINE),
        "alert-octagram" => Some(icons::ALERT_OCTAGRAM),
        "account-circle-outline" => Some(icons::ACCOUNT_CIRCLE_OUTLINE),
        "video-minus" => Some(icons::VIDEO_MINUS),
        "car-brake-low-pressure" => Some(icons::CAR_BRAKE_LOW_PRESSURE),
        "wifi-remove" => Some(icons::WIFI_REMOVE),
        "file-minus-outline" => Some(icons::FILE_MINUS_OUTLINE),
        "contain-end" => Some(icons::CONTAIN_END),
        "gamepad-round-left" => Some(icons::GAMEPAD_ROUND_LEFT),
        "saxophone" => Some(icons::SAXOPHONE),
        "clipboard-arrow-down" => Some(icons::CLIPBOARD_ARROW_DOWN),
        "sticker-emoji" => Some(icons::STICKER_EMOJI),
        "currency-krw" => Some(icons::CURRENCY_KRW),
        "close-octagon-outline" => Some(icons::CLOSE_OCTAGON_OUTLINE),
        "numeric-1-box" => Some(icons::NUMERIC_1_BOX),
        "tshirt-v-outline" => Some(icons::TSHIRT_V_OUTLINE),
        "table-account" => Some(icons::TABLE_ACCOUNT),
        "consolidate" => Some(icons::CONSOLIDATE),
        "pencil-circle" => Some(icons::PENCIL_CIRCLE),
        "xml" => Some(icons::XML),
        "motion-pause-outline" => Some(icons::MOTION_PAUSE_OUTLINE),
        "sack-outline" => Some(icons::SACK_OUTLINE),
        "format-letter-case-lower" => Some(icons::FORMAT_LETTER_CASE_LOWER),
        "replay" => Some(icons::REPLAY),
        "numeric-0-box-multiple-outline" => Some(icons::NUMERIC_0_BOX_MULTIPLE_OUTLINE),
        "notebook-heart" => Some(icons::NOTEBOOK_HEART),
        "logout-variant" => Some(icons::LOGOUT_VARIANT),
        "table-headers-eye" => Some(icons::TABLE_HEADERS_EYE),
        "audio-input-stereo-minijack" => Some(icons::AUDIO_INPUT_STEREO_MINIJACK),
        "human-queue" => Some(icons::HUMAN_QUEUE),
        "pencil-ruler-outline" => Some(icons::PENCIL_RULER_OUTLINE),
        "alarm-panel-outline" => Some(icons::ALARM_PANEL_OUTLINE),
        "routes" => Some(icons::ROUTES),
        "hand-saw" => Some(icons::HAND_SAW),
        "square-rounded-outline" => Some(icons::SQUARE_ROUNDED_OUTLINE),
        "shape-circle-plus" => Some(icons::SHAPE_CIRCLE_PLUS),
        "share-all-outline" => Some(icons::SHARE_ALL_OUTLINE),
        "calendar-question" => Some(icons::CALENDAR_QUESTION),
        "comment-account-outline" => Some(icons::COMMENT_ACCOUNT_OUTLINE),
        "tag-arrow-down" => Some(icons::TAG_ARROW_DOWN),
        "wifi-refresh" => Some(icons::WIFI_REFRESH),
        "arrow-right-bold-box" => Some(icons::ARROW_RIGHT_BOLD_BOX),
        "table-column-width" => Some(icons::TABLE_COLUMN_WIDTH),
        "image-frame" => Some(icons::IMAGE_FRAME),
        "view-comfy" => Some(icons::VIEW_COMFY),
        "train-car-hopper" => Some(icons::TRAIN_CAR_HOPPER),
        "archive-star-outline" => Some(icons::ARCHIVE_STAR_OUTLINE),
        #[allow(deprecated)]
        "disqus" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'disqus' is deprecated.").print(py);
            }
            Some(icons::DISQUS)
        }
        "battery-10" => Some(icons::BATTERY_10),
        "box-shadow" => Some(icons::BOX_SHADOW),
        "briefcase-remove-outline" => Some(icons::BRIEFCASE_REMOVE_OUTLINE),
        "volume-vibrate" => Some(icons::VOLUME_VIBRATE),
        "syllabary-katakana-halfwidth" => Some(icons::SYLLABARY_KATAKANA_HALFWIDTH),
        "camera-front" => Some(icons::CAMERA_FRONT),
        "notebook-remove-outline" => Some(icons::NOTEBOOK_REMOVE_OUTLINE),
        "phone-message" => Some(icons::PHONE_MESSAGE),
        "wrench-outline" => Some(icons::WRENCH_OUTLINE),
        #[allow(deprecated)]
        "midi" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'midi' is deprecated.").print(py);
            }
            Some(icons::MIDI)
        }
        "database-alert-outline" => Some(icons::DATABASE_ALERT_OUTLINE),
        "star-four-points-circle-outline" => Some(icons::STAR_FOUR_POINTS_CIRCLE_OUTLINE),
        "message-alert-outline" => Some(icons::MESSAGE_ALERT_OUTLINE),
        "home-variant-outline" => Some(icons::HOME_VARIANT_OUTLINE),
        "orbit-variant" => Some(icons::ORBIT_VARIANT),
        "phone-in-talk" => Some(icons::PHONE_IN_TALK),
        "hydraulic-oil-level" => Some(icons::HYDRAULIC_OIL_LEVEL),
        "emoticon-lol-outline" => Some(icons::EMOTICON_LOL_OUTLINE),
        "format-color-marker-cancel" => Some(icons::FORMAT_COLOR_MARKER_CANCEL),
        "incognito-off" => Some(icons::INCOGNITO_OFF),
        "pickaxe" => Some(icons::PICKAXE),
        "math-integral" => Some(icons::MATH_INTEGRAL),
        "arrow-left-bottom" => Some(icons::ARROW_LEFT_BOTTOM),
        "clipboard-list" => Some(icons::CLIPBOARD_LIST),
        "music-note-off-outline" => Some(icons::MUSIC_NOTE_OFF_OUTLINE),
        "pail-minus-outline" => Some(icons::PAIL_MINUS_OUTLINE),
        "network-strength-off" => Some(icons::NETWORK_STRENGTH_OFF),
        "battery-heart-variant" => Some(icons::BATTERY_HEART_VARIANT),
        "movie-open-off-outline" => Some(icons::MOVIE_OPEN_OFF_OUTLINE),
        "folder-arrow-right-outline" => Some(icons::FOLDER_ARROW_RIGHT_OUTLINE),
        "emoticon-kiss" => Some(icons::EMOTICON_KISS),
        "numeric-8-circle-outline" => Some(icons::NUMERIC_8_CIRCLE_OUTLINE),
        "checkbox-marked-circle" => Some(icons::CHECKBOX_MARKED_CIRCLE),
        "transcribe" => Some(icons::TRANSCRIBE),
        "arrow-expand-horizontal" => Some(icons::ARROW_EXPAND_HORIZONTAL),
        "account-tie-voice" => Some(icons::ACCOUNT_TIE_VOICE),
        "stomach" => Some(icons::STOMACH),
        "file-document-remove" => Some(icons::FILE_DOCUMENT_REMOVE),
        "heart-broken-outline" => Some(icons::HEART_BROKEN_OUTLINE),
        "food-drumstick" => Some(icons::FOOD_DRUMSTICK),
        "elevator-passenger-off-outline" => Some(icons::ELEVATOR_PASSENGER_OFF_OUTLINE),
        "watch-import-variant" => Some(icons::WATCH_IMPORT_VARIANT),
        "filter-settings" => Some(icons::FILTER_SETTINGS),
        "currency-eur-off" => Some(icons::CURRENCY_EUR_OFF),
        "head-outline" => Some(icons::HEAD_OUTLINE),
        "home-floor-2" => Some(icons::HOME_FLOOR_2),
        "bell-cancel" => Some(icons::BELL_CANCEL),
        "eye-lock-open" => Some(icons::EYE_LOCK_OPEN),
        "link-box-outline" => Some(icons::LINK_BOX_OUTLINE),
        "bell-badge-outline" => Some(icons::BELL_BADGE_OUTLINE),
        "stretch-to-page" => Some(icons::STRETCH_TO_PAGE),
        "account-cancel-outline" => Some(icons::ACCOUNT_CANCEL_OUTLINE),
        "numeric-3-circle-outline" => Some(icons::NUMERIC_3_CIRCLE_OUTLINE),
        "shuriken" => Some(icons::SHURIKEN),
        "emoticon-confused" => Some(icons::EMOTICON_CONFUSED),
        "zodiac-gemini" => Some(icons::ZODIAC_GEMINI),
        "selection-multiple-marker" => Some(icons::SELECTION_MULTIPLE_MARKER),
        "view-stream" => Some(icons::VIEW_STREAM),
        "account-tie-voice-off" => Some(icons::ACCOUNT_TIE_VOICE_OFF),
        "list-box-outline" => Some(icons::LIST_BOX_OUTLINE),
        "reply-outline" => Some(icons::REPLY_OUTLINE),
        "archive-off-outline" => Some(icons::ARCHIVE_OFF_OUTLINE),
        "zodiac-pisces" => Some(icons::ZODIAC_PISCES),
        "brightness-6" => Some(icons::BRIGHTNESS_6),
        "heart-minus-outline" => Some(icons::HEART_MINUS_OUTLINE),
        "skip-next-outline" => Some(icons::SKIP_NEXT_OUTLINE),
        "help-box-multiple-outline" => Some(icons::HELP_BOX_MULTIPLE_OUTLINE),
        "table-star" => Some(icons::TABLE_STAR),
        "shield-airplane" => Some(icons::SHIELD_AIRPLANE),
        "share-circle" => Some(icons::SHARE_CIRCLE),
        "arrow-decision-auto" => Some(icons::ARROW_DECISION_AUTO),
        "printer-3d-nozzle" => Some(icons::PRINTER_3D_NOZZLE),
        "folder-move-outline" => Some(icons::FOLDER_MOVE_OUTLINE),
        "map-marker-account" => Some(icons::MAP_MARKER_ACCOUNT),
        "alpha-o-circle" => Some(icons::ALPHA_O_CIRCLE),
        "meter-gas" => Some(icons::METER_GAS),
        "open-in-new" => Some(icons::OPEN_IN_NEW),
        "emoticon-sick-outline" => Some(icons::EMOTICON_SICK_OUTLINE),
        "emoticon-excited-outline" => Some(icons::EMOTICON_EXCITED_OUTLINE),
        "wave" => Some(icons::WAVE),
        "skip-forward" => Some(icons::SKIP_FORWARD),
        "coffee-outline" => Some(icons::COFFEE_OUTLINE),
        "printer-pos-check" => Some(icons::PRINTER_POS_CHECK),
        "pencil-box-multiple-outline" => Some(icons::PENCIL_BOX_MULTIPLE_OUTLINE),
        "clock-remove-outline" => Some(icons::CLOCK_REMOVE_OUTLINE),
        "printer-3d-nozzle-heat-outline" => Some(icons::PRINTER_3D_NOZZLE_HEAT_OUTLINE),
        "view-split-vertical" => Some(icons::VIEW_SPLIT_VERTICAL),
        "arrow-top-right-bold-box-outline" => Some(icons::ARROW_TOP_RIGHT_BOLD_BOX_OUTLINE),
        "table-of-contents" => Some(icons::TABLE_OF_CONTENTS),
        "content-save-move-outline" => Some(icons::CONTENT_SAVE_MOVE_OUTLINE),
        "view-parallel" => Some(icons::VIEW_PARALLEL),
        "numeric-7-circle" => Some(icons::NUMERIC_7_CIRCLE),
        "format-text-rotation-angle-up" => Some(icons::FORMAT_TEXT_ROTATION_ANGLE_UP),
        "shield-sword" => Some(icons::SHIELD_SWORD),
        "fridge-variant" => Some(icons::FRIDGE_VARIANT),
        "record-player" => Some(icons::RECORD_PLAYER),
        _ => None,
    }
}
