// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_34(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "view-column" => Some(icons::VIEW_COLUMN),
        "approximately-equal" => Some(icons::APPROXIMATELY_EQUAL),
        "border-bottom" => Some(icons::BORDER_BOTTOM),
        "sticker-minus" => Some(icons::STICKER_MINUS),
        "account-tag" => Some(icons::ACCOUNT_TAG),
        "panorama-variant" => Some(icons::PANORAMA_VARIANT),
        "invoice-text-clock-outline" => Some(icons::INVOICE_TEXT_CLOCK_OUTLINE),
        "order-bool-ascending" => Some(icons::ORDER_BOOL_ASCENDING),
        "car-brake-retarder" => Some(icons::CAR_BRAKE_RETARDER),
        "corn-off" => Some(icons::CORN_OFF),
        "tumble-dryer-alert" => Some(icons::TUMBLE_DRYER_ALERT),
        "invoice-text-multiple" => Some(icons::INVOICE_TEXT_MULTIPLE),
        "store-cog" => Some(icons::STORE_COG),
        "relation-many-to-zero-or-one" => Some(icons::RELATION_MANY_TO_ZERO_OR_ONE),
        "close-network-outline" => Some(icons::CLOSE_NETWORK_OUTLINE),
        "sphere-off" => Some(icons::SPHERE_OFF),
        "note-minus" => Some(icons::NOTE_MINUS),
        "arrow-right-thin" => Some(icons::ARROW_RIGHT_THIN),
        "fountain-pen" => Some(icons::FOUNTAIN_PEN),
        "headset-off" => Some(icons::HEADSET_OFF),
        "dump-truck" => Some(icons::DUMP_TRUCK),
        "music-accidental-double-flat" => Some(icons::MUSIC_ACCIDENTAL_DOUBLE_FLAT),
        "airplane-check" => Some(icons::AIRPLANE_CHECK),
        "pig" => Some(icons::PIG),
        "email-multiple" => Some(icons::EMAIL_MULTIPLE),
        "pencil-box" => Some(icons::PENCIL_BOX),
        "table-question" => Some(icons::TABLE_QUESTION),
        #[allow(deprecated)]
        "pinterest" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'pinterest' is deprecated.").print(py);
            }
            Some(icons::PINTEREST)
        }
        "format-annotation-plus" => Some(icons::FORMAT_ANNOTATION_PLUS),
        "message-check-outline" => Some(icons::MESSAGE_CHECK_OUTLINE),
        "axis-x-rotate-counterclockwise" => Some(icons::AXIS_X_ROTATE_COUNTERCLOCKWISE),
        "rss" => Some(icons::RSS),
        "camera-timer" => Some(icons::CAMERA_TIMER),
        "battery-medium" => Some(icons::BATTERY_MEDIUM),
        "play-pause" => Some(icons::PLAY_PAUSE),
        "numeric-6-box-outline" => Some(icons::NUMERIC_6_BOX_OUTLINE),
        "pencil-box-outline" => Some(icons::PENCIL_BOX_OUTLINE),
        "elevator" => Some(icons::ELEVATOR),
        "plus-minus-variant" => Some(icons::PLUS_MINUS_VARIANT),
        "select-all" => Some(icons::SELECT_ALL),
        "barrel-outline" => Some(icons::BARREL_OUTLINE),
        "briefcase-clock-outline" => Some(icons::BRIEFCASE_CLOCK_OUTLINE),
        "layers-triple-outline" => Some(icons::LAYERS_TRIPLE_OUTLINE),
        "social-distance-2-meters" => Some(icons::SOCIAL_DISTANCE_2_METERS),
        "heart-off" => Some(icons::HEART_OFF),
        #[allow(deprecated)]
        "language-javascript" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'language-javascript' is deprecated.")
                    .print(py);
            }
            Some(icons::LANGUAGE_JAVASCRIPT)
        }
        "head-alert" => Some(icons::HEAD_ALERT),
        "video-3d-variant" => Some(icons::VIDEO_3D_VARIANT),
        "draw" => Some(icons::DRAW),
        "image-edit-outline" => Some(icons::IMAGE_EDIT_OUTLINE),
        "floor-lamp-torchiere-variant" => Some(icons::FLOOR_LAMP_TORCHIERE_VARIANT),
        "tune-vertical-variant" => Some(icons::TUNE_VERTICAL_VARIANT),
        "fast-forward-30" => Some(icons::FAST_FORWARD_30),
        "cards-diamond" => Some(icons::CARDS_DIAMOND),
        "file-percent-outline" => Some(icons::FILE_PERCENT_OUTLINE),
        "shield-moon" => Some(icons::SHIELD_MOON),
        "mailbox-up" => Some(icons::MAILBOX_UP),
        "account-multiple-plus-outline" => Some(icons::ACCOUNT_MULTIPLE_PLUS_OUTLINE),
        "repeat-off" => Some(icons::REPEAT_OFF),
        "book-minus" => Some(icons::BOOK_MINUS),
        "border-all" => Some(icons::BORDER_ALL),
        "file-undo" => Some(icons::FILE_UNDO),
        "egg-off-outline" => Some(icons::EGG_OFF_OUTLINE),
        "dice-d6-outline" => Some(icons::DICE_D6_OUTLINE),
        "folder-lock-outline" => Some(icons::FOLDER_LOCK_OUTLINE),
        "lightbulb-cfl-off" => Some(icons::LIGHTBULB_CFL_OFF),
        "calendar-today-outline" => Some(icons::CALENDAR_TODAY_OUTLINE),
        "flag-variant-plus-outline" => Some(icons::FLAG_VARIANT_PLUS_OUTLINE),
        "air-humidifier" => Some(icons::AIR_HUMIDIFIER),
        "file-restore-outline" => Some(icons::FILE_RESTORE_OUTLINE),
        "arrow-u-right-bottom-bold" => Some(icons::ARROW_U_RIGHT_BOTTOM_BOLD),
        "file-table-box-multiple-outline" => Some(icons::FILE_TABLE_BOX_MULTIPLE_OUTLINE),
        "land-plots" => Some(icons::LAND_PLOTS),
        "file-search" => Some(icons::FILE_SEARCH),
        "feather" => Some(icons::FEATHER),
        "router-wireless" => Some(icons::ROUTER_WIRELESS),
        "beaker-outline" => Some(icons::BEAKER_OUTLINE),
        "account-tie-hat-outline" => Some(icons::ACCOUNT_TIE_HAT_OUTLINE),
        "message-reply" => Some(icons::MESSAGE_REPLY),
        "alphabet-aurebesh" => Some(icons::ALPHABET_AUREBESH),
        "ski-cross-country" => Some(icons::SKI_CROSS_COUNTRY),
        "application-braces-outline" => Some(icons::APPLICATION_BRACES_OUTLINE),
        "library-shelves" => Some(icons::LIBRARY_SHELVES),
        "cloud-refresh-outline" => Some(icons::CLOUD_REFRESH_OUTLINE),
        "valve-open" => Some(icons::VALVE_OPEN),
        "diving-snorkel" => Some(icons::DIVING_SNORKEL),
        "motion-outline" => Some(icons::MOTION_OUTLINE),
        "egg-fried" => Some(icons::EGG_FRIED),
        "folder-sync-outline" => Some(icons::FOLDER_SYNC_OUTLINE),
        "arrow-collapse-vertical" => Some(icons::ARROW_COLLAPSE_VERTICAL),
        "magnify-minus-outline" => Some(icons::MAGNIFY_MINUS_OUTLINE),
        "crane" => Some(icons::CRANE),
        "chili-hot" => Some(icons::CHILI_HOT),
        "phone-refresh" => Some(icons::PHONE_REFRESH),
        "relation-one-or-many-to-zero-or-one" => Some(icons::RELATION_ONE_OR_MANY_TO_ZERO_OR_ONE),
        "navigation-outline" => Some(icons::NAVIGATION_OUTLINE),
        "unfold-more-vertical" => Some(icons::UNFOLD_MORE_VERTICAL),
        "greenhouse" => Some(icons::GREENHOUSE),
        "radius-outline" => Some(icons::RADIUS_OUTLINE),
        "table-lock" => Some(icons::TABLE_LOCK),
        "airplane-clock" => Some(icons::AIRPLANE_CLOCK),
        "gamepad-round-up" => Some(icons::GAMEPAD_ROUND_UP),
        "bread-slice" => Some(icons::BREAD_SLICE),
        "console-network-outline" => Some(icons::CONSOLE_NETWORK_OUTLINE),
        "book-arrow-up-outline" => Some(icons::BOOK_ARROW_UP_OUTLINE),
        "key-outline" => Some(icons::KEY_OUTLINE),
        "bell-ring-outline" => Some(icons::BELL_RING_OUTLINE),
        "forum-outline" => Some(icons::FORUM_OUTLINE),
        "phone-incoming-outgoing-outline" => Some(icons::PHONE_INCOMING_OUTGOING_OUTLINE),
        #[allow(deprecated)]
        "nfc" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'nfc' is deprecated.").print(py);
            }
            Some(icons::NFC)
        }
        "airballoon-outline" => Some(icons::AIRBALLOON_OUTLINE),
        "routes-clock" => Some(icons::ROUTES_CLOCK),
        "mouse-move-up" => Some(icons::MOUSE_MOVE_UP),
        "numeric-1-box-multiple-outline" => Some(icons::NUMERIC_1_BOX_MULTIPLE_OUTLINE),
        "receipt-send" => Some(icons::RECEIPT_SEND),
        "chevron-down-box" => Some(icons::CHEVRON_DOWN_BOX),
        "copyleft" => Some(icons::COPYLEFT),
        #[allow(deprecated)]
        "firebase" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'firebase' is deprecated.").print(py);
            }
            Some(icons::FIREBASE)
        }
        "arrow-down-thin" => Some(icons::ARROW_DOWN_THIN),
        "format-text-rotation-down" => Some(icons::FORMAT_TEXT_ROTATION_DOWN),
        "arrow-top-right-thick" => Some(icons::ARROW_TOP_RIGHT_THICK),
        "waterfall" => Some(icons::WATERFALL),
        "database-clock-outline" => Some(icons::DATABASE_CLOCK_OUTLINE),
        "archive-alert-outline" => Some(icons::ARCHIVE_ALERT_OUTLINE),
        "drag-vertical-variant" => Some(icons::DRAG_VERTICAL_VARIANT),
        "beer" => Some(icons::BEER),
        "star-half-full" => Some(icons::STAR_HALF_FULL),
        "tag-check-outline" => Some(icons::TAG_CHECK_OUTLINE),
        "pound" => Some(icons::POUND),
        "shoe-sneaker" => Some(icons::SHOE_SNEAKER),
        "octagon-outline" => Some(icons::OCTAGON_OUTLINE),
        "cursor-default-click-outline" => Some(icons::CURSOR_DEFAULT_CLICK_OUTLINE),
        "folder-refresh-outline" => Some(icons::FOLDER_REFRESH_OUTLINE),
        "book-open-variant" => Some(icons::BOOK_OPEN_VARIANT),
        "camera-rear-variant" => Some(icons::CAMERA_REAR_VARIANT),
        "lightbulb-multiple-outline" => Some(icons::LIGHTBULB_MULTIPLE_OUTLINE),
        "timer-edit" => Some(icons::TIMER_EDIT),
        "comment-flash" => Some(icons::COMMENT_FLASH),
        "printer-pos-network" => Some(icons::PRINTER_POS_NETWORK),
        "weather-hurricane-outline" => Some(icons::WEATHER_HURRICANE_OUTLINE),
        "format-quote-open-outline" => Some(icons::FORMAT_QUOTE_OPEN_OUTLINE),
        "alphabetical" => Some(icons::ALPHABETICAL),
        "bell-minus-outline" => Some(icons::BELL_MINUS_OUTLINE),
        "water" => Some(icons::WATER),
        "newspaper-variant" => Some(icons::NEWSPAPER_VARIANT),
        "hours-12" => Some(icons::HOURS_12),
        "pump" => Some(icons::PUMP),
        "invoice-arrow-right" => Some(icons::INVOICE_ARROW_RIGHT),
        "dice-d8" => Some(icons::DICE_D8),
        "earth-arrow-down" => Some(icons::EARTH_ARROW_DOWN),
        "delete-alert" => Some(icons::DELETE_ALERT),
        "volcano" => Some(icons::VOLCANO),
        "dots-horizontal" => Some(icons::DOTS_HORIZONTAL),
        "ip-network-outline" => Some(icons::IP_NETWORK_OUTLINE),
        "cigar" => Some(icons::CIGAR),
        "smoke-detector" => Some(icons::SMOKE_DETECTOR),
        "account-eye-outline" => Some(icons::ACCOUNT_EYE_OUTLINE),
        "food-apple-outline" => Some(icons::FOOD_APPLE_OUTLINE),
        "network-off-outline" => Some(icons::NETWORK_OFF_OUTLINE),
        "package-variant-closed-check" => Some(icons::PACKAGE_VARIANT_CLOSED_CHECK),
        "tab-remove" => Some(icons::TAB_REMOVE),
        "infinity" => Some(icons::INFINITY),
        "timer-sand-full" => Some(icons::TIMER_SAND_FULL),
        "folder-remove" => Some(icons::FOLDER_REMOVE),
        "file-document-minus" => Some(icons::FILE_DOCUMENT_MINUS),
        "arrow-up-left-bold" => Some(icons::ARROW_UP_LEFT_BOLD),
        "transfer-left" => Some(icons::TRANSFER_LEFT),
        "play-box-lock" => Some(icons::PLAY_BOX_LOCK),
        "content-copy" => Some(icons::CONTENT_COPY),
        "wifi-lock" => Some(icons::WIFI_LOCK),
        "blinds" => Some(icons::BLINDS),
        "home-analytics" => Some(icons::HOME_ANALYTICS),
        "message-minus" => Some(icons::MESSAGE_MINUS),
        "message-reply-outline" => Some(icons::MESSAGE_REPLY_OUTLINE),
        "loupe" => Some(icons::LOUPE),
        "auto-fix" => Some(icons::AUTO_FIX),
        "folder-arrow-up" => Some(icons::FOLDER_ARROW_UP),
        "cactus" => Some(icons::CACTUS),
        "cart-heart" => Some(icons::CART_HEART),
        "resize-bottom-right" => Some(icons::RESIZE_BOTTOM_RIGHT),
        "cabin-a-frame" => Some(icons::CABIN_A_FRAME),
        "account-multiple-remove-outline" => Some(icons::ACCOUNT_MULTIPLE_REMOVE_OUTLINE),
        "chart-histogram" => Some(icons::CHART_HISTOGRAM),
        "folder-swap-outline" => Some(icons::FOLDER_SWAP_OUTLINE),
        "message-text" => Some(icons::MESSAGE_TEXT),
        "database-off-outline" => Some(icons::DATABASE_OFF_OUTLINE),
        "equalizer" => Some(icons::EQUALIZER),
        "arrow-up-bold-outline" => Some(icons::ARROW_UP_BOLD_OUTLINE),
        "microphone-plus" => Some(icons::MICROPHONE_PLUS),
        "cards-playing-club-outline" => Some(icons::CARDS_PLAYING_CLUB_OUTLINE),
        "star-three-points-outline" => Some(icons::STAR_THREE_POINTS_OUTLINE),
        "square-rounded-badge" => Some(icons::SQUARE_ROUNDED_BADGE),
        "image-filter-drama-outline" => Some(icons::IMAGE_FILTER_DRAMA_OUTLINE),
        "hand-front-left-outline" => Some(icons::HAND_FRONT_LEFT_OUTLINE),
        "email-minus-outline" => Some(icons::EMAIL_MINUS_OUTLINE),
        "invoice-list" => Some(icons::INVOICE_LIST),
        "briefcase-plus-outline" => Some(icons::BRIEFCASE_PLUS_OUTLINE),
        "hands-pray" => Some(icons::HANDS_PRAY),
        "file-image-plus" => Some(icons::FILE_IMAGE_PLUS),
        "scale-bathroom" => Some(icons::SCALE_BATHROOM),
        _ => None,
    }
}
