// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_11(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "cube-outline" => Some(icons::CUBE_OUTLINE),
        "cog-box" => Some(icons::COG_BOX),
        "fire-extinguisher" => Some(icons::FIRE_EXTINGUISHER),
        "human-greeting-proximity" => Some(icons::HUMAN_GREETING_PROXIMITY),
        "clock-time-six" => Some(icons::CLOCK_TIME_SIX),
        "ideogram-cjk" => Some(icons::IDEOGRAM_CJK),
        "pac-man" => Some(icons::PAC_MAN),
        "dresser" => Some(icons::DRESSER),
        "bed-double" => Some(icons::BED_DOUBLE),
        "check-bold" => Some(icons::CHECK_BOLD),
        "weather-cloudy" => Some(icons::WEATHER_CLOUDY),
        "pan-left" => Some(icons::PAN_LEFT),
        "bag-suitcase" => Some(icons::BAG_SUITCASE),
        "ev-plug-chademo" => Some(icons::EV_PLUG_CHADEMO),
        "bell-remove-outline" => Some(icons::BELL_REMOVE_OUTLINE),
        "wind-turbine-check" => Some(icons::WIND_TURBINE_CHECK),
        "orbit" => Some(icons::ORBIT),
        "alpha-n-circle" => Some(icons::ALPHA_N_CIRCLE),
        "movie-open-cog" => Some(icons::MOVIE_OPEN_COG),
        "restore" => Some(icons::RESTORE),
        "credit-card-refresh-outline" => Some(icons::CREDIT_CARD_REFRESH_OUTLINE),
        "credit-card-plus-outline" => Some(icons::CREDIT_CARD_PLUS_OUTLINE),
        "account-details-outline" => Some(icons::ACCOUNT_DETAILS_OUTLINE),
        "arrow-expand-vertical" => Some(icons::ARROW_EXPAND_VERTICAL),
        "restore-alert" => Some(icons::RESTORE_ALERT),
        "briefcase-variant-off" => Some(icons::BRIEFCASE_VARIANT_OFF),
        "format-list-group-plus" => Some(icons::FORMAT_LIST_GROUP_PLUS),
        "book-information-variant" => Some(icons::BOOK_INFORMATION_VARIANT),
        "lock-percent" => Some(icons::LOCK_PERCENT),
        "octagon" => Some(icons::OCTAGON),
        "ferry" => Some(icons::FERRY),
        "cloud-clock-outline" => Some(icons::CLOUD_CLOCK_OUTLINE),
        "printer-3d-nozzle-alert-outline" => Some(icons::PRINTER_3D_NOZZLE_ALERT_OUTLINE),
        "car-seat" => Some(icons::CAR_SEAT),
        #[allow(deprecated)]
        "gog" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'gog' is deprecated.").print(py);
            }
            Some(icons::GOG)
        }
        "vote-outline" => Some(icons::VOTE_OUTLINE),
        "underwear-outline" => Some(icons::UNDERWEAR_OUTLINE),
        "email-outline" => Some(icons::EMAIL_OUTLINE),
        "message-fast" => Some(icons::MESSAGE_FAST),
        "pin-outline" => Some(icons::PIN_OUTLINE),
        "mower-bag" => Some(icons::MOWER_BAG),
        "thermometer-plus" => Some(icons::THERMOMETER_PLUS),
        "projector-screen" => Some(icons::PROJECTOR_SCREEN),
        #[allow(deprecated)]
        "minecraft" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'minecraft' is deprecated.").print(py);
            }
            Some(icons::MINECRAFT)
        }
        "clock-time-two" => Some(icons::CLOCK_TIME_TWO),
        "bluetooth" => Some(icons::BLUETOOTH),
        "cellphone-arrow-down-variant" => Some(icons::CELLPHONE_ARROW_DOWN_VARIANT),
        "minus-circle-off-outline" => Some(icons::MINUS_CIRCLE_OFF_OUTLINE),
        "printer-off-outline" => Some(icons::PRINTER_OFF_OUTLINE),
        "lock-remove" => Some(icons::LOCK_REMOVE),
        "axis-x-y-arrow-lock" => Some(icons::AXIS_X_Y_ARROW_LOCK),
        "format-list-group" => Some(icons::FORMAT_LIST_GROUP),
        "skip-previous-circle" => Some(icons::SKIP_PREVIOUS_CIRCLE),
        "tray-full" => Some(icons::TRAY_FULL),
        "battery-arrow-down-outline" => Some(icons::BATTERY_ARROW_DOWN_OUTLINE),
        "chat-processing-outline" => Some(icons::CHAT_PROCESSING_OUTLINE),
        "arrow-top-left-bold-box-outline" => Some(icons::ARROW_TOP_LEFT_BOLD_BOX_OUTLINE),
        "fire-off" => Some(icons::FIRE_OFF),
        "numeric-7-box-multiple" => Some(icons::NUMERIC_7_BOX_MULTIPLE),
        "record" => Some(icons::RECORD),
        "sticker-check-outline" => Some(icons::STICKER_CHECK_OUTLINE),
        "arrow-u-left-bottom-bold" => Some(icons::ARROW_U_LEFT_BOTTOM_BOLD),
        "rounded-corner" => Some(icons::ROUNDED_CORNER),
        "monitor-share" => Some(icons::MONITOR_SHARE),
        "toy-brick-remove-outline" => Some(icons::TOY_BRICK_REMOVE_OUTLINE),
        "message-question-outline" => Some(icons::MESSAGE_QUESTION_OUTLINE),
        "led-strip" => Some(icons::LED_STRIP),
        "alert-outline" => Some(icons::ALERT_OUTLINE),
        "view-day-outline" => Some(icons::VIEW_DAY_OUTLINE),
        "food" => Some(icons::FOOD),
        "database-eye-off" => Some(icons::DATABASE_EYE_OFF),
        "jellyfish" => Some(icons::JELLYFISH),
        "note-edit-outline" => Some(icons::NOTE_EDIT_OUTLINE),
        "border-right" => Some(icons::BORDER_RIGHT),
        "integrated-circuit-chip" => Some(icons::INTEGRATED_CIRCUIT_CHIP),
        "eyedropper-off" => Some(icons::EYEDROPPER_OFF),
        "shield-star" => Some(icons::SHIELD_STAR),
        "airplane-settings" => Some(icons::AIRPLANE_SETTINGS),
        "spirit-level" => Some(icons::SPIRIT_LEVEL),
        "car-wireless" => Some(icons::CAR_WIRELESS),
        "web-clock" => Some(icons::WEB_CLOCK),
        "leaf-circle-outline" => Some(icons::LEAF_CIRCLE_OUTLINE),
        "camera-control" => Some(icons::CAMERA_CONTROL),
        "bottle-tonic-skull-outline" => Some(icons::BOTTLE_TONIC_SKULL_OUTLINE),
        "storefront-minus" => Some(icons::STOREFRONT_MINUS),
        "cart-arrow-down" => Some(icons::CART_ARROW_DOWN),
        "cast-audio" => Some(icons::CAST_AUDIO),
        "monitor-small" => Some(icons::MONITOR_SMALL),
        "shield-alert" => Some(icons::SHIELD_ALERT),
        "skip-previous" => Some(icons::SKIP_PREVIOUS),
        "book-arrow-up" => Some(icons::BOOK_ARROW_UP),
        "desk-lamp" => Some(icons::DESK_LAMP),
        "pool" => Some(icons::POOL),
        "poll" => Some(icons::POLL),
        "border-left-variant" => Some(icons::BORDER_LEFT_VARIANT),
        "view-split-horizontal" => Some(icons::VIEW_SPLIT_HORIZONTAL),
        "chevron-up-circle" => Some(icons::CHEVRON_UP_CIRCLE),
        "format-list-numbered-rtl" => Some(icons::FORMAT_LIST_NUMBERED_RTL),
        "overscan" => Some(icons::OVERSCAN),
        "chart-areaspline-variant" => Some(icons::CHART_AREASPLINE_VARIANT),
        "battery-plus" => Some(icons::BATTERY_PLUS),
        #[allow(deprecated)]
        "microsoft-bing" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'microsoft-bing' is deprecated.").print(py);
            }
            Some(icons::MICROSOFT_BING)
        }
        "wifi-strength-1-alert" => Some(icons::WIFI_STRENGTH_1_ALERT),
        "invoice-text-edit" => Some(icons::INVOICE_TEXT_EDIT),
        "sitemap" => Some(icons::SITEMAP),
        "volume-equal" => Some(icons::VOLUME_EQUAL),
        "flask-round-bottom" => Some(icons::FLASK_ROUND_BOTTOM),
        "synagogue" => Some(icons::SYNAGOGUE),
        "water-outline" => Some(icons::WATER_OUTLINE),
        "alpha-v-box-outline" => Some(icons::ALPHA_V_BOX_OUTLINE),
        "gamepad-circle-outline" => Some(icons::GAMEPAD_CIRCLE_OUTLINE),
        "contain" => Some(icons::CONTAIN),
        "card-off-outline" => Some(icons::CARD_OFF_OUTLINE),
        "puzzle-plus-outline" => Some(icons::PUZZLE_PLUS_OUTLINE),
        "numeric-2-circle-outline" => Some(icons::NUMERIC_2_CIRCLE_OUTLINE),
        "image-multiple" => Some(icons::IMAGE_MULTIPLE),
        "angle-obtuse" => Some(icons::ANGLE_OBTUSE),
        "archive-check-outline" => Some(icons::ARCHIVE_CHECK_OUTLINE),
        "account-hard-hat" => Some(icons::ACCOUNT_HARD_HAT),
        "printer-pos-stop" => Some(icons::PRINTER_POS_STOP),
        "arrow-down-thick" => Some(icons::ARROW_DOWN_THICK),
        "keyboard-f6" => Some(icons::KEYBOARD_F6),
        "pot-outline" => Some(icons::POT_OUTLINE),
        "store-search-outline" => Some(icons::STORE_SEARCH_OUTLINE),
        "file-image-minus" => Some(icons::FILE_IMAGE_MINUS),
        "folder-settings" => Some(icons::FOLDER_SETTINGS),
        "eye-check-outline" => Some(icons::EYE_CHECK_OUTLINE),
        "pencil-off" => Some(icons::PENCIL_OFF),
        "alert-decagram-outline" => Some(icons::ALERT_DECAGRAM_OUTLINE),
        "thumb-up" => Some(icons::THUMB_UP),
        "eject" => Some(icons::EJECT),
        "home-search" => Some(icons::HOME_SEARCH),
        "church-outline" => Some(icons::CHURCH_OUTLINE),
        "creation-outline" => Some(icons::CREATION_OUTLINE),
        "application-import" => Some(icons::APPLICATION_IMPORT),
        "image-multiple-outline" => Some(icons::IMAGE_MULTIPLE_OUTLINE),
        "alpha-u-box-outline" => Some(icons::ALPHA_U_BOX_OUTLINE),
        "gesture" => Some(icons::GESTURE),
        "folder-plus-outline" => Some(icons::FOLDER_PLUS_OUTLINE),
        "truck-fast-outline" => Some(icons::TRUCK_FAST_OUTLINE),
        "flip-horizontal" => Some(icons::FLIP_HORIZONTAL),
        "lock-minus-outline" => Some(icons::LOCK_MINUS_OUTLINE),
        "thermometer" => Some(icons::THERMOMETER),
        "globe-light-outline" => Some(icons::GLOBE_LIGHT_OUTLINE),
        "home-plus-outline" => Some(icons::HOME_PLUS_OUTLINE),
        "email-search" => Some(icons::EMAIL_SEARCH),
        "office-building-plus-outline" => Some(icons::OFFICE_BUILDING_PLUS_OUTLINE),
        "head-alert-outline" => Some(icons::HEAD_ALERT_OUTLINE),
        "reply-circle" => Some(icons::REPLY_CIRCLE),
        "share-variant-outline" => Some(icons::SHARE_VARIANT_OUTLINE),
        "stairs" => Some(icons::STAIRS),
        "broadcast-off" => Some(icons::BROADCAST_OFF),
        "alpha-z-box-outline" => Some(icons::ALPHA_Z_BOX_OUTLINE),
        "square-rounded-badge-outline" => Some(icons::SQUARE_ROUNDED_BADGE_OUTLINE),
        "code-array" => Some(icons::CODE_ARRAY),
        "playlist-music-outline" => Some(icons::PLAYLIST_MUSIC_OUTLINE),
        "monitor-arrow-down-variant" => Some(icons::MONITOR_ARROW_DOWN_VARIANT),
        "reply-all" => Some(icons::REPLY_ALL),
        "feature-search-outline" => Some(icons::FEATURE_SEARCH_OUTLINE),
        "file-upload-outline" => Some(icons::FILE_UPLOAD_OUTLINE),
        "transmission-tower" => Some(icons::TRANSMISSION_TOWER),
        "dns" => Some(icons::DNS),
        "cash-multiple" => Some(icons::CASH_MULTIPLE),
        "image-search-outline" => Some(icons::IMAGE_SEARCH_OUTLINE),
        "chevron-up-circle-outline" => Some(icons::CHEVRON_UP_CIRCLE_OUTLINE),
        "mouse-right-click-outline" => Some(icons::MOUSE_RIGHT_CLICK_OUTLINE),
        "account-network" => Some(icons::ACCOUNT_NETWORK),
        "move-resize" => Some(icons::MOVE_RESIZE),
        "tally-mark-3" => Some(icons::TALLY_MARK_3),
        "align-horizontal-left" => Some(icons::ALIGN_HORIZONTAL_LEFT),
        "currency-sign" => Some(icons::CURRENCY_SIGN),
        "timer-alert" => Some(icons::TIMER_ALERT),
        "align-vertical-center" => Some(icons::ALIGN_VERTICAL_CENTER),
        "clipboard-file-outline" => Some(icons::CLIPBOARD_FILE_OUTLINE),
        "badminton" => Some(icons::BADMINTON),
        "filter-minus" => Some(icons::FILTER_MINUS),
        "check-network-outline" => Some(icons::CHECK_NETWORK_OUTLINE),
        "email-search-outline" => Some(icons::EMAIL_SEARCH_OUTLINE),
        "battery-heart" => Some(icons::BATTERY_HEART),
        "file-phone-outline" => Some(icons::FILE_PHONE_OUTLINE),
        "arrow-right-circle-outline" => Some(icons::ARROW_RIGHT_CIRCLE_OUTLINE),
        "ninja" => Some(icons::NINJA),
        "countertop-outline" => Some(icons::COUNTERTOP_OUTLINE),
        "screen-rotation-lock" => Some(icons::SCREEN_ROTATION_LOCK),
        "boom-gate-outline" => Some(icons::BOOM_GATE_OUTLINE),
        "water-alert-outline" => Some(icons::WATER_ALERT_OUTLINE),
        "format-quote-close-outline" => Some(icons::FORMAT_QUOTE_CLOSE_OUTLINE),
        "cloud-sync" => Some(icons::CLOUD_SYNC),
        "table-alert" => Some(icons::TABLE_ALERT),
        "fruit-grapes-outline" => Some(icons::FRUIT_GRAPES_OUTLINE),
        "smart-card-reader-outline" => Some(icons::SMART_CARD_READER_OUTLINE),
        "selection-ellipse" => Some(icons::SELECTION_ELLIPSE),
        "view-comfy-outline" => Some(icons::VIEW_COMFY_OUTLINE),
        "face-woman-shimmer-outline" => Some(icons::FACE_WOMAN_SHIMMER_OUTLINE),
        "application-braces" => Some(icons::APPLICATION_BRACES),
        "sawtooth-wave" => Some(icons::SAWTOOTH_WAVE),
        "chart-box-outline" => Some(icons::CHART_BOX_OUTLINE),
        "playlist-check" => Some(icons::PLAYLIST_CHECK),
        "battery-charging-20" => Some(icons::BATTERY_CHARGING_20),
        "gamepad-square" => Some(icons::GAMEPAD_SQUARE),
        _ => None,
    }
}
