// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_16(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "phone-classic" => Some(icons::PHONE_CLASSIC),
        "diaper-outline" => Some(icons::DIAPER_OUTLINE),
        "hot-tub" => Some(icons::HOT_TUB),
        "medical-cotton-swab" => Some(icons::MEDICAL_COTTON_SWAB),
        "clock-time-three" => Some(icons::CLOCK_TIME_THREE),
        "numeric-3-box-multiple-outline" => Some(icons::NUMERIC_3_BOX_MULTIPLE_OUTLINE),
        "archive-remove-outline" => Some(icons::ARCHIVE_REMOVE_OUTLINE),
        "clock-plus" => Some(icons::CLOCK_PLUS),
        "shield-cross" => Some(icons::SHIELD_CROSS),
        "backspace-outline" => Some(icons::BACKSPACE_OUTLINE),
        "cloud-arrow-down-outline" => Some(icons::CLOUD_ARROW_DOWN_OUTLINE),
        "inbox-arrow-up-outline" => Some(icons::INBOX_ARROW_UP_OUTLINE),
        "fit-to-page" => Some(icons::FIT_TO_PAGE),
        "book-marker" => Some(icons::BOOK_MARKER),
        "dots-horizontal" => Some(icons::DOTS_HORIZONTAL),
        "movie-play-outline" => Some(icons::MOVIE_PLAY_OUTLINE),
        "weather-cloudy-clock" => Some(icons::WEATHER_CLOUDY_CLOCK),
        "chart-tree" => Some(icons::CHART_TREE),
        "silverware-clean" => Some(icons::SILVERWARE_CLEAN),
        "phone-off" => Some(icons::PHONE_OFF),
        "vacuum" => Some(icons::VACUUM),
        "phone-missed" => Some(icons::PHONE_MISSED),
        "shoe-heel" => Some(icons::SHOE_HEEL),
        "music-note-half" => Some(icons::MUSIC_NOTE_HALF),
        "folder-clock" => Some(icons::FOLDER_CLOCK),
        "signal-cellular-3" => Some(icons::SIGNAL_CELLULAR_3),
        "code-less-than-or-equal" => Some(icons::CODE_LESS_THAN_OR_EQUAL),
        "account-alert-outline" => Some(icons::ACCOUNT_ALERT_OUTLINE),
        "mirror-rectangle" => Some(icons::MIRROR_RECTANGLE),
        "arrow-top-right-bold-box-outline" => Some(icons::ARROW_TOP_RIGHT_BOLD_BOX_OUTLINE),
        "ray-start-arrow" => Some(icons::RAY_START_ARROW),
        "image-text" => Some(icons::IMAGE_TEXT),
        "vector-union" => Some(icons::VECTOR_UNION),
        "movie-plus" => Some(icons::MOVIE_PLUS),
        "invoice-text-plus-outline" => Some(icons::INVOICE_TEXT_PLUS_OUTLINE),
        "archive-music" => Some(icons::ARCHIVE_MUSIC),
        "dock-right" => Some(icons::DOCK_RIGHT),
        "wifi-strength-off-outline" => Some(icons::WIFI_STRENGTH_OFF_OUTLINE),
        "hand-back-left" => Some(icons::HAND_BACK_LEFT),
        "airplane-minus" => Some(icons::AIRPLANE_MINUS),
        "smog" => Some(icons::SMOG),
        "play" => Some(icons::PLAY),
        "omega" => Some(icons::OMEGA),
        "pan-right" => Some(icons::PAN_RIGHT),
        "numeric-5-box-multiple" => Some(icons::NUMERIC_5_BOX_MULTIPLE),
        "chart-sankey-variant" => Some(icons::CHART_SANKEY_VARIANT),
        "message-bookmark" => Some(icons::MESSAGE_BOOKMARK),
        "numeric-2-box" => Some(icons::NUMERIC_2_BOX),
        "bluetooth-off" => Some(icons::BLUETOOTH_OFF),
        "alpha-t-box-outline" => Some(icons::ALPHA_T_BOX_OUTLINE),
        #[allow(deprecated)]
        "sass" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'sass' is deprecated.").print(py);
            }
            Some(icons::SASS)
        }
        "clock-start" => Some(icons::CLOCK_START),
        "fridge-off" => Some(icons::FRIDGE_OFF),
        "account-details-outline" => Some(icons::ACCOUNT_DETAILS_OUTLINE),
        "hexagon-slice-5" => Some(icons::HEXAGON_SLICE_5),
        "numeric-5-box-outline" => Some(icons::NUMERIC_5_BOX_OUTLINE),
        "shark-off" => Some(icons::SHARK_OFF),
        "border-horizontal" => Some(icons::BORDER_HORIZONTAL),
        "water-minus" => Some(icons::WATER_MINUS),
        "water-boiler-off" => Some(icons::WATER_BOILER_OFF),
        "cards-heart-outline" => Some(icons::CARDS_HEART_OUTLINE),
        "hamburger" => Some(icons::HAMBURGER),
        "book-lock-open" => Some(icons::BOOK_LOCK_OPEN),
        "arrow-u-right-bottom" => Some(icons::ARROW_U_RIGHT_BOTTOM),
        "account-tie-hat-outline" => Some(icons::ACCOUNT_TIE_HAT_OUTLINE),
        "format-vertical-align-bottom" => Some(icons::FORMAT_VERTICAL_ALIGN_BOTTOM),
        "code-parentheses-box" => Some(icons::CODE_PARENTHESES_BOX),
        "ev-plug-chademo" => Some(icons::EV_PLUG_CHADEMO),
        "lead-pencil" => Some(icons::LEAD_PENCIL),
        "sort-variant-off" => Some(icons::SORT_VARIANT_OFF),
        "cursor-text" => Some(icons::CURSOR_TEXT),
        "alpha-n-box" => Some(icons::ALPHA_N_BOX),
        "lock-check" => Some(icons::LOCK_CHECK),
        "pine-tree-variant-outline" => Some(icons::PINE_TREE_VARIANT_OUTLINE),
        "tablet-dashboard" => Some(icons::TABLET_DASHBOARD),
        "store-edit" => Some(icons::STORE_EDIT),
        "arrow-up-drop-circle-outline" => Some(icons::ARROW_UP_DROP_CIRCLE_OUTLINE),
        "boom-gate-alert" => Some(icons::BOOM_GATE_ALERT),
        "pencil-box-outline" => Some(icons::PENCIL_BOX_OUTLINE),
        "file-video" => Some(icons::FILE_VIDEO),
        "battery-high" => Some(icons::BATTERY_HIGH),
        "shield-lock" => Some(icons::SHIELD_LOCK),
        "phone-in-talk" => Some(icons::PHONE_IN_TALK),
        "earbuds-outline" => Some(icons::EARBUDS_OUTLINE),
        "restore" => Some(icons::RESTORE),
        "account-plus-outline" => Some(icons::ACCOUNT_PLUS_OUTLINE),
        "timer-plus" => Some(icons::TIMER_PLUS),
        "seat-flat" => Some(icons::SEAT_FLAT),
        "tumble-dryer-alert" => Some(icons::TUMBLE_DRYER_ALERT),
        "calendar-text" => Some(icons::CALENDAR_TEXT),
        "draw" => Some(icons::DRAW),
        "watering-can-outline" => Some(icons::WATERING_CAN_OUTLINE),
        "cannabis-off" => Some(icons::CANNABIS_OFF),
        "numeric-2-circle-outline" => Some(icons::NUMERIC_2_CIRCLE_OUTLINE),
        "play-box-multiple" => Some(icons::PLAY_BOX_MULTIPLE),
        "pan-bottom-left" => Some(icons::PAN_BOTTOM_LEFT),
        "format-text-rotation-down" => Some(icons::FORMAT_TEXT_ROTATION_DOWN),
        "whistle" => Some(icons::WHISTLE),
        "checkbox-multiple-marked-outline" => Some(icons::CHECKBOX_MULTIPLE_MARKED_OUTLINE),
        "camera" => Some(icons::CAMERA),
        "office-building-marker-outline" => Some(icons::OFFICE_BUILDING_MARKER_OUTLINE),
        "tram-side" => Some(icons::TRAM_SIDE),
        "keyboard-off" => Some(icons::KEYBOARD_OFF),
        "format-letter-case" => Some(icons::FORMAT_LETTER_CASE),
        "rewind-5" => Some(icons::REWIND_5),
        "map-marker-check-outline" => Some(icons::MAP_MARKER_CHECK_OUTLINE),
        "greater-than" => Some(icons::GREATER_THAN),
        "weather-hazy" => Some(icons::WEATHER_HAZY),
        "battery-alert-variant-outline" => Some(icons::BATTERY_ALERT_VARIANT_OUTLINE),
        "printer-off-outline" => Some(icons::PRINTER_OFF_OUTLINE),
        "ceiling-light-multiple-outline" => Some(icons::CEILING_LIGHT_MULTIPLE_OUTLINE),
        "human-wheelchair" => Some(icons::HUMAN_WHEELCHAIR),
        "egg-outline" => Some(icons::EGG_OUTLINE),
        "bike-pedal-mountain" => Some(icons::BIKE_PEDAL_MOUNTAIN),
        "mixed-martial-arts" => Some(icons::MIXED_MARTIAL_ARTS),
        "account-search" => Some(icons::ACCOUNT_SEARCH),
        "cards-playing-club-outline" => Some(icons::CARDS_PLAYING_CLUB_OUTLINE),
        "altimeter" => Some(icons::ALTIMETER),
        "shield-account-outline" => Some(icons::SHIELD_ACCOUNT_OUTLINE),
        "database-off" => Some(icons::DATABASE_OFF),
        "alarm-check" => Some(icons::ALARM_CHECK),
        "car-hatchback" => Some(icons::CAR_HATCHBACK),
        "opacity" => Some(icons::OPACITY),
        "square-off-outline" => Some(icons::SQUARE_OFF_OUTLINE),
        "database-refresh" => Some(icons::DATABASE_REFRESH),
        "badge-account-outline" => Some(icons::BADGE_ACCOUNT_OUTLINE),
        "train-car-box-full" => Some(icons::TRAIN_CAR_BOX_FULL),
        "tooltip-question-outline" => Some(icons::TOOLTIP_QUESTION_OUTLINE),
        "microphone-minus" => Some(icons::MICROPHONE_MINUS),
        "account-edit" => Some(icons::ACCOUNT_EDIT),
        "star-circle-outline" => Some(icons::STAR_CIRCLE_OUTLINE),
        "alarm-light-off-outline" => Some(icons::ALARM_LIGHT_OFF_OUTLINE),
        "check-decagram" => Some(icons::CHECK_DECAGRAM),
        "light-switch" => Some(icons::LIGHT_SWITCH),
        "store-24-hour" => Some(icons::STORE_24_HOUR),
        "arrow-up-bold" => Some(icons::ARROW_UP_BOLD),
        "nail" => Some(icons::NAIL),
        "circle-slice-6" => Some(icons::CIRCLE_SLICE_6),
        "bookmark-multiple" => Some(icons::BOOKMARK_MULTIPLE),
        "hoop-house" => Some(icons::HOOP_HOUSE),
        "copyright" => Some(icons::COPYRIGHT),
        "arrow-right-top-bold" => Some(icons::ARROW_RIGHT_TOP_BOLD),
        "format-header-4" => Some(icons::FORMAT_HEADER_4),
        "storefront-minus-outline" => Some(icons::STOREFRONT_MINUS_OUTLINE),
        "protocol" => Some(icons::PROTOCOL),
        "memory" => Some(icons::MEMORY),
        "chat-sleep-outline" => Some(icons::CHAT_SLEEP_OUTLINE),
        "invoice" => Some(icons::INVOICE),
        "cart-plus" => Some(icons::CART_PLUS),
        "tennis-ball-outline" => Some(icons::TENNIS_BALL_OUTLINE),
        "arrow-u-left-bottom-bold" => Some(icons::ARROW_U_LEFT_BOTTOM_BOLD),
        "light-flood-up" => Some(icons::LIGHT_FLOOD_UP),
        "ghost-outline" => Some(icons::GHOST_OUTLINE),
        "square-rounded-badge" => Some(icons::SQUARE_ROUNDED_BADGE),
        "bomb-off" => Some(icons::BOMB_OFF),
        "file-account-outline" => Some(icons::FILE_ACCOUNT_OUTLINE),
        "airplane-marker" => Some(icons::AIRPLANE_MARKER),
        "music-accidental-natural" => Some(icons::MUSIC_ACCIDENTAL_NATURAL),
        "cloud-download-outline" => Some(icons::CLOUD_DOWNLOAD_OUTLINE),
        "robot-angry-outline" => Some(icons::ROBOT_ANGRY_OUTLINE),
        "cloud-arrow-right-outline" => Some(icons::CLOUD_ARROW_RIGHT_OUTLINE),
        "table-cancel" => Some(icons::TABLE_CANCEL),
        "animation-play" => Some(icons::ANIMATION_PLAY),
        "gesture" => Some(icons::GESTURE),
        "email-open-multiple" => Some(icons::EMAIL_OPEN_MULTIPLE),
        "book-settings" => Some(icons::BOOK_SETTINGS),
        "printer-pos-cog-outline" => Some(icons::PRINTER_POS_COG_OUTLINE),
        "car-brake-worn-linings" => Some(icons::CAR_BRAKE_WORN_LININGS),
        "stairs" => Some(icons::STAIRS),
        "micro-sd" => Some(icons::MICRO_SD),
        "battery-remove" => Some(icons::BATTERY_REMOVE),
        "keyboard-f10" => Some(icons::KEYBOARD_F10),
        "pin-outline" => Some(icons::PIN_OUTLINE),
        "book-remove-multiple-outline" => Some(icons::BOOK_REMOVE_MULTIPLE_OUTLINE),
        "ufo-outline" => Some(icons::UFO_OUTLINE),
        "movie-open" => Some(icons::MOVIE_OPEN),
        "disc-alert" => Some(icons::DISC_ALERT),
        "vector-square-remove" => Some(icons::VECTOR_SQUARE_REMOVE),
        "battery-bluetooth" => Some(icons::BATTERY_BLUETOOTH),
        "paperclip-off" => Some(icons::PAPERCLIP_OFF),
        "battery-70" => Some(icons::BATTERY_70),
        #[allow(deprecated)]
        "linkedin" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'linkedin' is deprecated.").print(py);
            }
            Some(icons::LINKEDIN)
        }
        "bookmark" => Some(icons::BOOKMARK),
        "account-tie-woman" => Some(icons::ACCOUNT_TIE_WOMAN),
        "bullseye-arrow" => Some(icons::BULLSEYE_ARROW),
        "file-png-box" => Some(icons::FILE_PNG_BOX),
        #[allow(deprecated)]
        "facebook" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'facebook' is deprecated.").print(py);
            }
            Some(icons::FACEBOOK)
        }
        "office-building" => Some(icons::OFFICE_BUILDING),
        "moon-waxing-crescent" => Some(icons::MOON_WAXING_CRESCENT),
        "forum-remove" => Some(icons::FORUM_REMOVE),
        "vector-intersection" => Some(icons::VECTOR_INTERSECTION),
        "card-multiple-outline" => Some(icons::CARD_MULTIPLE_OUTLINE),
        "phone-cancel-outline" => Some(icons::PHONE_CANCEL_OUTLINE),
        "waveform" => Some(icons::WAVEFORM),
        #[allow(deprecated)]
        "kickstarter" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'kickstarter' is deprecated.").print(py);
            }
            Some(icons::KICKSTARTER)
        }
        "kettle-pour-over" => Some(icons::KETTLE_POUR_OVER),
        "city" => Some(icons::CITY),
        "relation-many-to-one" => Some(icons::RELATION_MANY_TO_ONE),
        "filter-minus-outline" => Some(icons::FILTER_MINUS_OUTLINE),
        "monitor" => Some(icons::MONITOR),
        _ => None,
    }
}
