// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_0(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "fast-forward-10" => Some(icons::FAST_FORWARD_10),
        "arrow-up-circle-outline" => Some(icons::ARROW_UP_CIRCLE_OUTLINE),
        "timeline-question-outline" => Some(icons::TIMELINE_QUESTION_OUTLINE),
        "cards-playing-diamond-outline" => Some(icons::CARDS_PLAYING_DIAMOND_OUTLINE),
        "email-seal-outline" => Some(icons::EMAIL_SEAL_OUTLINE),
        "server-plus" => Some(icons::SERVER_PLUS),
        "sort-clock-descending" => Some(icons::SORT_CLOCK_DESCENDING),
        "phone-classic" => Some(icons::PHONE_CLASSIC),
        "flask-outline" => Some(icons::FLASK_OUTLINE),
        "briefcase-check" => Some(icons::BRIEFCASE_CHECK),
        "eye-minus-outline" => Some(icons::EYE_MINUS_OUTLINE),
        "format-letter-case-upper" => Some(icons::FORMAT_LETTER_CASE_UPPER),
        "border-style" => Some(icons::BORDER_STYLE),
        "clipboard-list" => Some(icons::CLIPBOARD_LIST),
        "plane-car" => Some(icons::PLANE_CAR),
        "invoice-send-outline" => Some(icons::INVOICE_SEND_OUTLINE),
        "text-box" => Some(icons::TEXT_BOX),
        "garage-open-variant" => Some(icons::GARAGE_OPEN_VARIANT),
        "credit-card-remove-outline" => Some(icons::CREDIT_CARD_REMOVE_OUTLINE),
        "fuse" => Some(icons::FUSE),
        "email-off-outline" => Some(icons::EMAIL_OFF_OUTLINE),
        "format-columns" => Some(icons::FORMAT_COLUMNS),
        "audio-input-rca" => Some(icons::AUDIO_INPUT_RCA),
        "printer-pos-star-outline" => Some(icons::PRINTER_POS_STAR_OUTLINE),
        "rodent" => Some(icons::RODENT),
        "text-search-variant" => Some(icons::TEXT_SEARCH_VARIANT),
        "account-arrow-down" => Some(icons::ACCOUNT_ARROW_DOWN),
        "lock-percent-open" => Some(icons::LOCK_PERCENT_OPEN),
        "comment-text-multiple" => Some(icons::COMMENT_TEXT_MULTIPLE),
        "emoticon-confused-outline" => Some(icons::EMOTICON_CONFUSED_OUTLINE),
        "border-right-variant" => Some(icons::BORDER_RIGHT_VARIANT),
        "hand-back-right-outline" => Some(icons::HAND_BACK_RIGHT_OUTLINE),
        "receipt-send" => Some(icons::RECEIPT_SEND),
        "clipboard-text" => Some(icons::CLIPBOARD_TEXT),
        "file-lock" => Some(icons::FILE_LOCK),
        "arrow-decision" => Some(icons::ARROW_DECISION),
        "account-circle-outline" => Some(icons::ACCOUNT_CIRCLE_OUTLINE),
        #[allow(deprecated)]
        "microsoft-dynamics-365" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'microsoft-dynamics-365' is deprecated.")
                    .print(py);
            }
            Some(icons::MICROSOFT_DYNAMICS_365)
        }
        "home-automation" => Some(icons::HOME_AUTOMATION),
        "account-arrow-left-outline" => Some(icons::ACCOUNT_ARROW_LEFT_OUTLINE),
        "invoice-text-fast-outline" => Some(icons::INVOICE_TEXT_FAST_OUTLINE),
        "human-male-female" => Some(icons::HUMAN_MALE_FEMALE),
        "microphone-outline" => Some(icons::MICROPHONE_OUTLINE),
        "card" => Some(icons::CARD),
        "translate" => Some(icons::TRANSLATE),
        "bike-pedal-clipless" => Some(icons::BIKE_PEDAL_CLIPLESS),
        "note-minus" => Some(icons::NOTE_MINUS),
        "numeric-6-box" => Some(icons::NUMERIC_6_BOX),
        "wifi-strength-2-lock-open" => Some(icons::WIFI_STRENGTH_2_LOCK_OPEN),
        "message-image-outline" => Some(icons::MESSAGE_IMAGE_OUTLINE),
        "border-inside" => Some(icons::BORDER_INSIDE),
        "format-list-group" => Some(icons::FORMAT_LIST_GROUP),
        "screen-rotation" => Some(icons::SCREEN_ROTATION),
        "arrow-down-bold-circle" => Some(icons::ARROW_DOWN_BOLD_CIRCLE),
        "source-branch-remove" => Some(icons::SOURCE_BRANCH_REMOVE),
        "elephant" => Some(icons::ELEPHANT),
        "credit-card-scan-outline" => Some(icons::CREDIT_CARD_SCAN_OUTLINE),
        "emoticon-remove" => Some(icons::EMOTICON_REMOVE),
        #[allow(deprecated)]
        "drupal" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'drupal' is deprecated.").print(py);
            }
            Some(icons::DRUPAL)
        }
        "file-document-edit" => Some(icons::FILE_DOCUMENT_EDIT),
        "wall-sconce-flat-variant" => Some(icons::WALL_SCONCE_FLAT_VARIANT),
        "dock-right" => Some(icons::DOCK_RIGHT),
        "timeline-check" => Some(icons::TIMELINE_CHECK),
        "file-refresh-outline" => Some(icons::FILE_REFRESH_OUTLINE),
        "rename" => Some(icons::RENAME),
        "email-edit" => Some(icons::EMAIL_EDIT),
        "plus-minus-box" => Some(icons::PLUS_MINUS_BOX),
        "camera-enhance" => Some(icons::CAMERA_ENHANCE),
        "crosshairs-off" => Some(icons::CROSSHAIRS_OFF),
        "thumb-down" => Some(icons::THUMB_DOWN),
        "bird" => Some(icons::BIRD),
        "fullscreen" => Some(icons::FULLSCREEN),
        "calendar-import-outline" => Some(icons::CALENDAR_IMPORT_OUTLINE),
        "saw-blade" => Some(icons::SAW_BLADE),
        "safe-square-outline" => Some(icons::SAFE_SQUARE_OUTLINE),
        "engine" => Some(icons::ENGINE),
        "printer-pos-play" => Some(icons::PRINTER_POS_PLAY),
        "wall-fire" => Some(icons::WALL_FIRE),
        "cookie-remove-outline" => Some(icons::COOKIE_REMOVE_OUTLINE),
        "table-network" => Some(icons::TABLE_NETWORK),
        "briefcase-arrow-left-right-outline" => Some(icons::BRIEFCASE_ARROW_LEFT_RIGHT_OUTLINE),
        "seal-variant" => Some(icons::SEAL_VARIANT),
        "notebook-minus" => Some(icons::NOTEBOOK_MINUS),
        "folder-cancel-outline" => Some(icons::FOLDER_CANCEL_OUTLINE),
        "relation-one-to-one-or-many" => Some(icons::RELATION_ONE_TO_ONE_OR_MANY),
        "tree" => Some(icons::TREE),
        "sign-direction-plus" => Some(icons::SIGN_DIRECTION_PLUS),
        "tooth" => Some(icons::TOOTH),
        "notebook-edit-outline" => Some(icons::NOTEBOOK_EDIT_OUTLINE),
        "multimedia" => Some(icons::MULTIMEDIA),
        "weather-tornado" => Some(icons::WEATHER_TORNADO),
        "smoking-off" => Some(icons::SMOKING_OFF),
        "map-marker-path" => Some(icons::MAP_MARKER_PATH),
        "rename-outline" => Some(icons::RENAME_OUTLINE),
        "format-align-top" => Some(icons::FORMAT_ALIGN_TOP),
        "login" => Some(icons::LOGIN),
        "application-variable-outline" => Some(icons::APPLICATION_VARIABLE_OUTLINE),
        "database-marker-outline" => Some(icons::DATABASE_MARKER_OUTLINE),
        "mouse-right-click" => Some(icons::MOUSE_RIGHT_CLICK),
        "infinity" => Some(icons::INFINITY),
        "network" => Some(icons::NETWORK),
        "orbit" => Some(icons::ORBIT),
        "format-line-style" => Some(icons::FORMAT_LINE_STYLE),
        "triangle" => Some(icons::TRIANGLE),
        "timer-sand" => Some(icons::TIMER_SAND),
        "source-repository-multiple" => Some(icons::SOURCE_REPOSITORY_MULTIPLE),
        "eye-arrow-right-outline" => Some(icons::EYE_ARROW_RIGHT_OUTLINE),
        "cookie-alert-outline" => Some(icons::COOKIE_ALERT_OUTLINE),
        "mouse-scroll-wheel" => Some(icons::MOUSE_SCROLL_WHEEL),
        "close-circle" => Some(icons::CLOSE_CIRCLE),
        "beekeeper" => Some(icons::BEEKEEPER),
        "pipe-valve" => Some(icons::PIPE_VALVE),
        "recycle-variant" => Some(icons::RECYCLE_VARIANT),
        "chart-donut" => Some(icons::CHART_DONUT),
        "star-four-points-circle-outline" => Some(icons::STAR_FOUR_POINTS_CIRCLE_OUTLINE),
        "map-marker-off" => Some(icons::MAP_MARKER_OFF),
        "vector-square-minus" => Some(icons::VECTOR_SQUARE_MINUS),
        "attachment-off" => Some(icons::ATTACHMENT_OFF),
        "chart-box-outline" => Some(icons::CHART_BOX_OUTLINE),
        "mirror" => Some(icons::MIRROR),
        "tshirt-crew" => Some(icons::TSHIRT_CREW),
        "robot-dead-outline" => Some(icons::ROBOT_DEAD_OUTLINE),
        "face-man-outline" => Some(icons::FACE_MAN_OUTLINE),
        "chat-outline" => Some(icons::CHAT_OUTLINE),
        "battery-charging-80" => Some(icons::BATTERY_CHARGING_80),
        #[allow(deprecated)]
        "youtube-tv" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'youtube-tv' is deprecated.").print(py);
            }
            Some(icons::YOUTUBE_TV)
        }
        "keyboard-space" => Some(icons::KEYBOARD_SPACE),
        "buffet" => Some(icons::BUFFET),
        "car-brake-parking" => Some(icons::CAR_BRAKE_PARKING),
        "information-variant-circle" => Some(icons::INFORMATION_VARIANT_CIRCLE),
        "hdr-off" => Some(icons::HDR_OFF),
        "rollerblade-off" => Some(icons::ROLLERBLADE_OFF),
        "arrow-right-drop-circle-outline" => Some(icons::ARROW_RIGHT_DROP_CIRCLE_OUTLINE),
        "account-tie-hat" => Some(icons::ACCOUNT_TIE_HAT),
        "clipboard-file-outline" => Some(icons::CLIPBOARD_FILE_OUTLINE),
        "key-remove" => Some(icons::KEY_REMOVE),
        "motion-pause" => Some(icons::MOTION_PAUSE),
        "credit-card-off" => Some(icons::CREDIT_CARD_OFF),
        "brush-off" => Some(icons::BRUSH_OFF),
        #[allow(deprecated)]
        "microsoft-xbox-controller-view" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err(
                    "The icon 'microsoft-xbox-controller-view' is deprecated.",
                )
                .print(py);
            }
            Some(icons::MICROSOFT_XBOX_CONTROLLER_VIEW)
        }
        "sort-calendar-descending" => Some(icons::SORT_CALENDAR_DESCENDING),
        "folder-multiple-plus-outline" => Some(icons::FOLDER_MULTIPLE_PLUS_OUTLINE),
        "notebook-heart-outline" => Some(icons::NOTEBOOK_HEART_OUTLINE),
        "printer-pos-alert-outline" => Some(icons::PRINTER_POS_ALERT_OUTLINE),
        "invert-colors-off" => Some(icons::INVERT_COLORS_OFF),
        "heart-multiple-outline" => Some(icons::HEART_MULTIPLE_OUTLINE),
        "account-arrow-left" => Some(icons::ACCOUNT_ARROW_LEFT),
        "chevron-left-circle-outline" => Some(icons::CHEVRON_LEFT_CIRCLE_OUTLINE),
        "fridge-industrial" => Some(icons::FRIDGE_INDUSTRIAL),
        "phone-return-outline" => Some(icons::PHONE_RETURN_OUTLINE),
        "database-arrow-right-outline" => Some(icons::DATABASE_ARROW_RIGHT_OUTLINE),
        "folder-key-network-outline" => Some(icons::FOLDER_KEY_NETWORK_OUTLINE),
        "office-building-plus-outline" => Some(icons::OFFICE_BUILDING_PLUS_OUTLINE),
        "music-note-plus" => Some(icons::MUSIC_NOTE_PLUS),
        "paw-off-outline" => Some(icons::PAW_OFF_OUTLINE),
        "card-bulleted" => Some(icons::CARD_BULLETED),
        "tag-plus" => Some(icons::TAG_PLUS),
        "format-align-right" => Some(icons::FORMAT_ALIGN_RIGHT),
        "assistant" => Some(icons::ASSISTANT),
        "circle-half" => Some(icons::CIRCLE_HALF),
        "volume-off" => Some(icons::VOLUME_OFF),
        "transit-connection" => Some(icons::TRANSIT_CONNECTION),
        "cloud-arrow-left-outline" => Some(icons::CLOUD_ARROW_LEFT_OUTLINE),
        "layers-off" => Some(icons::LAYERS_OFF),
        "television-box" => Some(icons::TELEVISION_BOX),
        "network-strength-3-alert" => Some(icons::NETWORK_STRENGTH_3_ALERT),
        "brightness-7" => Some(icons::BRIGHTNESS_7),
        "printer-off" => Some(icons::PRINTER_OFF),
        "comment-quote" => Some(icons::COMMENT_QUOTE),
        "invoice-arrow-right-outline" => Some(icons::INVOICE_ARROW_RIGHT_OUTLINE),
        "hospital-marker" => Some(icons::HOSPITAL_MARKER),
        "circle-half-full" => Some(icons::CIRCLE_HALF_FULL),
        "car-select" => Some(icons::CAR_SELECT),
        "space-station" => Some(icons::SPACE_STATION),
        "fire" => Some(icons::FIRE),
        "signal-distance-variant" => Some(icons::SIGNAL_DISTANCE_VARIANT),
        "ballot-recount" => Some(icons::BALLOT_RECOUNT),
        "store-plus" => Some(icons::STORE_PLUS),
        "arrow-expand-horizontal" => Some(icons::ARROW_EXPAND_HORIZONTAL),
        "alpha-l-box-outline" => Some(icons::ALPHA_L_BOX_OUTLINE),
        "phone-paused-outline" => Some(icons::PHONE_PAUSED_OUTLINE),
        "calendar-sync-outline" => Some(icons::CALENDAR_SYNC_OUTLINE),
        "folder-account" => Some(icons::FOLDER_ACCOUNT),
        "emoticon-sick" => Some(icons::EMOTICON_SICK),
        "train-car-centerbeam-full" => Some(icons::TRAIN_CAR_CENTERBEAM_FULL),
        "current-dc" => Some(icons::CURRENT_DC),
        "file-powerpoint" => Some(icons::FILE_POWERPOINT),
        "cards-playing-club-multiple" => Some(icons::CARDS_PLAYING_CLUB_MULTIPLE),
        "pig" => Some(icons::PIG),
        "surround-sound" => Some(icons::SURROUND_SOUND),
        "office-building-cog-outline" => Some(icons::OFFICE_BUILDING_COG_OUTLINE),
        "water-well-outline" => Some(icons::WATER_WELL_OUTLINE),
        "tower-fire" => Some(icons::TOWER_FIRE),
        "video-minus-outline" => Some(icons::VIDEO_MINUS_OUTLINE),
        "account-multiple-remove" => Some(icons::ACCOUNT_MULTIPLE_REMOVE),
        "clock-time-eleven" => Some(icons::CLOCK_TIME_ELEVEN),
        "numeric-9-circle" => Some(icons::NUMERIC_9_CIRCLE),
        "battery-charging-wireless-90" => Some(icons::BATTERY_CHARGING_WIRELESS_90),
        "wifi-check" => Some(icons::WIFI_CHECK),
        "alert-box" => Some(icons::ALERT_BOX),
        _ => None,
    }
}
