// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_22(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "dice-4-outline" => Some(icons::DICE_4_OUTLINE),
        "variable" => Some(icons::VARIABLE),
        "message-question" => Some(icons::MESSAGE_QUESTION),
        "flask-plus-outline" => Some(icons::FLASK_PLUS_OUTLINE),
        "cellphone" => Some(icons::CELLPHONE),
        "badge-account-horizontal-outline" => Some(icons::BADGE_ACCOUNT_HORIZONTAL_OUTLINE),
        "router-wireless-off" => Some(icons::ROUTER_WIRELESS_OFF),
        "car-brake-worn-linings" => Some(icons::CAR_BRAKE_WORN_LININGS),
        "numeric-8-circle" => Some(icons::NUMERIC_8_CIRCLE),
        "chili-alert-outline" => Some(icons::CHILI_ALERT_OUTLINE),
        "book-clock-outline" => Some(icons::BOOK_CLOCK_OUTLINE),
        "needle" => Some(icons::NEEDLE),
        "clipboard-multiple" => Some(icons::CLIPBOARD_MULTIPLE),
        "chess-bishop" => Some(icons::CHESS_BISHOP),
        "puzzle-heart" => Some(icons::PUZZLE_HEART),
        "package-variant-closed-plus" => Some(icons::PACKAGE_VARIANT_CLOSED_PLUS),
        "minus-box-outline" => Some(icons::MINUS_BOX_OUTLINE),
        "mini-sd" => Some(icons::MINI_SD),
        "book-heart" => Some(icons::BOOK_HEART),
        "send-variant-clock-outline" => Some(icons::SEND_VARIANT_CLOCK_OUTLINE),
        "mouse-off" => Some(icons::MOUSE_OFF),
        "serial-port" => Some(icons::SERIAL_PORT),
        "glass-mug-variant" => Some(icons::GLASS_MUG_VARIANT),
        "book-clock" => Some(icons::BOOK_CLOCK),
        "phone-remove" => Some(icons::PHONE_REMOVE),
        "trackpad" => Some(icons::TRACKPAD),
        "white-balance-auto" => Some(icons::WHITE_BALANCE_AUTO),
        "numeric-4-circle-outline" => Some(icons::NUMERIC_4_CIRCLE_OUTLINE),
        "alarm-panel-outline" => Some(icons::ALARM_PANEL_OUTLINE),
        "passport-remove" => Some(icons::PASSPORT_REMOVE),
        "square-outline" => Some(icons::SQUARE_OUTLINE),
        "numeric-5-box" => Some(icons::NUMERIC_5_BOX),
        "lightbulb-multiple-off" => Some(icons::LIGHTBULB_MULTIPLE_OFF),
        "movie-star-outline" => Some(icons::MOVIE_STAR_OUTLINE),
        "folder-sync" => Some(icons::FOLDER_SYNC),
        "clipboard-arrow-right" => Some(icons::CLIPBOARD_ARROW_RIGHT),
        "help-box-outline" => Some(icons::HELP_BOX_OUTLINE),
        "page-previous" => Some(icons::PAGE_PREVIOUS),
        "set-top-box" => Some(icons::SET_TOP_BOX),
        #[allow(deprecated)]
        "apple-safari" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'apple-safari' is deprecated.").print(py);
            }
            Some(icons::APPLE_SAFARI)
        }
        "fountain-pen-tip" => Some(icons::FOUNTAIN_PEN_TIP),
        "window-shutter-cog" => Some(icons::WINDOW_SHUTTER_COG),
        "scent-off" => Some(icons::SCENT_OFF),
        "car-wrench" => Some(icons::CAR_WRENCH),
        "gender-transgender" => Some(icons::GENDER_TRANSGENDER),
        "beaker" => Some(icons::BEAKER),
        "robot-mower-outline" => Some(icons::ROBOT_MOWER_OUTLINE),
        "chat-processing-outline" => Some(icons::CHAT_PROCESSING_OUTLINE),
        "nuke" => Some(icons::NUKE),
        "toy-brick-minus-outline" => Some(icons::TOY_BRICK_MINUS_OUTLINE),
        "relation-zero-or-many-to-many" => Some(icons::RELATION_ZERO_OR_MANY_TO_MANY),
        "map-marker-off-outline" => Some(icons::MAP_MARKER_OFF_OUTLINE),
        "coach-lamp" => Some(icons::COACH_LAMP),
        "timer-settings" => Some(icons::TIMER_SETTINGS),
        "autorenew-off" => Some(icons::AUTORENEW_OFF),
        "dock-window" => Some(icons::DOCK_WINDOW),
        "fishbowl-outline" => Some(icons::FISHBOWL_OUTLINE),
        "folder-clock-outline" => Some(icons::FOLDER_CLOCK_OUTLINE),
        "ev-plug-chademo" => Some(icons::EV_PLUG_CHADEMO),
        #[allow(deprecated)]
        "nodejs" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'nodejs' is deprecated.").print(py);
            }
            Some(icons::NODEJS)
        }
        "video-off" => Some(icons::VIDEO_OFF),
        "ship-wheel" => Some(icons::SHIP_WHEEL),
        "account-lock" => Some(icons::ACCOUNT_LOCK),
        "lightbulb-multiple" => Some(icons::LIGHTBULB_MULTIPLE),
        "message-reply-text" => Some(icons::MESSAGE_REPLY_TEXT),
        "usb" => Some(icons::USB),
        "cash-plus" => Some(icons::CASH_PLUS),
        "folder-minus-outline" => Some(icons::FOLDER_MINUS_OUTLINE),
        "note-text-outline" => Some(icons::NOTE_TEXT_OUTLINE),
        "link-lock" => Some(icons::LINK_LOCK),
        "clipboard-minus" => Some(icons::CLIPBOARD_MINUS),
        "omega" => Some(icons::OMEGA),
        "keyboard-f10" => Some(icons::KEYBOARD_F10),
        "fridge" => Some(icons::FRIDGE),
        "compass" => Some(icons::COMPASS),
        "account-tie" => Some(icons::ACCOUNT_TIE),
        "alpha-e-circle" => Some(icons::ALPHA_E_CIRCLE),
        "view-stream-outline" => Some(icons::VIEW_STREAM_OUTLINE),
        "invoice-text-remove-outline" => Some(icons::INVOICE_TEXT_REMOVE_OUTLINE),
        "view-sequential-outline" => Some(icons::VIEW_SEQUENTIAL_OUTLINE),
        "phone-rotate-portrait" => Some(icons::PHONE_ROTATE_PORTRAIT),
        "numeric-5" => Some(icons::NUMERIC_5),
        "clock-time-four" => Some(icons::CLOCK_TIME_FOUR),
        "archive-edit" => Some(icons::ARCHIVE_EDIT),
        "hub-outline" => Some(icons::HUB_OUTLINE),
        "purse" => Some(icons::PURSE),
        "progress-check" => Some(icons::PROGRESS_CHECK),
        "unicorn-variant" => Some(icons::UNICORN_VARIANT),
        "printer-3d" => Some(icons::PRINTER_3D),
        "refresh" => Some(icons::REFRESH),
        "numeric-1-box-outline" => Some(icons::NUMERIC_1_BOX_OUTLINE),
        "walk" => Some(icons::WALK),
        "book-open-blank-variant-outline" => Some(icons::BOOK_OPEN_BLANK_VARIANT_OUTLINE),
        "view-module-outline" => Some(icons::VIEW_MODULE_OUTLINE),
        "phone-sync-outline" => Some(icons::PHONE_SYNC_OUTLINE),
        "minidisc" => Some(icons::MINIDISC),
        "view-array" => Some(icons::VIEW_ARRAY),
        "email-arrow-left-outline" => Some(icons::EMAIL_ARROW_LEFT_OUTLINE),
        "credit-card-outline" => Some(icons::CREDIT_CARD_OUTLINE),
        "alpha-z-circle-outline" => Some(icons::ALPHA_Z_CIRCLE_OUTLINE),
        "stool-outline" => Some(icons::STOOL_OUTLINE),
        "selection-multiple" => Some(icons::SELECTION_MULTIPLE),
        "numeric-1-box" => Some(icons::NUMERIC_1_BOX),
        "sphere" => Some(icons::SPHERE),
        "calendar-alert" => Some(icons::CALENDAR_ALERT),
        "arrow-horizontal-lock" => Some(icons::ARROW_HORIZONTAL_LOCK),
        "passport" => Some(icons::PASSPORT),
        "file" => Some(icons::FILE),
        "tag-edit" => Some(icons::TAG_EDIT),
        "printer-pos-pause" => Some(icons::PRINTER_POS_PAUSE),
        "vector-triangle" => Some(icons::VECTOR_TRIANGLE),
        "weather-lightning-rainy" => Some(icons::WEATHER_LIGHTNING_RAINY),
        "information-box" => Some(icons::INFORMATION_BOX),
        "barrel-outline" => Some(icons::BARREL_OUTLINE),
        "checkbox-blank-circle" => Some(icons::CHECKBOX_BLANK_CIRCLE),
        "format-list-bulleted-type" => Some(icons::FORMAT_LIST_BULLETED_TYPE),
        "car-battery" => Some(icons::CAR_BATTERY),
        "view-dashboard-edit" => Some(icons::VIEW_DASHBOARD_EDIT),
        "remote-desktop" => Some(icons::REMOTE_DESKTOP),
        "plus-minus" => Some(icons::PLUS_MINUS),
        "diving-snorkel" => Some(icons::DIVING_SNORKEL),
        "tab-unselected" => Some(icons::TAB_UNSELECTED),
        "bell-ring" => Some(icons::BELL_RING),
        "smart-card-off" => Some(icons::SMART_CARD_OFF),
        "sync" => Some(icons::SYNC),
        "lightbulb-group-off-outline" => Some(icons::LIGHTBULB_GROUP_OFF_OUTLINE),
        "map-marker-account" => Some(icons::MAP_MARKER_ACCOUNT),
        "exclamation" => Some(icons::EXCLAMATION),
        "calendar-expand-horizontal" => Some(icons::CALENDAR_EXPAND_HORIZONTAL),
        "fridge-top" => Some(icons::FRIDGE_TOP),
        "weight-gram" => Some(icons::WEIGHT_GRAM),
        "battery-sync-outline" => Some(icons::BATTERY_SYNC_OUTLINE),
        "emoticon-tongue" => Some(icons::EMOTICON_TONGUE),
        "chair-school" => Some(icons::CHAIR_SCHOOL),
        "hand-pointing-left" => Some(icons::HAND_POINTING_LEFT),
        "clipboard-minus-outline" => Some(icons::CLIPBOARD_MINUS_OUTLINE),
        "human-male-height-variant" => Some(icons::HUMAN_MALE_HEIGHT_VARIANT),
        "flower-tulip" => Some(icons::FLOWER_TULIP),
        "weather-partly-snowy" => Some(icons::WEATHER_PARTLY_SNOWY),
        "file-account-outline" => Some(icons::FILE_ACCOUNT_OUTLINE),
        "laptop-account" => Some(icons::LAPTOP_ACCOUNT),
        "transit-detour" => Some(icons::TRANSIT_DETOUR),
        "vanity-light" => Some(icons::VANITY_LIGHT),
        "lotion-plus" => Some(icons::LOTION_PLUS),
        "cross-bolnisi" => Some(icons::CROSS_BOLNISI),
        "keyboard-off-outline" => Some(icons::KEYBOARD_OFF_OUTLINE),
        "parachute-outline" => Some(icons::PARACHUTE_OUTLINE),
        "music-note-quarter" => Some(icons::MUSIC_NOTE_QUARTER),
        "cellphone-link" => Some(icons::CELLPHONE_LINK),
        "truck-remove-outline" => Some(icons::TRUCK_REMOVE_OUTLINE),
        "star-box-outline" => Some(icons::STAR_BOX_OUTLINE),
        "plus-box-multiple" => Some(icons::PLUS_BOX_MULTIPLE),
        "printer-settings" => Some(icons::PRINTER_SETTINGS),
        "human-male-board" => Some(icons::HUMAN_MALE_BOARD),
        "car-estate" => Some(icons::CAR_ESTATE),
        "math-cos" => Some(icons::MATH_COS),
        "diving-scuba-mask" => Some(icons::DIVING_SCUBA_MASK),
        "train-car-autorack" => Some(icons::TRAIN_CAR_AUTORACK),
        "shield-link-variant-outline" => Some(icons::SHIELD_LINK_VARIANT_OUTLINE),
        "pencil-circle-outline" => Some(icons::PENCIL_CIRCLE_OUTLINE),
        "ev-plug-ccs1" => Some(icons::EV_PLUG_CCS1),
        "ferris-wheel" => Some(icons::FERRIS_WHEEL),
        "leaf-maple" => Some(icons::LEAF_MAPLE),
        "movie-cog" => Some(icons::MOVIE_COG),
        "format-quote-close" => Some(icons::FORMAT_QUOTE_CLOSE),
        "paper-cut-vertical" => Some(icons::PAPER_CUT_VERTICAL),
        "subdirectory-arrow-left" => Some(icons::SUBDIRECTORY_ARROW_LEFT),
        "invoice-arrow-left" => Some(icons::INVOICE_ARROW_LEFT),
        "send-clock-outline" => Some(icons::SEND_CLOCK_OUTLINE),
        #[allow(deprecated)]
        "dot-net" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'dot-net' is deprecated.").print(py);
            }
            Some(icons::DOT_NET)
        }
        "elevator-passenger-off-outline" => Some(icons::ELEVATOR_PASSENGER_OFF_OUTLINE),
        "corn" => Some(icons::CORN),
        "storage-tank-outline" => Some(icons::STORAGE_TANK_OUTLINE),
        "vector-difference-ab" => Some(icons::VECTOR_DIFFERENCE_AB),
        "lightbulb-on-30" => Some(icons::LIGHTBULB_ON_30),
        "vibrate" => Some(icons::VIBRATE),
        "clock-time-two" => Some(icons::CLOCK_TIME_TWO),
        "format-horizontal-align-center" => Some(icons::FORMAT_HORIZONTAL_ALIGN_CENTER),
        "cake-layered" => Some(icons::CAKE_LAYERED),
        "comma" => Some(icons::COMMA),
        "moon-waning-gibbous" => Some(icons::MOON_WANING_GIBBOUS),
        "wallpaper" => Some(icons::WALLPAPER),
        "account-sync" => Some(icons::ACCOUNT_SYNC),
        "bell-sleep-outline" => Some(icons::BELL_SLEEP_OUTLINE),
        "delta" => Some(icons::DELTA),
        "earth-arrow-down" => Some(icons::EARTH_ARROW_DOWN),
        "credit-card-fast-outline" => Some(icons::CREDIT_CARD_FAST_OUTLINE),
        "basket-minus-outline" => Some(icons::BASKET_MINUS_OUTLINE),
        "table-sync" => Some(icons::TABLE_SYNC),
        "account-music-outline" => Some(icons::ACCOUNT_MUSIC_OUTLINE),
        "toothbrush-paste" => Some(icons::TOOTHBRUSH_PASTE),
        "diving-flippers" => Some(icons::DIVING_FLIPPERS),
        "turnstile" => Some(icons::TURNSTILE),
        "database-eye-off" => Some(icons::DATABASE_EYE_OFF),
        "archive-lock-outline" => Some(icons::ARCHIVE_LOCK_OUTLINE),
        "table-alert" => Some(icons::TABLE_ALERT),
        "table-heart" => Some(icons::TABLE_HEART),
        "file-eye" => Some(icons::FILE_EYE),
        "magnify-plus" => Some(icons::MAGNIFY_PLUS),
        "file-rotate-left" => Some(icons::FILE_ROTATE_LEFT),
        _ => None,
    }
}
