// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_28(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "sim-off-outline" => Some(icons::SIM_OFF_OUTLINE),
        "home-minus" => Some(icons::HOME_MINUS),
        "puzzle-remove-outline" => Some(icons::PUZZLE_REMOVE_OUTLINE),
        "biohazard" => Some(icons::BIOHAZARD),
        "application-settings-outline" => Some(icons::APPLICATION_SETTINGS_OUTLINE),
        "code-parentheses" => Some(icons::CODE_PARENTHESES),
        #[allow(deprecated)]
        "microsoft-xbox-controller-view" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err(
                    "The icon 'microsoft-xbox-controller-view' is deprecated.",
                )
                .print(py);
            }
            Some(icons::MICROSOFT_XBOX_CONTROLLER_VIEW)
        }
        "sort-alphabetical-descending" => Some(icons::SORT_ALPHABETICAL_DESCENDING),
        "flask-empty-outline" => Some(icons::FLASK_EMPTY_OUTLINE),
        "fire-hydrant" => Some(icons::FIRE_HYDRANT),
        "database-import-outline" => Some(icons::DATABASE_IMPORT_OUTLINE),
        "folder-edit" => Some(icons::FOLDER_EDIT),
        "doctor" => Some(icons::DOCTOR),
        "decimal-comma" => Some(icons::DECIMAL_COMMA),
        "account-tie-voice-off" => Some(icons::ACCOUNT_TIE_VOICE_OFF),
        "calendar-range-outline" => Some(icons::CALENDAR_RANGE_OUTLINE),
        "track-light-off" => Some(icons::TRACK_LIGHT_OFF),
        "car-settings" => Some(icons::CAR_SETTINGS),
        "basket-minus-outline" => Some(icons::BASKET_MINUS_OUTLINE),
        "medication-outline" => Some(icons::MEDICATION_OUTLINE),
        "heating-coil" => Some(icons::HEATING_COIL),
        "bugle" => Some(icons::BUGLE),
        "food-variant-off" => Some(icons::FOOD_VARIANT_OFF),
        "alpha-r-box" => Some(icons::ALPHA_R_BOX),
        #[allow(deprecated)]
        "microsoft-word" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'microsoft-word' is deprecated.").print(py);
            }
            Some(icons::MICROSOFT_WORD)
        }
        "pound-box" => Some(icons::POUND_BOX),
        "set-top-box" => Some(icons::SET_TOP_BOX),
        "hair-dryer-outline" => Some(icons::HAIR_DRYER_OUTLINE),
        "credit-card-chip-outline" => Some(icons::CREDIT_CARD_CHIP_OUTLINE),
        "diameter-variant" => Some(icons::DIAMETER_VARIANT),
        "baseball-bat" => Some(icons::BASEBALL_BAT),
        "folder-move-outline" => Some(icons::FOLDER_MOVE_OUTLINE),
        "puzzle-remove" => Some(icons::PUZZLE_REMOVE),
        "paperclip-minus" => Some(icons::PAPERCLIP_MINUS),
        "camera-gopro" => Some(icons::CAMERA_GOPRO),
        "space-station" => Some(icons::SPACE_STATION),
        "arrow-right-bold-box" => Some(icons::ARROW_RIGHT_BOLD_BOX),
        "human-male" => Some(icons::HUMAN_MALE),
        "car-clutch" => Some(icons::CAR_CLUTCH),
        "square-edit-outline" => Some(icons::SQUARE_EDIT_OUTLINE),
        "file-music" => Some(icons::FILE_MUSIC),
        "numeric-4-box-outline" => Some(icons::NUMERIC_4_BOX_OUTLINE),
        "cloud-arrow-down" => Some(icons::CLOUD_ARROW_DOWN),
        "shield-half-full" => Some(icons::SHIELD_HALF_FULL),
        "baby-face-outline" => Some(icons::BABY_FACE_OUTLINE),
        "content-save-settings-outline" => Some(icons::CONTENT_SAVE_SETTINGS_OUTLINE),
        "archive-plus-outline" => Some(icons::ARCHIVE_PLUS_OUTLINE),
        "shield-remove-outline" => Some(icons::SHIELD_REMOVE_OUTLINE),
        "led-outline" => Some(icons::LED_OUTLINE),
        "source-branch-remove" => Some(icons::SOURCE_BRANCH_REMOVE),
        "car-wash" => Some(icons::CAR_WASH),
        "file-certificate" => Some(icons::FILE_CERTIFICATE),
        "chart-timeline" => Some(icons::CHART_TIMELINE),
        "arrow-left-drop-circle" => Some(icons::ARROW_LEFT_DROP_CIRCLE),
        "movie-open-off-outline" => Some(icons::MOVIE_OPEN_OFF_OUTLINE),
        "battery-70-bluetooth" => Some(icons::BATTERY_70_BLUETOOTH),
        "barn" => Some(icons::BARN),
        "movie-settings-outline" => Some(icons::MOVIE_SETTINGS_OUTLINE),
        "file-sync" => Some(icons::FILE_SYNC),
        "truck-alert-outline" => Some(icons::TRUCK_ALERT_OUTLINE),
        "notebook-check-outline" => Some(icons::NOTEBOOK_CHECK_OUTLINE),
        "car-electric-outline" => Some(icons::CAR_ELECTRIC_OUTLINE),
        "file-jpg-box" => Some(icons::FILE_JPG_BOX),
        "arrange-bring-to-front" => Some(icons::ARRANGE_BRING_TO_FRONT),
        "account-circle-outline" => Some(icons::ACCOUNT_CIRCLE_OUTLINE),
        "bicycle-basket" => Some(icons::BICYCLE_BASKET),
        "book-arrow-down" => Some(icons::BOOK_ARROW_DOWN),
        "text-box-minus-outline" => Some(icons::TEXT_BOX_MINUS_OUTLINE),
        "gesture-two-tap" => Some(icons::GESTURE_TWO_TAP),
        "upload-off-outline" => Some(icons::UPLOAD_OFF_OUTLINE),
        "file-undo" => Some(icons::FILE_UNDO),
        "bag-personal" => Some(icons::BAG_PERSONAL),
        "knob" => Some(icons::KNOB),
        "panorama-sphere-outline" => Some(icons::PANORAMA_SPHERE_OUTLINE),
        "checkbox-multiple-outline" => Some(icons::CHECKBOX_MULTIPLE_OUTLINE),
        "card-account-phone" => Some(icons::CARD_ACCOUNT_PHONE),
        "tooltip-remove" => Some(icons::TOOLTIP_REMOVE),
        "arrow-up-down-bold" => Some(icons::ARROW_UP_DOWN_BOLD),
        "gold" => Some(icons::GOLD),
        "view-gallery" => Some(icons::VIEW_GALLERY),
        "backup-restore" => Some(icons::BACKUP_RESTORE),
        "resize-bottom-right" => Some(icons::RESIZE_BOTTOM_RIGHT),
        "bed-outline" => Some(icons::BED_OUTLINE),
        "truck-cargo-container" => Some(icons::TRUCK_CARGO_CONTAINER),
        "led-variant-outline" => Some(icons::LED_VARIANT_OUTLINE),
        "toy-brick-plus" => Some(icons::TOY_BRICK_PLUS),
        "arrow-up-down" => Some(icons::ARROW_UP_DOWN),
        "skew-more" => Some(icons::SKEW_MORE),
        "printer-pos-edit-outline" => Some(icons::PRINTER_POS_EDIT_OUTLINE),
        "home-account" => Some(icons::HOME_ACCOUNT),
        "liquor" => Some(icons::LIQUOR),
        "account-details" => Some(icons::ACCOUNT_DETAILS),
        "map-outline" => Some(icons::MAP_OUTLINE),
        "cpu-64-bit" => Some(icons::CPU_64_BIT),
        "file-eye-outline" => Some(icons::FILE_EYE_OUTLINE),
        "kayaking" => Some(icons::KAYAKING),
        "truck-fast-outline" => Some(icons::TRUCK_FAST_OUTLINE),
        "relation-zero-or-one-to-many" => Some(icons::RELATION_ZERO_OR_ONE_TO_MANY),
        "application-edit-outline" => Some(icons::APPLICATION_EDIT_OUTLINE),
        "jellyfish-outline" => Some(icons::JELLYFISH_OUTLINE),
        "dome-light" => Some(icons::DOME_LIGHT),
        "powershell" => Some(icons::POWERSHELL),
        "book-open-variant-outline" => Some(icons::BOOK_OPEN_VARIANT_OUTLINE),
        "image-off-outline" => Some(icons::IMAGE_OFF_OUTLINE),
        "sword-cross" => Some(icons::SWORD_CROSS),
        "car-esp" => Some(icons::CAR_ESP),
        "note-edit-outline" => Some(icons::NOTE_EDIT_OUTLINE),
        "account-arrow-down" => Some(icons::ACCOUNT_ARROW_DOWN),
        "vector-curve" => Some(icons::VECTOR_CURVE),
        "bluetooth-connect" => Some(icons::BLUETOOTH_CONNECT),
        "arrow-down-box" => Some(icons::ARROW_DOWN_BOX),
        "needle" => Some(icons::NEEDLE),
        "size-xxl" => Some(icons::SIZE_XXL),
        "alpha-b-box" => Some(icons::ALPHA_B_BOX),
        "heart-broken-outline" => Some(icons::HEART_BROKEN_OUTLINE),
        "pyramid-off" => Some(icons::PYRAMID_OFF),
        "alphabetical-variant-off" => Some(icons::ALPHABETICAL_VARIANT_OFF),
        "printer-eye" => Some(icons::PRINTER_EYE),
        "arrow-top-right-thin" => Some(icons::ARROW_TOP_RIGHT_THIN),
        "human-female-female" => Some(icons::HUMAN_FEMALE_FEMALE),
        "cookie-check" => Some(icons::COOKIE_CHECK),
        "alert-circle-check" => Some(icons::ALERT_CIRCLE_CHECK),
        "view-array-outline" => Some(icons::VIEW_ARRAY_OUTLINE),
        "menorah" => Some(icons::MENORAH),
        "magnify-close" => Some(icons::MAGNIFY_CLOSE),
        "alpha-v-box-outline" => Some(icons::ALPHA_V_BOX_OUTLINE),
        "format-text-rotation-angle-up" => Some(icons::FORMAT_TEXT_ROTATION_ANGLE_UP),
        "cloud-arrow-up" => Some(icons::CLOUD_ARROW_UP),
        "download-lock" => Some(icons::DOWNLOAD_LOCK),
        "help-box-multiple" => Some(icons::HELP_BOX_MULTIPLE),
        "home-remove" => Some(icons::HOME_REMOVE),
        "fullscreen" => Some(icons::FULLSCREEN),
        "shape" => Some(icons::SHAPE),
        "mouse-variant-off" => Some(icons::MOUSE_VARIANT_OFF),
        "speaker-wireless" => Some(icons::SPEAKER_WIRELESS),
        "account-music-outline" => Some(icons::ACCOUNT_MUSIC_OUTLINE),
        "summit" => Some(icons::SUMMIT),
        "lan-connect" => Some(icons::LAN_CONNECT),
        "wifi-alert" => Some(icons::WIFI_ALERT),
        "firewire" => Some(icons::FIREWIRE),
        "upload-box" => Some(icons::UPLOAD_BOX),
        "wrap" => Some(icons::WRAP),
        "dice-d20-outline" => Some(icons::DICE_D20_OUTLINE),
        "cupboard-outline" => Some(icons::CUPBOARD_OUTLINE),
        "octagram-minus-outline" => Some(icons::OCTAGRAM_MINUS_OUTLINE),
        "swap-horizontal" => Some(icons::SWAP_HORIZONTAL),
        "access-point-network-off" => Some(icons::ACCESS_POINT_NETWORK_OFF),
        "tally-mark-5" => Some(icons::TALLY_MARK_5),
        "chevron-up-circle" => Some(icons::CHEVRON_UP_CIRCLE),
        "numeric-1-box-multiple" => Some(icons::NUMERIC_1_BOX_MULTIPLE),
        "comma-box" => Some(icons::COMMA_BOX),
        "script-text-play" => Some(icons::SCRIPT_TEXT_PLAY),
        "credit-card-lock" => Some(icons::CREDIT_CARD_LOCK),
        "cards-diamond-outline" => Some(icons::CARDS_DIAMOND_OUTLINE),
        "arrow-expand" => Some(icons::ARROW_EXPAND),
        "connection" => Some(icons::CONNECTION),
        "tag-off" => Some(icons::TAG_OFF),
        "spray" => Some(icons::SPRAY),
        "text-box-multiple-outline" => Some(icons::TEXT_BOX_MULTIPLE_OUTLINE),
        "menu-down-outline" => Some(icons::MENU_DOWN_OUTLINE),
        "car-brake-fluid-level" => Some(icons::CAR_BRAKE_FLUID_LEVEL),
        "human-male-board" => Some(icons::HUMAN_MALE_BOARD),
        "satellite" => Some(icons::SATELLITE),
        "shaker" => Some(icons::SHAKER),
        "application-cog-outline" => Some(icons::APPLICATION_COG_OUTLINE),
        "qrcode-remove" => Some(icons::QRCODE_REMOVE),
        "heart-box" => Some(icons::HEART_BOX),
        "book-remove-outline" => Some(icons::BOOK_REMOVE_OUTLINE),
        "smoke" => Some(icons::SMOKE),
        "mailbox-up" => Some(icons::MAILBOX_UP),
        "boomerang" => Some(icons::BOOMERANG),
        "message-text-fast" => Some(icons::MESSAGE_TEXT_FAST),
        "file-link-outline" => Some(icons::FILE_LINK_OUTLINE),
        "comment-remove-outline" => Some(icons::COMMENT_REMOVE_OUTLINE),
        "wallet-membership" => Some(icons::WALLET_MEMBERSHIP),
        "thermometer-water" => Some(icons::THERMOMETER_WATER),
        "merge" => Some(icons::MERGE),
        "battery-minus-outline" => Some(icons::BATTERY_MINUS_OUTLINE),
        "circle-box-outline" => Some(icons::CIRCLE_BOX_OUTLINE),
        "sort-bool-descending" => Some(icons::SORT_BOOL_DESCENDING),
        "network-strength-4" => Some(icons::NETWORK_STRENGTH_4),
        "heart-minus-outline" => Some(icons::HEART_MINUS_OUTLINE),
        "eject-circle-outline" => Some(icons::EJECT_CIRCLE_OUTLINE),
        "arrow-bottom-right-thin-circle-outline" => {
            Some(icons::ARROW_BOTTOM_RIGHT_THIN_CIRCLE_OUTLINE)
        }
        "music-note-off-outline" => Some(icons::MUSIC_NOTE_OFF_OUTLINE),
        "home-roof" => Some(icons::HOME_ROOF),
        "meter-electric" => Some(icons::METER_ELECTRIC),
        "email-arrow-right-outline" => Some(icons::EMAIL_ARROW_RIGHT_OUTLINE),
        "storefront-remove-outline" => Some(icons::STOREFRONT_REMOVE_OUTLINE),
        "parachute" => Some(icons::PARACHUTE),
        "invoice-outline" => Some(icons::INVOICE_OUTLINE),
        "clipboard-arrow-up-outline" => Some(icons::CLIPBOARD_ARROW_UP_OUTLINE),
        "ruler" => Some(icons::RULER),
        "border-none-variant" => Some(icons::BORDER_NONE_VARIANT),
        "numeric-6" => Some(icons::NUMERIC_6),
        "sledding" => Some(icons::SLEDDING),
        "book-open" => Some(icons::BOOK_OPEN),
        "format-header-increase" => Some(icons::FORMAT_HEADER_INCREASE),
        "calendar-multiselect-outline" => Some(icons::CALENDAR_MULTISELECT_OUTLINE),
        "notebook-multiple" => Some(icons::NOTEBOOK_MULTIPLE),
        _ => None,
    }
}
