// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_33(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "folder-key-network" => Some(icons::FOLDER_KEY_NETWORK),
        "chevron-triple-up" => Some(icons::CHEVRON_TRIPLE_UP),
        "alpha-n-circle" => Some(icons::ALPHA_N_CIRCLE),
        "key-star" => Some(icons::KEY_STAR),
        "database-arrow-right" => Some(icons::DATABASE_ARROW_RIGHT),
        "battery-low" => Some(icons::BATTERY_LOW),
        "star-off" => Some(icons::STAR_OFF),
        "message-check-outline" => Some(icons::MESSAGE_CHECK_OUTLINE),
        "periodic-table" => Some(icons::PERIODIC_TABLE),
        "key-link" => Some(icons::KEY_LINK),
        "sticker-circle-outline" => Some(icons::STICKER_CIRCLE_OUTLINE),
        "invoice-text-arrow-right" => Some(icons::INVOICE_TEXT_ARROW_RIGHT),
        "alpha-o-circle" => Some(icons::ALPHA_O_CIRCLE),
        "face-woman-shimmer-outline" => Some(icons::FACE_WOMAN_SHIMMER_OUTLINE),
        "gamepad-square" => Some(icons::GAMEPAD_SQUARE),
        "printer-pos-remove" => Some(icons::PRINTER_POS_REMOVE),
        "dance-pole" => Some(icons::DANCE_POLE),
        "database-plus" => Some(icons::DATABASE_PLUS),
        "table-eye-off" => Some(icons::TABLE_EYE_OFF),
        "battery-unknown" => Some(icons::BATTERY_UNKNOWN),
        "air-purifier" => Some(icons::AIR_PURIFIER),
        "arrow-up-bold-box" => Some(icons::ARROW_UP_BOLD_BOX),
        "plus-circle-multiple" => Some(icons::PLUS_CIRCLE_MULTIPLE),
        "briefcase-search" => Some(icons::BRIEFCASE_SEARCH),
        "briefcase-account-outline" => Some(icons::BRIEFCASE_ACCOUNT_OUTLINE),
        "music-rest-eighth" => Some(icons::MUSIC_REST_EIGHTH),
        "bug-check" => Some(icons::BUG_CHECK),
        "arrow-oscillating-off" => Some(icons::ARROW_OSCILLATING_OFF),
        "train-car-tank" => Some(icons::TRAIN_CAR_TANK),
        "format-letter-spacing" => Some(icons::FORMAT_LETTER_SPACING),
        "fast-forward" => Some(icons::FAST_FORWARD),
        "calendar-end" => Some(icons::CALENDAR_END),
        "filter-minus" => Some(icons::FILTER_MINUS),
        "lightbulb-cfl-spiral" => Some(icons::LIGHTBULB_CFL_SPIRAL),
        "swap-horizontal-variant" => Some(icons::SWAP_HORIZONTAL_VARIANT),
        "alert-plus-outline" => Some(icons::ALERT_PLUS_OUTLINE),
        "newspaper" => Some(icons::NEWSPAPER),
        "zip-disk" => Some(icons::ZIP_DISK),
        "square-rounded" => Some(icons::SQUARE_ROUNDED),
        "alpha-u-circle-outline" => Some(icons::ALPHA_U_CIRCLE_OUTLINE),
        "creation" => Some(icons::CREATION),
        "layers-minus" => Some(icons::LAYERS_MINUS),
        "alert-octagram" => Some(icons::ALERT_OCTAGRAM),
        "epsilon" => Some(icons::EPSILON),
        "shield-search" => Some(icons::SHIELD_SEARCH),
        "briefcase-upload-outline" => Some(icons::BRIEFCASE_UPLOAD_OUTLINE),
        "relation-one-or-many-to-zero-or-many" => Some(icons::RELATION_ONE_OR_MANY_TO_ZERO_OR_MANY),
        #[allow(deprecated)]
        "firefox" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'firefox' is deprecated.").print(py);
            }
            Some(icons::FIREFOX)
        }
        "cards-spade" => Some(icons::CARDS_SPADE),
        "chart-bar" => Some(icons::CHART_BAR),
        "map-search-outline" => Some(icons::MAP_SEARCH_OUTLINE),
        "account-plus" => Some(icons::ACCOUNT_PLUS),
        "eyedropper-off" => Some(icons::EYEDROPPER_OFF),
        "file-document-edit-outline" => Some(icons::FILE_DOCUMENT_EDIT_OUTLINE),
        "car-seat-cooler" => Some(icons::CAR_SEAT_COOLER),
        "email-arrow-left" => Some(icons::EMAIL_ARROW_LEFT),
        "dots-vertical-circle" => Some(icons::DOTS_VERTICAL_CIRCLE),
        "wardrobe-outline" => Some(icons::WARDROBE_OUTLINE),
        "human-male-board-poll" => Some(icons::HUMAN_MALE_BOARD_POLL),
        "table-sync" => Some(icons::TABLE_SYNC),
        "motorbike-off" => Some(icons::MOTORBIKE_OFF),
        "slope-downhill" => Some(icons::SLOPE_DOWNHILL),
        "link-plus" => Some(icons::LINK_PLUS),
        "map-marker-right-outline" => Some(icons::MAP_MARKER_RIGHT_OUTLINE),
        "message-cog" => Some(icons::MESSAGE_COG),
        "bus-wrench" => Some(icons::BUS_WRENCH),
        "link-variant-remove" => Some(icons::LINK_VARIANT_REMOVE),
        "format-underline-wavy" => Some(icons::FORMAT_UNDERLINE_WAVY),
        #[allow(deprecated)]
        "language-html5" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'language-html5' is deprecated.").print(py);
            }
            Some(icons::LANGUAGE_HTML5)
        }
        "sort-clock-descending" => Some(icons::SORT_CLOCK_DESCENDING),
        "arrow-down-bold-outline" => Some(icons::ARROW_DOWN_BOLD_OUTLINE),
        "map-marker-radius" => Some(icons::MAP_MARKER_RADIUS),
        "clipboard-clock-outline" => Some(icons::CLIPBOARD_CLOCK_OUTLINE),
        "alpha-l-circle" => Some(icons::ALPHA_L_CIRCLE),
        "bottle-tonic" => Some(icons::BOTTLE_TONIC),
        "alpha" => Some(icons::ALPHA),
        "human-male-female-child" => Some(icons::HUMAN_MALE_FEMALE_CHILD),
        "surfing" => Some(icons::SURFING),
        "table-cog" => Some(icons::TABLE_COG),
        "mortar-pestle-plus" => Some(icons::MORTAR_PESTLE_PLUS),
        "cart-arrow-down" => Some(icons::CART_ARROW_DOWN),
        "chevron-up" => Some(icons::CHEVRON_UP),
        "palette" => Some(icons::PALETTE),
        "database-settings" => Some(icons::DATABASE_SETTINGS),
        "camera-image" => Some(icons::CAMERA_IMAGE),
        "selection" => Some(icons::SELECTION),
        "globe-light-outline" => Some(icons::GLOBE_LIGHT_OUTLINE),
        "reply-all" => Some(icons::REPLY_ALL),
        "virus-off" => Some(icons::VIRUS_OFF),
        "monitor-speaker-off" => Some(icons::MONITOR_SPEAKER_OFF),
        "circle-half" => Some(icons::CIRCLE_HALF),
        "pan-down" => Some(icons::PAN_DOWN),
        "lock-percent-open-variant" => Some(icons::LOCK_PERCENT_OPEN_VARIANT),
        "arrow-left-bold" => Some(icons::ARROW_LEFT_BOLD),
        "truck-snowflake" => Some(icons::TRUCK_SNOWFLAKE),
        "keyboard-f6" => Some(icons::KEYBOARD_F6),
        "volume-high" => Some(icons::VOLUME_HIGH),
        "script-text-key-outline" => Some(icons::SCRIPT_TEXT_KEY_OUTLINE),
        "bell-off" => Some(icons::BELL_OFF),
        "wifi-strength-2-lock" => Some(icons::WIFI_STRENGTH_2_LOCK),
        "alpha-c-circle-outline" => Some(icons::ALPHA_C_CIRCLE_OUTLINE),
        "clipboard-account-outline" => Some(icons::CLIPBOARD_ACCOUNT_OUTLINE),
        "clock-time-nine-outline" => Some(icons::CLOCK_TIME_NINE_OUTLINE),
        "star-shooting-outline" => Some(icons::STAR_SHOOTING_OUTLINE),
        "tools" => Some(icons::TOOLS),
        "set-left-center" => Some(icons::SET_LEFT_CENTER),
        "fit-to-page-outline" => Some(icons::FIT_TO_PAGE_OUTLINE),
        "script-outline" => Some(icons::SCRIPT_OUTLINE),
        "gender-female" => Some(icons::GENDER_FEMALE),
        "crowd" => Some(icons::CROWD),
        "soy-sauce" => Some(icons::SOY_SAUCE),
        "ipod" => Some(icons::IPOD),
        "eye-check" => Some(icons::EYE_CHECK),
        "application-variable-outline" => Some(icons::APPLICATION_VARIABLE_OUTLINE),
        "checkbox-blank-badge" => Some(icons::CHECKBOX_BLANK_BADGE),
        "beehive-off-outline" => Some(icons::BEEHIVE_OFF_OUTLINE),
        "water-well" => Some(icons::WATER_WELL),
        "lock-open-plus-outline" => Some(icons::LOCK_OPEN_PLUS_OUTLINE),
        "filter-variant-remove" => Some(icons::FILTER_VARIANT_REMOVE),
        "fruit-pineapple" => Some(icons::FRUIT_PINEAPPLE),
        "gamepad-round" => Some(icons::GAMEPAD_ROUND),
        "emoticon-poop" => Some(icons::EMOTICON_POOP),
        "floor-lamp-dual" => Some(icons::FLOOR_LAMP_DUAL),
        "cookie-lock-outline" => Some(icons::COOKIE_LOCK_OUTLINE),
        "polo" => Some(icons::POLO),
        "minus-box-multiple" => Some(icons::MINUS_BOX_MULTIPLE),
        "key-wireless" => Some(icons::KEY_WIRELESS),
        "shower" => Some(icons::SHOWER),
        "gesture-swipe" => Some(icons::GESTURE_SWIPE),
        "format-text-wrapping-overflow" => Some(icons::FORMAT_TEXT_WRAPPING_OVERFLOW),
        "lungs" => Some(icons::LUNGS),
        "horse-variant-fast" => Some(icons::HORSE_VARIANT_FAST),
        "cellphone-message-off" => Some(icons::CELLPHONE_MESSAGE_OFF),
        "crop-portrait" => Some(icons::CROP_PORTRAIT),
        "form-textbox-lock" => Some(icons::FORM_TEXTBOX_LOCK),
        "draw-pen" => Some(icons::DRAW_PEN),
        "bookmark-music" => Some(icons::BOOKMARK_MUSIC),
        "battery-20" => Some(icons::BATTERY_20),
        "heart" => Some(icons::HEART),
        "flask-round-bottom-empty-outline" => Some(icons::FLASK_ROUND_BOTTOM_EMPTY_OUTLINE),
        "lock-open-variant-outline" => Some(icons::LOCK_OPEN_VARIANT_OUTLINE),
        "eye-arrow-right-outline" => Some(icons::EYE_ARROW_RIGHT_OUTLINE),
        "weather-moonset-down" => Some(icons::WEATHER_MOONSET_DOWN),
        "radio" => Some(icons::RADIO),
        "account-heart-outline" => Some(icons::ACCOUNT_HEART_OUTLINE),
        "cards-playing-spade" => Some(icons::CARDS_PLAYING_SPADE),
        "home-group" => Some(icons::HOME_GROUP),
        "cookie-alert" => Some(icons::COOKIE_ALERT),
        "heart-minus" => Some(icons::HEART_MINUS),
        "moped-electric-outline" => Some(icons::MOPED_ELECTRIC_OUTLINE),
        "vector-point-plus" => Some(icons::VECTOR_POINT_PLUS),
        "chevron-down-box-outline" => Some(icons::CHEVRON_DOWN_BOX_OUTLINE),
        "email-fast-outline" => Some(icons::EMAIL_FAST_OUTLINE),
        "star-check-outline" => Some(icons::STAR_CHECK_OUTLINE),
        "ethernet-cable" => Some(icons::ETHERNET_CABLE),
        "numeric-5-circle" => Some(icons::NUMERIC_5_CIRCLE),
        "cloud-sync" => Some(icons::CLOUD_SYNC),
        "hanger" => Some(icons::HANGER),
        "smoking-pipe-off" => Some(icons::SMOKING_PIPE_OFF),
        "star-crescent" => Some(icons::STAR_CRESCENT),
        "forum-remove-outline" => Some(icons::FORUM_REMOVE_OUTLINE),
        "bottle-tonic-outline" => Some(icons::BOTTLE_TONIC_OUTLINE),
        "corn" => Some(icons::CORN),
        #[allow(deprecated)]
        "yahoo" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'yahoo' is deprecated.").print(py);
            }
            Some(icons::YAHOO)
        }
        "timer-sand-paused" => Some(icons::TIMER_SAND_PAUSED),
        "window-shutter" => Some(icons::WINDOW_SHUTTER),
        "tower-fire" => Some(icons::TOWER_FIRE),
        "numeric-0-circle-outline" => Some(icons::NUMERIC_0_CIRCLE_OUTLINE),
        "sort-alphabetical-variant" => Some(icons::SORT_ALPHABETICAL_VARIANT),
        "numeric-9-box-multiple" => Some(icons::NUMERIC_9_BOX_MULTIPLE),
        "checkbox-marked-circle-auto-outline" => Some(icons::CHECKBOX_MARKED_CIRCLE_AUTO_OUTLINE),
        "alert-octagon-outline" => Some(icons::ALERT_OCTAGON_OUTLINE),
        "weather-sunset-up" => Some(icons::WEATHER_SUNSET_UP),
        "folder-arrow-up" => Some(icons::FOLDER_ARROW_UP),
        "folder-move" => Some(icons::FOLDER_MOVE),
        "clock-check" => Some(icons::CLOCK_CHECK),
        "magnify-minus" => Some(icons::MAGNIFY_MINUS),
        "contrast-circle" => Some(icons::CONTRAST_CIRCLE),
        "cookie" => Some(icons::COOKIE),
        "arrow-left-top-bold" => Some(icons::ARROW_LEFT_TOP_BOLD),
        "ocr" => Some(icons::OCR),
        "head-dots-horizontal" => Some(icons::HEAD_DOTS_HORIZONTAL),
        "alert-remove" => Some(icons::ALERT_REMOVE),
        "math-integral-box" => Some(icons::MATH_INTEGRAL_BOX),
        "beaker" => Some(icons::BEAKER),
        "wifi-sync" => Some(icons::WIFI_SYNC),
        "relation-one-or-many-to-only-one" => Some(icons::RELATION_ONE_OR_MANY_TO_ONLY_ONE),
        "sausage-off" => Some(icons::SAUSAGE_OFF),
        "rename-box" => Some(icons::RENAME_BOX),
        "star-four-points-box" => Some(icons::STAR_FOUR_POINTS_BOX),
        "air-humidifier" => Some(icons::AIR_HUMIDIFIER),
        "bookmark-check" => Some(icons::BOOKMARK_CHECK),
        "format-list-checkbox" => Some(icons::FORMAT_LIST_CHECKBOX),
        "account-arrow-left-outline" => Some(icons::ACCOUNT_ARROW_LEFT_OUTLINE),
        "file-delimited" => Some(icons::FILE_DELIMITED),
        "alpha-g-circle" => Some(icons::ALPHA_G_CIRCLE),
        "help-box" => Some(icons::HELP_BOX),
        "timer-edit" => Some(icons::TIMER_EDIT),
        "file-move-outline" => Some(icons::FILE_MOVE_OUTLINE),
        "test-tube-off" => Some(icons::TEST_TUBE_OFF),
        _ => None,
    }
}
