// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_14(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "shield-airplane" => Some(icons::SHIELD_AIRPLANE),
        "content-cut" => Some(icons::CONTENT_CUT),
        "high-definition" => Some(icons::HIGH_DEFINITION),
        "cards-playing-outline" => Some(icons::CARDS_PLAYING_OUTLINE),
        "music-accidental-sharp" => Some(icons::MUSIC_ACCIDENTAL_SHARP),
        "smoke-detector-alert-outline" => Some(icons::SMOKE_DETECTOR_ALERT_OUTLINE),
        "sticker-plus" => Some(icons::STICKER_PLUS),
        "home-floor-1" => Some(icons::HOME_FLOOR_1),
        "snowflake" => Some(icons::SNOWFLAKE),
        "airplane-edit" => Some(icons::AIRPLANE_EDIT),
        "credit-card-edit-outline" => Some(icons::CREDIT_CARD_EDIT_OUTLINE),
        "clipboard-text-clock" => Some(icons::CLIPBOARD_TEXT_CLOCK),
        "leaf-circle-outline" => Some(icons::LEAF_CIRCLE_OUTLINE),
        "bell-plus" => Some(icons::BELL_PLUS),
        "filter-off" => Some(icons::FILTER_OFF),
        "water-check-outline" => Some(icons::WATER_CHECK_OUTLINE),
        "sort-clock-descending-outline" => Some(icons::SORT_CLOCK_DESCENDING_OUTLINE),
        "record-circle" => Some(icons::RECORD_CIRCLE),
        "cards-spade-outline" => Some(icons::CARDS_SPADE_OUTLINE),
        "shield-link-variant" => Some(icons::SHIELD_LINK_VARIANT),
        "square-circle-outline" => Some(icons::SQUARE_CIRCLE_OUTLINE),
        "autorenew-off" => Some(icons::AUTORENEW_OFF),
        "text-box-edit-outline" => Some(icons::TEXT_BOX_EDIT_OUTLINE),
        "ethernet" => Some(icons::ETHERNET),
        "office-building-outline" => Some(icons::OFFICE_BUILDING_OUTLINE),
        "robot-industrial-outline" => Some(icons::ROBOT_INDUSTRIAL_OUTLINE),
        "folder-question" => Some(icons::FOLDER_QUESTION),
        "delete-off" => Some(icons::DELETE_OFF),
        "projector-screen" => Some(icons::PROJECTOR_SCREEN),
        "credit-card-wireless-outline" => Some(icons::CREDIT_CARD_WIRELESS_OUTLINE),
        "mouse-outline" => Some(icons::MOUSE_OUTLINE),
        "eye-arrow-left-outline" => Some(icons::EYE_ARROW_LEFT_OUTLINE),
        "audio-input-stereo-minijack" => Some(icons::AUDIO_INPUT_STEREO_MINIJACK),
        "pipe-wrench" => Some(icons::PIPE_WRENCH),
        "dialpad" => Some(icons::DIALPAD),
        "robot-vacuum-variant-alert" => Some(icons::ROBOT_VACUUM_VARIANT_ALERT),
        "folder-star-multiple" => Some(icons::FOLDER_STAR_MULTIPLE),
        "format-float-none" => Some(icons::FORMAT_FLOAT_NONE),
        "open-in-app" => Some(icons::OPEN_IN_APP),
        "shield-plus" => Some(icons::SHIELD_PLUS),
        "math-integral" => Some(icons::MATH_INTEGRAL),
        "format-text-wrapping-clip" => Some(icons::FORMAT_TEXT_WRAPPING_CLIP),
        "arrow-collapse-up" => Some(icons::ARROW_COLLAPSE_UP),
        "pi" => Some(icons::PI),
        "timer-cog-outline" => Some(icons::TIMER_COG_OUTLINE),
        "pencil-box" => Some(icons::PENCIL_BOX),
        "delete-off-outline" => Some(icons::DELETE_OFF_OUTLINE),
        "pan-horizontal" => Some(icons::PAN_HORIZONTAL),
        "eye-lock-open-outline" => Some(icons::EYE_LOCK_OPEN_OUTLINE),
        "music-box" => Some(icons::MUSIC_BOX),
        "stairs-down" => Some(icons::STAIRS_DOWN),
        "pencil-outline" => Some(icons::PENCIL_OUTLINE),
        "ideogram-cjk" => Some(icons::IDEOGRAM_CJK),
        "location-enter" => Some(icons::LOCATION_ENTER),
        "timeline-minus-outline" => Some(icons::TIMELINE_MINUS_OUTLINE),
        "briefcase-download" => Some(icons::BRIEFCASE_DOWNLOAD),
        "hamburger-remove" => Some(icons::HAMBURGER_REMOVE),
        "shape-polygon-plus" => Some(icons::SHAPE_POLYGON_PLUS),
        "wall-sconce-round-variant" => Some(icons::WALL_SCONCE_ROUND_VARIANT),
        "store-plus" => Some(icons::STORE_PLUS),
        "movie-roll" => Some(icons::MOVIE_ROLL),
        "form-textarea" => Some(icons::FORM_TEXTAREA),
        "subway" => Some(icons::SUBWAY),
        "beach" => Some(icons::BEACH),
        "chart-histogram" => Some(icons::CHART_HISTOGRAM),
        #[allow(deprecated)]
        "google-circles-group" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'google-circles-group' is deprecated.")
                    .print(py);
            }
            Some(icons::GOOGLE_CIRCLES_GROUP)
        }
        "kettle-steam-outline" => Some(icons::KETTLE_STEAM_OUTLINE),
        "table-large-remove" => Some(icons::TABLE_LARGE_REMOVE),
        "archive-lock-open-outline" => Some(icons::ARCHIVE_LOCK_OPEN_OUTLINE),
        "approximately-equal" => Some(icons::APPROXIMATELY_EQUAL),
        "priority-high" => Some(icons::PRIORITY_HIGH),
        "credit-card-scan-outline" => Some(icons::CREDIT_CARD_SCAN_OUTLINE),
        "select-marker" => Some(icons::SELECT_MARKER),
        "alpha-l" => Some(icons::ALPHA_L),
        "abugida-thai" => Some(icons::ABUGIDA_THAI),
        "file-chart-check" => Some(icons::FILE_CHART_CHECK),
        "bookmark-plus" => Some(icons::BOOKMARK_PLUS),
        "lock-open-remove" => Some(icons::LOCK_OPEN_REMOVE),
        "pool-thermometer" => Some(icons::POOL_THERMOMETER),
        "message-alert-outline" => Some(icons::MESSAGE_ALERT_OUTLINE),
        "coach-lamp-variant" => Some(icons::COACH_LAMP_VARIANT),
        "border-top-variant" => Some(icons::BORDER_TOP_VARIANT),
        "alpha-a-box" => Some(icons::ALPHA_A_BOX),
        "folder-star-outline" => Some(icons::FOLDER_STAR_OUTLINE),
        "table-lock" => Some(icons::TABLE_LOCK),
        "folder-play-outline" => Some(icons::FOLDER_PLAY_OUTLINE),
        "ph" => Some(icons::PH),
        "outdoor-lamp" => Some(icons::OUTDOOR_LAMP),
        "book-refresh" => Some(icons::BOOK_REFRESH),
        "alpha-f" => Some(icons::ALPHA_F),
        "arrow-horizontal-lock" => Some(icons::ARROW_HORIZONTAL_LOCK),
        "zodiac-gemini" => Some(icons::ZODIAC_GEMINI),
        #[allow(deprecated)]
        "webpack" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'webpack' is deprecated.").print(py);
            }
            Some(icons::WEBPACK)
        }
        "robot-love-outline" => Some(icons::ROBOT_LOVE_OUTLINE),
        "cloud-remove" => Some(icons::CLOUD_REMOVE),
        "volleyball" => Some(icons::VOLLEYBALL),
        "chili-alert-outline" => Some(icons::CHILI_ALERT_OUTLINE),
        "database-plus-outline" => Some(icons::DATABASE_PLUS_OUTLINE),
        "face-mask-outline" => Some(icons::FACE_MASK_OUTLINE),
        "account-filter-outline" => Some(icons::ACCOUNT_FILTER_OUTLINE),
        "folder-zip" => Some(icons::FOLDER_ZIP),
        "format-indent-increase" => Some(icons::FORMAT_INDENT_INCREASE),
        "marker-check" => Some(icons::MARKER_CHECK),
        "invert-colors" => Some(icons::INVERT_COLORS),
        "drag-variant" => Some(icons::DRAG_VARIANT),
        "fuse-off" => Some(icons::FUSE_OFF),
        "comment-arrow-left" => Some(icons::COMMENT_ARROW_LEFT),
        "keyboard-f8" => Some(icons::KEYBOARD_F8),
        #[allow(deprecated)]
        "language-css3" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'language-css3' is deprecated.").print(py);
            }
            Some(icons::LANGUAGE_CSS3)
        }
        "table-arrow-right" => Some(icons::TABLE_ARROW_RIGHT),
        "ruler-square-compass" => Some(icons::RULER_SQUARE_COMPASS),
        "brightness-percent" => Some(icons::BRIGHTNESS_PERCENT),
        "arrow-u-up-left" => Some(icons::ARROW_U_UP_LEFT),
        "alpha-h-circle" => Some(icons::ALPHA_H_CIRCLE),
        "metronome" => Some(icons::METRONOME),
        "car-traction-control" => Some(icons::CAR_TRACTION_CONTROL),
        "gesture-tap-hold" => Some(icons::GESTURE_TAP_HOLD),
        "car-wireless" => Some(icons::CAR_WIRELESS),
        "wall-sconce-round-outline" => Some(icons::WALL_SCONCE_ROUND_OUTLINE),
        "page-next-outline" => Some(icons::PAGE_NEXT_OUTLINE),
        "file-rotate-left" => Some(icons::FILE_ROTATE_LEFT),
        "thermostat-cog" => Some(icons::THERMOSTAT_COG),
        "alpha-y-circle" => Some(icons::ALPHA_Y_CIRCLE),
        "receipt-text-edit" => Some(icons::RECEIPT_TEXT_EDIT),
        "relation-one-to-zero-or-many" => Some(icons::RELATION_ONE_TO_ZERO_OR_MANY),
        "music-clef-treble" => Some(icons::MUSIC_CLEF_TREBLE),
        "weather-lightning" => Some(icons::WEATHER_LIGHTNING),
        "table-check" => Some(icons::TABLE_CHECK),
        "dumbbell" => Some(icons::DUMBBELL),
        "message-image-outline" => Some(icons::MESSAGE_IMAGE_OUTLINE),
        "folder-search-outline" => Some(icons::FOLDER_SEARCH_OUTLINE),
        "star-minus" => Some(icons::STAR_MINUS),
        "arrow-up-circle" => Some(icons::ARROW_UP_CIRCLE),
        "table-column-plus-before" => Some(icons::TABLE_COLUMN_PLUS_BEFORE),
        "calendar-search" => Some(icons::CALENDAR_SEARCH),
        "alpha-m-box-outline" => Some(icons::ALPHA_M_BOX_OUTLINE),
        "golf" => Some(icons::GOLF),
        "chess-queen" => Some(icons::CHESS_QUEEN),
        "swap-horizontal-bold" => Some(icons::SWAP_HORIZONTAL_BOLD),
        "tooltip-question" => Some(icons::TOOLTIP_QUESTION),
        "printer-3d-nozzle-off-outline" => Some(icons::PRINTER_3D_NOZZLE_OFF_OUTLINE),
        "ceiling-light" => Some(icons::CEILING_LIGHT),
        "presentation" => Some(icons::PRESENTATION),
        "calendar-account" => Some(icons::CALENDAR_ACCOUNT),
        "snowman" => Some(icons::SNOWMAN),
        "high-definition-box" => Some(icons::HIGH_DEFINITION_BOX),
        "basket-remove" => Some(icons::BASKET_REMOVE),
        "hook-off" => Some(icons::HOOK_OFF),
        "cloud-alert-outline" => Some(icons::CLOUD_ALERT_OUTLINE),
        "floor-lamp" => Some(icons::FLOOR_LAMP),
        "battery-10-bluetooth" => Some(icons::BATTERY_10_BLUETOOTH),
        "arrow-expand-vertical" => Some(icons::ARROW_EXPAND_VERTICAL),
        "alphabetical-off" => Some(icons::ALPHABETICAL_OFF),
        "calendar-minus" => Some(icons::CALENDAR_MINUS),
        "comma-box-outline" => Some(icons::COMMA_BOX_OUTLINE),
        "map-marker-account" => Some(icons::MAP_MARKER_ACCOUNT),
        "movie-open-play" => Some(icons::MOVIE_OPEN_PLAY),
        "bookmark-off-outline" => Some(icons::BOOKMARK_OFF_OUTLINE),
        "sort-bool-descending-variant" => Some(icons::SORT_BOOL_DESCENDING_VARIANT),
        "file-star" => Some(icons::FILE_STAR),
        "translate-off" => Some(icons::TRANSLATE_OFF),
        #[allow(deprecated)]
        "pandora" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'pandora' is deprecated.").print(py);
            }
            Some(icons::PANDORA)
        }
        "arrow-collapse-horizontal" => Some(icons::ARROW_COLLAPSE_HORIZONTAL),
        "food-drumstick" => Some(icons::FOOD_DRUMSTICK),
        "animation-outline" => Some(icons::ANIMATION_OUTLINE),
        "numeric-1-box-multiple-outline" => Some(icons::NUMERIC_1_BOX_MULTIPLE_OUTLINE),
        "serial-port" => Some(icons::SERIAL_PORT),
        "star-box-multiple-outline" => Some(icons::STAR_BOX_MULTIPLE_OUTLINE),
        "thumbs-up-down-outline" => Some(icons::THUMBS_UP_DOWN_OUTLINE),
        "octahedron" => Some(icons::OCTAHEDRON),
        "alpha-c" => Some(icons::ALPHA_C),
        "om" => Some(icons::OM),
        "bunk-bed" => Some(icons::BUNK_BED),
        "tag-arrow-up" => Some(icons::TAG_ARROW_UP),
        "briefcase-plus-outline" => Some(icons::BRIEFCASE_PLUS_OUTLINE),
        "sort-variant" => Some(icons::SORT_VARIANT),
        "file-image" => Some(icons::FILE_IMAGE),
        "view-sequential-outline" => Some(icons::VIEW_SEQUENTIAL_OUTLINE),
        "bed-double" => Some(icons::BED_DOUBLE),
        "elevator-passenger-outline" => Some(icons::ELEVATOR_PASSENGER_OUTLINE),
        "spa" => Some(icons::SPA),
        "alpha-j-box-outline" => Some(icons::ALPHA_J_BOX_OUTLINE),
        "chart-donut-variant" => Some(icons::CHART_DONUT_VARIANT),
        "home-alert-outline" => Some(icons::HOME_ALERT_OUTLINE),
        "arrow-top-left-bold-box" => Some(icons::ARROW_TOP_LEFT_BOLD_BOX),
        "paperclip-check" => Some(icons::PAPERCLIP_CHECK),
        "timer-off-outline" => Some(icons::TIMER_OFF_OUTLINE),
        "elevator" => Some(icons::ELEVATOR),
        "phone-alert" => Some(icons::PHONE_ALERT),
        "developer-board" => Some(icons::DEVELOPER_BOARD),
        "lightbulb-on-50" => Some(icons::LIGHTBULB_ON_50),
        "train" => Some(icons::TRAIN),
        "car-2-plus" => Some(icons::CAR_2_PLUS),
        "minus-box" => Some(icons::MINUS_BOX),
        "lightbulb-auto" => Some(icons::LIGHTBULB_AUTO),
        "seat-recline-extra" => Some(icons::SEAT_RECLINE_EXTRA),
        "qrcode-plus" => Some(icons::QRCODE_PLUS),
        "alpha-h-circle-outline" => Some(icons::ALPHA_H_CIRCLE_OUTLINE),
        "flag-variant-minus" => Some(icons::FLAG_VARIANT_MINUS),
        "undo" => Some(icons::UNDO),
        _ => None,
    }
}
