// This file was generated. DO NOT EDIT.
use crate::{Icon, icons};

#[cfg(feature = "pyo3")]
use pyo3::exceptions::PyDeprecationWarning;

#[cfg(feature = "pyo3")]
use pyo3::prelude::*;

pub(super) fn find_part_30(#[cfg(feature = "pyo3")] py: Python, slug: &str) -> Option<Icon> {
    match slug {
        "book-open-page-variant" => Some(icons::BOOK_OPEN_PAGE_VARIANT),
        "movie-open-play-outline" => Some(icons::MOVIE_OPEN_PLAY_OUTLINE),
        "alpha-t-circle-outline" => Some(icons::ALPHA_T_CIRCLE_OUTLINE),
        "inbox-full-outline" => Some(icons::INBOX_FULL_OUTLINE),
        "book-settings" => Some(icons::BOOK_SETTINGS),
        "call-made" => Some(icons::CALL_MADE),
        "led-variant-on" => Some(icons::LED_VARIANT_ON),
        "spider-web" => Some(icons::SPIDER_WEB),
        "bluetooth-connect" => Some(icons::BLUETOOTH_CONNECT),
        "format-horizontal-align-left" => Some(icons::FORMAT_HORIZONTAL_ALIGN_LEFT),
        "account-details" => Some(icons::ACCOUNT_DETAILS),
        "arrow-u-right-top-bold" => Some(icons::ARROW_U_RIGHT_TOP_BOLD),
        "sort" => Some(icons::SORT),
        "police-station" => Some(icons::POLICE_STATION),
        "home-import-outline" => Some(icons::HOME_IMPORT_OUTLINE),
        "information-slab-circle-outline" => Some(icons::INFORMATION_SLAB_CIRCLE_OUTLINE),
        "file-document-remove-outline" => Some(icons::FILE_DOCUMENT_REMOVE_OUTLINE),
        "nintendo-game-boy" => Some(icons::NINTENDO_GAME_BOY),
        "vector-polyline-remove" => Some(icons::VECTOR_POLYLINE_REMOVE),
        "comment-multiple-outline" => Some(icons::COMMENT_MULTIPLE_OUTLINE),
        "check-circle" => Some(icons::CHECK_CIRCLE),
        "folder-key-network-outline" => Some(icons::FOLDER_KEY_NETWORK_OUTLINE),
        "bell-off" => Some(icons::BELL_OFF),
        "account-tie-woman" => Some(icons::ACCOUNT_TIE_WOMAN),
        "latitude" => Some(icons::LATITUDE),
        "pipe" => Some(icons::PIPE),
        "emoticon-happy" => Some(icons::EMOTICON_HAPPY),
        "bag-personal-tag" => Some(icons::BAG_PERSONAL_TAG),
        "audio-input-rca" => Some(icons::AUDIO_INPUT_RCA),
        "guitar-electric" => Some(icons::GUITAR_ELECTRIC),
        "roman-numeral-1" => Some(icons::ROMAN_NUMERAL_1),
        "check-underline-circle-outline" => Some(icons::CHECK_UNDERLINE_CIRCLE_OUTLINE),
        #[allow(deprecated)]
        "black-mesa" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'black-mesa' is deprecated.").print(py);
            }
            Some(icons::BLACK_MESA)
        }
        "shopping-search-outline" => Some(icons::SHOPPING_SEARCH_OUTLINE),
        "calculator-variant-outline" => Some(icons::CALCULATOR_VARIANT_OUTLINE),
        "horse" => Some(icons::HORSE),
        "crop-rotate" => Some(icons::CROP_ROTATE),
        "calendar-remove" => Some(icons::CALENDAR_REMOVE),
        "owl" => Some(icons::OWL),
        "store-off" => Some(icons::STORE_OFF),
        "cash" => Some(icons::CASH),
        "movie-settings" => Some(icons::MOVIE_SETTINGS),
        "script-outline" => Some(icons::SCRIPT_OUTLINE),
        "flag-variant" => Some(icons::FLAG_VARIANT),
        "chevron-left-circle" => Some(icons::CHEVRON_LEFT_CIRCLE),
        "incognito-circle-off" => Some(icons::INCOGNITO_CIRCLE_OFF),
        "web-remove" => Some(icons::WEB_REMOVE),
        "arrow-up-bold-box" => Some(icons::ARROW_UP_BOLD_BOX),
        "menu" => Some(icons::MENU),
        "code-block-brackets" => Some(icons::CODE_BLOCK_BRACKETS),
        "alpha-d-box" => Some(icons::ALPHA_D_BOX),
        "calendar-collapse-horizontal-outline" => Some(icons::CALENDAR_COLLAPSE_HORIZONTAL_OUTLINE),
        "heart-circle-outline" => Some(icons::HEART_CIRCLE_OUTLINE),
        "chart-timeline" => Some(icons::CHART_TIMELINE),
        "code-parentheses" => Some(icons::CODE_PARENTHESES),
        "eyedropper-remove" => Some(icons::EYEDROPPER_REMOVE),
        "numeric-5-circle-outline" => Some(icons::NUMERIC_5_CIRCLE_OUTLINE),
        "submarine" => Some(icons::SUBMARINE),
        "filter-check-outline" => Some(icons::FILTER_CHECK_OUTLINE),
        "seed-plus-outline" => Some(icons::SEED_PLUS_OUTLINE),
        "grill" => Some(icons::GRILL),
        "radiator-off" => Some(icons::RADIATOR_OFF),
        "bank-outline" => Some(icons::BANK_OUTLINE),
        "tray-remove" => Some(icons::TRAY_REMOVE),
        "arrow-left-thin" => Some(icons::ARROW_LEFT_THIN),
        "elevator-passenger" => Some(icons::ELEVATOR_PASSENGER),
        "battery-charging-100" => Some(icons::BATTERY_CHARGING_100),
        "card-account-mail-outline" => Some(icons::CARD_ACCOUNT_MAIL_OUTLINE),
        "alpha-x-circle-outline" => Some(icons::ALPHA_X_CIRCLE_OUTLINE),
        "matrix" => Some(icons::MATRIX),
        "account-switch" => Some(icons::ACCOUNT_SWITCH),
        "access-point-minus" => Some(icons::ACCESS_POINT_MINUS),
        "diversify" => Some(icons::DIVERSIFY),
        "form-dropdown" => Some(icons::FORM_DROPDOWN),
        "monitor" => Some(icons::MONITOR),
        "reiterate" => Some(icons::REITERATE),
        "credit-card-search-outline" => Some(icons::CREDIT_CARD_SEARCH_OUTLINE),
        "camera-flip-outline" => Some(icons::CAMERA_FLIP_OUTLINE),
        "set-top-box" => Some(icons::SET_TOP_BOX),
        "bacteria" => Some(icons::BACTERIA),
        "cloud-arrow-right-outline" => Some(icons::CLOUD_ARROW_RIGHT_OUTLINE),
        "fuse" => Some(icons::FUSE),
        "battery-remove-outline" => Some(icons::BATTERY_REMOVE_OUTLINE),
        "flag-plus" => Some(icons::FLAG_PLUS),
        "sign-text" => Some(icons::SIGN_TEXT),
        "alpha-m-box" => Some(icons::ALPHA_M_BOX),
        "medical-bag" => Some(icons::MEDICAL_BAG),
        "diving-helmet" => Some(icons::DIVING_HELMET),
        "rotate-right" => Some(icons::ROTATE_RIGHT),
        "car-brake-temperature" => Some(icons::CAR_BRAKE_TEMPERATURE),
        "umbrella-closed-outline" => Some(icons::UMBRELLA_CLOSED_OUTLINE),
        "arrange-send-to-back" => Some(icons::ARRANGE_SEND_TO_BACK),
        "chat-plus-outline" => Some(icons::CHAT_PLUS_OUTLINE),
        "hiking" => Some(icons::HIKING),
        "bug-outline" => Some(icons::BUG_OUTLINE),
        "satellite" => Some(icons::SATELLITE),
        "apple-keyboard-shift" => Some(icons::APPLE_KEYBOARD_SHIFT),
        "beaker-question" => Some(icons::BEAKER_QUESTION),
        "math-cos" => Some(icons::MATH_COS),
        "horse-variant-fast" => Some(icons::HORSE_VARIANT_FAST),
        "cart" => Some(icons::CART),
        "cart-variant" => Some(icons::CART_VARIANT),
        "emoticon-dead" => Some(icons::EMOTICON_DEAD),
        "file-clock" => Some(icons::FILE_CLOCK),
        "human-male" => Some(icons::HUMAN_MALE),
        "microphone-question-outline" => Some(icons::MICROPHONE_QUESTION_OUTLINE),
        "light-switch" => Some(icons::LIGHT_SWITCH),
        "movie-roll" => Some(icons::MOVIE_ROLL),
        "countertop" => Some(icons::COUNTERTOP),
        "wifi-settings" => Some(icons::WIFI_SETTINGS),
        "link-variant-off" => Some(icons::LINK_VARIANT_OFF),
        "magnify-minus" => Some(icons::MAGNIFY_MINUS),
        "close-circle-multiple-outline" => Some(icons::CLOSE_CIRCLE_MULTIPLE_OUTLINE),
        "send-check" => Some(icons::SEND_CHECK),
        "invoice-plus" => Some(icons::INVOICE_PLUS),
        "receipt-text-edit-outline" => Some(icons::RECEIPT_TEXT_EDIT_OUTLINE),
        "account-file-text" => Some(icons::ACCOUNT_FILE_TEXT),
        "file-rotate-right" => Some(icons::FILE_ROTATE_RIGHT),
        "waveform" => Some(icons::WAVEFORM),
        "notebook-outline" => Some(icons::NOTEBOOK_OUTLINE),
        "flash-off-outline" => Some(icons::FLASH_OFF_OUTLINE),
        "home-lightning-bolt" => Some(icons::HOME_LIGHTNING_BOLT),
        "ornament" => Some(icons::ORNAMENT),
        "star-check" => Some(icons::STAR_CHECK),
        "human-scooter" => Some(icons::HUMAN_SCOOTER),
        "air-purifier-off" => Some(icons::AIR_PURIFIER_OFF),
        "briefcase-arrow-up-down" => Some(icons::BRIEFCASE_ARROW_UP_DOWN),
        "folder-key-network" => Some(icons::FOLDER_KEY_NETWORK),
        "file-star-four-points-outline" => Some(icons::FILE_STAR_FOUR_POINTS_OUTLINE),
        "book-check-outline" => Some(icons::BOOK_CHECK_OUTLINE),
        "view-array" => Some(icons::VIEW_ARRAY),
        "file-code" => Some(icons::FILE_CODE),
        "cached" => Some(icons::CACHED),
        "panorama" => Some(icons::PANORAMA),
        "slash-forward-box" => Some(icons::SLASH_FORWARD_BOX),
        "chart-sankey-variant" => Some(icons::CHART_SANKEY_VARIANT),
        "format-paragraph-spacing" => Some(icons::FORMAT_PARAGRAPH_SPACING),
        "file-lock" => Some(icons::FILE_LOCK),
        "music-box" => Some(icons::MUSIC_BOX),
        "traffic-cone" => Some(icons::TRAFFIC_CONE),
        "chevron-left" => Some(icons::CHEVRON_LEFT),
        "chat-sleep-outline" => Some(icons::CHAT_SLEEP_OUTLINE),
        "furigana-vertical" => Some(icons::FURIGANA_VERTICAL),
        "hot-tub" => Some(icons::HOT_TUB),
        "grid-off" => Some(icons::GRID_OFF),
        "fingerprint-off" => Some(icons::FINGERPRINT_OFF),
        "account-edit" => Some(icons::ACCOUNT_EDIT),
        "relation-zero-or-many-to-zero-or-one" => Some(icons::RELATION_ZERO_OR_MANY_TO_ZERO_OR_ONE),
        "paw-off" => Some(icons::PAW_OFF),
        #[allow(deprecated)]
        "microsoft-outlook" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'microsoft-outlook' is deprecated.")
                    .print(py);
            }
            Some(icons::MICROSOFT_OUTLOOK)
        }
        "handshake" => Some(icons::HANDSHAKE),
        "alpha-p-circle" => Some(icons::ALPHA_P_CIRCLE),
        "gamepad-left" => Some(icons::GAMEPAD_LEFT),
        "set-left-center" => Some(icons::SET_LEFT_CENTER),
        "whistle-outline" => Some(icons::WHISTLE_OUTLINE),
        "pliers" => Some(icons::PLIERS),
        "file-image-outline" => Some(icons::FILE_IMAGE_OUTLINE),
        "gesture-spread" => Some(icons::GESTURE_SPREAD),
        "seed-off" => Some(icons::SEED_OFF),
        "monitor-lock" => Some(icons::MONITOR_LOCK),
        "message-alert" => Some(icons::MESSAGE_ALERT),
        "apple-keyboard-caps" => Some(icons::APPLE_KEYBOARD_CAPS),
        "star" => Some(icons::STAR),
        "alpha-s-box-outline" => Some(icons::ALPHA_S_BOX_OUTLINE),
        "arrow-bottom-right" => Some(icons::ARROW_BOTTOM_RIGHT),
        "book-marker-outline" => Some(icons::BOOK_MARKER_OUTLINE),
        #[allow(deprecated)]
        "onepassword" => {
            #[cfg(feature = "pyo3")]
            {
                PyDeprecationWarning::new_err("The icon 'onepassword' is deprecated.").print(py);
            }
            Some(icons::ONEPASSWORD)
        }
        "arrow-bottom-left-thick" => Some(icons::ARROW_BOTTOM_LEFT_THICK),
        "airballoon" => Some(icons::AIRBALLOON),
        "cup" => Some(icons::CUP),
        "shield-car" => Some(icons::SHIELD_CAR),
        "fast-forward-outline" => Some(icons::FAST_FORWARD_OUTLINE),
        "keyboard" => Some(icons::KEYBOARD),
        "chart-scatter-plot-hexbin" => Some(icons::CHART_SCATTER_PLOT_HEXBIN),
        "arrow-projectile" => Some(icons::ARROW_PROJECTILE),
        "alpha-n-box" => Some(icons::ALPHA_N_BOX),
        "offer" => Some(icons::OFFER),
        "receipt-clock-outline" => Some(icons::RECEIPT_CLOCK_OUTLINE),
        "ev-plug-type2" => Some(icons::EV_PLUG_TYPE2),
        "axis-z-rotate-clockwise" => Some(icons::AXIS_Z_ROTATE_CLOCKWISE),
        "guitar-pick-outline" => Some(icons::GUITAR_PICK_OUTLINE),
        "vector-point-minus" => Some(icons::VECTOR_POINT_MINUS),
        "heart-multiple" => Some(icons::HEART_MULTIPLE),
        "contrast" => Some(icons::CONTRAST),
        "information-slab-symbol" => Some(icons::INFORMATION_SLAB_SYMBOL),
        "battery-charging-wireless-40" => Some(icons::BATTERY_CHARGING_WIRELESS_40),
        "panorama-vertical" => Some(icons::PANORAMA_VERTICAL),
        "fish-off" => Some(icons::FISH_OFF),
        "mailbox" => Some(icons::MAILBOX),
        "upload-box" => Some(icons::UPLOAD_BOX),
        "content-save-settings-outline" => Some(icons::CONTENT_SAVE_SETTINGS_OUTLINE),
        "code-parentheses-box" => Some(icons::CODE_PARENTHESES_BOX),
        "file-chart-check" => Some(icons::FILE_CHART_CHECK),
        "spider" => Some(icons::SPIDER),
        "copyright" => Some(icons::COPYRIGHT),
        "check-all" => Some(icons::CHECK_ALL),
        "pen-minus" => Some(icons::PEN_MINUS),
        "heart-circle" => Some(icons::HEART_CIRCLE),
        "traffic-light-outline" => Some(icons::TRAFFIC_LIGHT_OUTLINE),
        "robot-vacuum-variant-alert" => Some(icons::ROBOT_VACUUM_VARIANT_ALERT),
        _ => None,
    }
}
