name: Check deno updates

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0,2,4"

permissions: {}

jobs:
  check-updates:
    runs-on: ubuntu-latest
    environment: deno-upgrades

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.REDIST_ICONS_UPDATE }}
          fetch-depth: 0
          persist-credentials: true # needed for git push

      - run: rustup update --no-self-update

      - name: Setup nushell
        uses: hustcer/setup-nu@92c296ba1ba2ba04cc948ab64ddefe192dc13f0c # v3.23
        with:
          version: ${{ vars.NU_SHELL_VERSION || '*' }}

      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          cache: true
      - name: Install Deno deps
        run: deno install

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Python deps
        run: uv sync

      - name: Cache pre-commit environments
        uses: actions/cache@v5.0.5
        with:
          path: "~/.cache/pre-commit"
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Check for updates
        run: nu .github/workflows/check-deno-updates.nu
        env:
          GITHUB_TOKEN: ${{ secrets.REDIST_ICONS_UPDATE }}
